<div class="page-header">
    <h1>
        Auditorias del Sistema 
        <small>Usuario: <?php eh(strtoupper($usuario->login)) ?></small>
        
    </h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php echo Form::open('admin/auditorias/resultados_usuario/' . $usuario->id) ?>
<div>
    <div class="span3">
        <label for="filtro_tabla_afectada">Tabla Afectada</label>
   	<?php echo Form::select('filtro.tabla_afectada', $tablas_afectadas) ?></div>
    <div class="span3">
        <label for="filtro_fecha_at">Fecha</label>
   	<?php echo Form::date('filtro.fecha_at') ?></div>
    <div class="span3">
        <label for="filtro_accion_realizada">Acci&oacute;n Realizada</label>
   	<?php echo Form::text('filtro.accion_realizada') ?></div>
</div>
<div class="row">
    <div class="span3"></div>
    <div class="span3"></div>
    <div class="span3"></div>
    <div class="span3" style1="white-space: nowrap;">
        <?php echo Form::submit('Aplicar Filtro', 'class="btn btn-primary"') ?>                
        <?php echo Html::linkAction('usuario/' . $usuario->id, 'Mostrar Todos', 'class="btn"') ?>   
    </div>
</div>
<?php echo Form::close() ?>
<div id="scaffold">
    <?php
    Table::headers('Accion Realizada', 'Fecha y Hora', 'Tabla Afectada');
    Table::fields('accion_realizada', 'fecha_at', 'tabla_afectada');
    Table::url($url);
    echo Table::create($auditorias, 'class="table table-bordered table-striped"');
    ?>
</div>
<style>
    .span4 label{
        text-align: center;
    }
</style>
<a href="../" class="btn" style="float: right">Volver</a>
<?php
    Tag::css('datepicker');
    echo Tag::js('datepicker/datepicker');
?>