<?php View::content()?>
<div class="card">
<h1>Produccion Diaria<span>Ingreso de las producciones por turnos</span></h1>
</div>

<div class="form-actions">
<?php echo Menu::efe($action_name)?>
</div> 
<div class="menu">
<ul>
<li>
<a href="javascript:;">Año 
<select id="anio">
<?php
for($i=2011;$i<=2020;$i++)
{
	$selec='';
	if($anio==$i){
	$selec=' selected="selected"';
	}
	echo '<option value="'.$i.'" '.$selec.'>'.$i.'</option>';
}
?>
</select>
</a>
</li>
</ul> 
<?php 
$mes_actual=date('Y-m');
foreach($meses as $clave => $mes):
if($anio.'-'.$clave<=$mes_actual){
$class='';
if($mes_activo==$clave)$class=' active';
echo '<ul>';
echo '<li><a class="enviar'.$class.'" id="mes-'.$mes.'" href="javascript:;" data-id="'.$anio.'-'.$clave.'-01">'.$mes.'</a></li>'; 
echo '</ul>';
}
endforeach;?>

</div>
<?php echo Sp::imprimir('Eficiencias - ','P',array("W"=>"1","P"=>"1","PDF"=>"1"));?> 
<div class="">
	<div class="tabbable">
 <!-- Only required for left/right tabs -->
	<ul class="nav nav-tabs">
	  <?php 
	  $tejedores=array();
	  for($i=1;$i<=$vals;$i++)
    {
        $val_id='';
		$val_n='';
        $val_m='';
        $val_f='';
		$val_id='id'.$i;
        $val_n='nombre'.$i;
        $val_m='maquinas'.$i;
        $val_f='fechas'.$i;
    ?>
        <li><a href="#tab<?Php echo $i?>" data-toggle="tab"><?php $tejedores[${$val_id}]=${$val_n};echo ${$val_n}?></a></li>
    <?php }
	$i=$i+1;?>
    <li class="active"><a href="#tab<?Php echo $i?>" data-toggle="tab"><?php echo "TOTALES"?></a></li>
    <?php
	$i=$i+1;?>
    <li><a href="#tab<?Php echo $i?>" data-toggle="tab"><?php echo "Detallado"?></a></li>
      </ul>
	<div class="tab-content page">
<?php for($i=1;$i<=$vals;$i++)
{
	
	$z=0;
	$val_n='';
	$val_m='';
	$val_f='';
	$val_id='';
	$val_id='id'.$i;
	$val_n='nombre'.$i;
	$val_m='maquinas'.$i;
	$val_f='fechas'.$i;
?>
<div class="tab-pane " id="tab<?Php echo $i?>">
<h3><?php echo ${$val_n}?><?php //echo ${$val_id}?></h3>
<table id="<?php echo ${$val_id}?>" class="table table-bordered">
<thead>
<tr>
<td>Maquina<br />Fechas</td>
<?php 
//"<br />".($maquina->getPromaquinas()->maxproduccion)
$total_m=0;
$suma_max=0;
foreach(${$val_m} as $maquina)
{
	$total_m++;
	$maxproduccion=number_format($maquina->getPromaquinas()->maxproduccion*((60*8)/1000),0,'.','');
	$suma_max=$suma_max+$maxproduccion;
	echo "<th>";
	echo $maquina->getPromaquinas()->nombre."<br />(".$maxproduccion.")"; 
	echo "</th>";
}?>
<th>Total<br />(<?php echo $suma_max;?>)</th> 
</tr>
</thead>
<?php $f_1=0;
foreach(${$val_f} as $fecha)
{
	$f_2=$fecha->fecha;
	if($f_1!=$f_2)
	{
		$f_1=$fecha->fecha;
		echo "<tr><td>";
		echo Sp::formatFecha('%d/%m/%Y',$fecha->fecha); 
		echo "</td>";
		   $total_suma=0;
			foreach(${$val_m} as $maquina)
			{
				$i_m=0;
				$sumas_t='+';
				$divisor=number_format($maquina->getPromaquinas()->maxproduccion*((60*8)/1000),0,'.','');
				$td=0;
				$resta1=0;
				foreach(${$val_f} as $valor)
				{
					$i_m++;
					$totales='fecha-'.$i_m.$valor->promaquinas_id;
					if($fecha->fecha==$valor->fecha && $valor->promaquinas_id==$maquina->promaquinas_id)
					{
						$total_suma=$total_suma+$valor->resta;
						$td++;
						//echo "<td align='right' title='".$valor->id."'></td>";
						echo "<td align='right' title='".$valor->id." ($valor->resta*100)/$divisor'>";
						$t=number_format(($valor->resta*100)/$divisor,1,'.','');
						echo $t;
						if(Auth::get('id')==3){
							echo '(';
						    echo $valor->id;
							echo "(".$valor->valor."->".$valor->resta_valor.")resta->".$valor->resta.")";
						    echo ')';
						}
						echo "%</td>";
						//echo $valor->id_s."--> ".number_format(($valor->resta*100)/$divisor,2,'.','')."%</td>";
					}
					if($f_2==$valor->fecha && $valor->promaquinas_id==$maquina->promaquinas_id && $valor->acldatos_id==${$val_id})
					{
						$item=$z.$maquina->promaquinas_id.$valor->acldatos_id;
						${$totales}[$item]=$sumas_t=$sumas_t+$t;
						if(Auth::get('id')==3){
						//echo $item;
						//print_r(${$totales});
						};
					}
					$z=0;
				}
				if($td==0){
						echo "<td align='right' title='Aun no hay valores'>00</td>";
						//if($f_2==$valor->fecha)${$totales}[$f_2]=$sumas_t=$sumas_t+0;
					}
			}
		echo "<td>".number_format(($total_suma/$suma_max)*100,1,',','')."% </td>";
		echo "</tr>";
	}
}?>
</table>
</div>
<?php 
	//print_r(${$val_m});
	//print_r(${$val_f});
	}
$i=$i+1;
?>
<div class="tab-pane active" id="tab<?Php echo $i?>">
<h1>Totales</h1>
<table id="TOTALES" class="table table-bordered">
<thead>
<tr>
<td>Maquina<br />Fechas</td>
<?php 
//"<br />".($maquina->getPromaquinas()->maxproduccion)
$total_m=0;foreach(${$val_m} as $maquina){$total_m++;echo "<th>";echo $maquina->getPromaquinas()->nombre."<br />(".number_format($maquina->getPromaquinas()->maxproduccion*((60*8)/1000),0,'.','').")"; echo "</th>";}?>
<td>Total</td>
</tr>
</thead>
<tbody>
<?php $f_1=0;
foreach(${$val_f} as $fecha)
{
	
	$f_2=$fecha->fecha;
	if($f_1!=$f_2)
	{
		$f_1=$fecha->fecha;
		echo "<tr><td scope='row'>";
		echo Sp::formatFecha('%d/%m/%Y',$fecha->fecha); 
		echo "</td>";
		$total_suma=0;
			foreach($maquinas1 as $maquina)
			{
				$i_m=0;
				$sumas_t='+';
				$divisor=number_format($maquina->getPromaquinas()->maxproduccion*((60*8)/1000),0,'.','');
				$td=0;
				$resta1=0;
				foreach($fechas1 as $valor)
				{
					
					$i_m++;
					if($fecha->fecha==$valor->fecha && $valor->promaquinas_id==$maquina->promaquinas_id)
					{
						$td++;
						//echo "<td align='right' title='".$valor->id."'>(".$valor->valor."->".$valor->resta_valor.")resta->".$valor->resta."</td>";
						echo "<td align='right' class='htooltip'>";
						foreach($maquinas1 as $maq)
						{
							
							if(isset(${'fecha-'.$i_m.$maq->promaquinas_id}))
							{
								if($maq->promaquinas_id==$maquina->promaquinas_id)
								{
									$prom_suma=number_format(array_sum(${'fecha-'.$i_m.$maquina->promaquinas_id})/3,1,'.','');
									$menor=' style="width:90%; display:inline-table;"';
									if($prom_suma<Session::get('MIN_PRODUCCION'))$menor=' style="color:#F00; width:90%; display:inline-table;"';
									
									echo '<i '.$menor.'>'.$prom_suma.'</i>';    
									
									$total_suma=$total_suma+$prom_suma;
									
								}
							}
						}
						echo "%";
						?>
                        <span><?Php //echo "'(".$valor->id.") ";
						$uziel=$arr=${'fecha-'.$i_m.$maquina->promaquinas_id};
						//print_r($arr);?>
                        <?php $v_x=max($arr);$v_m=min($arr);?>
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <thead>
                          <tr>
                            <th colspan="3" align="center">Comparativo Eficiencias Tejedores!<br /><?Php echo Sp::formatFecha('%d/%m/%Y',$fecha->fecha);?> - <?php echo $maquina->getPromaquinas()->nombre?></th>
                          </tr>
                          <tr>
                            <th>Tejedor</th>
                            <th>Turno</th>
                            <th>Valor</th>
                          </tr>
                         </thead>
                         <tbody>
                         <?php foreach($arr as $item=>$value)
						{
						  $color='';
						  if($v_x==$value)$color=' style="background-color:#3C0;"';
						  if($v_m==$value)$color=' style="background-color:#F00;"';
						  ?>
                          <tr>
                            <td><?php $dato_id=substr($item,-2,2);echo $tejedores[$dato_id]; ?></td>
                            <td><?php $maquina_id=substr($item,-3,1);$turnos=$valor->getTurno($dato_id,$fecha->fecha,$maquina_id);echo $turnos->nombre; if(!empty($turnos->observaciones)) echo ' Observacion: '.$turnos->observaciones;?></td>
                            <td<?php echo $color; ?>><?php echo $value ?>%</td>
                          </tr>
                         <?php }?>
                          </tbody>
                        </table>

                        
                        </span>
                        <?php echo "</td>";
						//echo $valor->id_s."--> ".number_format(($valor->resta*100)/$divisor,2,'.','')."%</td>";
					}
					
				}
				if($td==0){
						echo "<td align='right' title='Aun no hay valores'>00</td>";
						//if($f_2==$valor->fecha)${$totales}[$f_2]=$sumas_t=$sumas_t+0;
					}
			}
		echo "<td>".number_format($total_suma/$total_m,1,'.','');
		if(Auth::get('id')==3)print_r($uziel);
		echo"</td>";
		echo "</tr>";
	}
}?>
</tbody>
</table>
        </div>

<?php //print_r(${$totales});
$i=$i+1;
?>
<div class="tab-pane" id="tab<?Php echo $i?>">
<h1>Detallado</h1>
<table class="table table-bordered">
<tr>
<td>Maquina<br />Fechas</td>
<?php 
//"<br />".($maquina->getPromaquinas()->maxproduccion)
$total_m=0;foreach(${$val_m} as $maquina){$total_m++;echo "<th>";echo $maquina->getPromaquinas()->nombre."<br />(".number_format($maquina->getPromaquinas()->maxproduccion*((60*8)/1000),0,'.','').")"; echo "</th>";}?>
<th>Turno</th>
</tr>
<?php $f_1=0;
/*Array con lo valores en detalle no es de consulta si no de php*/
$arr_datos=${'fecha-'.$i_m.$maquina->promaquinas_id};
foreach(${$val_f} as $fecha)
{
	
	$f_2=$fecha->fecha;
	if($f_1!=$f_2)
	{
		$f_1=$fecha->fecha;
		echo "<tr>";
		echo "<td colspan='11'>";
		echo Sp::formatFecha('%d/%m/%Y',$fecha->fecha);
		 
		echo "</td>";
		echo "</tr>";
		echo "<tr>";
		echo "<td>";?>
         <?php foreach($arr_datos as $item=>$value){?>
				<?php $dato_id=substr($item,-2,2); echo $tejedores[$dato_id]; ?> <br />
        <?php }?>
        <?Php echo "</td>";?>
		<?
			foreach($maquinas1 as $maquina)
			{
				$i_m=0;
				$sumas_t='+';
				$divisor=number_format($maquina->getPromaquinas()->maxproduccion*((60*8)/1000),0,'.','');
				$td=0;
				$resta1=0;
				foreach($fechas1 as $valor)
				{
					$i_m++;
					if($fecha->fecha==$valor->fecha && $valor->promaquinas_id==$maquina->promaquinas_id)
					{
						$td++;
						//echo "<td align='right' title='".$valor->id."'>(".$valor->valor."->".$valor->resta_valor.")resta->".$valor->resta."</td>";
						echo "<td align='right'>";
						foreach($maquinas1 as $maq)
						{
							
							if(isset(${'fecha-'.$i_m.$maq->promaquinas_id}))
							{
								if($maq->promaquinas_id==$maquina->promaquinas_id)
								{
									$total_porcentaje=number_format(array_sum(${'fecha-'.$i_m.$maquina->promaquinas_id})/3,2,'.','');
								}
							}
						}
						//echo "%";
						?><?Php 
						$arr=${'fecha-'.$i_m.$maquina->promaquinas_id};?>
                        <?php $v_x=max($arr);$v_m=min($arr);?>
                         <?php foreach($arr as $item=>$value)
						{
						  $color=' style="width:90%; display:inline-table;"';
						  if($v_x==$value)$color=' style="background-color:#3C0; width:90%; display:inline-table;"';
						  if($v_m==$value)$color=' style="background-color:#F00; width:90%; display:inline-table;"';
						  ?>
						  <?php $dato_id=substr($item,-2,2); $tejedores[$dato_id]; ?>
                          <?php $maquina_id=substr($item,-3,1);$turnos=$valor->getTurno($dato_id,$fecha->fecha,$maquina_id); $turnos->nombre; if(!empty($turnos->observaciones))' Observacion: '.$turnos->observaciones;?>
                            <span<?php echo $color; ?>><?php echo $value ?>%</span> <br />
                         <?php }
						 ?>
						 <span style="color:#333333; font-weight:bold; border-top:inset 2px #000000; width:100%; display:inline-table;">
						 <?php
						 echo $total_porcentaje;
						 ?>%
                         </span>
                        <?php echo "</td>";
						//echo $valor->id_s."--> ".number_format(($valor->resta*100)/$divisor,2,'.','')."%</td>";
					}
					
				}
				if($td==0){
						echo "<td align='right' title='Aun no hay valores'>00</td>";
						//if($f_2==$valor->fecha)${$totales}[$f_2]=$sumas_t=$sumas_t+0;
					}
			}
			?>
		<?php
		echo "<td>";
		foreach($arr_datos as $item=>$value){
		$dato_id=substr($item,-2,2);
		$maquina_id=substr($item,-3,1);$turnos=$valor->getTurno($dato_id,$fecha->fecha,0); echo $turnos->nombre.'<br />';
		}
          echo " </td>
		</tr>";
	}
}?>
</table>
        </div>
</div>
</div>
</div>
<style type="text/css">
.menu {position:relative;}
.menu ul {padding:0; margin:0; list-style:none; float:left;}
.menu ul ul {position:absolute;
-webkit-transition: 0.5s;
-moz-transition: 0.5s;
-ms-transition: 0.5s;
-o-transition: 0.5s;
transition: 0.5s;
transition-delay: 0.5s;
-o-transition-delay: 0.5s;
-moz-transition-delay: 0.5s;
-ms-transition-delay: 0.5s;
-webkit-transition-delay: 0.5s;
}
.menu ul ul ul {position:absolute; left:150px; top:0;}
.menu ul ul ul.rgt {position:absolute; left:auto; right:150px; top:0;}

.menu ul li {float:left; position:relative;
-webkit-transition: 0.25s;
-moz-transition: 0.25s;
-ms-transition: 0.25s;
-o-transition: 0.25s;
}

.menu ul li a {display:block; height:29px; padding:2px 10px; background:#ddd; font:normal 12px/29px arial, sans-serif; color:#000; text-decoration:none; margin-bottom:1px; margin-right:1px;
-o-border-radius: 10px;
-moz-border-radius: 10px;
-ms-border-radius: 10px;
-webkit-border-radius: 10px;
border-radius: 10px;
}
.menu ul li a.fly {background:#ddd no-repeat right center;}
.menu ul li:hover > a {background-color:#999; color:#fff;}
.menu ul li:hover > a.fly {background:#999 no-repeat right center;}
.menu ul li a.active {background-color:#999; color:#fff;}
.reporte
{
	display:block;
	margin-top:20px;
}
.reporte h2 span{color:#333333;}
.reporte h2
{
	padding:0 20%;
	border-bottom:#000000 solid 1px;
}
.reporte h2 span{
	font-weight:lighter;
	}
.sin_reporte{
	border-bottom:#666666 1px solid; padding:5px;}
.sin_reporte span
{
	padding:35%;
}
</style>
<script type="text/javascript">
$(document).ready(function() {
	$("#anio").change(function(event){
    	var id = $("#anio").find(':selected').val();
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?php echo $action_name?>/'+id;
     });
	$(".enviar").click(function()
	{
		var fecha = $(this).attr('data-id');
		var F=fecha.split('-');
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?php echo $action_name?>/'+F[0]+'/'+F[1];
	});
	$(".botonExcel").click(function(event)
	{
		$("#datos_a_enviar").val( $("<div>").append( $("#exportar_excel").eq(0).clone()).html());
		$("#FormularioExportacion").submit();
	});
});
</script>