<div class="card">
    <h1>Grabar Produccion de las Coneras</h1>
</div>
 <div class="form-actions">
 <?Php //echo Html::linkAction('grabar_coneras')?>
<?php /*?><a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/" class="btn btn-xs btn-primary">Tejeduria</a>
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/index/140" class="btn btn-xs btn-primary">Hilatura-Chenillera</a>
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/index/141" class="btn btn-xs btn-primary">Urdido</a>
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/index/142" class="btn btn-xs btn-primary">Control de Calidad</a>
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/index/143" class="btn btn-xs btn-primary">Estampado</a>
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/index/144" class="btn btn-xs btn-primary">Soporte</a>
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/index/163" class="btn btn-xs btn-primary">Enconado</a><?php */?>
</div>
<div class="card-body">
<h1>Ver los resultados de las coneras</h1>
</div>