<div class="card">
    <h1><em>Selector de Tipo de Maquinas </em></h1>
</div>
 <div class="form-actions">
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/eficiencia" class="btn btn-xs btn-primary">Tejeduria</a>
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/coneras/" class="btn btn-xs btn-primary">Hilatura-Chenillera</a>
<?php /*?><a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/index/141" class="btn btn-xs btn-primary">Urdido</a>
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/index/142" class="btn btn-xs btn-primary">Control de Calidad</a>
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/index/143" class="btn btn-xs btn-primary">Estampado</a>
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/index/144" class="btn btn-xs btn-primary">Soporte</a>
<a href="/<?Php echo $module_name;?>/<?Php echo $controller_name;?>/index/163" class="btn btn-xs btn-primary">Enconado</a><?php */?>
</div>