<?php
$simbolo="S/. ";
if(empty($igv))$igv=0;
switch ($monedas)
{
	case 1: $simbolo='S/. ';$moneda_letras='SOLES'; break;
	case 2: $simbolo='$. ';$moneda_letras='DOLARES';  break;
	case 4: $simbolo='S/. ';$moneda_letras='SOLES';  break;
	case 5: $simbolo='$. ';$moneda_letras='DOLARES';  break;
	case 0: $simbolo='S/. ';$moneda_letras='SOLES';  break;
}


View::content();
echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<script type="text/javascript">	

/*INICIO */
<?php 
/* TR PARA INGRESAR*/
$tr='<tr id="\'+IDnew+\'" class="item-row">';
$tr.='<td><div class="delete-wpr"><input id="codigo-\'+IDnew+\'" name="codigo-\'+IDnew+\'" type="text" readonly="readonly" size="10"><a id="del-\'+IDnew+\'" class="delete" href="javascript:;" title="Elimar registro" data-id="0" style="">X</a></div></td>';
$tr.='<td class="item-name"><input id="productos_id-\'+IDnew+\'" name="productos_id-\'+IDnew+\'" type="hidden" class="productos_id" readonly="readonly"><span id="ver-name\'+IDnew+\'" style="display:none;"><input id="productoname-\'+IDnew+\'" name="productoname-\'+IDnew+\'" type="text" value="" readonly="readonly"></span><span id="ver\'+IDnew+\'" class="ver"><input id="producto\'+IDnew+\'" name="producto\'+IDnew+\'" type="text" class="producto" placeholder="Producto" size="30" readonly="readonly"></span></td>';
$tr.='<td><input id="tesunidadesmedidas\'+IDnew+\'" name="tesunidadesmedidas\'+IDnew+\'" type="text" value=""><input class="unidad" id="tesunidadesmedidas_id-\'+IDnew+\'" name="tesunidadesmedidas_id-\'+IDnew+\'" type="hidden" value=""></td>';
//$tr.='<td><input id="tescolores\'+IDnew+\'" name="tescolores\'+IDnew+\'" type="text" value=""><input class="color" id="tescolores_id-\'+IDnew+\'" name="tescolores_id-\'+IDnew+\'" type="hidden" value=""></td>';
//$tr.='<td> <input id="lote\'+IDnew+\'" class="save" name="lote\'+IDnew+\'" type="text" value="" size="10"/></td>';
if($hilo)$tr.='<td> <input data-id="0" class="save cajas" id="empaque\'+IDnew+\'" name="empaque\'+IDnew+\'" type="text" value="" size="10"/> <div class="flotante" id="cajas-\'+IDnew+\'"></div></td>';
if($hilo)$tr.='<td> <input id="bobinas\'+IDnew+\'" name="bobinas\'+IDnew+\'" type="text" value="" size="10"/></td>';
$tr.='<td> <input id="pesoneto\'+IDnew+\'" class="save peso_neto" name="pesoneto\'+IDnew+\'" type="text" value="" size="10"/></td>';
$tr.='<td> <input id="pesobruto\'+IDnew+\'" class="save" name="pesobruto\'+IDnew+\'" type="text" value="" size="10"/></td>';
$tr.='</tr>';
/**/

$code='function roundNumber(number,decimals)
		{
  			var newString;// The new rounded number
  			decimals = Number(decimals);
  			if (decimals < 1) 
			{
    			newString = (Math.round(number)).toString();
  			}else
			{
    			var numString = number.toString();
    			if (numString.lastIndexOf(".") == -1)
				{// If there is no decimal point
      				numString += ".";// give it one at the end
    			}
    			var cutoff = numString.lastIndexOf(".") + decimals;// The point at which to truncate the number
    			var d1 = Number(numString.substring(cutoff,cutoff+1));// The value of the last decimal place that we\'ll end up with
    			var d2 = Number(numString.substring(cutoff+1,cutoff+2));// The next decimal, after the last one we want
    			if (d2 >= 5)
				{// Do we need to round up at all? If not, the string will just be truncated
      				if (d1 == 9 && cutoff > 0)
					{// If the last digit is 9, find a new cutoff point
        				while (cutoff > 0 && (d1 == 9 || isNaN(d1))) {
          				if (d1 != ".")
						{
            				cutoff -= 1;
            				d1 = Number(numString.substring(cutoff,cutoff+1));
         				} else {
            				cutoff -= 1;
          				}
        			}
      			}
      			d1 += 1;
    		} 
    		if (d1 == 10)
			{
      			numString = numString.substring(0, numString.lastIndexOf("."));
      			var roundedNum = Number(numString) + 1;
      			newString = roundedNum.toString() + \'.\';
    		}else
			{
				newString = numString.substring(0,cutoff) + d1.toString();
		    }
  		}
  		if (newString.lastIndexOf(".") == -1) 
		{// Do this again, to the new string
    		newString += ".";
  		}
  		var decs = (newString.substring(newString.lastIndexOf(".")+1)).length;
  		for(var i=0;i<decimals-decs;i++) newString += "0";
  		//var newNumber = Number(newString);// make it a number if you like
		return newString; // Output the result to the form field (change for your purposes)
		}';
$code.='
$(document).ready(function()
		{	
			bind();  
			$("input").click(function(){
    		$(this).select();
			});';
$code.='$("#paid").blur(function(){update_balance();});
		$("#paid_total").blur(function(){update_balance();});';
   /*
  Para grabar el tr - id buscando la clase :save y mandando todo el contenido del tr:
  */
$code.='$("#addrow").click(function()
		{
			var ID = $(".item-row:last").attr("id");
			//alert(ID);
			grabarDetalle(ID);
			var IDnew=Number(ID)+Number(1);
			var tr=\''.$tr.'\';
    		$(".item-row:last").after(tr);
    		if ($(".delete").length > 1) $(".delete").show();else $(".delete").hide();
			bind();
  		});';
/* ------- FIN contenido del tr: ------- */
$code.='$(".delete").live("click",function()
		{
		  var row =$(this).parents(".item-row")
		  var id=row.find(\'.delete\').attr(\'data-id\');
		  EliminarDetalle(id);
			$(this).parents(\'.item-row\').remove();
		  	update_total();
			if ($(".delete").length < 2) $(".delete").hide();
	    });';
/**/
  
  		//$("#pre_descripcion").blur(function(){$("#observacion").val($(this).val());GRABAR();});

$code.='$("#paid").blur(function(){$("#descuento").val($(this).val());GRABAR();});';
$code.='$("#glosa").change(function(){GRABAR();});';
$code.='$("#femision").change(function(){GRABAR();});'; 
$code.='$("#numero").blur(function(){GRABAR();});';
$code.='$(".grabar_form").blur(function(){GRABAR();});';
$code.='$("#monedas").change(function()
		{
			GRABAR();
			var op = $("#monedas option:selected").val();
			if(op==1)
			{
			$(".simbolo").html("S/. ");
			}
			if(op==2)
			{
			$(".simbolo").html("$. ");
			}
		});';
/*Busqueda del Cliente*/
$code.='$("#CL").tokenInput("/santapatricia/salidas/buscarproveedor", 
		{
			tokenLimit: 1,
			minChars: 2,';
	//echo $cliente_id; 
	if($cliente_id!=0){
	$code.='prePopulate: [ 
						 {id: '.$cliente_id.', name: "'.$nombre.'"},
						 ],';
			}
	$code.='onAdd: function (item){
			   var VAL=item.id;
			   $("#cliente_id").val(VAL);
			   $("#customer-title").val(item.name);
			   GRABAR();
			},
			onDelete: function (item) {
			}
		});';
/*---FIN Busqueda del Cliente*/	
$code.='});';
/*fin de Documento ready*/

/*FIN DE REDONDEO*/
$code.='
function bind(){
  if ($(".delete").length > 1) $(".delete").show();else $(".delete").hide();
  //$(".cost").blur(function(){update_price();});
  //$(".qty").blur(function(){update_price();});
  $(".producto").click(buscarProducto());
 // $(".color").click(buscarColor());
  $(".unidad").click(buscarUnidad());
  $(".save").blur(function(){Detalle($(this).attr("id"));
  $(".peso_neto").blur(function(){update_peso();});';
  
if($hilo)$code.='$(".caja").click(buscarCaja());';

$code.='
});
}';

/*BUSCAR PRODUCTO*/
	/*  */		
$code.='function buscarProducto()
{
	var row = $(this).parents(\'.item-row:last\');
	var ID = $(\'.item-row:last\').attr(\'id\');
	$("#productos_id-"+ID).val();
	if($("#productos_id-"+ID).val()!=\'\'){
	$("#producto"+ID).tokenInput("/santapatricia/plegadores/buscarplegador/I", 
		{
		tokenLimit: 1,
		minChars: 1,
		
		prePopulate: [ 
		             {id: $("#productos_id-"+ID).val(), name: ""+$("#producto"+ID).val()+""},
					],
		onAdd: function (item) {
		   var VAL=item.id;
		   var row =$(this).parents(\'.item-row\')
		   row.find(\'.productos_id\').val(VAL[\'id\']);
		   row.find(\'.pro_descripcion\').val(VAL[\'detalle\']);
		   row.find(\'.cost\').val(VAL[\'precio\']);
		   row.find(\'.delete\').attr("data-id",0);
		   $(\'#codigo-\'+ID).val(VAL[\'codigo\']);
		   $(\'#ver\'+ID).hide();
		   $(\'#ver-name\'+ID).show();
		   $(\'#productoname-\'+ID).val(VAL[\'detalle\']);
		},
		onDelete: function (item) {
			var row =$(this).parents(\'.item-row\')
		   row.find(\'.productos_id\').val(\'\');
		   row.find(\'.pro_descripcion\').val(\'\');
		   row.find(\'.cost\').val(\'\');
		   row.find(\'.qty\').val(\'\');
		   var id=row.find(\'.delete\').attr(\'data-id\');
		  	EliminarDetalle(id);
		}
	});
	}else
	{
		$("#producto"+ID).tokenInput("/santapatricia/plegadores/buscarplegador/I", 
		{			
		tokenLimit: 1,
		minChars: 1,
		onAdd: function (item) {
		   var VAL=item.id;
		   var row =$(this).parents(\'.item-row\')
		   row.find(\'.productos_id\').val(VAL[\'id\']);
		   row.find(\'.pro_descripcion\').val(VAL[\'detalle\']);
		   row.find(\'.cost\').val(VAL[\'precio\']);
		   row.find(\'.delete\').attr("data-id",0);
		   $(\'#codigo-\'+ID).val(VAL[\'codigo\']);
		   $(\'#ver\'+ID).hide();
		   $(\'#ver-name\'+ID).show();
		   $(\'#productoname-\'+ID).val(VAL[\'detalle\']);
		},
		onDelete: function (item) {
			var row =$(this).parents(\'.item-row\')
		   row.find(\'.productos_id\').val(\'\');
		   row.find(\'.pro_descripcion\').val(\'\');
		   row.find(\'.cost\').val(\'\');
		   row.find(\'.qty\').val(\'\');
		   var id=row.find(\'.delete\').attr(\'data-id\');
		  	EliminarDetalle(id);
		}
	});
	}
}';
/*BUSCAR UNIDAD*/
	/*  */		
$code.='function buscarUnidad()
{
	var row = $(this).parents(\'.item-row:last\');
	var ID = $(\'.item-row:last\').attr(\'id\');
	//alert($("#tesunidadesmedidas"+ID).val());
	if($("#tesunidadesmedidas"+ID).val()!=\'\'){
	$("#tesunidadesmedidas"+ID).tokenInput("/santapatricia/ingresos/medidas/", 
		{			
		tokenLimit: 1,
		minChars: 1,
		prePopulate: [ 
		             {id: $("#tesunidadesmedidas_id-"+ID).val(), name: ""+$("#tesunidadesmedidas"+ID).val()+""},
					],
		onAdd: function (item) {
		   var VAL=item.id;
		   $("#tesunidadesmedidas_id-"+ID).val(item.id);
		   $("#tesunidadesmedidas"+ID).val(item.name);
		   grabarDetalle(ID);
		},
		onDelete: function (item) {
		  $("#tesunidadesmedidas_id-"+ID).val(\'\');
		   $("#tesunidadesmedidas"+ID).val(\'\');
		}
	});
	}else
	{
	$("#tesunidadesmedidas"+ID).tokenInput("/santapatricia/ingresos/medidas/", 
		{
			
		tokenLimit: 1,
		minChars: 1,
		onAdd: function (item) {
		   var VAL=item.id;
		   $("#tesunidadesmedidas_id-"+ID).val(item.id);
		   $("#tesunidadesmedidas"+ID).val(item.name);
		   grabarDetalle(ID);
		},
		onDelete: function (item) {
		  $("#tesunidadesmedidas_id-"+ID).val(\'\');
		   $("#tesunidadesmedidas"+ID).val(\'\');
		}
	});
	}
}';

/*envio dew Formulario PROFORMAS*/
$code.='function GRABAR()
{
     //alert($("#inventarios").serialize());
	 if($("#cliente_id").val()){
	 $.ajax({
            type:"POST",
            url:"/santapatricia/ingresos/grabar/1",
            data:$("#inventarios").serialize(),
            beforeSend:function(){
              $("#loading").show();
          	},
            success:function(response){
                $("#loading").hide();
				$("#id").val(response);
				//alert(response);
            }
 
          	});
	 }else
	 {
		 return FALSE;
	}
 
      };';

/*GRABAR DETALLE DE PROFORMAS*/

$code.='';
$code.='function EliminarDetalle(id)
{
	if(id!=0){
	$.ajax({
            type:"POST",
            url:"/santapatricia/ingresos/eliminarDetalle/"+id,
            beforeSend:function(){
              $("#loading").show();
            },
            success:function(response){
				alert(\'Se elimino de la base de dato\');
            }
 
         });
	}else
	{
		return false;
	}
}';


$code.='function Detalle(id){
	  if(id){
	  var idletras=id;
	  //alert(id);
	  var ID=idletras.split("");
	  var n=idletras.length;
	  grabarDetalle(ID[n-1]);
	  }else
	  {
		  return FALSE;
	  }
}';


echo $code;

?>
function grabarDetalle(tr_id) 
{
  //alert(tr_id);
  var producto_id=$('#productos_id-'+tr_id).val();
  var pro_descripcion=$('#pro_descripcion-'+tr_id).val();
  var costo=isNaN($('#precio-'+tr_id).val())? 0 : $('#precio-'+tr_id).val();
  var cantidad=isNaN($('#cantidad-'+tr_id).val())? 0 : $('#cantidad-'+tr_id).val();
  var lote=isNaN($('#lote'+tr_id).val())? 0 : $('#lote'+tr_id).val();
  var empaque=isNaN($('#empaque'+tr_id).val())? 0 : $('#empaque'+tr_id).val();
  var bobinas=isNaN($('#bobinas'+tr_id).val())? 0 : $('#bobinas'+tr_id).val();
  var pesoneto=isNaN($('#pesoneto'+tr_id).val())? 0 : $('#pesoneto'+tr_id).val();
  var pesobruto=isNaN($('#pesobruto'+tr_id).val())? 0 : $('#pesobruto'+tr_id).val();
  var price = isNaN($('#total-'+tr_id).html())? 0 : $('#total-'+tr_id).html();
  var id_detalle=$('#del-'+tr_id).attr("data-id");
  var unidadmedida_id=$('#tesunidadesmedidas_id-'+tr_id).val();
  var colores_id=$('#tescolores_id-'+tr_id).val();
  var total=isNaN(price)? 0 : price;
 //alert('ID del PRODUCTO'+producto_id);
 //alert('unidad de medida'+unidadmedida_id);
 //alert('id del detalle es 0 cuando es nuevo--->\'+id_detalle);
// alert('id del tr que se graba-->\'+tr_id);
  
  if(producto_id!='' && unidadmedida_id!='')
  {
	  var dataString ='id_detalle='+id_detalle+'&tesunidadesmedidas_id='+ unidadmedida_id+'&productos_id='+ producto_id+'&pro_descripcion='+pro_descripcion+'&cantidad='+cantidad+'&precio='+costo+'&total='+total+'&lote='+lote+'&empaque='+empaque+'&bobinas='+bobinas+'&pesoneto='+pesoneto+'&pesobruto='+pesobruto+'&colores_id='+ colores_id;
	 //alert(dataString);
	  $.ajax({
            type:"POST",
            url:"/santapatricia/ingresos/grabarDetalle/1",
            data:dataString,
            beforeSend:function(){
              $("#loading").show();
            },
            success:function(response){
                $("#loading").hide();
				//alert('id del detalle grabado'+response);
				$('#del-'+tr_id).attr("data-id", response);
				$('#empaque'+tr_id).attr("data-id", response);
            }
 
         });
  }
  
}
function update_peso()
		{
  			var total = 0.00;
  			$('.peso_neto').each(function(i)
  			{
    			peso = $(this).val();
    			//alert ('peso: '+peso+' ->>>>'+i);
				if(!isNaN(peso)) total =parseFloat(total)+parseFloat(peso);
  				//alert (\'el total es : \'+total+\' ->>>>\');
   			});
			var peso = roundNumber(total,2);
			//alert ('el total es : '+total);
			//alert(\'el igv es: \'+igv);
			$('#totalkilos').val(peso);
			
			GRABAR();
		}
function update_peso_bruto(n)
{
	var a =$("#tara-"+n).val();
	var b =$("#pesoneto"+n).val();
	var c=parseFloat(a)+parseFloat(b);
	$("#pesobruto"+n).val(c);
	update_peso()
	//alert(c);
	
}
$(document).ready(function()
{
	 $('.peso').change(function(){
		 var a=$(this).attr('id');
	 	 var n= a.substr(-1);
		//alert(n);
		 update_peso_bruto(n);
		 });
	var glosa= new Array()
	$("#titulo_hilo").blur(function(){
	glosa[0]='HILOS:'+$(this).val();valglosa(glosa);
	});
	$("#color").blur(function(){
	glosa[1]='COLOR:'+$(this).val();valglosa(glosa);
	});
	$("#ancho").blur(function(){
	glosa[2]='ANCHO:'+$(this).val();valglosa(glosa);
	});
	$("#nhilos").blur(function(){
	glosa[3]='#HILOS:'+$(this).val();valglosa(glosa);
	});
	$("#metros").blur(function(){
	glosa[4]='METROS:'+$(this).val();valglosa(glosa);
	});
	$("#plegadores").blur(function(){
	glosa[5]='PLEGADORES:'+$(this).val();valglosa(glosa);
	});
	$("#totalkilos").blur(function(){
	glosa[6]=',T.KILOS:'+$(this).val();valglosa(glosa);
	});
	function valglosa(g)
	{
	g[0]='HILOS:'+$("#titulo_hilo").val();
	g[1]='COLOR:'+$("#color").val();
	g[2]='ANCHO:'+$("#ancho").val();
	g[3]='#HILOS:'+$("#nhilos").val();
	g[4]='METROS:'+$("#metros").val();
	g[5]='PLEGADORES:'+$("#plegadores").val();
	g[6]='T.KILOS:'+$("#totalkilos").val();
		$("#glosa").val(g.join(','));
		GRABAR();
	}
});
</script> 
<style type="text/css">
/*.container {
  width: 1124px;
}*/
/*.flotante{position:relative; width:350px; margin:0 auto; z-index:99999;} */
.simbolo
{
	position:absolute;
	float:left;
	margin-left:-15px !important;
}
.table th
{
	font-size:12px;
	text-align:center;
}
#items .item-row td{
	font-size:10px !important;
	padding-left:15px !important;
	}
#items .item-row input[type="text"]{
	font-size:10px !important;
	padding:0;
	}
#paid
{
	width:80% !important;
}
#glosa
{
	width:99% !important;
}
.page ul {
margin:0 !important;
}
</style>
<br />
<div class="card">
<h1>Detalle-Ingreso de Plegadores!<?php //echo "id--->".Session::get('INVENTARIO_ID')?></h1>
</div>
<div class="card-body">
<form id="inventarios">
<?php echo Form::hidden('id')?>
<?php echo Form::hidden('pr','','PL')?>
  <table width="70%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered">
     <tr>
     	<th width="56" align="left" valign="top" class="meta-head">Moneda:</th>
        <td width="302" align="left" valign="top"><?php echo Form::dbSelect('monedas','nombre',array('tesmonedas','find','aclempresas_id='.Session::get("EMPRESAS_ID")))?></td>
     	<th align="left" valign="top">Proveedor:</th>
        <td align="left" valign="top"> <input id="CL" type="text">
    <?php echo Form::hidden('cliente_id')?></td>
       </tr>
     <tr>
        <th align="left" valign="top">Fecha Emision:</th>
        <td align="left" valign="top"><?php echo Calendar::selector('femision');?></td>
        <th width="69" align="left" valign="top" class="meta-head">Serie-Número:</th>
          <td width="255" align="left" valign="top"><?php echo Form::text('serie','size="3"')?>-<?php echo Form::text('numero','size="6"')?></td>
      </tr>
     <tr>
        <th width="110" align="left" class="meta-head">F. Traslado:</th>
        <td width="236" align="left"><?php echo Calendar::selector('finiciotraslado');?></td>
        <th align="left"><span class="meta-head">Nro.Factura:</span></th>
        <td align="left"><?php echo Form::text('numerofactura','size="16" class="grabar_form"')?>
        <?php //echo Form::select('movimiento',array("AB"=>"ABONO","FA"=>'FACTURA ADELANTO',"VT"=>'VENTA',"NC"=>"NOTA DE CREDITO"))?></td>
      </tr>
      <tr>
        <th width="116" align="left" class="meta-head">Nro. O/C:</th>
        <td width="333" align="left"><?php echo Form::text('ordendecompra','size="5" class="grabar_form"')?></td>
        <th width="116" align="left" class="meta-head">&nbsp;</th>
        <td width="333" align="left">&nbsp;</td>
      </tr>
      <tr>
        <th width="116" align="left" class="meta-head">Titulo:</th>
        <td width="333" align="left"><?php echo Form::text('titulo_hilo','class="grabar_form"')?></td>
        <th width="116" align="left" class="meta-head">&nbsp;</th>
        <td width="333" align="left">&nbsp;</td>
      </tr>
      <tr>
        <th align="left" class="meta-head">Color:</th>
        <td align="left"><?php echo Form::text('color');?></td>
        <th align="left" class="meta-head">&nbsp;</th>
        <td align="left">&nbsp;</td>
      </tr>
      <tr>
        <th width="116" align="left" class="meta-head">Ancho:</th>
        <td width="333" align="left"><?php echo Form::text('ancho',' class="grabar_form"')?></td>
        <th width="116" align="left" class="meta-head">&nbsp;</th>
        <td width="333" align="left">&nbsp;</td>
      </tr>
      <tr>
        <th align="left" class="meta-head">Nro de Hilos:</th>
        <td align="left"><?php echo Form::text('nhilos');?></td>
        <th align="left" class="meta-head">&nbsp;</th>
        <td align="left">&nbsp;</td>
      </tr>
      <tr>
        <th width="116" align="left" class="meta-head">Metros:</th>
        <td width="333" align="left"><?php echo Form::text('metros','size="5" class="grabar_form"')?></td>
        <th width="116" align="left" class="meta-head">&nbsp;</th>
        <td width="333" align="left">&nbsp;</td>
      </tr>
      <tr>
        <th align="left" class="meta-head">Total Kilos:</th>
        <td align="left"><?php echo Form::text('totalkilos','size="5" class="grabar_form"')?></td>
        <th align="left" class="meta-head"></th>
        <td align="left">&nbsp;</td>
      </tr>
      <tr>
        <th width="116" align="left" class="meta-head">Plegadores:</th>
        <td width="333" align="left"><?php echo Form::text('plegadores','size="5" class="grabar_form"')?></td>
        <th width="116" align="left" class="meta-head"></th>
        <td width="333" align="left"><?php echo Form::hidden('glosa','class="grabar_form"');?></td>
      </tr>
    </table>
</form> 	
    <table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-striped" id="items">
		  <tr>
		      <th width="7%" align="left">Codigo</th>
		      <th width="34%" align="left">Producto</th>
		      <th width="14%" align="left">Medida</th>
		      <?php if($hilo){?><th width="16%" align="left">Nº Caja/Bolsa</th>
		      <th width="8%" align="left">Bobinas</th><?php }?>
              <th width="6%" align="left">P/N</th>
		      <th width="6%" align="left">P/B</th>
		  </tr>
          <?php
			if($DETALLE)
			{
				$n=0;
				$subtotal=0;
				foreach($detalles as $item){
						  $n++;
						  $subtotal=$subtotal+$item->importe;
					  ?>
				  <tr id="<?php echo $n?>" class="item-row">
				   <td>
						  <div class="delete-wpr">
						  <?php echo Form::text('codigo-'.$n,'size="10" readonly="readonly"',$item->getTesproductos()->codigo)?>
						  <a id="del-<?php echo $n?>" class="delete" href="javascript:;" title="Elimar registro" data-id="<?php echo $item->id?>">X</a>
						  </div>
					</td>
					  <td class="item-name">
						  <?php echo Form::hidden('productos_id-'.$n,'class="productos_id" readonly="readonly"',$item->tesproductos_id)?>
						  <span id="ver-name<?php echo $n?>" style="display:none;"><?php echo Form::text('productoname-'.$n,'class="producto"')?></span>
						  <span id="ver<?php echo $n;?>" class="ver"><?php echo Form::text('producto'.$n,'class="producto" placeholder="Producto" size="30"',$item->getTesproductos()->nombre.' '.$item->getTesproductos()->getProplegadores()->numero)?></span>
					  </td>
					  <td><?php echo Form::hidden('tesunidadesmedidas_id-'.$n,'readonly="readonly"',$item->tesunidadesmedidas_id)?> <?php echo Form::text('tesunidadesmedidas'.$n,'class="unidad" size="10"',$item->getTesunidadesmedidas()->nombre)?></td>
					  <?php /*?><td><?php echo Form::hidden('tescolores_id-'.$n,'readonly="readonly"',$item->tescolores_id)?> <?php echo Form::text('tescolores'.$n,'class="color" size="10"',$item->getTescolores()->nombre)?></td><?php */?>
					  <?php if($hilo){?><td> <?php echo Form::text('empaque'.$n,'class="save cajas" data-id="'.$item->id.'" size="10"',$item->empaque)?><div class="flotante" id="cajas-<?php echo $n?>"></div></td>
					  <td> <?php echo Form::text('bobinas'.$n,'class="save" size="10"',$item->bobinas)?></td><?php }?>
					  <td> <?php echo Form::hidden('tara-'.$n,'class="save" size="10"',$item->pesoneto)?><?php echo Form::text('pesoneto'.$n,'class="save peso_neto peso" size="10"')?></td>
					  <td> <?php echo Form::text('pesobruto'.$n,'class="save" size="10"',$item->pesobruto)?></td>
				  </tr>
				  
				  <?php
					  }/*FIN FOREACH*/
					if($n==0)
						{  $n=1; ?>
						  <tr id="1" class="item-row">
							 <td class="item-name">
								  <div class="delete-wpr">
								  <?php echo Form::text('codigo-1','class="productos_id" size="10" readonly="readonly"')?>
								  <a id="del-1" class="delete" href="javascript:;" title="Elimar registro" data-id="0">X</a>
								  </div>
							</td>
							  <td class="item-name">
								 <?php echo Form::hidden('productos_id-1','class="productos_id" readonly="readonly"')?>
								  <span id="ver-name1" style="display:none;"><?php echo Form::text('productoname-1','readonly="readonly"')?></span>
								  <span id="ver1" class="ver"><?php echo Form::text('producto1','class="producto" placeholder="Producto" size="30"')?></span>
							  </td>
							  <td><?php echo Form::hidden('tesunidadesmedidas_id-1')?> <?php echo Form::text('tesunidadesmedidas1','class="unidad"')?></td>
					  <?php /*?><td width="9%"><?php echo Form::hidden('tescolores_id-'.$n,'readonly="readonly"')?> <?php echo Form::text('tescolores'.$n,'class="color" size="10"')?></td><?php */?>
					  <?php if($hilo){?><td> <?php echo Form::text('empaque'.$n,'data-id="0" class="save cajas" size="10"')?><div class="flotante" id="cajas-<?php echo $n?>"></div></td>
					  <td> <?php echo Form::text('bobinas'.$n,'class="save" size="5" ')?></td><?php }?>
					  <td> <?php echo Form::text('pesoneto'.$n,'class="save peso_neto" size="5"')?></td>
					  <td> <?php echo Form::text('pesobruto'.$n,'class="save" size="5"')?></td>
							 
						  </tr>
				  <?php
						}?>
				  <?php 
				  }else{
					 $n=1; ?>

				  <tr id="1" class="item-row">
					 <td>
						  <div class="delete-wpr">
						  <?php echo Form::text('codigo-1','class="productos_id" readonly="readonly"')?>
						  <a id="del-1" class="delete" href="javascript:;" title="Elimar registro" data-id="0">X</a>
						  </div>
					</td>
					  <td>
						 <?php echo Form::hidden('productos_id-1','class="productos_id" readonly="readonly"')?>
						  <span id="ver-name1" style="display:none;"><?php echo Form::text('productoname-1','readonly="readonly"')?></span>
						  <span id="ver1" class="ver"><?php echo Form::text('producto1','class="producto" placeholder="Producto" size="30"')?></span>
					  </td>
					  <td><?php echo Form::hidden('tesunidadesmedidas_id-1')?> <?php echo Form::text('tesunidadesmedidas1','class="unidad"')?></td>
					  <?php /*?><td><?php echo Form::hidden('tescolores_id-'.$n,'readonly="readonly"')?> <?php echo Form::text('tescolores'.$n,'class="color" size="10"')?></td><?php */?>
					 <?php if($hilo){?> <td> <?php echo Form::text('empaque'.$n,'data-id="0" size="5" class="save cajas"')?><div class="flotante" id="cajas-<?php echo $n?>"></div></td>
					  <td> <?php echo Form::text('bobinas'.$n,'class="save" size="5"')?></td><?php }?>
					  <td> <?php echo Form::text('pesoneto'.$n,'class="save peso_neto" size="5"')?></td>
					  <td> <?php echo Form::text('pesobruto'.$n,'class="save" size="5"')?></td>
					  
				  </tr>
			<?php }  
			?>
            <tr id="hiderow">
		    <td colspan="12"></td>
		  </tr>
  </table>
  <table class="table-boreder">
      <tr>
     	<th colspan="5"><div style="text-align:left;"id="moneda_en_letras"><?php echo $totalenletras?></div></th>
       </tr>
  </table>
	<div class="form-actions">
    <?php echo Html::linkAction("terminar/ingresos",'TERMINAR','class="btn btn-xs btn-primary grabar_form"') ?> <?php echo Html::linkAction("ingresos/",'CANCELAR','class="btn btn-xs btn-secondary"') ?> 
</div><div id="loading" style="display:none;"><img src="/img/spin.gif" /></div>
     <div style="clear:both"></div>
</div>