<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>
<br />
<div class="card">
    <h1>Salida de Plegadores<span><?php echo Session::get('DOC_NOMBRE')?></span></h1>
</div>

<div class="form-actions">
<?php echo Html::linkAction("cargarsalida/0", 'Nueva '.Session::get('DOC_NOMBRE'),'class="btn btn-primary"') ?>&nbsp;<?php echo Html::linkAction("plegadoresmov", 'Volver ','class="btn"') ?>
</div>
<div class="menu">
<ul><li><a>Año
<select id="anio">
<?php
for($i=2011;$i<=2020;$i++)
{
	$selec='';
	if($anio==$i){
	$selec=' selected="selected"';
	}
	echo '<option value="'.$i.'" '.$selec.'>'.$i.'</option>';
}
?>
</select> 
</a></li></ul>
<?php 
$mes_actual=date('Y-m');
foreach($meses as $clave => $mes):
if($anio.'-'.$clave<=$mes_actual){
$class='';
if($mes_activo==$clave)$class=' active';
echo '<ul>';
echo '<li><a class="enviar'.$class.'" id="mes-'.$mes.'" href="javascript:;" data-id="'.$anio.'-'.$clave.'-01">'.$mes.'</a></li>'; 
echo '</ul>';
}
endforeach;?>
</div>

<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="card-body">

<div id="ver_resultado"></div>
<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">
<caption>Guias Enviadas para Servivio de Urdido</caption>
  <tr>
  	<th width="0" height="0" align="left">Nº</th>
    <th width="0" height="0" align="left">Cliente</th>
    <th width="0" height="0" align="left">Número Doc.</th>
    <th width="0" height="0" align="left">Productos </th>
    <th width="0" height="0" align="center">Acciones </th>
  </tr>
<?php $number=0;
foreach($salidas as $item){ 
$simbolo="S/. ";

switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

$number++;?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $number?></td>
  	<td height="20"><?php echo $item->getTesdatos()->razonsocial?></td>
    <td><?php echo $item->serie?>-<?php echo $item->numero?></td>
    <td>
    <small style="color:#666; font-size:10px !important; font-style:italic; ">
	<?php
    
	$n=0;$m=0;
	foreach($item->getTesdetallesalidas() as $det)
	{
		if($det->tesproductos_id!=0){$n++;
		echo $det->getTesproductos()->nombre;if(count($item->getTesdetallesalidas())>$n){echo ", ";}
		}else{
			echo $det->concepto;
			}
	}
	?>
    </small>
    </td>
    <td align="center">
   <?php if($item->codigo=='P')echo Html::linkAction('cargarsalida/'.$item->id.'/',Html::img("figuras/editar.png",'EDITAR','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar Guia - 002 - Plegadores"')?>
	<?php echo Html::linkAction('cargarsalida/'.$item->id.'/versalida',Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Ver e Imprimir Guia - 002 - Plegadores"')?>
	<?php if($item->codigo=='P')echo Html::linkAction('anular_salida/'.$item->id,"[ X ]",'class="btn btn-danger" title="ANULAR LA SALIDA DE PLEGADORES"')?>
    </td>
  </tr>
<?php }?>
</table>

</div>
<script type="text/javascript">
$(document).ready(function() {	
	$("#anio").change(function(event){
    	var id = $("#anio").find(':selected').val();
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/'+id;
     });
	$(".enviar").click(function()
	{
		var fecha = $(this).attr('data-id');
		var F=fecha.split('-');
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/'+F[0]+'/'+F[1];
	});
});
</script>