<style type="text/css">
body,td,th {
	font-family: "Times New Roman", Times, serif;
	font-size: 12px;
	color: #000;
}
body {
	background-color: #FFF;
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
</style>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<table width="110%" border="0" cellspacing="0" align="left">
  <tr>
   
    <td width="85" align="center">000883-84</td>
    <td width="388" align="lefth">DECORACIONES D EINTERIORES SUMAQ WASI SAC</td>
    <td width="99" align="lefth">001-0000000</td>
    <td width="124" align="lefth">03/11/2012</td>
  </tr>

</table>
<BR />
<br />
<br />
<table width="110%" border="0" cellspacing="1">
  <tr>
    
    <td width="13%" align="center"><p>20101619240</p></td>
    <td width="61%" align="left">CAL. PROLG.GAMARRA NO. 1151 INT.105 GAMARRA LA VICTORIA - LIMA</td>
    <td width="26%">CANJE DE LETRAS (2)</td>
  </tr>
</table>
<br />
<br />
<table width="102%" border="0" cellspacing="1">
  <tr>
    <td width="65" align="center">
		<p>579</p>
		<p>526</p>
	</td>
    
    <td width="54" align="center">
		<p>105.00</p>
		<p>48.50</p>
	</td>
    <td width="41" align="center">
		<p>Mts</p>
		<p>Mts</p>
	</td>
    <td width="259">
		<p>Tela para cortina Tull bashir Perla light</p>
		<p>Tela para cortina Tull bashir Perla light</p>
	</td>
    <td width="52">
		<p>13.30</p>
		<p>13.30</p>
	</td>
    <td width="64">
		<p>0.00</p>
		<p>0.00</p>
	</td>
    <td width="63">
		<p align="center">1396.50</p>
		<p align="center">645.00</p>
	</td>
    <td width="30">&nbsp;</td>
  </tr>
</table>
<table width="102%" border="0" cellspacing="1">
	<tr>
		<td width="87%" align="right">&nbsp;</td>
		<td width="7%">----------</td>
		<td width="6%">&nbsp;</td>
	</tr>
</table>
<table width="102%" border="0" cellspacing="1">
	<tr>
		<td width="84%" align="right">&nbsp;</td>
		<td width="11%" align="center">1000000</td>
		<td width="5%">&nbsp;</td>
	</tr>
</table>

<br />
<table width="100%" border="0" cellspacing="1">
  <tr>
    <td width="9%" align="right">&nbsp;</td>
    <td width="59%" align="lefth" >Son Mil Quinientos Noventa y 50/100 nuevos soles</td>
    <td width="32%" align="center" >&nbsp;</td>
  </tr>
</table>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<table width="268" border="0" cellspacing="1">
	<tr>
		<td width="21">&nbsp;</td>
		<td width="71">NRO LETRA:</td>
		<td width="77">1</td>
		<td width="86">2</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>F.VTO:</td>
		<td width="77">01/12/2012</td>
		<td width="86">01/01/2013</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>MONTO:</td>
		<td>S/.5000</td>
		<td>S/.5000</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>DIAS</td>
		<td>30</td>
		<td>60</td>
	</tr>
</table>
<br />
<br />
<table width="113%" border="0" cellspacing="1">
  <tr>
    <td width="25%">&nbsp;</td>
    <td width="20%">&nbsp;</td>
    <td width="6%">&nbsp;</td>
    <td width="15%">&nbsp;</td>
    <td width="12%">IGV.(18.00%)</td>
    <td width="20%">S/.398.00</td>
    <td width="2%">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>S/.10000.00</td>
    <td>&nbsp;</td>
  </tr>
</table>

