<?php
echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<script type="text/javascript">
        $(document).ready(function() {
            $("#cliente").tokenInput("<?php echo "/".$module_name."/clientes/resultados"?>", 
			{
				tokenLimit: 1,minChars: 3,
                onAdd: function (item) {
                   //item.name;
				   //alert(item.id);
				   $("#ver_resultado").load("/<?php echo $module_name?>/clientes/ver/<?php echo $campo?>/<?php echo $direccion?>/"+item.id+"/<?php echo $page?>");
				   $("#ver_resultado").css('display','block');
                },
                onDelete: function (item) {
				  $("#ver_resultado").css('display','none');
                }
            });
        });
 </script>
<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>
<div class="card">
   <h1>Clientes de la Empresa <span><?Php echo Session::get('EMPRESAS_NOMBRE')?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="form-actions">
    <?php echo Html::linkAction('crear/'.$campo.'/'.$direccion.'/'.$page, 'Nuevo Cliente','class="btn btn-primary"') ?>			    <?php echo Html::linkAction('reporte_clientes/'.$campo.'/'.$direccion.'/', 'Reporte de Clientes','class="btn btn-info"') ?>
    <?php echo Html::linkAction('listar_direcciones', 'Direcciones','class="btn btn-info"') ?>
</div>
<label>Busqueda por: (Razon Social,Ruc,Codigo, Direccion)</label>
<input id="cliente" name="cliente" type="text"/> <hr />
<div class="card-body">
<div id="ver_resultado"></div>
<table width="99%" class="table table-bordered table-striped">
  <tr>
  	<td width="17"><h4>Nº</h4></td>
    <td width="32"><h4>Cod:<span class="span_float"><?php echo Html::linkAction('listado/codigo/ASC/'.$page,Html::img("figuras/ascendente.gif",'Editar','style="width: 8px;"'),'');?>
    	<?php echo Html::linkAction('listado/codigo/DESC/'.$page,Html::img("figuras/descendente.gif",'Editar','style="width: 8px;"'),'');?></span></h4></td>
    <td width="60"><h4>Nº-Ant:<span class="span_float"><?php echo Html::linkAction('listado/codigo_ant/ASC/'.$page,Html::img("figuras/ascendente.gif",'Editar','style="width: 8px;"'),'');?>
    	<?php echo Html::linkAction('listado/codigo/DESC/'.$page,Html::img("figuras/descendente.gif",'Editar','style="width: 8px;"'),'');?></span></h4></h4></td>
    <td width="52"><h4>Razon Social:<span class="span_float"><?php echo Html::linkAction('listado/razonsocial/ASC/'.$page,Html::img("figuras/ascendente.gif",'Editar','style="width: 8px;"'),'');?>
    	<?php echo Html::linkAction('listado/razonsocial/DESC/'.$page,Html::img("figuras/descendente.gif",'Editar','style="width: 8px;"'),'');?></span></h4></td>
    <td width="34"><h4>Ruc:<span class="span_float"><?php echo Html::linkAction('listado/ruc/ASC/'.$page,Html::img("figuras/ascendente.gif",'Editar','style="width: 8px;"'),'');?>
    	<?php echo Html::linkAction('listado/ruc/DESC/'.$page,Html::img("figuras/descendente.gif",'Editar','style="width: 8px;"'),'');?></span></h4></td>
    <td width="84"><h4>Direccion:</h4></td>
    <td width="64"><h4>Telefono:</h4></td>
    <td width="33"><h4>Pais:<span class="span_float"><?php echo Html::linkAction('listado/pais/ASC/'.$page,Html::img("figuras/ascendente.gif",'Editar','style="width: 8px;"'),'');?>
    	<?php echo Html::linkAction('listado/pais/DESC/'.$page,Html::img("figuras/descendente.gif",'Editar','style="width: 8px;"'),'');?></span></h4></td>
    <td width="74"><h4>Contacto:</h4></td>
    <td width="51"><h4>Estado:</h4></td>
    <td width="65"><h4>Acciones:</h4></td>
  </tr>
<?php $n=0;
foreach($datos->items as $item){ $n++;?>
  <tr id="<?php echo $item->id?>">
  	<td><?php echo $n?></td>
    <td><?php echo $item->codigo?>-<?php echo $item->sufijo?></td>
    <td><?php echo $item->codigo_ant?></td>
    <td><?php echo $item->razonsocial?></td>
    <td><?php echo $item->ruc?></td>
    <td><?php echo $item->direccion?></td>
    <td><?php echo $item->telefono?></td>
    <td><?php echo $item->pais?></td>
    <td><?php echo $item->contacto?><br />
	<?php if(empty($item->contacto))
	{
		echo Ajax::link($module_name."/contactos/crear/$item->id",'Agregar',$item->id); }else{ 
		//echo Ajax::link("santapatricia/contactos/borrar/$item->idcontato",Html::img("figuras/eliminar.png",'Eliminar','style="width: 15px;margin-left:2px;margin-right:2px;"'),$item->id,'','title="Borrar este Contacto" onclick="return confirm(\'¿Está Seguro de borrar a este conacto?\')"');
		echo Ajax::link($module_name."/contactos/listado/$item->id",Html::img("figuras/ver.png",'Ver','style="width: 15px;margin-left:2px;margin-right:2px;"'),$item->id,NULL,'title="Ver todos los contactos"');
		}?></td>
    <td>
    <?php 
	 if($item->activo=='0'){
	 echo Html::linkAction('activar/'.$campo.'/'.$direccion.'/'.$item->id.'/'.$page,Html::img("figuras/circulo_rojo.png",'Editar','style="width: 20px;margin-left:5px;margin-right:5px;"'),'');
	 }else{
	 echo Html::linkAction('desactivar/'.$campo.'/'.$direccion.'/'.$item->id.'/'.$page,Html::img("figuras/circulo_verde.png",'Editar','style="width: 20px;margin-left:5px;margin-right:5px;"'), 'onclick="return confirm(\'¿Está seguro?\')"');}?>
    </td>
    <td>
	<?php echo Html::linkAction('editar/'.$campo.'/'.$direccion.'/'.$item->id.'/'.$page,Html::img("figuras/editar.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'')?>
    <?php echo Html::linkAction('borrar/'.$campo.'/'.$direccion.'/'.$item->id.'/'.$page,Html::img("figuras/eliminar.png",'Eliminar','style="width: 20px;margin-left:1px;margin-right:1px;"'), 'onclick="return confirm(\'¿Está seguro?\')"');?>
    <?php echo Html::linkAction('ver/'.$campo.'/'.$direccion.'/'.$item->id.'/'.$page,Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'));?>
    </td>
  </tr>
<?php }?>
</table>
<?php View::partial('paginators/classic', false, array('page' => $datos ,'url' => Router::get('controller_path').'/listado/'.$campo.'/'.$direccion.'')); ?>
<div class="form-actions">
    <?php //echo Html::linkAction('crear/'.$campo.'/'.$direccion.'/'.$page, 'Crear Clientes','class="btn btn-primary"') ?>
</div>
</div>