<div class="card">
    <h1>Proveedores de la Empresa <span><?Php echo Session::get('EMPRESAS_NOMBRE')?></span></h1>
</div>
<div class="form-actions">
    <?php echo Html::linkAction('crear/'.$campo.'/'.$direccion.'/', 'Nuevo Cliente','class="btn btn-xs btn-primary"') ?>			    <?php echo Html::linkAction('listado/'.$campo.'/'.$direccion.'/', 'Volver','class="btn btn-xs btn-info"') ?>
    <?php echo Html::linkAction('reporte_clientes_imprimir/'.$campo.'/'.$direccion.'/','Ver Para Imprimir','class="btn btn-xs btn-info"');?>
    </div>
    
<div class="card-body">
<div id="ver_resultado"></div>
<table id="exportar_excel" width="99%" class="table table-bordered table-striped">
  <tr>
  	<th width="17">Nº</th>
    <th width="109">Cod:<span class="span_float"><?php echo Html::linkAction('reporte_clientes/codigo/ASC/',Html::img("figuras/ascendente.gif",'Editar','style="width: 8px;"'),'');?>
   	  <?php echo Html::linkAction('reporte_clientes/codigo/DESC/',Html::img("figuras/descendente.gif",'Editar','style="width: 8px;"'),'');?></span></th>
    <th width="101">Nº-Ant:<span class="span_float"><?php echo Html::linkAction('reporte_clientes/codigo_ant/ASC/',Html::img("figuras/ascendente.gif",'Editar','style="width: 8px;"'),'');?>
   	  <?php echo Html::linkAction('reporte_clientes/codigo/DESC/',Html::img("figuras/descendente.gif",'Editar','style="width: 8px;"'),'');?></span></th>
    <th width="226">Razon Social:<span class="span_float"><?php echo Html::linkAction('reporte_clientes/razonsocial/ASC/',Html::img("figuras/ascendente.gif",'Editar','style="width: 8px;"'),'');?>
   	  <?php echo Html::linkAction('reporte_clientes/razonsocial/DESC/',Html::img("figuras/descendente.gif",'Editar','style="width: 8px;"'),'');?></span></th>
    <th width="78">Ruc:<span class="span_float"><?php echo Html::linkAction('reporte_clientes/ruc/ASC/',Html::img("figuras/ascendente.gif",'Editar','style="width: 8px;"'),'');?>
   	  <?php echo Html::linkAction('reporte_clientes/ruc/DESC/',Html::img("figuras/descendente.gif",'Editar','style="width: 8px;"'),'');?></span></th>
    <th width="251">Direccion:</th>
    <th width="64">Telefono:</th>
    <th width="31">Pais:<span class="span_float"><?php echo Html::linkAction('reporte_clientes/pais/ASC/',Html::img("figuras/ascendente.gif",'Editar','style="width: 8px;"'),'');?>
   	  <?php echo Html::linkAction('reporte_clientes/pais/DESC/',Html::img("figuras/descendente.gif",'Editar','style="width: 8px;"'),'');?></span></th>
  </tr>
<?php $n=0;
foreach($datos as $item){ $n++;?>
  <tr id="<?php echo $item->id?>">
  	<td><?php echo $n?></td>
    <td><?php echo $item->codigo?>-<?php echo $item->sufijo?></td>
    <td><?php echo $item->codigo_ant?></td>
    <td><?php echo $item->razonsocial?></td>
    <td><?php echo $item->ruc?></td>
    <td><?php echo $item->direccion?></td>
    <td><?php echo $item->telefono?></td>
    <td><?php echo $item->pais?></td>
  </tr>
<?php }?>
</table>
<?php //View::partial('paginators/classic', false, array('page' => $datos ,'url' => Router::get('controller_path').'/listado/'.$campo.'/'.$direccion.'')); ?>
<div class="form-actions">
    <?php //echo Html::linkAction('crear/'.$campo.'/'.$direccion.'/'.$page, 'Crear Clientes','class="btn btn-xs btn-primary"') ?>
</div>
</div>