<div id="pago_con_cheques">
       
<script type="text/javascript">
$(document).ready(function()
{
	$('#tesbancos_id').live("change",function(){
		var value = $('#tesbancos_id option:selected').html();
		$("#bancos").html(value);
		});
	$('#cuentas_id').live("change",function(){
		var value = $('#cuentas_id option:selected').val();
		var v = $('#cuentas_id option:selected').html();
		$("#tesdetallevauchers_tescuentascorrientes_id").val(value);
		$.ajax({
            type:"POST",
            url:"/<?php echo $module_name?>/vouchers/plancontable/"+value,
            success:function(response){
			$("#tesdetallevauchers_plancontable").val(response);
			$("#plan").html(response);
            }
 		});
		
		
	 });

});
</script>
<?php if($tessalidas_id==0){?>
<div>Seleccione el Banco: <?php echo Ajax::dbSelect('tesbancos_id','nombre',array('tesbancos','find','conditions: aclempresas_id='.Session::get('EMPRESAS_ID')),'cuentas',$module_name.'/vouchers/cuentacorriente/','Seleccione');?></div>
<div id="cuentas"></div>
<?php }?>
<div id="detalle">
<?php echo Form::open()?>
<?php echo Form::hidden('tesdetallevauchers.id');?>
<?php echo Form::hidden('tesdetallevauchers.tesvauchers_id','',Session::get('V_ID'));?>
<?php echo Form::hidden('tesdetallevauchers.tesingresos_id','',0);?>
<?php echo Form::hidden('tesdetallevauchers.tessalidas_id','',0);?>
<?php echo Form::hidden('tesdetallevauchers.abono','',1);?>
<?php echo Form::hidden('tesdetallevauchers.cargos','',0);?>
<?php echo Form::hidden('tesdetallevauchers.tesdatos_id','',0);?>
<?php echo Form::hidden('tesdetallevauchers.tescuentascorrientes_id','',0);?>
<?php echo Form::hidden('tesdetallevauchers.estado','',1);?>
<?php echo Form::hidden('tesdetallevauchers.cargos','',0);?>
<?php echo Form::hidden('tesdetallevauchers.plancontable'); ?>
<table id="vauchers" width="86%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
  <tr>
    <th align="left">Cuenta General</th>
    <th align="left">Nº Docuemnto</th>
    <th align="left">Fecha Vcto</th>
    <th align="left">Codigo Auxiliar</th>
    <th align="left">Descripcion</th>
    <th align="left">Cargo</th>
    <th align="left">Abono</th>
  </tr>
  <tr>
    <td width="19%" id="plan"></td>
    <td width="10%"><?php echo Form::text('tesdetallevauchers.noperacion','placeholder="# operacion"'); ?></td>
    <td width="14%">-</td>
    <td width="14%">-</td>
    <td width="14%"><?php echo $pago->nombre;?></td>
    <td width="14%">-</td>
    <td width="15%"><?php if(!empty($total)){$total=$total;}else{$total=0;}echo Form::text('tesdetallevauchers.monto','',number_format($total,2,'.','')); ?></td>
  </tr>
</table>
<?php echo Form::submit('GRABAR','class="btn btn-primary"');?>
<?php echo Form::close()?>
</div>
</div>