<?php 
View::content();
//echo $salida_id;
switch ($vc->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
	default: $simbolo=''; break;
}
if($vc->voucherformadepagos_id==10)$simbolo='S/. ';
switch ($vc->voucherformadepagos_id)
{
	case 1: $url='efectivo/1'; break;
	case 2: $url='cheques/2/'.$salida_id; break;
	case 3: $url='letras/3/0'; break;
	case 4: $url=''; break;
	case 5: $url='bancos/6'; break;
	case 6: $url='bancos/5'; break;
	case 7: $url=''; break;
	case 8: $url='bancos/8'; break;
	case 9: $url=''; break;
	case 10: $url='detraccion/10'; break;
	default: $url=''; break;
}
?>
<div class="card">
<h2>Vouchers</h2>
</div>

<div class="card-body">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <caption> Aun no se ha grabado</caption>
  <tr>
    <td colspan="2"><?php echo $empresa->razonsocial?></td>
    <td width="13%">VOUCHERS GENERAL #</td>
    <td width="15%"><?php echo $numero?></td>
    <td width="13%">OPERACION:</td>
    <td width="12%"><?php echo $vc->getVoucherformadepagos()->operacion?></td>
    <td width="14%">ASIENTO:</td>
    <td width="5%"><?Php echo $asiento?></td>
    <td width="5%">MES:</td>
    <td width="5%"><?php echo date('m');?></td>
  </tr>
  <tr>
    <td width="10%">FECHA:</td>
    <td width="8%"><?php echo date('Y-m-d');?></td>
    <td>IMPORTE:</td>
    <td><?php echo $simbolo?> <?php echo number_format($vc->importe,2,'.','')?></td>
    <td>T/C</td>
    <td><?php echo $vc->getTestipocambios()->compra;?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th align="left">Cta. General</th>
    <th align="left">Nº Doc.</th>
    <th align="left">F. Vto.</th>
    <th align="left">Cod Auxiliar</th>
    <th colspan="4" align="left">Descripcion</th>
    <th align="left">Cargos</th>
    <th>Abonos</th>
    <th>Accion</th>
  </tr>
  <?Php 
  $doc='';
  $i=0;
  foreach($detalles as $item):
  $i++;
	$cuenta=$item->plancontable;
	$fechavcto=NULL;
	$descripcion=$vc->getVoucherformadepagos()->nombre;
  if($item->tesingresos_id!=0)
  {
	  $cuenta=$item->getTesingresos()->cuentaporpagar;
	  $num_doc=$item->getTesingresos()->serie.'-'.$item->getTesingresos()->numero;
	  $fechavcto=$item->getTesingresos()->fvencimiento;
	  $codauxiliar=$item->getTesingresos()->getTesdatos()->ruc;
	  $descripcion=$item->getTesingresos()->getTesdatos()->razonsocial;
  }
  if($item->tessalidas_id!=0)
  {
	 $cuenta=$item->getTessalidas()->cuentaporpagar;
	 $num_doc=$item->getTessalidas()->serie.'-'.$item->getTessalidas()->numero;
	 $fechavcto=$item->getTessalidas()->fvencimiento;
	 $codauxiliar=$item->getTessalidas()->getTesdatos()->ruc;
	 $descripcion=$item->getTessalidas()->getTesdatos()->razonsocial;
  }
  ?>
  <?php echo Form::open()?>
  <?php echo Form::hidden('contador','',$i)?>
  <?php echo Form::hidden('tesdetallevauchers-'.$i.'.id','',$item->id);?>
  <?php echo Form::hidden('tesdetallevauchers-'.$i.'.tesingresos_id','',$item->tesingresos_id);?>
  <tr>
    <td><?php echo $cuenta?></td>
    <td><?php echo $num_doc?></td>
    <td><?php if(!empty($fechavcto))echo $fechavcto;else echo '-';?></td>
    <td><?php echo $codauxiliar?></td>
    <td colspan="4"><?php echo $descripcion?></td>
    <td><?php if($item->cargos==1)echo Form::text('tesdetallevauchers-'.$i.'.monto','',$item->monto).Form::submit('Modificar','class="btn btn-primary"'); else echo '';?></td>
    <td><?php if($item->abono==1)echo $item->monto; else echo '';?></td>
    <td><?php echo Html::linkAction('eliminardetalle/'.$item->id,Html::img("figuras/eliminar.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'));?></td>
  </tr>
  <?php echo Form::close()?>
  <?php 
  if($i==1)$doc.=$num_doc;else $doc.='-'.$num_doc;
  endforeach;?>
  <tr>
    <th colspan="3">&nbsp;</th>
    <th colspan="3"></th>
    <th colspan="3"></th>
    <th></th>
  </tr>
  <tr>
    <td colspan="3">Aprobador pro:</td>
    <td colspan="3">Contador</td>
    <td colspan="3">Recibido por:</td>
    <td>&nbsp;</td>
  </tr>
  </table>
  
<script type="text/javascript">
$(document).ready(function()
{
$("#pago").load('/<?php echo $module_name?>/vouchers/<?php echo $url?><?php if($vc->voucherformadepagos_id==3)echo '/'.$doc?>');
});
</script>
<hr />
<div id="pago"></div>
<div class="form-actions">
    <?php echo Html::linkAction("creardetalle/", 'Agregar detalles','class="btn btn-secondary"') ?>
    <?php //echo Html::linkAction("terminer/100", 'Terminar','class="btn btn-primary"') ?>
</div>
<?php echo Form::close()?>
</div>