<?php //echo $vale?>
<table id="vauchers" width="86%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped"> 
  <tr>
    <th width="19%" align="left">Cuenta General</th>
    <th width="10%" align="left">Nº Docuemnto</th>
    <th width="14%" align="left">Fecha Vcto</th>
    <th width="14%" align="left">Codigo Auxiliar</th>
    <th width="14%" align="left">Descripcion</th>
    <th width="14%" align="left">Cargo</th>
    <th width="15%" align="left">Abono</th>
  </tr>
  <tr>
    <td width="19%"><?php echo $tesdetallevauchers->plancontable;
	 echo Form::hidden('tesdetallevauchers.plancontable'); ?></td>
    <td width="10%"><?php echo $ingreso->numero?></td>
    <td width="14%"><?php echo $ingreso->fvencimiento?></td>
    <td width="14%">-</td>
    <td width="14%"><?php echo $ingreso->getTesdatos()->razonsocial;?></td>
    <td width="14%">-</td>
    <td width="15%"><?php echo number_format($tesdetallevauchers->monto,2,'.',''); ?></td>
  </tr>
</table>
