<div class="page-header">
    <h1>Crear Banco</h1>
</div>      
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('tesbancos.id') ?>
<div class="control-group">
    <label class="control-label">Nombre de la Empresa* : </label>
    <div class="controls">
        <?php echo Form::dbSelect('tesbancos.aclempresas_id', 'nombre') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Nombre del Banco* : </label>
    <div class="controls">
        <?php echo Form::text('tesbancos.nombre') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Abreviatura* : </label>
    <div class="controls">
        <?php echo Form::text('tesbancos.abr') ?>
    </div>
</div>

<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
