<div class="page-header">
    <h1>
        Edición del Banco
        <small><?php eh(strtoupper($tesbancos->login)) ?></small>
    </h1>
</div>      
     
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('tesbancos.id') ?>
<div class="control-group">
    <label for="tesbancos_aclempresas_id">Nombre de la Empresa* : </label>
    <div class="controls">
        <?php echo Form::dbSelect('tesbancos.aclempresas_id', 'nombre') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_clave">Nombre del Banco* : </label>
    <div class="controls">
        <?php echo Form::text('tesbancos.nombre') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_clave2">Abreviatura* : </label>
    <div class="controls">
        <?php echo Form::text('tesbancos.abr') ?>
    </div>
</div>

<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
