<?php View::content();?>
<div class="card">
    <h1>Listado de <?Php echo Session::get('tipo_nombre')?><span>Eventos de <?Php echo Session::get('tipo_nombre')?></span></h1>
</div>
<div class="form-actions">
<?php echo Html::linkAction('crear','Volver a crear','class="btn btn-xs"')?>
<?php echo Html::linkAction('','Ir a calendario ','class="btn btn-xs"')?>
</div>
<div class="card-body">
<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
  <tr>
  	<th width="17">Nº</th>
    <th width="107">Titulo</th>
    <th width="135">Fecha inicio</th>
    <th width="93">Fecha fin</th>
    <th width="93">mas_info</th>
    <th width="93">observaciones</th>
    <th width="93">acciones</th>
  </tr>
<?php $n=0;
foreach($eventos as $item){ $n++;?>
  <tr>
  	<td><?php echo $n?></td>
    <td><?php echo $item->titulo?> <?php echo $item->subtitulo?></td>
    <td><?php echo $item->fecha_inicio?> <?php echo $item->hora_inicio ?></td>
    <td><?php echo $item->fecha_fin?> <?php echo $item->hora_fin ?></td>
    <td><?Php echo $item->telefono?> / <?Php echo $item->correo?> / <?Php echo $item->correo?></td>
    <td><?Php echo $item->mas_info?></td>
    <td><?php echo Html::linkAction('editar/'.$item->id,'Editar','class="btn btn-xs"')?><?php echo Html::linkAction('eliminar/'.$item->id,'Eliminar','class="btn btn-xs"')?></td>
  </tr>
<?php }?>
</table>
</div>