<script type="text/javascript">
$(document).ready(function()
{
	$(".ocultar").live("click",function(){
		var id=$(this).attr('id');
		$("#caja-"+id).hide();
});
$("#CL").tokenInput("/<?php echo $module_name?>/salidas/buscarproveedor", 
{
	tokenLimit: 1,
	minChars: 2,
<?php if(!empty($salida->tesdatos_id)){?>
	prePopulate: [ 
	{id: <?Php echo $salida->tesdatos_id?>, name: "<?php echo $salida->getTesdatos()->razonsocial?>"},
	 ],
<?php }?>
	onAdd: function (item){
	var VAL=item.id;
	$("#salida_tesdatos_id").val(VAL);
	var DIR=item.name.split('(');
    $("#salida_direccion_entrega").val(DIR[1]);
	},
	onDelete: function (item) {
	}
	});
/*transporte*/
$("#prodetalletransportes_protransportes_id").tokenInput("/<?php echo $module_name?>/salidas/transportes", 
{
	tokenLimit: 1,
	minChars: 2,
<?php if(!empty($prodetalletransportes->protransportes_id)){?>
	prePopulate: [ 
	 {id: <?php echo $prodetalletransportes->protransportes_id?>, name: "<?php echo $prodetalletransportes->getProtransportes()->marca.' '.$prodetalletransportes->getProtransportes()->numeroplaca?>"},
	 ],
<?php }?>
		});
/*transportistas*/
	$("#prodetalletransportes_protransportistas_id").tokenInput("/<?php echo $module_name?>/salidas/transportistas", 
	{
	tokenLimit: 1,
	minChars: 2,
<?php if(!empty($prodetalletransportes->protransportistas_id)){?>
	prePopulate: [ 
	 {id: <?php echo $prodetalletransportes->protransportistas_id?>, name: "<?php echo $prodetalletransportes->getProtransportistas()->nombre?> <?php echo $prodetalletransportes->getProtransportistas()->numerobrevete?>"},
	 ],
<?php }?>
	});
	$("#detalles_tescolores_id").tokenInput("/<?php echo $module_name?>/salidas/colores/", 
	{
	tokenLimit: 1,
	minChars: 1,
	onAdd: function (item) {
	},
	onDelete: function (item) {
	}
	});
	$("#detalles_tesproductos_id").tokenInput("<?php echo "/".$module_name."/salidas/producto/"?>", 
	{
	tokenLimit: 1,
	minChars: 1,
	onAdd: function (item) {
	},
	onDelete: function (item) {
	}
	});
	$("#detalles_tesunidadesmedidas_id").tokenInput("<?php echo "/".$module_name."/ordendecompra/medidas/"?>", 
	{
	tokenLimit: 1,
	minChars: 1,
	onAdd: function (item) {
		},
	onDelete: function (item) {
		}
	});
});
</script>
<?php View::content()?>
<?php echo Ajax::form('guia',$module_name."/ventasproductos/grabardetalle",'form-inline','post')?>
<pre> Ingresar productos para : <?php echo Session::get('DOC_NOMBRE')?></pre>
  <div class="input-prepend input-append">
  <span class="add-on">Producto</span>
  <?php echo Form::text('detalles.tesproductos_id')?>
  </div>
  <div class="input-prepend input-append">
  <span class="add-on">Modelo</span>
  <?php echo Form::text('detalles.tesunidadesmedidas_id')?>
  </div>
  <div class="input-prepend input-append">
  <span class="add-on">Marca</span>
  <?php echo Form::text('detalles.tescolores_id')?>
  </div>
  <div class="input-prepend input-append">
  <span class="add-on">Cantida</span>
  <?php echo Form::text('detalles.cantidad')?>
  </div>
  <div class="input-prepend input-append">
  <span class="add-on">Precio</span>
  <?php echo Form::text('detalles.preciounitario')?>
  </div>
  <button type="submit" class="btn btn-xs">Enviar</button>
<?php echo Form::close()?>
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="1" class="table table-hover">
<caption> Lista de productos en contrato </caption>
  <tr>
    <th width="34%">Producto</th>
    <th width="9%">Cantidad</th>
    <th width="20%">Unidad</th>
    <th width="20%">Costo unitario</th>
    <th width="9%">Total</th>
    <th width="8%">Accion</th>
  </tr>
  <?php 
  $n=0;
  foreach($detalles as $item){
	  $n++;
	  ?> 
  <tr id="<?php echo $item->id?>">
    <td><?php echo $n?>. <?php if(!empty($item->tesproductos_id)){echo $item->getTesproductos()->detalle?> <?Php echo $item->getTescolores()->nombre;}?></td>
    <td><?php echo $item->cantidad?></td>
    <td><?Php echo $item->getTesunidadesmedidas()->simbolo?></td>
    <td><?php echo $item->preciounitario?></td>
    <td><?php echo $item->importe?></td>
    <td><?php echo Html::linkAction('eliminar/'.$item->id,'Elminar',"class='btn'")?></td>
  </tr>
  <?php }?>
</table>