<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>
<div class="card">
    <h1>Facturacion!<span><?php echo $titulo?> <?php echo Session::get('DOC_NOMBRE')?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>

<div class="form-actions">
<?php ?><?php if(Session::get('DOC_ID')==7)echo Html::linkAction("", 'Volver ','class="btn"').' '.Html::linkAction("cargar_doc/7/factura_servicio", 'Crear Factura por Servicio ','class="btn btn-primary"').'-'.Html::linkAction("cargar_doc/15/listado_servicio", 'Guias por servicios','class="btn btn-primary"');
 if(Session::get('DOC_ID')==15)echo Html::linkAction("cargar_doc/7/listado_servicio", 'Volver ','class="btn"').' '.Html::linkAction("cargar_doc/15/guia_servicio", 'Crear Guia por Servicio ','class="btn btn-primary"') ?> 
</div>
<div class="card-body">
<div id="ver_resultado"></div>
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">
<caption><?php $titulos="Facturas Emitidas";if(Session::get('DOC_ID')==15)$titulos="Guias Emitidas"; echo $titulos?></caption>
<thead>
  <tr>
 	<th width="17">Nº</th>
    <th width="108">Cliente</th>
    <th width="54">Número Doc.</th>
    <th width="200">Productos </th>
    <th width="77">Sub-total</th>
    <th width="60">Igv</th>
    <th width="72">Total</th>
    <th width="60">Acciones </th>
  </tr>
</thead>
<?php $number=0;
foreach($salidas as $item){ 
$simbolo="S/. ";

switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

$number++;?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $number?></td>
 	<td height="20"><?php echo $item->getTesdatos()->razonsocial?></td>
    <td><?php echo $item->serie?>-<?php echo $item->numero?></td>
    <td>
    <small style="color:#666; font-size:10px !important; font-style:italic; ">
	<?php
	$n=0;$m=0;
	foreach($item->getTesdetallesalidas() as $det)
	{
		if($det->tesproductos_id!=0){$n++;
		echo $det->getTesproductos()->nombre;if(count($item->getTesdetallesalidas())>$n){echo ", ";}
		}else{
			echo $det->concepto;
			}
	}
	?>
    </small>
    </td>
    <td><?php if($item->totalconigv!='NaN.00' && !empty($item->totalconigv))echo $simbolo.number_format($item->totalconigv-$item->igv,2,'.','');else echo('S/ 00.00');?></td>
    <td><?php if($item->totalconigv!='NaN.00' && !empty($item->totalconigv))echo $simbolo.number_format($item->igv,2,'.','');else echo('S/ 00.00')?></td>
    <td><?php if($item->totalconigv!='NaN.00' && !empty($item->totalconigv))echo $simbolo.number_format($item->totalconigv,2,'.','');else echo('S/ 00.00')?></td>
  <td>
   <?php if($item->estadosalida=="Editable"){
	   $pos=strpos($item->npedido,'PA');
	if($pos===FALSE){echo Html::linkAction('cargarsalida/'.$item->id.'/factura_servicio_detalle',Html::img("figuras/editar.png",'EDITAR','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar Guia - 001"');}else
	{
		//factura_adelanto
		echo Html::linkAction('factura_adelanto/'.$item->id,Html::img("figuras/editar.png",'EDITAR','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar Factura! - 001"');
	}
   }?>
	<?php 
	//echo $item->npedido;
	$pos=strpos($item->npedido,'PA');
	if($pos===FALSE){
	echo Html::linkAction('cargarsalida/'.$item->id.'/versalida_f',Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Ver e Imprimir Factura!"');}else{echo Html::linkAction('cargarsalida/'.$item->id.'/versalida_adelanto',Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Ver e Imprimir Factura!"');}?>
    </td>
  </tr>
<?php }?>
</table>
<hr />
<?php if(Session::get('DOC_ID')==7){?>
<?Php echo Form::open($module_name.'/ventas/generarfactura','POST');?>
<fieldset>
  <legend>Seleccionar Guia(s) a Facturar!</legend>
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">
<caption>Seleccionar Guia(s)para Facturar!</caption>
  <thead>
  <tr>
  	<th width="17">Nº</th>
    <th width="288">Cliente</th>
    <th width="88">Número Doc.</th>
    <th width="193"> Numero de Factura</th>
    <th width="92">Acciones </th>
  </tr>
  </thead>
<?php $number=0;
foreach($guias as $item){ 
$simbolo="S/. ";
switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

$number++;?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $number?></td>
  	<td height="20"><?php echo $item->getTesdatos()->razonsocial?></td>
    <td><?php echo $item->serie?>-<?php echo $item->numero?></td>
    <td><?php echo $item->numerofactura?></td>
  <td>
    <label class="checkbox" style="float:left; width:90px;">
          <input type="checkbox" name="itemSelect[]" value="<?php echo $item->id?>" class="sele"> Seleccionar
        </label>
    </td>
 </tr>
<?php }?>
</table>
<?php if($number!=0){?>
 <button type="submit" class="btn btn-primary">Emitir Factura!</button> 
 <?php }?>
  </fieldset>
  <?php echo Form::hidden('facturas.ids');?>
<?Php echo Form::close();?>
<script type="text/javascript">
$(document).ready(function(){
	$('.sele').click(function(){
		var selectedItems = new Array();
		$("input[@name='itemSelect[]']:checked").each(function(){
			selectedItems.push($(this).val());
		});
		$("#facturas_ids").val(selectedItems);
	});
});
</script>
<?php }?>
</div>