<div class="card">
    <h1>Detalle del Documento!<span><?php echo Session::get('DOC_NOMBRE')?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered">
  <tr>
    <th width="21%" align="left">Pedido:</th>
    <td width="45%"><?php echo $salida->npedido;?></td>
    <th width="20%" align="left">Serie-Numero:</th>
    <td width="14%"><?php echo $salida->serie;?>-<?php echo $salida->numero;?></td>
  </tr>
  <tr>
    <th align="left">Moneda:</th>
    <td><?php echo $salida->getTesmonedas()->nombre;?></td>
    <th align="left">Fecha de Traslado:</th>
    <td><?php echo $salida->finiciotraslado;//finiciotraslado?></td>
  </tr>
  <tr>
    <th align="left">Proveedor:</th>
    <td colspan="3"><?php echo $salida->getTesdatos()->razonsocial?></td>
  </tr>
  <tr>
    <th align="left">Direccion de Entrega:</th>
    <td colspan="3"><?php echo $salida->direccion_entrega;//finiciotraslado?></td>
  </tr><?php if(Session::get('DOC_ID')==15){?>
  <tr>
    <th align="left">Conductor:</th>
    <td>
      <?php echo $prodetalletransportes->getProtransportistas()->nombre;?>
    </td>
    <th align="left">Transporte:</th>
    <td><?php echo $prodetalletransportes->getProtransportes()->modelo;?></td>
  </tr><?php }?>
</table>
<br />
<div id="guia">
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-striped table-hover">
<caption>Lista de productos en Guia</caption>
  <thead>
  <tr>
    <th width="46%" align="left">Producto</th>
    <th width="13%" align="left">Cantidad</th>
    <th width="7%"align="left">Unidad</th>
    <th width="23%"align="left">P/unitario</th>
    <th width="11%"align="left">Total</th>
  </tr>
  </thead>
  <?php 
  $n=0;
  $subtotal=0;
  foreach($detalles as $item){
	  $n++;
	  $subtotal=$subtotal+$item->importe;
	  ?> 
  <tr id="<?php echo $item->id?>">
    <td><?php echo $n?>. <?php echo $item->getTesproductos()->detalle?> <?Php echo $item->getTescolores()->nombre?></td>
    <td><?php echo $item->cantidad?></td>
    <td><?Php echo $item->getTesunidadesmedidas()->simbolo?></td>
    <td><?php if(!empty($item->preciounitario))echo number_format ($item->preciounitario,2,'.','')?></td>
    <td><?php if(!empty($item->preciounitario))echo number_format ($item->importe,2,'.','')?></td>
  </tr>
  <?php }?>
  <tr>
  <th colspan="5">&nbsp;</th>
    </tr>
  <?php if(Session::get('DOC_ID')==9){
  $igv=0;
  ?>
  <tr>
  <td width="46%">&nbsp;</td>
    <td width="13%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <th width="23%">Sub-Total</th>
    <th width="11%"><?php if(!empty($salida->tescontratos_id))$subtotal=$subtotal*$salida->getTescontratos()->duracion; else $subtotal?><?php echo number_format($subtotal,2,'.','')?></th>
    </tr>
    <tr>
  <td width="46%">&nbsp;</td>
    <td width="13%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <th width="23%">A cuenta</th>
    <th width="11%"><?php  echo number_format($salida->acuenta,2,'.','')?></th>
    </tr>
    <tr>
  <td width="46%">&nbsp;</td>
    <td width="13%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <th width="23%">Total</th>
    <th width="11%"><?php if(!empty($salida->totalconigv))$total=$salida->totalconigv; else $total=$subtotal-$salida->acuenta?><?php echo number_format($total,2,'.','')?></th>
    </tr>
  <?php 
  }else{?>
  <tr>
  <td width="46%">&nbsp;</td>
    <td width="13%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <th width="23%">Sub-Total</th>
    <th width="11%"><?php if(!empty($salida->tescontratos_id))$subtotal=$subtotal*$salida->getTescontratos()->duracion; else $subtotal?><?php echo number_format($subtotal,2,'.','')?></th>
    </tr>
    <tr>
  <td colspan="3" align="left"><?php if(!empty($salida->total))$total=$salida->total; else $total=$subtotal?><?php	
echo $totalenletras=strtoupper(NumerosLetras::NL($total,$salida->getTesmonedas()->nombre));
?></td>
    <th width="23%">Total</th>
    <th width="11%"><?php echo number_format($total,2,'.','')?></th>
    </tr>
    <?php }?>
</table>
</div> 

<?php //echo nl::numerosALetras(3.141516)?>
<?php echo Form::open(NULL,'POST','class="form-inline"')?>
<?php echo Form::hidden('salida.id')?>
<?php echo Form::hidden('salida.aclusuarios_id')?>
<?php echo Form::hidden('salida.tesmonedas_id')?>
<?php echo Form::hidden('salida.tesdatos_id')?>
<?php echo Form::hidden('salida.tesdocumentos_id')?>
<?php echo Form::hidden('salida.testipocambios_id')?>
<?php echo Form::hidden('salida.acuenta')?>
<?php echo Form::hidden('salida.total','',$total)?>
<?php echo Form::hidden('salida.totalenletras','',$totalenletras)?>
<?php echo Form::hidden('salida.estadosalida','','Pendiente')?>
<?php if($salida->estadosalida=='Editable'){?><button type="submit" class="btn btn-xs btn-primary">Finalizar</button> <?php echo Html::linkAction('agregardetalles_internas','Editar','class="btn btn-xs"')?><?Php }else{?> <?php //echo Html::linkAction('versalida_i_internas','Imprimir','class="btn btn-xs"')?><?php }?>
<?php echo Form::close();?>
<div class="form-actions">
<button onclick="myFunction()" class="btn btn-xs btn-info"> IMPRIMIR </button> <?php echo Html::linkAction('salidas_internas/'.Session::get('DOC_ID'),'Listado','class="btn btn-xs"')?>
</div>
<script>
function myFunction() {
    window.open("http://"+document.domain+"/imprimir/detalles", "_blank", "toolbar=NO, scrollbars=yes, resizable=yes, top=100, left=250, width=600, height=400");
}
</script>
</div>