<div class="card">
    <h1>Ver Salida <span><?php echo Session::get('DOC_NOMBRE')?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="form-actions">
<?php echo Html::linkAction("f_salidas/7", 'Regresar ','class="btn btn-xs"') ?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>

<table width="75%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered">
<caption>Detalle de la factura</caption>
  <tr>
    <th width="22%" align="left">Pedido:</th>
    <td width="34%"><?php echo $salida->npedido;?></td>
    <th width="34%" align="left">Serie-Numero:</th>
    <td width="10%"><?php echo $salida->serie;?>-<?php echo $salida->numero;?></td>
  </tr>
  <tr>
    <th align="left">Moneda:</th>
    <td><?php echo $salida->getTesmonedas()->nombre;?></td>
    <th align="left">Fecha de Traslado:</th>
    <td><?php echo $salida->finiciotraslado;//finiciotraslado?></td>
  </tr>
  <tr>
    <th align="left">Cliente:</th>
    <td colspan="3"><?php echo $salida->getTesdatos()->razonsocial?>  <?php echo ($salida->getTesdatos()->ar=='SI') ? ' <b class="text-error">Es Agente de Retencion</b>': '';?></td>
  </tr>
  <tr>
    <th align="left">Direccion de Entrega:</th>
    <td colspan="3"><?php echo $salida->direccion_entrega;//finiciotraslado?></td>
  </tr><?php if(Session::get('DOC_ID')==15){?>
  <tr>
    <th align="right">Conductor:</th>
    <td>
      <?php echo $prodetalletransportes->getProtransportistas()->nombre;?>
    </td>
    <th align="right">Transporte:</th>
    <td><?php echo $prodetalletransportes->getProtransportes()->modelo;?></td>
  </tr><?php }?>
</table>
<br />
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-striped">
  <tr>
    <th width="44%" align="left">Producto</th>
    <th width="15%" align="left">Cantidad</th>
    <th width="7%" align="left">Unidad</th>
    <th width="23%" align="right">P/unitario</th>
    <th width="11%" align="right">Total</th>
  </tr>
  <?php 
  $n=0;
  $subtotal=0;
  foreach($detalles as $item){
	  $n++;
	  $subtotal=$subtotal+$item->importe;
	  ?> 
  <tr id="<?php echo $item->id?>">
    <td><?php echo $n?>. 
	<?php if(!empty($item->tesproductos_id))echo $item->getTesproductos()->detalle?> 
	<?Php if(!empty($item->tescolores_id))echo $item->getTescolores()->nombre?></td>
    <td><?php echo $item->cantidad?></td>
    <td><?Php echo $item->getTesunidadesmedidas()->simbolo?></td>
    <td align="right"><?php echo $item->preciounitario?></td>
    <td align="right"><?php echo number_format($item->importe,2,'.','')?></td>
  </tr>
  <?php }?>
  <tr>
  <td colspan="5">&nbsp;</td>
    </tr>
  <?php if(Session::get('DOC_ID')==9){
  $igv=0;
  ?>
  <tr>
  <td width="44%">&nbsp;</td>
    <td width="15%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <th width="23%" align="right">Sub-Total</th>
    <td width="11%" align="right"><?php if(!empty($salida->tescontratos_id))$subtotal=$subtotal*$salida->getTescontratos()->duracion; else $subtotal?><?php echo number_format($subtotal,2,'.','')?></td>
    </tr>
    <tr>
  <td width="44%">&nbsp;</td>
    <td width="15%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <th width="23%" align="right">A cuenta</th>
    <td width="11%" align="right"><?php  echo number_format($salida->acuenta,2,'.','')?></td>
    </tr>
    <tr>
  <td width="44%">&nbsp;</td>
    <td width="15%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <th width="23%" align="right">Total</th>
    <td width="11%" align="right"><?php if(!empty($salida->totalconigv))$total=$salida->totalconigv; else $total=$subtotal-$salida->acuenta?><?php echo number_format($total,2,'.','')?></td>
    </tr>
  <?php 
  }else{?>
  <tr>
  <td width="44%">&nbsp;</td>
    <td width="15%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <th width="23%" align="right">Sub-Total</th>
    <td width="11%" align="right"><?php if(!empty($salida->tescontratos_id))$subtotal=$subtotal*$salida->getTescontratos()->duracion; else $subtotal?><?php echo number_format($subtotal,2,'.','')?></td>
    </tr>
    <tr>
  <td width="44%">&nbsp;</td>
    <td width="15%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <th width="23%" align="right">Igv</th>
    <td width="11%" align="right"><?php if(!empty($salida->igv))$igv=$salida->igv; else $igv=$subtotal*Session::get('IGV')?><?php echo number_format($igv,2,'.','')?></td>
    </tr>
    <tr>
  <td colspan="3">
    <?php echo $totalenletras=strtoupper(NumerosLetras::NL($salida->totalconigv,$salida->getTesmonedas()->nombre));?></td>
    <th width="23%" align="right">Total</th>
    <td width="11%" align="right"><?php if(!empty($salida->totalconigv))$total=$salida->totalconigv; else $total=$subtotal+$igv?><?php echo number_format($total,2,'.','')?></td>
    </tr>
    <?php }?>
</table>
<?php //echo $totalenletras=strtoupper(NumerosLetras::NL($total,$salida->getTesmonedas()->nombre));?>

<?php //echo nl::numerosALetras(3.141516)?>
<?php echo Form::open(NULL,'POST','class="form-inline"')?>
<?php echo Form::hidden('salida.id')?>
<?php echo Form::hidden('salida.aclusuarios_id')?>
<?php echo Form::hidden('salida.tesmonedas_id')?>
<?php echo Form::hidden('salida.tesdatos_id')?>
<?php echo Form::hidden('salida.tesdocumentos_id')?>
<?php echo Form::hidden('salida.testipocambios_id')?>
<?php echo Form::hidden('salida.acuenta')?>
<?php echo Form::hidden('salida.igv','',$igv)?>
<?php echo Form::hidden('salida.totalconigv','',$total)?>
<?php echo Form::hidden('salida.totalenletras','',$totalenletras)?>
<?php echo Form::hidden('salida.estadosalida','','Pendiente')?>
<?php if($salida->estadosalida=='Editable'){?><button type="submit" class="btn btn-xs btn-primary">Finalizar</button> <?php echo Html::linkAction('agregardetalles','Editar','class="btn btn-xs"')?><?Php }else{?><?php }?>
<?php echo Form::close();?>
<div class="form-actions">
<button onclick="myFunction()" class="btn btn-xs btn-info"> IMPRIMIR </button>
</div>
<?php 
$hrf='facturas';
if(Session::get('DOC_ID')==15)$hrf='guias';
?>
<script>
function myFunction() {
    window.open("http://"+document.domain+"/imprimir/<?php echo $hrf?>", "_blank", "toolbar=NO, scrollbars=yes, resizable=yes, top=100, left=250, width=600, height=400");
}
</script>
</div>