<div class="card">
    <h1>Ver Salida<span><?php echo Session::get('DOC_NOMBRE')?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>

    <form class="form-inline">
    <div class="input-prepend">
    <span class="add-on">Pedido</span>
    <?php echo $salida->npedido;?>
    <span class="add-on">Serie</span>
    <?php echo $salida->serie;?>&nbsp;
    <span class="add-on">Numero</span>
    <?php echo $salida->numero;?>&nbsp;
    <span class="add-on">Moneda</span>
    <?php echo $salida->tesmonedas_id;?>&nbsp;
    <span class="add-on">Destino:</span>
    <?php echo $salida->hilodestino_id;?><br />
    <span class="add-on">Proveedor</span>
      <?php echo $salida->tesdatos_id?><br />
    <span class="add-on">Direccion de Entrega</span>
      <?php echo $salida->direccion_entrega;//finiciotraslado?><br />
    <span class="add-on">Fecha de Traslado</span>
      <?php echo $salida->finiciotraslado;//finiciotraslado?><br />
    <span class="add-on">Conductor</span>
      <?php echo $prodetalletransportes->protransportistas_id;?>
    <span class="add-on">Transporte</span>
      <?php echo $prodetalletransportes->protransportes_id;?>
	</div>      
  <div class="control-group">
    <div class="controls">
       
    </div>
  </div>
  </form>

<div id="guia">
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="1" class="table table-hover">
<caption>Lista de Cajas en Guia</caption>
  <tr style="font-size:12px; color:#333; font-weight:bold;">
    <th width="9%" align="left">Codigo</th>
    <th width="17%" align="left">Cantidad</th>
    <th width="11%" align="left">Unidad</th>
    <th width="53%" align="left">Descripcion</th>
  </tr>
  <?php 
  $n=0;
  foreach($detalles as $item){
	  $n++;
	  ?> 
  <tr id="<?php echo $item->id?>">
    <td><?php echo $n?>. <?php echo $item->getTescajas()->numerodecaja?></td>
    <td><?php echo $item->cantidad?></td>
    <td><?Php echo $item->getTesunidadesmedidas()->simbolo?></td>
    <td><?php echo $item->getTesproductos()->detalle?> <?Php echo $item->getTescolores()->nombre?></td>
  </tr>
  <?php }?>
</table>
</div> 
<?php echo Form::open(NULL,'POST','class="form-inline"')?>
<?php echo Form::hidden('salida.id')?>
<?php echo Form::hidden('salida.aclusuarios_id')?>
<?php echo Form::hidden('salida.tesmonedas_id')?>
<?php echo Form::hidden('salida.tesdatos_id')?>
<?php echo Form::hidden('salida.tesdocumentos_id')?>
<?php echo Form::hidden('salida.testipocambios_id')?>
<?php echo Form::hidden('salida.estadosalida','','TERMINADO')?>
<div class="form-actions">
<?php if($salida->estadosalida=='Editable'){?><button type="submit" class="btn btn-primary">Finalizar</button> <?php echo Html::linkAction('agregardetalles','Editar','class="btn"')?><?Php }else{?><?php echo Html::linkAction('salidas','Listado','class="btn"')?> <?php echo Html::linkAction('versalida_i','Imprimir','class="btn"')?><?php }?>
</div>
<?php echo Form::close();?>
</div>