<div class="card">
<h1><em>Vouchers !<span> Vista de Impresion de Vauchers</span></em></h1>
    <?php echo Html::linkAction("salidas", 'Volver al Inicio','class="btn btn-xs btn-primary"') ?> <a href="#" class="print btn btn-primary" rel="content"> Imprimir ! </a>
</div>
<br />
<br />
<br />
<div class="card-body">
<table width="255" border="0" cellspacing="1">
  <tr>
    <td width="169" align="right"><?php echo date("H:i:s")?></td>
    <td width="79">&nbsp;</td>
  </tr>
</table>
<table width="113%" border="0" cellspacing="1">
  <tr>
    <td align="right">&nbsp;</td>
    <td>&nbsp;</td>
    <td width="335" rowspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td width="141" height="10" align="right"><?php echo Sp::formatFecha('%d / %m / %Y',$salida->femision)?></td>
    <td width="215" align="right"><?php echo Sp::formatFecha('%d / %m / %Y',$salida->finiciotraslado)?><?php //echo $finiciotraslado?></td>
  </tr>
</table>
<br />
<br />
<table width="113%" border="0" cellspacing="0">
  <tr>
    <td width="50" align="right">&nbsp;</td>
    <td width="328" align="lefth">LOS ALFAREROS Nro.136 URB. EL ARTEZANO - ATE</td>
    <td width="317" align="lefth"><?php echo $salida->direccion_entrega?></td>
  </tr>

</table>
<br />
<br />
<table width="113%" border="0" cellspacing="1">
  <tr>
    <td width="43" height="31">&nbsp;</td>
    <td width="221" valign="bottom"><?php echo $salida->getTesdatos()->razonsocial?></td>
    <td width="10">&nbsp;</td>
    <td width="112" valign="bottom"><?php echo $salida->getTesdatos()->codigo_ant?></td>
    <td width="38">&nbsp;</td>
    <td width="258" valign="bottom"><?php echo $prodetalletransportes->getProtransportes()->marca?> <?php //echo $prodetalletransportes->getProtransportes()->modelo?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><?php echo $salida->getTesdatos()->direccion?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><?Php echo $salida->getTesdatos()->distrito?></td>
    <td>&nbsp;</td>
    <td><?php echo $salida->getTesdatos()->ruc?></td>
    <td>&nbsp;</td>
    <td><?Php echo $prodetalletransportes->getProtransportistas()->numerobrevete?></td>
  </tr>
</table>
<br />
<table width="113%" border="0" cellspacing="1">

  <tr>
    <td width="200" height="26" align="center" valign="bottom">&nbsp;</td>
    <td width="78" valign="bottom"><?php echo $salida->npedido?></td>
    <td width="111" valign="bottom">&nbsp;</td>
    <td width="51">&nbsp;</td>
    <td width="76">&nbsp;</td>
    <td width="166">&nbsp;</td>
  </tr>
</table>

<table width="113%" border="0" cellspacing="1">
  <tr>
    <td width="7%" height="21">&nbsp;</td>
    <td width="6%">&nbsp;</td>
    <td width="3%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="3%">&nbsp;</td>
    <td width="3%">&nbsp;</td>
    <td width="21%">x</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="8%">&nbsp;</td>
  </tr>
</table>
<br />
<table width="100%" border="0" cellspacing="1" s>
  <?php 
  $n=0;
  foreach($detalles as $item){
	  $mas_15=count($detalles);
	  if($mas_15<15){
	  $n++;
	  ?> 
  <tr>
    <td width="78" align="center"><?php echo $n?>. <?php echo $item->getTescajas()->numerodecaja?>
</td>
    <td width="60" align="right"><?php echo $item->cantidad?>
</td>
    
    <td width="65" align="center"><?Php echo $item->getTesunidadesmedidas()->simbolo?>
 </td>
    <td width="404"><?php echo $item->getTesproductos()->detalle?> <?Php echo $item->getTescolores()->nombre?>
    </td>
  </tr>
  <?php }
 }?>
 
  <tr>
    <td width="78">&nbsp;</td>
    <td colspan="3" align="left"><?php $T=explode("-",$item->getTotales(Session::get('SALIDA_ID_I')));?>Totol P.N. <?php echo $T[0]?> &nbsp;&nbsp;Cajas y/o Bolsas <?php echo $T[1] ?>&nbsp;&nbsp; Conos: <?Php echo $T[2]?></td>
  </tr>
</table>
<hr />
<br/>
<table width="113%" border="0" cellspacing="1">
  <tr>
    <td width="9%">&nbsp;</td>
    <td width="89%"><?Php //echo $prodetalletransportes->getProtransportistas()->nombre?></td>
    <td width="1%">&nbsp;</td>
    <td width="1%">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><?Php echo $prodetalletransportes->getProtransportistas()->nombre?><?php //echo Session::get('EMPRESAS_NOMBRE') ?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><?Php echo $prodetalletransportes->getProtransportistas()->direccion?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td height="22">&nbsp;</td>
    <td><?Php echo $prodetalletransportes->getProtransportistas()->ruc?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><?php echo $prodetalletransportes->getProtransportes()->numeroplaca?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</div>