 <!-- Main Sidebar Container -->
 <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
      <img src="/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="/admin/usuarios/perfil" class="d-block"><?php echo Auth::get('usuario'); ?></a>
        </div>
      </div>
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        
        <?php
        $empreas_id=$modulo = Router::get('module');
        switch($empreas_id){
          case $empreas_id == 'admin': 
            View::renderMenu(Menu::BACKEND,3,'class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false"');
            break;
          case $empreas_id == 'santapatricia': 
            View::renderMenu(Menu::SPATRICIA,3,'class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false"');
            break;
          case $empreas_id == 'santacarmela': 
            View::renderMenu(Menu::SCARMELA,3,'class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false"');
            break; 
          default:
            View::renderMenu(Menu::BACKEND,3,'class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false"');
            break;

        }
        
        ?>
        
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>