<div id="pago_con_cheques">
<h3>Cheque</h3>
<?php View::content();?>
<script type="text/javascript">
$(document).ready(function()
{
	$('#tesbancos_id').live("change",function(){
		var value = $('#tesbancos_id option:selected').html();
		$("#bancos").html(value);
		//$("tesdetallevauchers_tescuentascorrientes_id").val(value);
		
		});

});
</script>
<?php 

if($tesingresos_id==0){?>
<?php echo Session::get('A_ID'); echo Ajax::form('pago_con_cheques')?>
<div>Seleccione el Banco: <?php echo Form::dbSelect('tesbancos_id','nombre',array('tesbancos','find','conditions: aclempresas_id='.Session::get('EMPRESAS_ID')));?></div>
<div id="cuentas"></div>
<div>
<div id="cheques">
	 <?php echo Form::hidden('ingresos.id')?>
     <?php echo Form::hidden('ingresos.aclusuarios_id','',Auth::get('id'))?>
     <?php echo Form::hidden('ingresos.tesmonedas_id','',$tesmonedas_id)?>
     <?php echo Form::hidden('ingresos.tesdocumentos_id','','35')?>
     <?php echo Form::hidden('ingresos.codigo','',time())?>
     <?php echo Form::hidden('ingresos.femision','',date('Y-m-d'))?>
     <?php echo Form::hidden('ingresos.movimiento','','AB')?>
     <?php echo Form::hidden('ingresos.estado','',1)?>
     <?php echo Form::hidden('ingresos.userid','',Auth::get('id'))?>
     <?php echo Form::hidden('ingresos.aclempresas_id','',Session::get('EMPRESAS_ID'))?>
     <?php echo Form::hidden('ingresos.tesdatos_id','',$tesdatos_id)?>
      <?php echo Form::hidden('ingresos.tescuentascorrientes_id')?>
<table width="86%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped" id="abonos">
  <tr>
    <th align="left">Numero</th>
    <th align="left">Provedor</th>
    <th align="left">Banco</th>
    <th align="left">F. de Cobro</th>
    <th align="left">Monto</th>
    </tr>
  <tr>
    <td>
     <?php echo Form::text('ingresos.numero','')?> </td>
    <td>
     <?php echo $proveedor?> </td>
    <td id="bancos"></td>
    <td><?php echo Calendar::text('ingresos.fvencimiento');?></td>
    <td> 
     <?php echo Form::text('ingresos.totalconigv','',$total)?>
     </td>
    </tr>
</table>

<?php echo Form::submit('GRABAR','class="btn btn-primary"');?>
<?php echo Form::close()?>
</div>
<?php }?>
<?php if($tesingresos_id!=0){?>
<h3>Detalle del abono </h3>
<div id="detalle">
<?php echo Form::open()?>
<?php echo Form::hidden('tesdetalles.id');?>
<?php echo Form::hidden('tesdetalles.tesabonos_id','',Session::get('A_ID'));?>
<?php echo Form::hidden('tesdetalles.tessalidas_id','',0);?>
<?php echo Form::hidden('tesdetalles.tessalidasinternas_id','',0);?>
<?php echo Form::hidden('tesdetalles.tesingresos_id','');?>
<?php echo Form::hidden('tesdetalles.abono','',1);?>
<?php echo Form::hidden('tesdetalles.cargos','',0);?>
<?php echo Form::hidden('tesdetalles.tesdatos_id','',0);?>
<?php echo Form::hidden('tesdetalles.tescuentascorrientes_id','',$ingreso->tescuentascorrientes_id);?>
<?php echo Form::hidden('tesdetalles.estado','',1);?>
<?php echo Form::hidden('tesdetalles.cargos','',0);?>
<table width="100%" border="0" cellspacing="1" cellpadding="0">
  <tr>
    <th width="19%">Cuenta General</th>
    <th width="10%">Nº Docuemnto</th>
    <th width="14%">Fecha Vcto</th>
    <th width="14%">Codigo Auxiliar</th>
    <th width="14%">Descripcion</th>
    <th width="14%">Cargo</th>
    <th width="15%">Abono</th>
  </tr>
  <tr>
    <td width="19%"><?php echo $tesdetalles->plancontable;
	 echo Form::hidden('tesdetalles.plancontable'); ?></td>
    <td width="10%"><?php echo $ingreso->numero?></td>
    <td width="14%"><?php echo $ingreso->fvencimiento;?></td>
    <td width="14%"><?php echo $tesdetalles->fecha_cobro;?></td>
    <td width="14%"><?php echo $ingreso->getTeschequesingresos()->getTesbancos()->nombre;?></td>
    <td width="14%"><?php echo Session::get("EMPRESAS_NOMBRE")?></td>
    <td width="15%"><?php echo Form::text('tesdetalles.monto',''); ?></td>
  </tr>
</table>
<?php echo Form::submit('GRABAR','class="btn btn-primary"');?>
<?php echo Form::close()?>

</div>
<?php }?>
</div>