<div id="pago_con_letras"> 

	<script type="text/javascript">
$(document).ready(function()
{
	//alert('1');
	$("#enviar_numero_de_letras").click(function(){
		var numero_letras= $("#letras").val();
		$("#pago_con_letras").html('');
		alert('Ud. Esta generando '+numero_letras+' Letras');
		$("#pago_con_letras").load('/<?php echo $module_name?>/abonos/letras/3/<?php echo $tessalidas_id?>/<?php echo $numerofactura?>/<?php echo $ids?>/'+numero_letras);
		$("#n_let").hide();
		});
});
</script>
	
<?php
	//echo $numerofactura;echo $ids.'sesion '.Session::get('DOC_ID');
 if($tessalidas_id==0){?>
<h4>
	<strong><em>Nro. de Letras a Ingresar !<br /></em></strong><?php echo Form::text('letras');?> <a href="javascript:;" class="btn btn-xs btn-primary" id="enviar_numero_de_letras">Enviar</a>
</h4>
<div>
	<?php
	$numero=$SALD->generarNumeroLetras('001');
 for($q=1;$q<=$nletras;$q++){
//echo $q;
	?>
	<div id="letras-<?php echo $q?>">
<?php echo Ajax::form('letras-'.$q,$module_name.'/abonos/ingresoletras/'.$q)?>
	 <?php echo Form::hidden('salidas-'.$q.'.id')?>
     <?php echo Form::hidden('salidas-'.$q.'.aclusuarios_id','',Auth::get('id'))?>
     <?php echo Form::hidden('salidas-'.$q.'.tesmonedas_id','',$tesmonedas_id)?>
     <?php echo Form::hidden('salidas-'.$q.'.tesdocumentos_id','','34')?>
     <?php echo Form::hidden('salidas-'.$q.'.codigo','',time())?>
     <?php echo Form::hidden('salidas-'.$q.'.movimiento','','')?>
     <?php echo Form::hidden('salidas-'.$q.'.estado','',1)?>
     <?php echo Form::hidden('salidas-'.$q.'.userid','',Auth::get('id'))?>
     <?php echo Form::hidden('salidas-'.$q.'.aclempresas_id','',Session::get('EMPRESAS_ID'))?>
     <?php echo Form::hidden('salidas-'.$q.'.tesdatos_id','',$tesdatos_id)?>
      <?php echo Form::hidden('salidas-'.$q.'.numerofactura','',$numerofactura)?>
      <?php echo Form::hidden('salidas-'.$q.'.estadosalida','','Editable')?>
      <?php echo Form::text('ids-'.$q,'',$ids)?>
	  <?php echo Form::text('docs-'.$q,'',$numerofactura)?>
<table width="100%" border="0" cellspacing="1" cellpadding="0">
  <tr>
    <th width="13%" align="left">Nro. Letra</th>
    <th width="16%" align="left">Provedor</th>
    <th width="29%" align="left">F. Emision</th>
    <th width="35%" align="left">F. Vencimiento</th>
    <th width="7%" align="left">Monto</th>
    </tr>
  <tr>
    <td>
      <?php echo Form::text('salidas-'.$q.'.numero','size="10" placeholder="numero" required',$numero)?> </td>
    <td>
     <?php echo $proveedor?> </td>
    <td><?php echo Calendar::selector('salidas-'.$q.'.femision','');?></td>
    <td><?php echo Calendar::selector('salidas-'.$q.'.fvencimiento','');?></td>
    <td> 
     <?php echo Form::text('salidas-'.$q.'.totalconigv','',number_format(($total/$nletras),2,'.',''))?>
<?php echo Form::submit('GRABAR','class="btn btn-xs btn-primary"');?>
     </td>
    </tr>
</table>
<?php echo Form::close()?>
</div>
<?php 
$numero++;
}?>
<?php echo Ajax::linkAction('letras/3/'.$tessalidas_id.'/'.$numerofactura.'/'.$ids,'Siguente','pago_con_letras','btn btn-primary');?>
<?php }?>
<?php if($tessalidas_id!=0){?>
<?php 
$q=0;
foreach($tesdetallevauchers as $detalle){
	$q++;
	?>
<div id="detalle-<?php echo $q?>">
<?php echo Ajax::form('detalle-'.$q,$module_name.'/abonos/ingresoletras/'.$q)?>
<?php echo Form::hidden('tesdetalles-'.$q.'.id','',$detalle->id);?>
<?php echo Form::hidden('tesdetalles-'.$q.'.tesabonos_id','',Session::get('A_ID'));?>
<?php echo Form::hidden('tesdetalles-'.$q.'.tessalidas_id','',$detalle->tessalidas_id);?>
<?php echo Form::hidden('tesdetalles-'.$q.'.abono','',1);?>
<?php echo Form::hidden('tesdetalles-'.$q.'.cargos','',0);?>
<?php echo Form::hidden('tesdetalles-'.$q.'.tesdatos_id','',$detalle->tesdatos_id);?>
<?php echo Form::hidden('tesdetalles-'.$q.'.estado','',1);?>
<table width="100%" border="0" cellspacing="1" cellpadding="0">
  <tr>
    <th width="19%">Cuenta General</th>
    <th width="10%">Nº Docuemnto</th>
    <th width="14%">Fecha Vcto</th>
    <th width="14%">Codigo Auxiliar</th>
    <th width="14%">Descripcion</th>
    <th width="14%">Cargo</th>
    <th width="15%">Abono</th>
  </tr>
  <tr>
    <td width="19%"><?php echo $detalle->plancontable;
	 echo Form::hidden('tesdetalles-'.$q.'.plancontable','',$detalle->plancontable); ?></td>
    <td width="10%"><?php echo $detalle->getTessalidas()->serie?> - <?php echo $detalle->getTessalidas()->numero?></td>
    <td width="14%"><?php echo $detalle->getTessalidas()->fvencimiento?></td>
    <td width="14%">-</td>
    <td width="14%"><?php echo $detalle->getTessalidas()->getTesdatos()->razonsocial;?></td>
    <td width="14%">-</td>
    <td width="15%"><?php echo Form::text('tesdetalles-'.$q.'.monto','',$detalle->monto); ?>
<?php echo Form::submit('GRABAR','class="btn btn-xs btn-primary"');?></td>
  </tr>
</table>
<?php echo Form::close()?>
</div>
<?php 
}?>

<?php //echo Ajax::form('pago_con_letras',$module_name.'/vouchers/ingresoletras/')?>
<?php echo Form::open($module_name.'/abonos/ingresoletras/'.$q)?>
<?php echo Form::hidden('terminar.id','',$detalle->id);?>
<?php echo Form::submit('Terminar','class="btn btn-xs btn-primary"');?>
<?php echo Form::close()?>
<?php
}?>
</div>