<div class="page-header">
    <h1>Crear Tipo de Persona</h1>
</div>      
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('testipodatos.id') ?>
<div class="control-group">
    <label for="tastipodatos_nombre">Nombre: </label>
    <div class="controls">
        <?php echo Form::text('testipodatos.nombre') ?>
    </div>
</div>
<div class="control-group">
    <label for="tastipodatos_descripcion">Descripcion: </label>
    <div class="controls">
        <?php echo Form::textarea('testipodatos.descripcion') ?>
    </div>
</div>

<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
