<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>
<div class="card">
    <h1>Proformas<span>Listado de Proformas Enviadas a Clientes</span>
		<div class="icoimg-proformas"></div></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>

<div class="form-actions">
    <?php echo Html::linkAction("cargar/0", 'Crear Proformas','class="btn btn-primary"') ?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>
<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
  <tr>
  	<td width="26">Nº</td>
    <td width="52">Numero</td>
    <td width="354">Producto</td>
    <td width="106">Descuento</td>
    <td width="62">Subtotal</td>
    <td width="62">Igv</td>
    <td width="62">Total</td>
    <td width="106">Acciones </td>
  </tr>
<?php $n=0;
foreach($proformas as $item){ 
$n++;
switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $n?></td>
    <td><?php echo $item->numero?></td>
    <td>
    <small style="color:#666; font-size:10px !important; font-style:italic; ">
	<?php $n=0;$m=0;
	foreach($item->getTesdetalleproformas() as $det)
	{
		$n++;
		echo $det->getTesproductos()->nombre;if(count($item->getTesdetalleproformas())>$n){echo ", ";}
	}
	?>
    </small>
    </td>
    <td><?php echo $simbolo;if(empty($item->descuento))echo " 00.00";else echo number_format($item->descuento,2,'.','');?></td>
    <td><?php echo $simbolo; echo number_format($item->TOTAL,2,'.','');?></td>
    <td><?php echo $simbolo; echo number_format($item->igv,2,'.','');?></td>
    <td><?php echo $simbolo; echo number_format($item->totalconigv,2,'.','');?></td>
   <td>
   <?php echo Html::linkAction('cargar/'.$item->id.'/',Html::img("figuras/editar.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'')?>
   <?php echo Html::linkAction('ver/'.$item->numero.'/',Html::img("figuras/ver.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'')?>
    </td>
  </tr>
<?php }?>
</table>
</div>