<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>
<div class="card">
    <h1>Guias de Venta<span><?php echo $titulo?> <?php echo Session::get('DOC_NOMBRE')?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>

<div class="form-actions">
<?php echo Html::linkAction("crear/", 'Crear Guia sin Detalles','class="btn btn-primary"') ?>
 - <?php echo Html::linkAction($url."/", 'Crear Nueva Guia ','class="btn btn-primary"') ?> <?php echo Html::linkAction("", 'Regresar ','class="btn"') ?> <?php echo Html::linkAction("cargar_doc/13/nota_creditos", 'NC ','class="btn"') ?>  <?php echo Html::linkAction("cargar_doc/14/nota_debitos", 'ND ','class="btn"') ?>
</div>
<?Php 
$clas='';
if($Ped=='MT')$clas='btn-success';else $clas='';
echo Html::linkAction('guias/15/MT','Muestras','class="btn btn-mini '.$clas.'"').' ';
$clas='';
if($Ped=='VT')$clas='btn-success';else $clas='';
echo Html::linkAction('guias/15/VT','Ventas','class="btn btn-mini '.$clas.'"').' ';
if($Ped=='PT')$clas='btn-success'; else $clas='';
echo Html::linkAction('guias/15/PT','Transformaciones','class="btn btn-mini '.$clas.'"');?>
<div class="card-body">
<div id="ver_resultado"></div>
<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">
<caption>Guias Generadas el dia de hoy! (Telas)</caption>
  <tr>
  	<th width="21">Nº</th>
    <th width="138">Cliente</th>
    <th width="85">Número Doc.</th>
    <th width="240">Productos </th>
    <th width="98">Sub-total</th>
    <th width="76">Igv</th>
    <th width="92">Total</th>
    <th width="80">Acciones </th>
  </tr>
<?php $number=0;
foreach($salidas as $item){ 
$simbolo="S/. ";

switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

$number++;?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $number?></td>
  	<td height="20"><?php echo $item->getTesdatos()->razonsocial?></td>
    <td><?php echo $item->serie?>-<?php echo $item->numero?></td>
    <td>
    <small style="color:#666; font-size:10px !important; font-style:italic; ">
	<?php
    
	$n=0;$m=0;
	foreach($item->getTesdetallesalidasinternas() as $det)
	{
		if($det->tesproductos_id!=0){$n++;
		echo $det->getTesproductos()->nombre;if(count($item->getTesdetallesalidasinternas())>$n){echo ", ";}
		}else{
			echo $det->concepto;
			}
	}
	?>
    </small>
    </td>
    <td><?php if(!empty($item->total))echo $simbolo.number_format($item->total-$item->igv,2,'.','');else echo('S/ 00.00');?></td>
    <td><?php if(!empty($item->total))echo $simbolo.number_format($item->igv,2,'.','');else echo('S/ 00.00')?></td>
    <td><?php if(!empty($item->total))echo $simbolo.number_format($item->total,2,'.','');else echo('S/ 00.00')?></td>
   <td>
   <?php if($item->estadosalida=="Editable"){
	   if(empty($det->concepto))echo Html::linkAction('cargarsalida/'.$item->id.'/',Html::img("figuras/editar.png",'EDITAR','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar Guia - 002 - Hilos"');else
	   {
		   echo Html::linkAction('cargarsalida/'.$item->id.'/crear_detalle',Html::img("figuras/editar.png",'EDITAR','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar Guia - 002 - Hilos"');
		  }}?>
	<?php echo Html::linkAction('cargarsalida/'.$item->id.'/versalida',Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Ver e Imprimir Guia - 002 - Hilos"')?>

    <?php if($item->estadosalida!='ANULADO')echo Html::linkAction("anularguias/$item->id/",' X ','class="btn btn-danger" title="Anular" onclick="return confirm(\'¿Está seguro de anular esta guia los rollos seran restablecidos ?\')"'); else echo "Anulado";?>
    </td>
  </tr>
<?php }?>
</table>
</div>