<style type="text/css">
body,td,th {
	font-family: "Times New Roman", Times, serif;
	font-size: 12px;
	color: #000;
}
body {
	background-color: #FFF;
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
</style>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<table width="110%" border="0" cellspacing="0" align="left">
  <tr>
   
    <td width="77" align="center">000883-84</td>
    <td width="362" align="lefth">DECORACIONES D EINTERIORES SUMAQ WASI SAC</td>
    <td width="108" align="lefth">20101619240</td>
    <td width="149" align="lefth"><?php //echo Sp::formatFecha('%d / %m / %Y',$femision)?>13/03/2013</td>
  </tr>
</table>
<br />
<br />
<table width="95%" border="0" cellspacing="1">
  <tr>
    <td width="8%" align="center"><p>&nbsp;</p></td>
    <td width="92%" align="left">CAL. PROLG.GAMARRA NO. 1151 INT.105 GAMARRA LA VICTORIA - LIMA</td>
    </tr>
</table>
<br />
<table width="705" border="0" cellspacing="1">
	<tr>
		<td width="44">&nbsp;</td>
		<td width="654">Segun factura nro. 001-0015046 de fecha 01/09/2012</td>
	</tr>
</table>
<br />
<br />
<br />
<br />
<br />
<br />
<table width="102%" border="0" cellspacing="1">
  <tr>
   
    <td width="32" align="center"><p>&nbsp;</p>
    <p>&nbsp;</p></td>
    
    <td width="50" align="left"><p>&nbsp;</p>
    	<p>Dice:</p>
    	<p>Debe decir: </p>
</td>
    <td width="478" align="left"><p>Por descuento acordado con el cliente en la tela para cortina Tull Bashir: </p>
    	<p>105 mts x s/.15.00 = s/.1575.00</p>
<p>105 mts x s/.13.30 = 1396.50</p></td>
    <td width="80" align="center">&nbsp;</td>
    </tr>
</table>
<table width="234" border="0" cellspacing="1">
	<tr>
		<td width="116">&nbsp;</td>
		<td width="111">-------------------------</td>
	</tr>
</table>
<table width="227" border="0" cellspacing="1">
	<tr>
		<td width="144">&nbsp;</td>
		<td width="76">s/.178.50</td>
	</tr>
</table>

<table width="100%" border="0" cellspacing="1">
  <tr>
    <td width="9%" align="right">&nbsp;</td>
    <td width="59%" align="lefth" >Son Mil Quinientos Noventa y 50/100 nuevos soles</td>
    <td width="32%" align="center" >&nbsp;</td>
  </tr>
</table>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<table width="113%" border="0" cellspacing="1">
  <tr>
    <td width="25%">&nbsp;</td>
    <td width="20%">&nbsp;</td>
    <td width="6%">&nbsp;</td>
    <td width="14%">&nbsp;</td>
    <td width="12%">SUBTOTAL</td>
    <td width="21%">178.50</td>
    <td width="2%">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>IGV.(18.00%)</td>
    <td>S/.398.00</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
  	</tr>
  <tr>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
  	<td>&nbsp;</td>
  	<td>S/.10000.00</td>
  	<td>&nbsp;</td>
  	</tr>
</table>

