
<div class="card">
    <h1>Notas de Debito <span><?php echo Session::get('EMPRESAS_NOMBRE')?></span></h1>
</div>
<div id="mensajes_flash" >       
    <?php View::content();?>
</div>

<div class="form-actions"><?php echo Html::linkAction("guias/15", 'Listado de guias ','class="btn btn-secondary"') ?>  <?php echo Html::linkAction('nota_debitos','Listado de Nota de Credito','class="btn btn-info"');?> 
<?php echo Html::linkAction('crear_nota','Crear Nota de Debito','class="btn btn-primary"');?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>
<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">
<caption>Notas de Debito! </caption>
  <tr>
  	<th width="17">Nº</th>
    <th width="108">Cliente</th>
    <th width="54">Número Doc.</th>
    <th width="200">Referencias </th>
    <th width="77">Sub-total</th>
    <th width="72">Total</th>
    <th width="72">Acciones</th>
  </tr>
<?php $number=0;
foreach($salidas as $item){ 
$simbolo="S/. ";

switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

$number++;?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $number?></td>
  	<td height="20"><?php echo $item->getTesdatos()->razonsocial?></td>
    <td><?php echo $item->serie?>-<?php echo $item->numero?></td>
    <td>  <?php echo $item->glosa?>  </td>
    <td align="right"><?php if($item->total!='NaN.00' && !empty($item->total))echo $simbolo.number_format($item->total,2,'.','');else echo('S/ 00.00');?></td>
    <td align="right"><?php if($item->total!='NaN.00' && !empty($item->total))echo $simbolo.number_format($item->total,2,'.','');else echo('S/ 00.00')?></td>
    <td align="center">
    <?php if($item->estadosalida=="Editable")echo Html::linkAction('crear_nota/'.$item->id,Html::img("figuras/editar.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar!"')?>
    <?php echo Html::linkAction('cargarsalida/'.$item->id.'/notadebito',Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'), 'title="ver Imprimir"');?>
    </td>
  </tr>
<?php }?>
</table>

</div>
