<?php 
$monedas= $salida->tesmonedas_id;
switch ($monedas)
{
	case 1: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES'; break;
	case 2: $simbolo='$. ';$moneda_letras='DOLARES AMERICANOS';  break;
	case 4: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES';  break;
	case 5: $simbolo='$. ';$moneda_letras='DOLARES AMERICANOS';  break;
	case 0: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES';  break;
}

?>

<div class="card">
    <h1>Venta<span><?php echo Session::get('DOC_NOMBRE')?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>

<div class="form-actions">
<?php echo Html::linkAction("guias/15", 'Regresar ','class="btn"') ?>
</div>
<?php if($salida->estadosalida=='ANULADO'){?><div class="texto"> ANULADO </div><?php }?>
<div class="card-body">
<?php echo Form::open()?>

<table width="50%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered">
<caption>Detalle de la venta </caption>
  <tr>
    <th width="38%" align="left">Cliente:</th>
    <td width="62%">&nbsp;<?php echo $salida->getTesdatos()->razonsocial?></td>
  </tr>
  <tr>
    <th align="left">F. emision:</th>
    <td>&nbsp;<?php echo $salida->femision?></td>

  </tr>
  <tr>
  	<th align="left">Nº</th><td>&nbsp;<?php echo $salida->serie?>-<?php echo $salida->numero?></td></tr><tr>
  		<th align="left">Condiciones de pago:</th><td>&nbsp;<?php echo $salida->getTescondicionespagos()->nombre?></td></tr><tr>
    <th align="left">Guias:</th>
    <td>&nbsp;<?php echo $salida->numeroguia?></td>

  </tr>
</table>
<br />
<div id="aplicar">
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped ">
  <tr>
    <th width="8%" align="left">Codigo</th>
    <th width="13%" align="left">Cantidad</th>
    <th width="6%" align="left">Unidad</th>
    <th width="37%" align="left">Descripcion</th>
    <th width="7%" align="left">P/U</th>
    <th width="13%" align="left">Dsto</th>
    <th width="16%" align="left">Total vta</th>
  </tr>
  <?php 
  $n=0;
  $total=0;
  foreach($detalles as $item){
	$n++;
	  ?>
  <tr id="<?php echo $item->id?>">
    <td><?php echo $n.'.'; echo $item->getProrollos()->codigo?>-<?php echo $item->getProrollos()->numeroventa; echo ' '.$item->getProrollos()->getNprocesos($item->prorollos_id);?></td>
    <td><?php echo $item->cantidad?></td>
    <td><?Php echo $item->getTesunidadesmedidas()->simbolo?></td>
    <td><?php echo $item->getTesproductos()->nombre?> <?php echo $item->getTesproductos()->detalle?> <?Php echo $item->getTescolores()->nombre?></td>
    <td><?php echo $simbolo?><?php echo number_format($item->preciounitario,2,'.','');?></td>
    <td><?php if(empty($item->descuento))echo "0.00";else echo $item->descuento/100?></td>
    <td><?php echo $simbolo?><?php 
	$total=$total+$item->importe;
	if(!empty($item->importe))echo number_format($item->importe,2,'.','');else echo "0.00";
	//echo "&#398;";
	?></td>
  </tr>
  <?php }?>
   <?php 
   /*muesra la aplicacion a esta factura */
  if($aplicaciones){
  foreach($aplicaciones as $aplicacion){
  $n++;
  ?>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td align="right"> Pago adelantado <?php echo $aplicacion->id.' '.$aplicacion->tesletrassalidasinternas_id?> <?php echo $aplicacion->getTesletrassalidasinternas()->numerodeletra?> </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><?php echo $simbolo?><?php 
	
	//$total=$total-$aplicacion->monto;
	echo '-'.number_format($aplicacion->monto,2,'.','')?> <?php echo Html::linkACtion('eliminar_app/'.$aplicacion->id,'','class="icon-remove-circle"');?></td>
  </tr>
  <?php }
   }?>
  <?php 
  /*mustra las facturas por adelanto*/
  if($adelantos){?>
  <tr>
  <td colspan="7">
  <div style="margin:20px;">
  <blockquote>
  	<ul>
	<li><strong>LETRAS ADELANTADAS</strong></li>
	<?php foreach($adelantos as $adelanto)
  	{
		?>
        <li class="well well-small">
		<?php echo '&nbsp;&nbsp;'.$adelanto->numerodeletra;?> <?php echo 'Letra por adelanto';?>
        <span style="float:right;">
        <label>
		<?Php echo $adelanto->getTesmonedas()->simbolo?> <?php echo $total_a=number_format($adelanto->total,2,'.','')?>
        <i>Para <?php echo Html::linkAction('limpiar_letra/'.$adelanto->id,'Recalcular el monto')?> del adelanto</i><?php if($total!=0)echo Ajax::link($module_name.'/ventasinternas/aplicaradelanto_interno/'.$salida->id.'/'.$adelanto->id.'/'.$total,'Aplicar','aplicar','btn', $attrs=NULL);?></label>
        </span>
       </li>        
<?php }?>
    </ul>
    <span>** Si no esta complemante seguro de aplicar comuníquese con sistemas</span>
    </blockquote>
  </div>
  </td>
  </tr> 
  <?php }?>
  
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Sub total</td>
    <td><?php echo $simbolo?><?php echo number_format($total,2,'.','');?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>TOTAL</td>
    <td>* <?php echo $simbolo?><?php $TOTAL=$total;?><?php echo Form::text('salida.total','style="float: right;width: 75%;"',number_format($TOTAL,2,'.',''));?></td>
  </tr>
  </table>
<?php echo Form::hidden('salida.id');?>
<?php echo Form::hidden('salida.tesmonedas_id');?>
<?php echo Form::hidden('salida.aclusuarios_id');?>
<?php echo Form::hidden('salida.tesdocumentos_id');?>
<?php echo Form::hidden('salida.testipocambios_id');?>
<?php echo Form::hidden('salida.tesdatos_id');?>
<?php echo Form::hidden('salida.total','',$TOTAL);?>
<div class="form-actions">
<?php //echo Form::textArea('salida.glosa','style="margin: 0px 0px 9px;height: 60px;width:95%;"');?>
<?php echo Form::submit('Siguente','class="btn btn-primary"')?> <?php echo Html::linkAction('agregardetalles','Editar','class="btn btn-secondary"')?></div>
<?php echo Form::close();?>
<i>* para modificar el total</i>
</div>

</div>