<style type="text/css">
.page {
position: relative;
z-index: 2;
}

.texto {
color:#F00;
position:absolute;
padding-top:10%;
text-align:center ;
z-index:1;
top:0;
left:0;
right:0;
bottom:0;
font-size:36px !important;
}
</style>
<?php 
$monedas= $salida->tesmonedas_id;
switch ($monedas)
{
	case 1: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES'; break;
	case 2: $simbolo='$. ';$moneda_letras='DOLARES AMERICANOS';  break;
	case 4: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES';  break;
	case 5: $simbolo='$. ';$moneda_letras='DOLARES AMERICANOS';  break;
	case 0: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES';  break;
}
?>
<div class="card"><h1>Vista previa del documento</h1></div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="form-actions"><?php echo Html::linkAction('guias/'.Session::get('DOC_ID'),'Listado','class="btn btn-xs"')?> </div>
<div class="card-body">
<div id="ver_resultado"></div>
<table align="center" width="50%" border="0" cellspacing="0" cellpadding="0" class="table-bordered"> 
<caption>Venta - <?php echo Session::get('DOC_NOMBRE')?></caption>
  <tr>
    <th width="40%" align="left">Cliente:</th>
    <td width="60%"><?php echo $salida->getTesdatos()->razonsocial?> </td>
  </tr>
  <tr>
    <th align="left">Serie-Numero:</th>
    <td><?php echo $salida->serie?>-<?php echo $salida->numero?></td>
  </tr>
  <tr>
    <th align="left">Pedido :</th>
    <td><?php echo $salida->npedido?></td>
  </tr>
  <tr>
    <th align="left">Fecha de Emision:</th>
    <td><?php echo Sp::formatFecha('%d/%m/%Y',$salida->femision);?></td>
  </tr>
</table>
<br />
<div id="guia">
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">
<caption>Lista de Telas en Guia</caption>
  <thead>
  <tr>
    <th width="13%" align="left">Codigo</th>
    <th width="42%" align="left">Descripcion</th>
    <th width="7%" align="left">UNI</th>
    <th width="8%" align="left">Cant.</th>
    <th width="8%" align="left">P.U.</th>
    <th width="10%" align="left">Dscto</th>
    <th width="12%" align="left">Importe</th>
  </tr>
  </thead>
  <tbody>
  <?php
  $n=0;
  $total=0;
  foreach($detalles as $item){
	  $n++;
	  ?> 
  <tr id="<?php echo $item->id?>">
    <td><?php echo $n?>. <?php if(!empty($item->tesproductos_id)){if(empty($item->getProrollos()->prorollos_id)){echo $item->getProrollos()->numero?>-M<?php echo $item->getProrollos()->maquina_numero;}else{echo $item->getProrollos()->codigo?>-<?php echo $item->getProrollos()->numeroventa; echo ' '.$item->getProrollos()->getNprocesos($item->prorollos_id);}}else{echo $item->concepto;}?></td>
    <td><?php if(!empty($item->tesproductos_id)){ echo $item->getTesproductos()->nombre?> <?php echo $item->getTesproductos()->detalle?> <?Php echo $item->getTescolores()->nombre;}?></td>
    <td><?Php echo $item->getTesunidadesmedidas()->simbolo?></td>
    <td><?php if(Session::get('DOC_ID')==15)echo $item->pesoneto;else echo $item->cantidad?></td>
    <td><?php echo $simbolo?><?php if(!empty($item->preciounitario))echo number_format($item->preciounitario,2,'.','');?></td>
    <td><?php if(empty($item->descuento))echo "0.00";else echo $item->descuento/100?></td>
    <td><?php echo $simbolo?><?php 
	$total=$total+$item->importe;
	if(!empty($item->importe))echo number_format($item->importe,2,'.','');else echo "0.00";?></td>
  </tr>
  <?php }?>
     <?php 
   /*muesra la aplicacion a esta factura */
  if($aplicaciones){
  foreach($aplicaciones as $aplicacion){
  $n++;
  ?>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td colspan="3" align="right">Nro. doc.P/A:<?php echo $aplicacion->getTesletrassalidasinternas()->numerodeletra?></td>
    <td><?php echo $simbolo?><?php 
	
	//$total=$total-$aplicacion->monto;
	echo '-'.number_format($aplicacion->monto,2,'.','')?></td>
  </tr>
  <?php }
   }?>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Sub total</td>
    <td><?php echo $simbolo?><?php echo number_format($total,2,'.','');?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>Total</td>
    <td><?php echo $simbolo?><?php $TOTAL=$total;echo number_format($TOTAL,2,'.','');?></td>
  </tr>
  </tbody>
  <tfoot>
  <tr>
    <td colspan="7">
<?php echo $texto=NumerosLetras::NL($total,$moneda_letras);?></td>
  </tr>
  </tfoot>
</table>
<script type="text/javascript">
function cargar()
	{
		$("#pago_con_letras").load('/<?php echo $module_name?>/cancelacionfacturas/unafactura_i/<?php echo $salida->id?>/'+<?php echo $letras?>);
	}
$(document).ready(function()
{

	$("#editar_letras").click(function(){
		alert('hola');
		cargar();
	});
});
	</script>
 <div class="form-actions">
    <?php 
	//echo $salida->tescondicionespagos_id;
	if($salida->tescondicionespagos_id==2){
	if($letras>0){?>
	<script type="text/javascript">
	$(document).ready(cargar);
	</script>
	<div id="pago_con_letras">
    </div>
	
	<?php }elseif($l_f==0){?>
    <strong>Nro. de Letras a Ingresar !<br /></strong><?php echo Form::text('letras');?> <a href="javascript:;" class="btn btn-xs btn-primary" id="enviar_numero_de_letras">Enviar</a>
   
    <script type="text/javascript">
$(document).ready(function()
{
	//alert('1');
	$("#enviar_numero_de_letras").click(function(){
		var numero_letras= $("#letras").val();
		$("#pago_con_letras").html('');
		alert('Ud. Esta generando '+numero_letras+' Letras');
		$("#pago_con_letras").load('/<?php echo $module_name?>/cancelacionfacturas/unafactura_i/<?php echo $salida->id?>/'+numero_letras,function() {
		for(i=0;i<=numero_letras;i++){
		$("#salida-"+i+"_totalconigv").val(parseFloat(<?php echo $TOTAL?>/numero_letras));
		//alert($("#salida-"+i+"_totalconigv").val());
		}
});
		
		
		$("#n_let").hide();
		});
});
</script>
<?php echo Form::open(NULL,'POST','class="form-inline"')?>
<?php echo Form::hidden('salida.id')?>
<?php echo Form::hidden('salida.aclusuarios_id')?>
<?php echo Form::hidden('salida.tesmonedas_id')?>
<?php echo Form::hidden('salida.tesdatos_id')?>
<?php echo Form::hidden('salida.tesdocumentos_id')?>
<?php echo Form::hidden('salida.testipocambios_id')?>
<?php echo Form::hidden('salida.estadosalida','','Pendiente')?>
<?php echo Form::hidden('salida.total','',$TOTAL);?>
<?php echo Form::hidden('salida.totalenletras','',$texto);?>
<?php if($salida->estadosalida=='Editable'){?><button type="submit" class="btn btn-xs btn-primary">Finalizar Sin crear Letras</button> 
<?php echo Html::linkAction('agregardetalles','Editar','class="btn btn-xs"')?><?Php }else{?><?php //echo Html::linkAction('versalida_i','Imprimir','class="btn btn-xs"')?><?php }?>
<?php echo Form::close();?>
	<div id="pago_con_letras">
    </div>
<?php }else{?>
<div id="pago_con_letras">
<table width="50%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <th width="13%" align="left">Nro. Letra</th>
    <th width="29%" align="left">F. Emision</th>
    <th width="35%" align="left">F. Vencimiento</th>
    <th width="7%" align="left">Monto</th>
    </tr>
   <?php
foreach($lets as $let){
$q=$let->id;
	?>
  <tr>
    <td>
      <?php echo $let->getTessalidasinternas()->numero?> </td>
    <td><?php echo Sp::formatFecha('%d/%m/%Y',$let->getTessalidasinternas()->femision);?></td>
    <td><?php echo Sp::formatFecha('%d/%m/%Y',$let->getTessalidasinternas()->fvencimiento);?></td>
    <td> 
     <?php echo number_format($let->getTessalidasinternas()->total,2,'.','')?>
     </td>
    </tr>
	<?php }?>
</table>
 </div>
<?php 
//echo $salida->estadosalida;
if($salida->estadosalida=="Editable"){?><a href="javascript:;" id="editar_letras" class="btn btn-xs btn-primary">Editar la Informacion de las letras</a><?php }?>
<?php }
	}?>
<?php 
if($l_f>0 || $salida->tescondicionespagos_id!=2)
	{$salida->tescondicionespagos_id;?>
	<?php echo Form::open(NULL,'POST','class="form-inline"')?>
	<?php echo Form::hidden('salida.id')?>
	<?php echo Form::hidden('salida.aclusuarios_id')?>
	<?php echo Form::hidden('salida.tesmonedas_id')?>
	<?php echo Form::hidden('salida.tesdatos_id')?>
	<?php echo Form::hidden('salida.tesdocumentos_id')?>
	<?php echo Form::hidden('salida.testipocambios_id')?>
	<?php echo Form::hidden('salida.total','',$TOTAL);?>
	<?php echo Form::hidden('salida.totalenletras','',$texto);?>
	<?php 
	if($salida->estadosalida=='Pendiente')echo Form::Select('salida.estadosalida',array('Pendiente'=>'Pendiente','PAGADO'=>'Pagado'),'','Pendiente');else echo Form::hidden('salida.estadosalida','','Pendiente');?>
	<?php if($salida->estadosalida=='Editable'){?><button type="submit" class="btn btn-xs btn-primary">Finalizar</button> 
	<?php echo Html::linkAction('agregardetalles','Editar','class="btn btn-xs"')?><?Php }else{?><?php //echo Html::linkAction('versalida_i','Imprimir','class="btn btn-xs"')?><?php }?>
<?php echo Form::close();
}
?>
<button onclick="myFunction()" class="btn btn-xs btn-info"> IMPRIMIR </button>
</div>
<script>
function myFunction() {
    window.open("http://"+document.domain+"/imprimir/detalles", "_blank", "toolbar=NO, scrollbars=yes, resizable=yes, top=100, left=250, width=600, height=400");
}
</script>

</div>
