<?php
View::content();
echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<script type="text/javascript">
        $(document).ready(function() {
            $("#prod").tokenInput("<?php echo "/santacarmela/maquinas/resultados/18"?>", 
			{
				tokenLimit: 1,minChars: 1,
                onAdd: function (item) {
                   var VAL=item.id;
				   $("#tesproductos_id").val(VAL['id']);
				   $("#tesproductos_codigo").val(VAL['codigo']);
				   $("#tesproductos_nombre").val(VAL['nombre']);
				   $("#tesproductos_nombrecorto").val(VAL['nombrecorto']);
				   $("#tesproductos_abr").val(VAL['abr']);
				   $("#tesproductos_detalle").val(VAL['detalle']);
				   $("#tesproductos_precio").val(VAL['precio']);
                },
                onDelete: function (item) {
					$("#tesproductos_id").val('');
				   $("#tesproductos_codigo").val('<?php echo $codigo?>');
				   $("#tesproductos_nombre").val('');
				   $("#tesproductos_nombrecorto").val('');
				   $("#tesproductos_abr").val('');
				   $("#tesproductos_detalle").val('');
				   $("#tesproductos_precio").val('');
                }
            });
		});
        </script>
<strong>Si ya creó el producto puede buscarlo aqui</strong>
<br /><input name="prod" id="prod" type="text">
<hr />

<?php echo Form::open(NULL, 'post', 'class="form-horizontal"');
echo Form::hidden('tesproductos.id')
?>

<table width="75%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">
  <tr>
    <th width="19%" align="right" valign="top">Codigo:&nbsp;</th>
    <td width="34%" valign="top">
	<?php 
	echo Form::text('tesproductos.codigo','size="20" readonly="readonly"',$codigo)?></td>
    <th width="33%" align="right" valign="top">Nombre:&nbsp;</th>
    <td width="14%" valign="top"><?php echo Form::text('tesproductos.nombre','size="40"') ?></td>
  </tr>
  <tr>
    <th align="right" valign="top">Nombre corto:&nbsp;</th>
    <td valign="top"><?php echo Form::text('tesproductos.nombrecorto','size="30"') ?></td>
    <th align="right" valign="top">Abreviatura:&nbsp;</th>
    <td valign="top"><?php echo Form::text('tesproductos.abr','size="10"') ?></td>
  </tr>
  <tr>
    <th align="right" valign="top">Descripcion:&nbsp;</th>
    <td valign="top"><?php echo Form::textarea('tesproductos.detalle','cols="35" rows="4"') ?></td>
    <th align="right" valign="top">Maxima Produccion</th>
    <td valign="top"><?php echo Form::text('promaquinas.maxproduccion','size="6" class="qty"')?></td>
  </tr>
  <tr>
    <th align="right" valign="top">Sotk Minimo</th>
    <td valign="top"><?php echo Form::text('tesproductos.stokminimo','size="10"')?></td>
    <th align="right" valign="top">Sotk Maximo</th>
    <td valign="top"><?php echo Form::text('tesproductos.stokmaximo','size="10"')?></td>
  </tr>
  <tr>
    <th align="right" valign="top">Precio:&nbsp;</th>
    <td valign="top"><?php echo Form::text('tesproductos.precio') ?></td>
    <th align="right" valign="top">Codigo Proveedor</th>
    <td valign="top"><?php echo Form::text('testproductos.cod_proveedor','size="30"')?></td>
  </tr>
  <tr>
    <th align="right" valign="top">Prefijo:&nbsp;</th>
    <td valign="top"><?php echo Form::text('promaquinas.prefijo') ?></td>
    <th align="right" valign="top">Número:&nbsp;</th>
    <td valign="top"><?php echo Form::text('promaquinas.numero') ?></td>
  </tr>
</table>
<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('listado', 'Cancelar', 'class="btn"'); ?>
    </div>