<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>
<div class="card">
    <h1><em>Maquinas de Tejer</em></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="form-actions">
    <?php echo Html::linkAction("crear/$page", 'Ingresar Nueva Maquina','class="btn btn-xs btn-primary"') ?>
</div>
<div id="ver_resultado"></div>
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
  <tr>
  	<th width="17">Nº</th>
    <th width="62">Codigo</th>
    <th width="53">Prefijo</th>
    <th width="36">Numero </th>
    <th width="218">Nombre </th>
    <th width="42">Estado </th>
    <th width="56">Acciones </th>
  </tr>
<?php $n=0;
foreach($maquinas->items as $item){ $n++;?>
  <tr id="<?php echo $item->id?>">
  	<td><?php echo $n?></td>
    <td><?php echo $item->getTesproductos()->codigo?></td>
    <td><?php echo $item->prefijo?></td>
    <td><?php echo $item->numero?></td>
    <td><?php echo $item->getTesproductos()->nombre.' ('.$item->nombre.')';?></td>
   <td>
    <?php 
	 if($item->activo=='0'){
	 echo Html::linkAction('activar/'.$item->id.'/'.$page,Html::img("figuras/circulo_rojo.png",'Editar','style="width: 20px;margin-left:5px;margin-right:5px;"'),'');
	 }else{
	 echo Html::linkAction("desactivar/$item->id/$page",Html::img("figuras/circulo_verde.png",'Editar','style="width: 20px;margin-left:5px;margin-right:5px;"'), 'onclick="return confirm(\'¿Está seguro?\')"');}?>
    </td>
    <td>
	<?php echo Html::linkAction('editar/'.$item->id.'/'.$page,Html::img("figuras/editar.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'')?>
    <?php echo Html::linkAction("borrar/$item->id/$page",Html::img("figuras/eliminar.png",'Eliminar','style="width: 20px;margin-left:1px;margin-right:1px;"'), 'onclick="return confirm(\'¿Está seguro?\')"');?>
    <?php //echo Html::linkAction("ver/$item->id/$page",Html::img("figuras/ver.png",'Eliminar','style="width: 20px;margin-left:1px;margin-right:1px;"'));?>
    </td>
  </tr>
<?php }?>
</table>
<?php View::partial('paginators/classic', false, array('page' => $maquinas ,'url' => Router::get('controller_path').'/listado')); ?>
<div class="form-actions">
    <?php //echo Html::linkAction("crear/$page", 'Crear Maquinas','class="btn btn-xs btn-primary"') ?>
</div>