<?php
//$inven=$INGR->getInventario(Session::get("TIPOPRODUCTO_ID"));

View::content();
echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<style type="text/css">
/*.container {
  width: 1124px;
}*/
#items,input,tesarea,th,td{
	font-size:11px !important;
}
.item-row td{
	padding-left:15px !important;
	}
#paid
{
	width:80% !important;
}
.meta td{
	font-size:14px !important;
	
	}
ul.token-input-list{ width:150px !important;}
</style>
<div class="card">
	<h1>Reporte de Hilos<span>Reporte de precios de hilo por producto</span></h1>
</div>
    <div style="clear:both"></div>
<form id="buscar" class="form-inline">
<div class="input-prepend input-append">
  <span class="add-on" title="Buscar Producto!">Buscar Producto:</span>
  <input type="text" id="local_producto" name="local_producto" class="input-medium search-query" />
</div>
<div class="input-prepend input-append">
  <span class="add-on" title="Ingrese el Color del Producto!">Color:</span>
  <input type="text" id="local_color" name="local_color" class="input-medium search-query" />
</div>
<div class="form-actions" title="Regresar!">
    <?php echo Html::linkAction("",'Regresar ','class="btn btn-xs btn"') ?><button id="enviar" type="button" class="btn btn-xs" title="Movimientos!">Ver</button>
</div>
  	
</form>
<hr />
    <div class="card-body">
    <div id="loading" style="display:none;"><img src="/img/spin.gif" /></div>
    <div id="kardex"></div>
    <div style="clear:both"></div>
	</div>
<script type="text/javascript">
$(document).ready(function()
{
	$("#enviar").click(function()
	{
		var data=$("#buscar").serialize();
		$.ajax({
			type:"POST",
			url:"/<?php echo $module_name?>/<?php echo $controller_name?>/ver_hilo",
			data:data,
			beforeSend:function(){
				$("#loading").show();
				},
			success:function(response){
				$("#loading").hide();
				$("#kardex").prepend(response);
				//alert(response);
			}
		});
				
	});
	
	$("#local_producto").tokenInput(
	[<?php echo (string)$PP?>],
	{
		minChars: 1,
		tokenLimit: 1
	});
	$("#local_color").tokenInput(
	[<?php echo (string)$CC?>],
	{
		minChars: 1,
		tokenLimit: 1
	});
			
});
</script>
        