<?php View::content();?>
<div class="form-actions">
<span class="print btn btn-primary"> Print </span> 
<a href="javascript:;" class="btn btn-xs botonExcel">Enviar a Excel<img src="/img/export_to_excel.gif" class="" /></a>
<form action="/utiles/excel" method="post" target="_blank" id="FormularioExportacion" class="form-inline">
<input type="hidden" id="datos_a_enviar" name="datos_a_enviar"/>
<input type="hidden" id="nombre" name="nombre" value="Precios_Clientes <?php echo $dato->id?>"/>
</form>
</div>
<div class="input-prepend input-append">
  <span class="add-on">Buscar :</span>
 <input type="search" id="txtBuscar" autofocus placeholder="Digite el texto que desea encontrar y presione ENTER. Para cancelar la tecla ESCAPE." class="span7 input-medium search-query">
</div>
<div class="card-body">
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped" id="cliente">
<caption><?php echo Session::get("EMPRESAS_NOMBRE");?></caption>
  <tr>
    <th colspan="6" align="left"><?Php echo $dato->razonsocial;?>
    </th>
  </tr>
  <tr>
    <th width="24%" align="left">Fechas</th>
	<th width="22%" align="left">Documentos</th>
    <?php /*?><th width="10%" align="left">Codigo</th><?php */?>
    <th width="30%" align="left">Tela</th>
    <th width="15%" align="right">Metros</th>
    <th width="9%" align="right">Peso</th>
  </tr>
 <?Php foreach($detalles as $item){?>
  <tr>
    <td><?php echo Sp::formatFecha('%d/%m/%Y',$item->a)?> - <?php echo Sp::formatFecha('%d/%m/%Y',$item->b)?></td>
	<td><?php echo $item->numero?></td>
    <?php /*?><td><?php //echo $item->codigo?></td><?php */?>
    <td><?php echo $item->nombre?></td>
   
    <td align="right"><?php echo number_format($item->metros,2,'.',',');?></td>
    <td align="right"><?php echo number_format($item->peso,2,'.',',');?></td>
  </tr>
 <?php }?>
</table>
<script type="text/javascript">
$(document).ready(function()
{
	$('#txtBuscar').on('search',function(){
		$.fntBuscarEnTabla($(this).val(),'cliente');
		
	});
$(".botonExcel").click(function(event)
	{
		$("#datos_a_enviar").val( $("<div>").append( $("#cliente").eq(0).clone()).html());
		$("#FormularioExportacion").submit();
	});
});
$(function() {
	
	$('.print').click(function() {
		$('div.page').printArea();
		return false;
	});
	
});
</script>
</div>