<?php echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<div class="card">
    <h1>Reporte de Cantidades<span>Reporte de Cantidades por cliente en un rango de fechas</span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="span12">
  <div style="margin:5px;float:left; width:40%; display:inline-block;"> 
   <label><b>Cliente</b></label>
    <input id="CL" />
      <?php echo Form::hidden('tesdatos_id');?>
     <a href="javascript:;" id="ver_d" class="btn"> Ver >></a>
  </div>
  <div style="margin:5px;float:left; width:40%; display:inline-block;"> 
   <label><b>Fecha inicio</b></label><?php echo Calendar::text('inicio')?>
   <label><b>Fecha Fin</b></label> <?php echo Calendar::text('fin')?>
  </div>
  
</div>
<div class="clear"></div>
<hr />
<div id="ver"><div class="form-actions"><?php echo Html::linkAction('precios','Ver Reporte de Precios','class="btn btn-primary"')?></div></div>
<script type="text/javascript">
$(document).ready(function()
{
	$("#CL").tokenInput("/<?php echo $module_name?>/salidas/buscarcliente", 
		{
			tokenLimit: 1,
			minChars: 2,
	
			onAdd: function (item){
			   var VAL=item.id;
			   $("#tesdatos_id").val(VAL);
			},
			onDelete: function (item) {
				$("#ver").html('');
			}
		});

$("#ver_d").click(function(){
	alert("/"+$("#inicio").val()+"/"+$("#fin").val());
	$.ajax({
		type:"POST",
		url:"/<?php echo $module_name?>/<?php echo $controller_name?>/cantidades_clientes/"+$("#tesdatos_id").val()+"/"+$("#inicio").val()+"/"+$("#fin").val(),
		success:function(response)
		{
			$("#ver").html(response);
		}
		});
	});

});
</script>