
<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>
<table width="556" border="0">
	<tr>
		<td width="60">&nbsp;</td>
		<td width="111">Textil Santa Patricia SA</td>
		<td width="36">&nbsp;</td>
		<td width="40">&nbsp;</td>
		<td width="33">&nbsp;</td>
		<td width="36">&nbsp;</td>
		<td width="41">&nbsp;</td>
		<td width="31">&nbsp;</td>
		<td width="32">Fecha:</td>
		<td width="34">14/03/2013</td>
		<td width="32">&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td colspan="9">--------------------------------------------------------------------------------------------------------------</td>
		<td>&nbsp;</td>
	</tr>
	
</table>

<table width="556" border="0">
	<tr>
		<td width="61">&nbsp;</td>
		<td colspan="9" align="center">***Ultimos Movimientos***</td>
		<td width="34">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="11">&nbsp;</td>
	</tr>
	
</table>

<table width="556" border="0">
	<tr>
		<td width="61">&nbsp;</td>
		<td width="72">Cliente:</td>
		<td width="76">000901-14---&gt;</td>
		<td colspan="2">CY ARTESANIAS TRADING S.A.C.</td>
		<td width="34">&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>Direccion:</td>
		<td colspan="3">Cal. WALLALLO MZA Q INT. F LT. 7 CIENEGUILLA</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>Telefono(s):</td>
		<td>4799198</td>
		<td width="59">Contacto:</td>
		<td width="228">Juan Enrique Albarado</td>
		<td>&nbsp;</td>
	</tr>
</table>
<p>&nbsp;</p>
<table width="556" border="0">
	<tr>
		<td width="58">&nbsp;</td>
		<td width="74">Fecha</td>
		<td width="134">Documento de Referencia</td>
		<td width="29">Mov</td>
		<td width="56">Abono S/.</td>
		<td width="50">Cargo S/.</td>
		<td width="50">Abono $/.</td>
		<td width="42">Cargo $/.</td>
		<td width="25">&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td colspan="7"><hr /></td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>01/02/2013</td>
		<td>001-15764</td>
		<td>VT</td>
		<td>&nbsp;</td>
		<td>1000</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>08/02/2013</td>
		<td>001-17769</td>
		<td>VT</td>
		<td>&nbsp;</td>
		<td>1500</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>10/02/2013</td>
		<td>ACC-CREDITO</td>
		<td>AB</td>
		<td>2500</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
</table>
<table width="556" border="0">
	<tr>
		<td width="60">&nbsp;</td>
		<td width="286">Pendiente de Cobranza----&gt;</td>
		<td width="17">S/.</td>
		<td width="84">0.00</td>
		<td width="16">$/.</td>
		<td width="40">0.00</td>
		<td width="23">&nbsp;</td>
	</tr>
</table>

<p>&nbsp;</p>
<table width="556">
	<tr>
		<td width="58">&nbsp;</td>
		<td colspan="4">Letras Giradas-----&gt;</td>
		<td width="116">&nbsp;</td>
		<td width="19">&nbsp;</td>
		<td width="85">&nbsp;</td>
		<td width="12">&nbsp;</td>
		<td width="32">&nbsp;</td>
		<td width="24">&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td width="30">&nbsp;</td>
		<td width="44">&nbsp;</td>
		<td width="44">&nbsp;</td>
		<td width="44">&nbsp;</td>
		<td>Marzo:</td>
		<td>S/</td>
		<td>1500.00</td>
		<td>$/</td>
		<td>0.00</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>Abril:</td>
		<td>S/</td>
		<td>1480.00</td>
		<td>$/</td>
		<td>0.00</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>Mayo</td>
		<td>S/</td>
		<td>19000.00</td>
		<td>$/</td>
		<td>0.00</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>Meses Posteriores:</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td colspan="4">&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td colspan="4">Credito Total-----&gt;</td>
		<td>&nbsp;</td>
		<td>S/</td>
		<td>21980.00</td>
		<td>$/</td>
		<td>0.00</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td colspan="4">Total General-----&gt;</td>
		<td>&nbsp;</td>
		<td>S/</td>
		<td>21980.00</td>
		<td>$/</td>
		<td>0.00</td>
		<td>&nbsp;</td>
	</tr>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
