<div id="mensajes_flash">
	<?php View::content() ?>
</div>
<div class="card">
	<div class="card-header">
		<h3 class="card-title"><?php echo $titulo ?></h3>
		<div class="card-tools">
			<?php echo Menu::menuVentas($action_name); ?>
		</div>
	</div>
	<div class="form-actions">
		<?php if (Session::get('DOC_ID') == 7) { ?>
			
		<?php } else {
			//echo Html::link("guias/15", "Volver a Guias", "class='btn btn-info'");
		} ?>
	</div>
	<div class="card-body">

<?php echo Calendar::getMeses($anio, $meses, $mes_activo) ?>
		<div id="ver_resultado"></div>
		<table width="80%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
			<caption>Ultimas <?php echo Session::get('DOC_NOMBRE') ?> Emitidas ! 
			 <?php echo Html::linkAction("cargar_doc/7/factura_adelanto", 'Crear FA ', 'class="btn btn-xs btn-info float-right" title="Crear Factura Adelanto"') ?></caption>
			<tr>
				<th width="73" align="left">Fecha.</th>
				<th width="91" align="left">Número Doc.</th>
				<th width="91" align="left">Codigo</th>
				<th width="190" align="left">Cliente</th>
				<th width="62" align="right">Sub-total</th>
				<th width="66" align="right">Igv</th>
				<th width="56" align="right">Total</th>
				<th width="114" align="center">Acciones </th>
			</tr>
			<?php $number = 0;
			foreach ($salidas as $item) {
				$simbolo = "S/. ";

				switch ($item->tesmonedas_id) {
					case 1:
						$simbolo = 'S/. ';
						break;
					case 2:
						$simbolo = '$. ';
						break;
					case 4:
						$simbolo = 'S/. ';
						break;
					case 5:
						$simbolo = '$. ';
						break;
					case 0:
						$simbolo = 'S/. ';
						break;
				}

				$number++; ?>
				<tr id="<?php echo $item->id ?>">
					<td height="20"><?php //echo $item->femision
									?><?php echo Sp::formatFecha('%d/%m/%Y', $item->femision); ?></td>
					<td height="20"><?php echo $item->serie ?>-<?php echo $item->numero ?></td>
					<td height="20"><?php echo $item->npedido ?></td>
					<td><?php echo $item->getTesdatos()->razonsocial ?></td>

					<td align="right"><?php if ($item->totalconigv != 'NaN.00' && !empty($item->totalconigv)) echo $simbolo . number_format($item->totalconigv - $item->igv, 2, '.', '');
										else echo ('S/ 00.00'); ?></td>
					<td align="right"><?php if ($item->totalconigv != 'NaN.00' && !empty($item->totalconigv)) echo $simbolo . number_format($item->igv, 2, '.', '');
										else echo ('S/ 00.00') ?></td>
					<td align="right"><?php if ($item->totalconigv != 'NaN.00' && !empty($item->totalconigv)) echo $simbolo . number_format($item->totalconigv, 2, '.', '');
										else echo ('S/ 00.00') ?></td>
					<td align="center">
						<?php if ($item->estadosalida == "Editable") {
							$pos = strpos($item->npedido, 'PA');
							if ($pos === FALSE) {
								echo Html::linkAction('cargarsalida/' . $item->id . '/venta', Html::img("figuras/editar.png", 'EDITAR', 'style="width: 20px;margin-left:1px;margin-right:1px;"'), 'title="Editar Guia - 001"');
							} else {
								//factura_adelanto
								echo Html::linkAction('factura_adelanto/' . $item->id, Html::img("figuras/editar.png", 'EDITAR', 'style="width: 20px;margin-left:1px;margin-right:1px;"'), 'title="Editar Factura! - 001"');
							}
						} ?>
						<?php
						//echo $item->npedido;
						$pos = strpos($item->npedido, 'PA');
						if ($pos === FALSE) {
							echo Html::linkAction('cargarsalida/' . $item->id . '/versalida', Html::img("figuras/ver.png", 'Ver', 'style="width: 20px;margin-left:1px;margin-right:1px;"'), 'title="Ver e Imprimir Factura!"');
						} else {
							echo Html::linkAction('cargarsalida/' . $item->id . '/versalida_adelanto', Html::img("figuras/ver.png", 'Ver', 'style="width: 20px;margin-left:1px;margin-right:1px;"'), 'title="Ver e Imprimir Factura!"');
						} ?>
						<?php //echo Html::linkAction("borrar/$item->id",Html::img("figuras/eliminar.png",'Eliminar','style="width: 20px;margin-left:1px;margin-right:1px;"'), 'onclick="return confirm(\'¿Está seguro?\')"');
						?>
						<?php if (Session::get('DOC_ID') != 15) {
							if ($item->estadosalida != 'ANULADO') echo Html::linkAction("anularfacturas/$item->id/", ' X ', 'class="btn btn-xs btn-danger" title="Anular" onclick="return confirm(\'¿Está seguro de anular esta factura ?\')"');
							else echo "Anulado";
						} ?>
					</td>
				</tr>
			<?php } ?>
		</table>
		<hr />

		<?Php
		if ($guias) {
			echo Form::open($module_name . '/ventas/generarfactura', 'POST'); ?>
			<fieldset>
				<legend>Seleccionar Guia(s) a Facturar!

				</legend>
				<table width="80%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
					<caption>Seleccionar Guia(s)para Facturar!</caption>
					<tr>
						<th width="57" align="left">Fecha.</th>
						<th width="247" align="left">Cliente</th>
						<th width="125" align="left">Número de Guia.</th>
						<th width="119" align="left"> Numero de Factura</th>
						<th width="112" align="center">Acciones </th>
					</tr>
					<?php $number = 0;
					foreach ($guias as $item) {
						$simbolo = "S/. ";

						switch ($item->tesmonedas_id) {
							case 1:
								$simbolo = 'S/. ';
								break;
							case 2:
								$simbolo = '$. ';
								break;
							case 4:
								$simbolo = 'S/. ';
								break;
							case 5:
								$simbolo = '$. ';
								break;
							case 0:
								$simbolo = 'S/. ';
								break;
						}

						$number++; ?>
						<tr id="<?php echo $item->id ?>">
							<td height="20"><?php //echo $item->femision
											?><?php echo Sp::formatFecha('%d/%m/%Y', $item->femision); ?></td>
							<td height="20"><?php echo $item->getTesdatos()->razonsocial ?></td>
							<td><?php echo $item->serie ?>-<?php echo $item->numero ?></td>
							<td><?php echo $item->numerofactura ?></td>
							<td align="center">

								<label class="checkbox" style="float:left; width:90px;">
									<input type="checkbox" name="itemSelect[]" value="<?php echo $item->id ?>" class="sele"> Seleccionar
								</label>
								<?php if ($item->estadosalida != 'ANULADO') echo Html::linkAction("anularguias/$item->id/", ' X ', 'class="btn btn-xs btn-danger" title="Anular" onclick="return confirm(\'¿Está seguro de anular esta guia los rollos seran restablecidos ?\')"');
								else echo "Anulado"; ?>

							</td>
						</tr>
					<?php } ?>
				</table>
				<button type="submit" class="btn btn-xs btn-primary">Emitir Factura!</button>
			</fieldset>
			<?php echo Form::hidden('facturas.ids'); ?>
		<?Php echo Form::close();
		} ?>
	</div>


	<script type="text/javascript">
		$(document).ready(function() {

			$('.sele').click(function() {
				var selectedItems = new Array();

				$("input[@name='itemSelect[]']:checked").each(function() {
					selectedItems.push($(this).val());
				});
				$("#facturas_ids").val(selectedItems);
			});
		});
	</script>
	<script type="text/javascript">
		$(document).ready(function() {
			$("#anio").change(function(event) {
				var id = $("#anio").find(':selected').val();
				location.href = '/<?php echo $module_name ?>/<?php echo $controller_name ?>/<?php echo $action_name ?>/' + id;
			});
			$(".enviar").click(function() {
				var fecha = $(this).attr('data-id');
				var F = fecha.split('-');
				location.href = '/<?php echo $module_name ?>/<?php echo $controller_name ?>/<?php echo $action_name ?>/' + F[0] + '/' + F[1];
			});
		});
	</script>
</div>