<div id="mensajes_flash">
	<?php View::content() ?>
</div>
<div class="card">
	<div class="card-header">
		<h3 class="card-title">Ventas por mes!</h3>
		<div class="card-tools">
			<?php echo Menu::menuVentas($action_name); ?>
		</div>
	</div>
	<div class="card-body">
		<?php echo Calendar::getMeses($anio,$meses,$mes_activo)?>
		<div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <button type="button" class="btn btn-xs btn-sm">Buscar :</button>
                  </div>
                  <!-- /btn-group -->
				  <input type="search" id="txtBuscar" autofocus="" placeholder="Digite el texto que desea encontrar y presione ENTER. Para cancelar la tecla ESCAPE." 
				  class="form-control form-control-sm input-medium search-query">
		
                </div>
		<?php echo Sp::imprimir('Ventas - ', 'P'); ?>
			<div id="ver_resultado"></div>
			<table width="99%" cellpadding="0" cellspacing="0" class="table-bordered table-striped" id="exportar_excel">
				<caption>Facturas del Mes!</caption>
				<tr>
					<th width="17">Nº</th>
					<th width="63">F. Emision.</th>
					<th width="196">Cliente</th>
					<th width="91">Número Doc.</th>
					<th width="68">Sub-total</th>
					<th width="65">Igv</th>
					<th width="82">Total</th>
				</tr>
				<?php $number = 0;
				foreach ($ventas as $item) {
					$simbolo = "S/. ";

					switch ($item->tesmonedas_id) {
						case 1:
							$simbolo = 'S/. ';
							break;
						case 2:
							$simbolo = '$. ';
							break;
						case 4:
							$simbolo = 'S/. ';
							break;
						case 5:
							$simbolo = '$. ';
							break;
						case 0:
							$simbolo = 'S/. ';
							break;
					}

					$number++; ?>
					<tr id="<?php echo $item->id ?>">
						<td height="20"><?php echo $number ?></td>
						<td height="20"><?php echo Sp::formatFecha('%d/%m/%Y', $item->femision) ?></td>
						<td height="20"><?php echo $item->getTesdatos()->razonsocial ?></td>
						<td><?php echo $item->serie ?>-<?php echo $item->numero ?></td>
						<td align="right"><?php if ($item->totalconigv != 'NaN.00' && !empty($item->totalconigv)) echo $simbolo . number_format($item->totalconigv - $item->igv, 2, '.', '');
											else echo ('S/ 00.00'); ?></td>
						<td align="right"><?php if ($item->igv != 'NaN.00' && !empty($item->totalconigv)) echo $simbolo . number_format($item->igv, 2, '.', '');
											else echo ('S/ 00.00') ?></td>
						<td align="right"><?php if ($item->totalconigv != 'NaN.00' && !empty($item->totalconigv)) echo $simbolo . number_format($item->totalconigv, 2, '.', '');
											else echo ('S/ 00.00') ?></td>
					</tr>
				<?php } ?>
			</table>
		<script type="text/javascript">
			$(document).ready(function() {
				$('#txtBuscar').on('search', function() {
					//le decimos a la funcion que busque en la tabla tblTabla el
					//valor que contiene el campo actual
					$.fntBuscarEnTabla($(this).val(), 'exportar_excel');

				});
				$("#anio").change(function(event) {
					var id = $("#anio").find(':selected').val();
					location.href = '/<?php echo $module_name ?>/ventas/index/' + id;
				});
				$(".enviar").click(function() {
					var fecha = $(this).attr('data-id');
					var F = fecha.split('-');
					location.href = '/<?php echo $module_name ?>/ventas/index/' + F[0] + '/' + F[1];
				});

			});
		</script>
	</div>
</div>