<style type="text/css">
	.span_float {
		float: right !important;
		margin-left: 0px;
		margin-right: -5px;
	}
</style>
<div id="mensajes_flash">
	<?php View::content() ?>
</div>
<div class="card">
	<div class="card-header">
		<h3 class="card-title"><?php echo $titulo ?></h3>
		<div class="card-tools">
			<?php echo Menu::menuVentas($action_name); ?>
		</div>
	</div>
	<div class="card-body">

		<?php echo Calendar::getMeses($anio, $meses, $mes_activo) ?>
		<div id="ver_resultado"></div>
		<table border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
			<caption>
				<?php $titulos = "Facturas Emitidas";
				if (Session::get('DOC_ID') == 15) $titulos = "Guias Emitidas";
				echo $titulos ?>
				<?php
				if (Session::get('DOC_ID') == 15) echo Html::linkAction("cargar_doc/7/listado_servicio", 'Volver ', 'class="btn btn-xs"') . ' ' . Html::linkAction("cargar_doc/15/guia_servicio", 'Crear Guia por Servicio ', 'class="btn btn-xs btn-primary float-right"') ?>

			</caption>
			<tr>
				<th width="21">Nº</th>
				<th width="169">Cliente</th>
				<th width="102">Número Doc.</th>
				<th width="241">Productos</th>
				<th width="112">Sub-total</th>
				<th width="61">Igv</th>
				<th width="72">Total</th>
				<th width="52" align="right">Acciones</th>
			</tr>
			<?php $number = 0;
			foreach ($salidas as $item) {
				$simbolo = "S/. ";

				switch ($item->tesmonedas_id) {
					case 1:
						$simbolo = 'S/. ';
						break;
					case 2:
						$simbolo = '$. ';
						break;
					case 4:
						$simbolo = 'S/. ';
						break;
					case 5:
						$simbolo = '$. ';
						break;
					case 0:
						$simbolo = 'S/. ';
						break;
				}

				$number++; ?>
				<tr id="<?php echo $item->id ?>" title="<?Php echo $item->femision ?>">
					<td height="20"><?php echo $number ?></td>
					<td height="20"><?php echo $item->getTesdatos()->razonsocial ?></td>
					<td><?php echo $item->serie ?>-<?php echo $item->numero ?></td>
					<td>
						<small style="color:#666; font-size:10px !important; font-style:italic; ">
							<?php

							$n = 0;
							$m = 0;
							foreach ($item->getTesdetallesalidas() as $det) {
								if ($det->tesproductos_id != 0) {
									$n++;
									echo $det->getTesproductos()->nombre;
									if (count($item->getTesdetallesalidas()) > $n) {
										echo ", ";
									}
								} else {
									echo $det->concepto;
								}
							}
							?>
						</small>
					</td>
					<td align="right"><?php if ($item->totalconigv != 'NaN.00' && !empty($item->totalconigv)) echo $simbolo . number_format($item->totalconigv - $item->igv, 2, '.', '');
										else echo ('S/ 00.00'); ?></td>
					<td align="right"><?php if ($item->totalconigv != 'NaN.00' && !empty($item->igv)) echo $simbolo . number_format($item->igv, 2, '.', '');
										else echo ('S/ 00.00') ?></td>
					<td align="right"><?php if ($item->totalconigv != 'NaN.00' && !empty($item->totalconigv)) echo $simbolo . number_format($item->totalconigv, 2, '.', '');
										else echo ('S/ 00.00') ?></td>
					<td align="right">
						<?php
						if ($item->estadosalida == "Editable") {
							$pos = strpos($item->npedido, 'PA');
							if ($pos === FALSE) {
								if(Session::get('DOC_ID') == 7){
									echo Html::linkAction('cargarsalida/' . $item->id . '/factura_servicio', '<i class="fa fa-edit"></i>', 'title="Editar Guia - 001"');
								}
								if(Session::get('DOC_ID') == 15){
									echo Html::linkAction('cargarsalida/' . $item->id. '/factura_servicio_detalle' , '<i class="fa fa-edit"></i>', 'title="Editar Guia - 001"');
								}
							} else {
								//factura_adelanto
								echo Html::linkAction('factura_adelanto/' . $item->id, '<i class="fa fa-search"></i>', 'title="Editar Factura! - 001"');
							}
						} ?>
						<?php
						//echo $item->npedido;
						$pos = strpos($item->npedido, 'PA');
						if ($pos === FALSE) {
							echo Html::linkAction('cargarsalida/' . $item->id . '/versalida_servicio', '<i class="fa fa-search"></i>', 'title="Ver e Imprimir Factura!"');
						} else {
							echo Html::linkAction('cargarsalida/' . $item->id . '/versalida', '<i class="fa fa-search"></i>', 'title="Ver e Imprimir Factura!"');
						} ?>
						<?php //if($item->estadosalida!='ANULADO')echo Html::linkAction("anularfacturas/$item->id/",' X ','class="btn btn-xs btn-danger" title="Anular" onclick="return confirm(\'¿Está seguro de anular esta factura ?\')"'); else echo "Anulado";
						?>
					</td>
				</tr>
			<?php } ?>
		</table>
		<hr />
		<?php if (Session::get('DOC_ID') == 7) { ?>
			<?Php echo Form::open($module_name . '/ventas/generarfactura', 'POST'); ?>
			<fieldset>
				<legend>Seleccionar Guia(s) a Facturar!

				</legend>
				<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">
					<caption>Seleccionar Guia(s)para Facturar!</caption>
					<tr>
						<th width="20">Nº</th>
						<th width="307">Cliente</th>
						<th width="220">Número Doc.</th>
						<th width="187">Numero de Factura</th>
						<th width="94">Acciones</th>
					</tr>
					<?php $number = 0;
					foreach ($guias as $item) {
						$simbolo = "S/. ";

						switch ($item->tesmonedas_id) {
							case 1:
								$simbolo = 'S/. ';
								break;
							case 2:
								$simbolo = '$. ';
								break;
							case 4:
								$simbolo = 'S/. ';
								break;
							case 5:
								$simbolo = '$. ';
								break;
							case 0:
								$simbolo = 'S/. ';
								break;
						}

						$number++; ?>
						<tr id="<?php echo $item->id ?>">
							<td height="20"><?php echo $number ?></td>
							<td height="20"><?php echo $item->getTesdatos()->razonsocial ?> </td>
							<td><?php echo $item->serie ?>-<?php echo $item->numero ?></td>
							<td align="center"><?php echo $item->numerofactura ?></td>
							<td>

								<label class="checkbox" style="float:left; width:90px;">
									<input type="checkbox" name="itemSelect[]" value="<?php echo $item->id ?>" class="sele"> Seleccionar
								</label>

							</td>
						</tr>
					<?php } ?>
				</table>
				<?php if ($number != 0) { ?><button type="submit" class="btn btn-xs btn-primary">Emitir Factura!</button> <?Php } ?>
			</fieldset>
			<?php echo Form::hidden('facturas.ids'); ?>
			<?Php echo Form::close(); ?>



			<script type="text/javascript">
				$(document).ready(function() {

					$('.sele').click(function() {
						var selectedItems = new Array();

						$("input[@name='itemSelect[]']:checked").each(function() {
							selectedItems.push($(this).val());
						});
						$("#facturas_ids").val(selectedItems);
					});
				});
			</script>
		<?php } ?>

		<script type="text/javascript">
			$(document).ready(function() {
				$("#anio").change(function(event) {
					var id = $("#anio").find(':selected').val();
					location.href = '/<?php echo $module_name ?>/<?php echo $controller_name ?>/<?php echo $action_name ?>/' + id;
				});
				$(".enviar").click(function() {
					var fecha = $(this).attr('data-id');
					var F = fecha.split('-');
					location.href = '/<?php echo $module_name ?>/<?php echo $controller_name ?>/<?php echo $action_name ?>/' + F[0] + '/' + F[1];
				});
			});
		</script>
	</div>


</div>