<?php View::content();?>
<div class="form-actions">

<span class="print btn btn-primary"> Print </span> 
<a href="javascript:;" class="btn btn-xs botonExcel">Enviar a Excel<img src="/img/export_to_excel.gif" class="" /></a>
<form action="/utiles/excel" method="post" target="_blank" id="FormularioExportacion" class="form-inline">
<input type="hidden" id="datos_a_enviar" name="datos_a_enviar"/>
<input type="hidden" id="nombre" name="nombre" value="Precios_Clientes <?php echo $producto->id?>"/>
</form>
</div>

<div class="card-body">
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped" id="cliente">
  <tr>
    <th colspan="7" align="left">
    <h2>
    Tela: <?Php echo $producto->nombre;?>
    </h2>
    </th>
  </tr>
  <tr>
    <th width="12%" align="left">Fecha</th>
	<th width="8%" align="left">No. Doc</th>
    <th width="27%" align="left">Cliente</th>
    <th width="11%" align="left">Color</th>
    <th width="15%" align="left">Metros</th>
    <th width="14%" align="right">Precio S/.</th>
    <th width="13%" align="right">Precio $.</th>
  </tr>
 <?Php foreach($detalles as $item){?>
  <tr>
    <td><?php echo Sp::formatFecha('%d/%m/%Y',$item->fecha)?></td>
	<td><?php echo $item->numero?></td>
    <td><?php echo $item->razonsocial?> </td>
    <td><?php echo $item->tescolores_id!='' ? $item->getTescolores()->nombre : ''; ?></td>
    <td><?php echo number_format($item->cantidad,2,'.','')?></td>
    <td align="right"><?php if($item->tesmonedas_id==1)echo number_format($item->preciounitario,2,'.','');?></td>
    <td align="right"><?php /*echo $item->preciounitario*/ if($item->tesmonedas_id==2)echo number_format($item->preciounitario,2,'.','');?></td>
  </tr>
 <?php }?>
</table>
<script type="text/javascript">
$(document).ready(function()
{	

});
$(function() {
	
	$('.print').click(function() {
		$('div.page').printArea();
		return false;
	});
	
});
</script>
</div>