<div class="card">
    <div class="card-header">
        <h3 class="card-title">Facturacion!</h3>
		<div class="card-tools">
			<?php echo Menu::menuVentas($action_name); ?>
		</div>
    </div>
    <div class="card-body">
        <div class="col-sm-12">
            <?php echo Html::linkAction("cargar_doc/7/facturas", 'Facturas de telas', 'class="btn btn-primary"') ?>
            - <?php echo Html::linkAction("cargar_doc/7/factura_adelanto", 'Factura por Adelanto ', 'class="btn btn-primary"') ?>
            - <?php echo Html::linkAction("cargar_doc/7/listado_servicio", 'Facturas por Servicio', 'class="btn btn-primary"') ?>
            - <?php echo Html::link($module_name . "/ventasproductos", 'Facturas de productos', 'class="btn btn-primary"') ?>
        </div>
    </div>
</div>