<div class="card"><h1>Venta - <?php echo Session::get('DOC_NOMBRE')?></h1></div>
<style type="text/css">
.page {
position: relative;
z-index: 2;
}

.texto {
color:#F00;
position:absolute;
padding-top:10%;
text-align:center ;
z-index:1;
top:0;
left:0;
right:0;
bottom:0;
font-size:36px !important;
}
</style>
<?php 
$monedas= $salida->tesmonedas_id;
switch ($monedas)
{
	case 1: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES'; break;
	case 2: $simbolo='$. ';$moneda_letras='DOLARES AMERICANOS';  break;
	case 4: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES';  break;
	case 5: $simbolo='$. ';$moneda_letras='DOLARES AMERICANOS';  break;
	case 0: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES';  break;
}

?>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="card-body">
<?php if($salida->estadosalida=='ANULADO'){?><div class="texto"> ANULADO </div><?php }?>
<div id="ver_resultado"></div>

<table width="75%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered">
<caption>Detalle de la factura</caption>
  <tr>
    <th width="22%" align="left">Pedido:</th>
    <td width="34%"><?php echo $salida->npedido;?></td>
    <th width="34%" align="left">Serie-Numero:</th>
    <td width="10%"><?php echo $salida->serie;?>-<?php echo $salida->numero;?></td>
  </tr>
  <tr>
    <th align="left">Moneda:</th>
    <td><?php echo $salida->getTesmonedas()->nombre;?></td>
    <th align="left">Fecha de Traslado:</th>
    <td><?php echo $salida->finiciotraslado;//finiciotraslado?></td>
  </tr>
  <tr>
    <th align="left">Cliente:</th>
    <td colspan="3"><?php echo $salida->getTesdatos()->razonsocial?> <?php echo ($salida->getTesdatos()->ar=='SI') ? ' <b class="text-error">Es Agente de Retencion</b>': '';?></td>
  </tr>
  <tr>
    <th align="left">Direccion de Entrega:</th>
    <td colspan="3"><?php echo $salida->direccion_entrega;//finiciotraslado?></td>
  </tr><?php if(Session::get('DOC_ID')==15){?>
  <tr>
    <th align="right">Conductor:</th>
    <td>
      <?php echo $prodetalletransportes->getProtransportistas()->nombre;?>
    </td>
    <th align="right">Transporte:</th>
    <td><?php echo $prodetalletransportes->getProtransportes()->modelo;?></td>
  </tr><?php }?>
</table>
<div id="guia">
<table width="81%" border="0" align="center" cellpadding="0" cellspacing="1" class="table table-hover">
<caption>Detalle del documento </caption>
  <tr>
    <th width="13%" align="left">Codigo</th>
    <th width="23%" align="left">Descripcion</th>
    <th width="14%" align="left">Cantidad</th>
    <th width="17%" align="left">Unidad</th>
    <?php //if(Session::get('DOC_ID')==7){?>
    <th width="11%" align="left">P. U</th>
    <th width="10%" align="left">Desto</th>
    <th width="12%" align="left">Importe</th>
	<?Php //}?>
  </tr>
  <?php
  $n=0;
  $total=0;
  foreach($detalles as $item){
	  $n++;
	  ?> 
  <tr id="<?php echo $item->id?>">
    <td><?php echo $n?>.
	<?php 
	if(empty($item->getProrollos()->prorollos_id))
	{
		//echo $item->prorollos_id
		echo $item->getProrollos()->numero?>-M
		<?php echo $item->getProrollos()->maquina_numero;
	}else{
	echo $item->getProrollos()->codigo?>-
	<?php echo $item->getProrollos()->numeroventa; 
	echo ' '.$item->getProrollos()->getNprocesos($item->prorollos_id);
	}?></td>
    <td><?php echo $item->getTesproductos()->nombre?> <?php echo $item->getTesproductos()->detalle?> <?Php if(!empty($item->tescolores_id))echo $item->getTescolores()->nombre?></td>
    <td><?php echo $item->cantidad?></td>
    <td><?Php echo $item->getTesunidadesmedidas()->simbolo?></td>
    <?php //if(Session::get('DOC_ID')==7){?>
    <td><?php echo $simbolo?><?php echo number_format($item->preciounitario,2,'.','');?></td>
    <td><?php if(empty($item->descuento))echo "0.00";else echo $item->descuento/100?></td>
    <td><?php echo $simbolo?><?php 
	if(empty($item->importe)){$total=$total+$item->preciounitario*$item->cantidad; echo $item->preciounitario*$item->cantidad; }else{ echo number_format($item->importe,2,'.','');$total=$total+number_format($item->importe,2,'.','');}?></td>
    <?php //}?>
  </tr>
  <?php }?>

 <?php 
   /*muesra la aplicacion a esta factura */
  if($aplicaciones){
  foreach($aplicaciones as $aplicacion){
  $n++;
  ?>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td align="right"> P/A <?php echo $aplicacion->getTesfacturasadelantos()->getTessalidas()->serie.'-'.$aplicacion->getTesfacturasadelantos()->getTessalidas()->numero?> </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><?php echo $simbolo?><?php 
	/*echo (float)$total;
	echo '/**';
	echo (float)$aplicacion->montototal;
	echo '<br />';*/
	$total=number_format((float)$total,2,'.','')-number_format($aplicacion->montototal,2,'.','');
	echo number_format($aplicacion->montototal,2,'.','')?></td>
  </tr>
  <?php }
   }?>
   
   <?php //if(Session::get('DOC_ID')==7){?>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><strong>Sub Total</strong></td>
    <td><?php echo $simbolo?><?php echo $total;//echo number_format($total,2,'.','');?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><strong>IGV</strong></td>
    <td><?php echo $simbolo?><?php $igv=$total*(Session::get('IGV'));echo number_format($igv,2,'.','')?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><strong>Total</strong></td>
    <td><?php echo $simbolo?><?php $TOTAL=$total+$igv;echo number_format($TOTAL,2,'.','');?></td>
  </tr>
  <tr>
  <td colspan="7">
<?php echo $texto=NumerosLetras::NL($total+$igv,$moneda_letras);?></td>
  </tr>
  <?php //}?>
</table>
<?php if(Session::get('DOC_ID')==7){?>
<script type="text/javascript">
function cargar()
	{
		$("#pago_con_letras").load('/<?php echo $module_name?>/cancelacionfacturas/unafactura/<?php echo $salida->id?>/'+<?php echo $letras?>);
	}
$(document).ready(function()
{

	$("#editar_letras").click(function(){
		alert('hola');
		cargar();
	});
});
	</script>
    <?php 
if($salida->tescondicionespagos_id==2){
	if($letras>0){?>
	<script type="text/javascript">
	$(document).ready(cargar);
	</script>
	<div id="pago_con_letras">
    </div>
	<?php }elseif($l_f==0){?>
    <strong><em>Nro. de Letras a Ingresar !<br /></em></strong><?php echo Form::text('letras');?> <a href="javascript:;" class="btn btn-xs btn-primary" id="enviar_numero_de_letras">Enviar</a>
    <script type="text/javascript">
$(document).ready(function()
{
	//alert('1');
	$("#enviar_numero_de_letras").click(function(){
		var numero_letras= $("#letras").val();
		$("#pago_con_letras").html('');
		alert('Ud. Esta generando '+numero_letras+' Letras');
		$("#pago_con_letras").load('/<?php echo $module_name?>/cancelacionfacturas/unafactura/<?php echo $salida->id?>/'+numero_letras);
		$("#n_let").hide();
		});
});
</script>
<?php echo Form::open(NULL,'POST','class="form-inline"')?>
<?php echo Form::hidden('salida.id')?>
<?php echo Form::hidden('salida.aclusuarios_id')?>
<?php echo Form::hidden('salida.tesmonedas_id')?>
<?php echo Form::hidden('salida.tesdatos_id')?>
<?php echo Form::hidden('salida.tesdocumentos_id')?>
<?php echo Form::hidden('salida.testipocambios_id')?>
<?php echo Form::hidden('salida.estadosalida','','Pendiente')?>
<?php echo Form::hidden('salida.totalconigv');?>
<?php echo Form::hidden('salida.igv');?>
<?php echo Form::hidden('salida.totalenletras');?>

<?php if($salida->estadosalida=='Editable'){?><button type="submit" class="btn btn-xs btn-primary">Finalizar Sin crear Letras</button> 
<?php echo Html::linkAction('agregardetalles','Editar','class="btn btn-xs"')?><?Php }else{?><?php echo Html::linkAction('guias/'.Session::get('DOC_ID'),'Listado','class="btn btn-xs"')?> <?php //echo Html::link('imprimir/facturas','Imprimir','class="btn btn-xs-info"')?> <?php //echo Html::linkAction('versalida_i','Imprimir','class="btn btn-xs"')?><?php }?>
<?php echo Form::close();?>
	<div id="pago_con_letras">
    </div>
<?php }else{?>
<div id="pago_con_letras">
<table width="50%" border="0" cellspacing="1" cellpadding="0">
  <tr>
    <th width="13%" align="left">Nro. Letra</th>
    <th width="29%" align="left">F. Emision</th>
    <th width="35%" align="left">F. Vencimiento</th>
    <th width="7%" align="left">Monto</th>
    <th width="7%" align="left">Accion</th>
    </tr>
   <?php
foreach($lets as $let){
$q=$let->id;
$factura_id=$let->factura_id;
	?>
  <tr>
    <td>
      <?php echo $let->getTessalidas()->numero?> </td>
    <td><?php echo Sp::formatFecha('%d/%m/%Y',$let->getTessalidas()->femision);?></td>
    <td><?php echo Sp::formatFecha('%d/%m/%Y',$let->getTessalidas()->fvencimiento);?></td>
    <td> 
     <?php echo number_format($let->getTessalidas()->totalconigv,2,'.','')?>
    </td>
    <td>
    <button onclick="myFunction_<?php echo $let->id?>()" class="btn btn-xs btn-info" id="<?php echo $let->id?>"><i class="icon-print"></i></button>
    <?php 
$factura_id;
$hrf_l='letra';?>
<script type="text/javascript">

function myFunction_<?Php echo $let->id?>() {
   window.open("http://"+document.domain+"/imprimir/<?php echo $hrf_l?>/<?php echo $factura_id?>/<?php echo $salida->tesdatos_id?>/<?php echo $let->id?>", "_blank", "toolbar=NO, scrollbars=yes, resizable=yes, top=100, left=250, width=600, height=400");
}
</script>
    </td>
    </tr>
	<?php }?>
</table>
 </div>
 
<?php 
echo $salida->estadosalida;
if($salida->estadosalida=="Editable"){?><a href="javascript:;" id="editar_letras" class="btn btn-xs btn-primary">Editar la Informacion de las letras</a><?php }?>
<?php }
	}?>
<?php 
//echo $salida->tescondicionespagos_id;
if($l_f>0 || $salida->tescondicionespagos_id!=2){?>
<?php echo Form::open(NULL,'POST','class="form-inline"')?>
<?php echo Form::hidden('salida.id')?>
<?php echo Form::hidden('salida.aclusuarios_id')?>
<?php echo Form::hidden('salida.tesmonedas_id')?>
<?php echo Form::hidden('salida.tesdatos_id')?>
<?php echo Form::hidden('salida.tesdocumentos_id')?>
<?php echo Form::hidden('salida.testipocambios_id')?>
<?php echo Form::hidden('salida.totalconigv');?>
<?php echo Form::hidden('salida.igv');?>
<?php echo Form::hidden('salida.totalenletras');?>
<?php if(Auth::get('aclroles_id')==4 || Auth::get('aclroles_id')==8 || Auth::get('aclroles_id')==2){
	?>* Si desea Cancelar la factura sin generar ningun abono seleccione "Cancelar" <?php echo Form::select('salida.estadosalida',array('PAGADO'=>'Cancelar','Pendiente'=>'Pendiente'),'','Pendiente');}?><br />
<?php if($salida->estadosalida=='Editable'){?><button type="submit" class="btn btn-xs btn-primary">Finalizar</button> 
<?php echo Html::linkAction('agregardetalles','Editar','class="btn btn-xs"')?><?Php }else{?><?php echo Html::linkAction('guias/'.Session::get('DOC_ID'),'Listado','class="btn btn-xs"')?> <?php //echo Html::link('imprimir/facturas','Imprimir','class="btn btn-xs-info"')?> <?php //echo Html::linkAction('versalida_i','Imprimir','class="btn btn-xs"')?><?php }?>
<?php echo Form::close();
}
}else{
?>
<?php echo Form::open(NULL,'POST','class="form-inline"')?>
<?php echo Form::hidden('salida.id')?>
<?php echo Form::hidden('salida.aclusuarios_id')?>
<?php echo Form::hidden('salida.tesmonedas_id')?>
<?php echo Form::hidden('salida.tesdatos_id')?>
<?php echo Form::hidden('salida.tesdocumentos_id')?>
<?php echo Form::hidden('salida.testipocambios_id')?>
<?php echo Form::hidden('salida.estadosalida','','Pendiente')?>
<?php echo Form::hidden('salida.totalconigv');?>
<?php echo Form::hidden('salida.igv');?>
<?php echo Form::hidden('salida.totalenletras');?>
<?php if(Auth::get('aclroles_id')==4 || Auth::get('aclroles_id')==8){/*echo Form::text('salida.estadosalida');*/}?>
<?php if($salida->estadosalida=='Editable'){?><button type="submit" class="btn btn-xs btn-primary">Finalizar</button> 
<?php echo Html::linkAction('agregardetalles','Editar','class="btn btn-xs"')?><?Php }else{?><?php echo Html::linkAction('guias/'.Session::get('DOC_ID'),'Listado','class="btn btn-xs"')?> <?php //echo Html::link('imprimir/facturas','Imprimir','class="btn btn-xs-info"')?> <?php //echo Html::linkAction('versalida_i','Imprimir','class="btn btn-xs"')?> <?php }?>
<?php echo Form::close();?>
  	<?php }?>
<button onclick="myFunction()" class="btn btn-xs btn-info"> IMPRIMIR </button> <?php echo Html::linkAction('venta',' Editar Aplicaciones','class="btn btn-xs"')?>
<?php 
$hrf='facturas';
if(Session::get('DOC_ID')==15)$hrf='guias';
?>
<script>
function myFunction() {
    window.open("http://"+document.domain+"/imprimir/<?php echo $hrf?>", "_blank", "toolbar=NO, scrollbars=yes, resizable=yes, top=100, left=250, width=600, height=400");
}
</script>
</div>
</div>
