<?php 
//echo $salida_id;
switch ($vc->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}
switch ($vc->voucherformadepagos_id)
{
	case 1: $url='efectivo/1'; break;
	case 2: $url='cheques/2/'.$salida_id; break;
	case 3: $url='letras/3/0'; break;
	case 4: $url=''; break;
	case 5: $url='bancos/6'; break;
	case 6: $url='bancos/5'; break;
	case 7: $url=''; break;
	case 8: $url='bancos/8'; break;
	case 9: $url=''; break;
	case 11: $url='aplicacion/11/0'; break;
	case 12: $url='cuotas/12/0'; break;
}
?>
<div class="card">
<h2><strong><em>Generacion de Vaucher!</em></strong></h2>
</div>

<div class="card-body">
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <caption>
  <pre><strong>Aún, no ha grabado este Baucher!</strong></pre></caption>
  <tr>
    <td colspan="2"><?php echo $empresa->razonsocial?></td>
    <td colspan="2"><strong>Vaucher General #</strong></td>
    <td width="7%"><?php echo $numero?></td>
    <td width="12%"><strong>Operacion:</strong></td>
    <td width="8%"><?php echo $vc->getVoucherformadepagos()->operacion?></td>
    <td width="9%"><strong>Asiento:<?Php echo $asiento?></strong></td>
    <td width="9%">&nbsp;</td>
    <td width="8%"><strong>Mes:</strong><?php echo date('m');?></td>
    <td width="8%">&nbsp;</td>
    <td></td>
  </tr>
  <tr>
    <td width="9%"><strong>Fecha:</strong></td>
    <td width="13%"><?php echo date('Y-m-d');?></td>
    <td width="10%"><strong>Importe:</strong></td>
    <td colspan="2"><?php echo $simbolo?> <?php if(!empty($vc->importe))echo number_format($vc->importe,2,'.',' ')?></td>
    <td><strong>T/C:<?php echo $vc->getTestipocambios()->compra;?></strong></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td></td>
  </tr>
  <tr>
  	<td colspan="11"><hr /></td>
  	<td></td>
  	</tr>
  <tr class="card">
    <th align="left">Cuenta General</th>
    <th align="left">Nº Documento</th>
    <th align="left">F. Vto.</th>
    <th colspan="2" align="left">Cod Auxiliar</th>
    <th colspan="4" align="left">Descripcion</th>
    <th align="left">Cargos</th>
    <th align="left">Abonos</th>
    <th width="4%">Acc</th>
    <td width="0%"></td>
  </tr>
  <?Php 
  $doc='';
  $i=0;
  foreach($detalles as $item):
  $i++;
	$cuenta=$item->plancontable;
	$fechavcto=NULL;
	$descripcion=$vc->getVoucherformadepagos()->nombre;
  if($item->tesingresos_id!=0)
  {
	  $cuenta=$item->getTesingresos()->cuentaporpagar;
	  $num_doc=$item->getTesingresos()->serie.'-'.$item->getTesingresos()->numero;
	  $fechavcto=$item->getTesingresos()->fvencimiento;
	  $codauxiliar=$item->getTesingresos()->getTesdatos()->ruc;
	  $descripcion=$item->getTesingresos()->getTesdatos()->razonsocial;
  }
  if($item->tessalidas_id!=0)
  {
	 $cuenta=$item->getTessalidas()->cuentaporpagar;
	 $num_doc=$item->getTessalidas()->serie.'-'.$item->getTessalidas()->numero;
	 $fechavcto=$item->getTessalidas()->fvencimiento;
	 $codauxiliar=$item->getTessalidas()->getTesdatos()->ruc;
	 $descripcion=$item->getTessalidas()->getTesdatos()->razonsocial;
  }
  ?>
  <tr>
    <td><?php echo $cuenta?></td>
    <td><?php echo $num_doc?></td>
    <td><?php if(!empty($fechavcto))echo $fechavcto;else echo '-';?></td>
    <td colspan="2"><?php echo $codauxiliar?></td>
    <td colspan="4"><?php echo $descripcion?></td>
    <td><?php if($item->cargos==1)echo $item->monto; else echo '';?></td>
    <td><?php if($item->abono==1)echo $item->monto; else echo '';?></td>
    <td><?php echo Html::linkAction('eliminardetalle/'.$item->id,Html::img("figuras/eliminar.png",'Eliminar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'onclick="return confirm(\'¿Está seguro?\')"');?></td>
  </tr>
  <?php 
  if($i==1)$doc.=$num_doc;else $doc.='-'.$num_doc;
  endforeach;?>
  <tr>
    <th colspan="3">&nbsp;</th>
    <th colspan="4"></th>
    <th colspan="3"></th>
    <th></th>
    <td></td>
  </tr>
  <tr>
    <td colspan="3">Aprobador por:</td>
    <td colspan="4">Contador</td>
    <td colspan="3">Recibido por:</td>
    <td>&nbsp;</td>
    <td></td>
  </tr>
  </table>
  
  
<script type="text/javascript">
$(document).ready(function()
{
$("#pago").load('/<?php echo $module_name?>/letras/<?php echo $url?><?php if($vc->voucherformadepagos_id==3)echo '/'.$doc?>');
});
</script>
<hr />
<div id="pago"></div>
<div class="form-actions">
    <?php echo Html::linkAction("creardetalle/", 'Agregar detalles','class="btn btn-secondary"') ?>
    <?php //echo Html::linkAction("terminer/100", 'Terminar','class="btn btn-primary"') ?>
</div>
<?php echo Form::close()?>
</div>