<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}.rojo{
	color:#FF0000;}
	.verde{
	color:#090;}
</style>
<div class="card">
    <h1>Obligaciones por Pagar<span><?php echo $empresa->razonsocial?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="form-actions">
<?Php echo Html::linkAction('obligacionespendientes','Imprimir pendientes','class="btn btn-xs btn-info"');?> 
<?Php echo Html::linkAction('obligacionesporfecha/'.$todo,'Imprimir Todos los pendientes','class="btn btn-xs btn-info"');?></div>
<?php echo Sp::imprimir('Letras pendientes por semana  - ','P');?>
<div class="card-body">
<div id="ver_resultado"></div>
<table width="99%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">

<caption> <?php echo Session::get('EMPRESAS_NOMBRE')?> <?php echo date("d-m-Y")?></caption>
  <thead>
  <tr>
  	<th width="24" align="left">Nº</th>
    <th width="324" align="left">Proveedor</th>
    <th width="148" align="left">Nro Doc.</th>
    <th width="108" align="left">Nro unico</th>
    <th width="85" align="left">Banco</th>
    <th width="86" align="left">F.de Vto</th>
    <th width="138" align="right">Total</th>
  </tr>
  </thead>
<?php $number=0;
$semana=0;
$a=0;
$T_soles=0;
$T_dolares=0;
foreach($obligaciones as $item){ 
$class='';
if($item->fvencimiento<date("Y-m-d"))$class=' class="rojo" ';
if($item->fvencimiento==date("Y-m-d"))$class=' class="verde" ';
$simbolo="S/. ";
$T_letras=$item->Totalporsemana($item->semana,$item->fvencimiento);
$number++;?>
<?php 
$b=$item->semana;
if($a!=$b){

$number=1;
$T_soles=0;
$T_dolares=0;
?>
<thead>
<tr id="<?php echo $item->id?>">
  	<td colspan="7"><b>Semana Nº <?php echo $item->semana?></b></td>
</tr>
</thead>
<?php 
}
$a=$item->semana;
switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. ';$T_soles=$T_soles+$item->totalconigv; break;
	case 2: $simbolo='$. ';$T_dolares=$T_dolares+$item->totalconigv;break;
	case 4: $simbolo='S/. ';$T_soles=$T_soles+$item->totalconigv; break;
	case 5: $simbolo='$. ';$T_dolares=$T_dolares+$item->totalconigv;break;
	case 0: $simbolo='S/. ';$T_soles=$T_soles+$item->totalconigv; break;
}
?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $number?> <?php //if(Auth::get('id')==3){echo $item->semana; echo $number."==".$T_letras;}?></td>
  	<td height="20"><?php echo $item->getTesdatos()->razonsocial?></td>
    <td><?php echo $item->getTesdocumentos()->abr;?> <?php if(!empty($item->serie))echo $item->serie.'-';?><?php echo $item->numero?></td>
    <td><?php 
	
	if($item->tesdocumentos_id==34)
	{
		echo $item->getTesletrasingresos()->numerounico;
	}
	if($item->tesdocumentos_id==37)
	{
		//echo $item->numero;
	}
	if($item->tesdocumentos_id==38)
	{
		//echo $item->numero;
	}/*pagare*/;
	if($item->tesdocumentos_id==39)
	{
		//echo $item->numero;
	}/*leasing*/;?></td>
    <td><?php if($item->tesdocumentos_id==34)
	{
		echo $item->getTesletrasingresos()->bancos;
	}
	if($item->tesdocumentos_id==37)
	{
		//echo $item->getTesdatos()->razonsocial;
	}
	if($item->tesdocumentos_id==38)
	{
		//echo $item->getTesdatos()->razonsocial;
	}/*pagare*/;
	if($item->tesdocumentos_id==39)
	{
		//echo $item->getTesdatos()->razonsocial;
	}/*leasing*/;?></td>
    
    <td<?php echo $class?>><?php echo Sp::formatFecha('%d/%m/%Y',$item->fvencimiento)?></td>
    <td align="right"><?php if($item->totalconigv!='NaN.00' && !empty($item->totalconigv))echo $simbolo.number_format($item->totalconigv,2,'.','');else echo('S/ 00.00')?>
	<?Php echo $item->getValidar($item->id)?>
	<?php //echo $number."==".$T_letras ?></td>
  </tr>
  <?Php if($number==$T_letras){?>
  <tr >
  <td style="border-bottom:#999 double 1px;" colspan="2">Total de la semana <?php echo $item->semana?></td>
  <td style="border-bottom:#999 double 1px;" colspan="3">Total en S/.<?php echo number_format($T_soles,2,'.',' ')?></td>
  <td style="border-bottom:#999 double 1px;" colspan="2">Total en $/.<?php echo number_format($T_dolares,2,'.',' ')?></td>
  </tr>
  <tr>
  <td colspan="7">&nbsp;</td>
  </tr>
  <?php }?>
<?php 
	}?>
</table>
<div class="form-actions">
<?php //echo Html::linkAction("cargaringreso/0", 'Nueva '.Session::get('DOC_NOMBRE'),'class="btn btn-xs btn-primary"') ?>&nbsp;<?php echo Html::linkAction("", 'Volver ','class="btn btn-xs"') ?>
</div>
</div>