
  <div id="mensajes_flash">
    <?php View::content() ?>
  </div>
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Cheques Pendientes de Cobro!</h3>

    <div class="card-tools">
      <?php echo Menu::menuCheques_emitidos(); ?>
    </div>
  </div>
  <div class="card-body">
    <div id="ver_resultado"></div>
    <table id="exportar_excel" class="table table-bordered table-striped">
      <caption>Cheques del Mes!</caption>
      <tr>
        <th width="17" align="left">Nº</th>
        <th width="58" align="center">F. Emision.</th>
        <th width="180" align="left">Cliente</th>
        <th width="58" align="left">Banco</th>
        <th width="77">Cobrar. Desde!</th>
        <th width="67">Nro. Doc.</th>
        <th width="57">Total</th>
        <th width="64">Accion</th>
      </tr>
      <?php $number = 0;
      foreach ($cheques as $item) {
        $simbolo = "S/. ";

        switch ($item->getTessalidas()->tesmonedas_id) {
          case 1:
            $simbolo = 'S/. ';
            break;
          case 2:
            $simbolo = '$. ';
            break;
          case 4:
            $simbolo = 'S/. ';
            break;
          case 5:
            $simbolo = '$. ';
            break;
          case 0:
            $simbolo = 'S/. ';
            break;
        }

        $number++; ?>
        <tr id="<?php echo $item->id ?>">
          <td height="20"><?php echo $number ?></td>
          <td height="20" align="center"><?php echo Sp::formatFecha('%d / %m / %Y', $item->getTessalidas()->femision) ?></td>
          <td height="20"><?php if ($item->getTessalidas()->tesdatos_id != 0) {
                            echo $item->getTessalidas()->getTesdatos()->razonsocial;
                          } else {
                            echo "Interno"; /*$item->tesdatos_id;*/
                          } ?></td>
          <td><?php echo $item->getTesbancos()->nombre ?></td>
          <td><?php echo Sp::formatFecha('%d/%m/%Y', $item->fecha_cobro) ?></td>
          <td><?php echo $item->numerodecheque ?> (<?php if (!empty($item->estadocheque)) echo $item->estadocheque;
                                                  else echo "Sin registrar"; ?>)</td>
          <td align="right" valign="top"><?php if ($item->monto != 'NaN.00' && !empty($item->monto)) echo $simbolo . number_format($item->monto, 2, '.', '');
                                          else echo ('S/ 00.00') ?></td>
          <td title="Clic! Si fue cobrado por el Interezado!" align="center"><?php echo Html::linkAction('cobrar/' . $item->id, Html::img("figuras/pagar.png", 'Pagar', 'style="width: 30px;margin-left:1px;margin-right:1px;"'), 'class="btn btn-xs"'); ?>
            <?php //echo Html::linkAction('stornar/'.$item->id,Html::img("figuras/protestar.png",'Stornar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'class="btn btn-xs" title="Stornar cheque !!!!" onclick="return confirm(\'¿Está seguro de estornar el cheque?\')"');
            ?>
          </td>
        </tr>
      <?php } ?>
    </table>

  </div>

</div>