<div class="page-header">
    <h1>
        Edición del Empresa
        <small><?php eh(strtoupper($aclempresas->login)) ?></small>
    </h1>
</div>      
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('aclempresas.id') ?>
<div class="control-group">
    <label for="usuario_login">Nombre de la Empresa* : </label>
    <div class="controls">
        <?php echo Form::text('aclempresas.nombre') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_clave">Razon Social* : </label>
    <div class="controls">
        <?php echo Form::text('aclempresas.razonsocial') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_clave2">Ruc* : </label>
    <div class="controls">
        <?php echo Form::text('aclempresas.ruc') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_nombres">Direccion* : </label>
    <div class="controls">
        <?php echo Form::text('aclempresas.direccion') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_email">Movimiento de la Empresa* : </label>
    <div class="controls">
        <?php echo Form::textarea('aclempresas.detalle') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_roles_id">Telefono Fijo* : </label>
    <div class="controls">
        <?php echo Form::text('aclempresas.telefonos') ?>
    </div>
</div><div class="control-group">
    <label for="usuario_roles_id">Celular/Movil* : </label>
    <div class="controls">
        <?php echo Form::text('aclempresas.telefonos1') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_roles_id">Fax* : </label>
    <div class="controls">
        <?php echo Form::text('aclempresas.telefonos2') ?>
    </div>
</div>
<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
