
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="1" class="table table-hover">
<caption> Lista de Cajas en Guia </caption>
  <tr>
    <th width="9%">Codigo</th>
    <th width="17%">Cantidad</th>
    <th width="11%">Unidad</th>
    <th width="53%">Descripcion</th>
    <th width="10%">Accion</th>
  </tr>
  <?php 
  $n=0;
  foreach($detalles as $item){
	  $n++;
	  ?> 
  <tr id="d-<?php echo $item->id?>">
    <td><?php echo $n?>. <?php echo $item->getTescajas()->numerodecaja?></td>
    <td><?php echo $item->pesoneto?></td>
    <td><?Php echo $item->getTesunidadesmedidas()->simbolo?></td>
    <td><?php echo $item->getTesproductos()->detalle?> <?Php //echo $item->getTescolores()->nombre?></td>
    <td><?php echo Html::link($module_name.'/cajas/borrarsalidacajas_i/'.$item->id.'/'.$item->tescajas_id.'/','Elminar','class="mostrar" id="'.$item->tescajas_id.'"')?></td>
  </tr>
  <?php }?>
</table>