<?php
$simbolo="S/. ";

switch ($monedas)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}


View::content();
//echo Tag::js('jquery/jquery.tokeninput');
//Tag::css('token-input');?>
<script type="text/javascript">
// from http://www.mediacollege.com/internet/javascript/number/round.html
function roundNumber(number,decimals)
{
  var newString;// The new rounded number
  decimals = Number(decimals);
  if (decimals < 1) {
    newString = (Math.round(number)).toString();
  } else {
    var numString = number.toString();
    if (numString.lastIndexOf(".") == -1) {// If there is no decimal point
      numString += ".";// give it one at the end
    }
    var cutoff = numString.lastIndexOf(".") + decimals;// The point at which to truncate the number
    var d1 = Number(numString.substring(cutoff,cutoff+1));// The value of the last decimal place that we'll end up with
    var d2 = Number(numString.substring(cutoff+1,cutoff+2));// The next decimal, after the last one we want
    if (d2 >= 5) {// Do we need to round up at all? If not, the string will just be truncated
      if (d1 == 9 && cutoff > 0) {// If the last digit is 9, find a new cutoff point
        while (cutoff > 0 && (d1 == 9 || isNaN(d1))) {
          if (d1 != ".") {
            cutoff -= 1;
            d1 = Number(numString.substring(cutoff,cutoff+1));
          } else {
            cutoff -= 1;
          }
        }
      }
      d1 += 1;
    } 
    if (d1 == 10) {
      numString = numString.substring(0, numString.lastIndexOf("."));
      var roundedNum = Number(numString) + 1;
      newString = roundedNum.toString() + '.';
    } else {
      newString = numString.substring(0,cutoff) + d1.toString();
    }
  }
  if (newString.lastIndexOf(".") == -1) {// Do this again, to the new string
    newString += ".";
  }
  var decs = (newString.substring(newString.lastIndexOf(".")+1)).length;
  for(var i=0;i<decimals-decs;i++) newString += "0";
  //var newNumber = Number(newString);// make it a number if you like

  return newString; // Output the result to the form field (change for your purposes)
}
/*FIN DE REDONDEO*/
function addCommas(nStr)
{
    nStr += '';
    x = nStr.split('.');
    x1 = x[0];
    x2 = x.length > 1 ? '.' + x[1] : '';
    var rgx = /(\d+)(\d{3})/;
    while (rgx.test(x1)) {
        x1 = x1.replace(rgx, '$1' + ',' + '$2');
    }
    return x1 + x2;
}
function update_total()
{
  var total = 0.00;
  $('.price').each(function(i)
  {
    price = $(this).html();
    //alert ('precio: '+price+' ->>>>'+i);
	if (!isNaN(price)) total =parseFloat(total)+parseFloat(price);
   //alert ('el total es : '+total+' ->>>>');
   
   });
   

	total = roundNumber(total,2);
	//alert ('el total es : '+total+' ->>>>');
	var igv= total*0.18;
	var totalconigv=(parseFloat(total)+parseFloat(igv));
	//alert('el igv es: '+igv);
	$("#paid").val(igv);
	$("#igv").val(igv);
	$("#totalconigv").val(totalconigv);
	$('#subtotal').html(total);
	$('#paid_total').html(total);
	//update_balance();
}

function update_balance()
{
  //alert ($("#paid").val());
  var due =parseFloat( $("#paid_total").html())+ parseFloat($("#paid").val());
  due = roundNumber(due,2);
 // alert ('===: '+due);
	$('.due').html(due);
	//GRABAR();
}

function update_price()
{
  var ID = $(this).attr('id');
  var I=ID.split('-');
  //alert ('id del tr que se manda a grabar->>>'+ID);
  var row = $(this).parents('.item-row');
  var price = row.find('.cost').val() * row.find('.qty').val();
  price = roundNumber(price,2);
  isNaN(price) ? row.find('.price').html("N/A") : row.find('.price').html(price);
  //update_total();
  grabarDetalle(I[1]);
}


/*envio dew Formulario PROFORMAS*/
function GRABAR(){
     
	 
          $.ajax({
            type:"POST",
            url:"/santapatricia/inventarios/grabar/1",
            data:$("#inventarios").serialize(),
            beforeSend:function(){
              $("#loading").show();
            },
            success:function(response){
                $("#loading").hide();
				$("#id").val(response);
            }
 
          	});
 
      };

/*GRABAR DETALLE DE PROFORMAS*/

function grabarDetalle(tr_id) {

 // alert(tr_id);
  var producto_id=$('#productos_id-'+tr_id).val();
  var pro_descripcion=$('#pro_descripcion-'+tr_id).val();
  var costo=$('#precio-'+tr_id).val();
  var cantidad=$('#cantidad-'+tr_id).val();
  var lote=$('#lote'+tr_id).val();
  var empaque=$('#empaque'+tr_id).val();
  var bobinas=$('#bobinas'+tr_id).val();
  var pesoneto=$('#pesoneto'+tr_id).val();
  var pesobruto=$('#pesobruto'+tr_id).val();
  var price = $('#total-'+tr_id).html();
  var id_detalle=$('#del-'+tr_id).attr("data-id");
  var unidadmedida_id=$('#tesunidadesmedidas_id-'+tr_id).val();
  var total=price;
 //alert('ID del PRODUCTO'+producto_id);
 //alert('id del detalle es 0 cuando es nuevo--->'+id_detalle);
 //alert('id del tr que se graba-->'+tr_id);
  
  if(producto_id!='' && unidadmedida_id!='')
  {
	  var dataString ='id_detalle='+id_detalle+'&tesunidadesmedidas_id='+ unidadmedida_id+'&productos_id='+ producto_id+'&pro_descripcion='+pro_descripcion+'&cantidad='+cantidad+'&precio='+costo+'&total='+total+'&lote='+lote+'&empaque='+empaque+'&bobinas='+bobinas+'&pesoneto='+pesoneto+'&pesobruto='+pesobruto;
	// alert(dataString);
	  $.ajax({
            type:"POST",
            url:"/santapatricia/inventarios/grabarDetalle/1",
            data:dataString,
            beforeSend:function(){
              $("#loading").show();
            },
            success:function(response){
                $("#loading").hide();
				//alert('id del detalle grabado'+response);
				$('#del-'+tr_id).attr("data-id", response);
            }
 
         });
  }
  
}
function bind() {
	$(".delete").hide()
  $(".cost").blur(update_price);
  $(".qty").blur(update_price);
}

$(document).ready(function()
{	  
	
  $('input').click(function(){
    $(this).select();
  });
  $("#paid").blur(update_balance);

  
	 bind();
  	 $(".delete").hide()

	$("#glosa").change(function(){GRABAR();});
  	$("#femision").change(function(){GRABAR();});
	$("#monedas").change(function()
	{
		GRABAR();
		var op = $("#monedas option:selected").val();
		if(op==1)
		{
			$(".simbolo").html("S/. ");
		}
		if(op==2)
		{
			$(".simbolo").html("$. ");
		}
	});
	 
});
</script>
<script type="text/javascript">
$(document).ready(function(){
		$("#tipoproducto").change(function(){
                var op = $("#tipoproducto option:selected").val();
                document.location = "/santapatricia/inventarios/crear/"+op;
        });
		$("#mas").click(function(){
			var op = $(this).attr("data-id");
			//alert(op);
			document.location = "/santapatricia/inventarios/crear/<?php echo $tipos_id?>/"+op;
			});
});
</script>
<style type="text/css">
.simbolo
{
	position:absolute;
	float:left;
	margin-left:-15px !important;
}
.item-row td{
	padding-left:15px !important;
	font-size:10px !important;
	}
#paid
{
	width:80% !important;
}
</style>

<div id="page-wrap">
	<div id="header">INVENTARIO <?php echo "id--->".Session::get('INVENTARIO_ID')?></div>
	<div id="identity">
        <div id="address">
            <?php echo $empresa->razonsocial?><br />
            <?php echo $empresa->direccion?>
        </div>
        <div id="logo">
            <img id="image" src="/img/<?php echo $empresa->logo?>" alt="logo" />
        </div>
	</div>
	<div style="clear:both"></div>
	<div id="customer">
    <?php echo Form::open('','post','id="inventarios"');?>
    <?php echo Form::hidden('id')?>
    <div id="descripcion">
		  <label>Descripcion: </label>
		  <?php echo Form::textArea('glosa');?>
	</div>
    <?php echo Form::hidden('cliente_id')?>
	 <table width="75%" align="center">
                <tr>
                    <th width="129" class="meta-head">Moneda</th>
                    <th width="81"><?php echo Form::dbSelect('monedas','nombre',array('tesmonedas','find','aclempresas_id='.Session::get("EMPRESAS_ID")))?></th>
                    <th width="113" class="meta-head">Número #</th>
                    <th width="78"><?php echo Form::text('numero',' readonly="readonly"',$numero)?></th>
                </tr>
                <tr>
					<th>Fecha de Emision</th>
                    <th><?php echo Calendar::selector('femision');?></th>
                    <th class="meta-head">Monto Total</th>
                    <th><span class="simbolo"><?php echo $simbolo?></span></span><span class="due"><?php echo number_format($totalconigv+$igv,2,'.','')?></span></th>
       </tr>

            </table>
	 <?php echo Form::hidden('totalconigv');?>
            <?php echo Form::hidden('igv');?>
        <?php echo Form::close();?>
	</div>
    <p>
	Seleccione el Tipo de Producto a ver!
	  <?php echo Form::dbSelect('tipoproducto','nombre',array("testipoproductos",'find','conditions: activo=1'),'Cambiar de linea de producto','',$tipos_id);?>
    </p>
    <?php View::partial('paginators/classic', false, array('page' => $productos ,'url' => Router::get('controller_path').'/crear/'.$id)); ?>

	<table width="100%" id="items" class="table table-bordered table-striped">
		  <tr>
		      <th width="7%" align="left">Codigo</th>
		      <th width="9%" align="left">Producto</th>
		      <th width="8%" align="left">Medida</th>
              <th width="7%" align="left">Lote</th>
		      <th width="9%" align="left">Empaque</th>
		      <th width="10%" align="left">Bobinas</th>
              <th width="8%">P/N</th>
		      <th width="11%">P/B</th>
		      <th width="7%">Costo Unit</th>
		      <th width="9%">Cantidad</th>
		      <th width="15%">Precio</th>
		  </tr>
		  <?php 
			  $n=0;
			  $subtotal=0;
			foreach($productos->items as $item):
			     $n++;
				 $detalle_id=0;
				  $medida=0;
				  $importe=0;
				  $lote='';
				  $empaque='';
				  $bobinas='';
				  $pesoneto='';
				  $pesobruto='';
				  $cantidad='';
				  $preciounitario=$item->precio;
				  if($detalles->exists('tesingresos_id='.$id.' AND tesproductos_id='.$item->id))
				  {
				  $det=$detalles->find_first('conditions: tesingresos_id='.$id.' AND tesproductos_id='.$item->id);
				  $medida=$det->tesunidadesmedidas_id;
				  $detalle_id=$det->id;
				  $importe=$det->importe;
				  $lote=$det->lote;
				  $empaque=$det->empaque;
				  $bobinas=$det->bobinas;
				  $pesoneto=$det->pesoneto;
				  $pesobruto=$det->pesobruto;
				  $cantidad=$det->cantidad;
				  }
			  ?>
		  <tr id="<?php echo $n?>" class="item-row">
           <td>
                  <div class="delete-wpr">
                  <?php echo Form::text('codigo-'.$n,'size="10" readonly="readonly"',$item->codigo)?>
                  <a id="del-<?php echo $n?>" class="delete" href="javascript:;" title="Elimar registro" data-id="<?php echo $detalle_id?>">X</a>
                  </div>
              </td>
		      <td class="item-name">
                  <?php echo Form::hidden('productos_id-'.$n,'class="productos_id" readonly="readonly"',$item->id)?>
                  <span id="ver-name<?php echo $n?>" style="display:none;"><?php echo Form::text('productoname-'.$n,'readonly="readonly"')?></span>
                  <span id="ver<?php echo $n;?>" class="ver"><?php echo Form::text('producto'.$n,'class="producto" placeholder="Producto" size="30" readonly="readonly"',$item->nombre)?></span>
              </td>
		      <td><?php echo Form::dbSelect('tesunidadesmedidas_id-'.$n,'nombre',array('tesunidadesmedidas','find','aclempresas_id='.Session::get("EMPRESAS_ID")),'seleccione','',$medida)?> </td>
		      <td> <?php echo Form::text('lote'.$n,'size="12"',$lote)?></td>
              <td> <?php echo Form::text('empaque'.$n,'size="10"',$empaque)?></td>
              <td> <?php echo Form::text('bobinas'.$n,'size="10"',$bobinas)?></td>
              <td> <?php echo Form::text('pesoneto'.$n,'size="10"',$pesoneto)?></td>
              <td> <?php echo Form::text('pesobruto'.$n,'size="10"',$pesobruto)?></td>
              <td><span class="simbolo"><?php echo $simbolo?></span><?php echo Form::text('precio-'.$n,'size="10" class="cost" placeholder="0.0"',number_format($preciounitario,2,'.',''))?></td>
		      <td><?php echo Form::text('cantidad-'.$n,' class="qty" size="10" placeholder="0.0"',$cantidad);?></td>
		      <td><span class="simbolo"><?php echo $simbolo?></span><span id='total-<?php echo $n?>' class="price"><?php echo number_format($importe,2,'.','')?></span></td>
		  </tr>
		  
		  <?php
			endforeach;
		/*FIN FOREACH*/?>
          </table>

          <?php /*?><table class="meta" width="60%">
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line"><strong>Subtotal : </strong></td>
		      <td width="24%" class="total-value"><span class="simbolo"><?php echo $simbolo?></span><span id="subtotal"><?php echo number_format($subtotal,2,'.','')?></span></td>
		  </tr>
		  <tr>

		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line"><strong>Total : </strong></td>
		      <td class="total-value"><span class="simbolo"><?php echo $simbolo?></span><span id="paid_total"><?php echo number_format($subtotal,2,'.','')?></span></td>
		  </tr>
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line"><strong>IGV : </strong></td>

		      <td class="total-value"><span class="simbolo"><?php echo $simbolo?></span><?php echo Form::text('paid','placeholder="0.00" readonly="readonly"')?></td>
		  </tr>
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line balance"><strong>Total a Pagar : </strong> </td>
		      <td class="total-value balance"><span class="simbolo"><?php echo $simbolo?></span><span class="due"><?php echo number_format($subtotal+$igv,2,'.','')?></span></td>
		  </tr>
		</table><?php */?>
  <div id="loading" style="display:none;"><img src="/img/spin.gif" /></div>
     <div style="clear:both"></div>
	<div id="terms">
	  <h5>Terminos del Inventario <?php echo $n?></h5><?php echo Form::textArea('pre_descripcion');?>
		</div>
</div>