<?php
$simbolo="S/. ";

switch ($ingreso->tesmonedas_id)
{
	case 1: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES'; break;
	case 2: $simbolo='$. ';$moneda_letras='DOLARES AMERICANOS';  break;
	case 4: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES';  break;
	case 5: $simbolo='$. ';$moneda_letras='DOLARES AMERICANOS';  break;
	case 0: $simbolo='S/. ';$moneda_letras='NUEVOS SOLES';  break;
}

$id=$ingreso->id;
		$numero=$ingreso->numero;
		$glosa=$ingreso->glosa;
		$serie=$ingreso->serie;
		$numero=$ingreso->numero;
		$codigo=$ingreso->codigo;//fvencimiento
		$femision=$ingreso->femision;
		$fvencimiento=$ingreso->fvencimiento;
		$monedas=$ingreso->tesmonedas_id;
		$monedas_nombre=$ingreso->getTesmonedas()->nombre;
		$cliente_id=$ingreso->tesdatos_id;
		/*nombre del cliente*/
		$nombre=$ingreso->getTesdatos()->razonsocial." ruc: ".$ingreso->getTesdatos()->ruc." (".$ingreso->getTesdatos()->departamento.' - '.$ingreso->getTesdatos()->provincia.' - '.$ingreso->getTesdatos()->distrito.' - '.$ingreso->getTesdatos()->direccion.')';
		/**/
		$totalconigv=$ingreso->totalconigv;
		$igv=$ingreso->igv;
		$paid=$ingreso->igv;
		$fregistro=$ingreso->fregistro;
		$npedido=$ingreso->npedido;
		$numeroguia=$ingreso->numeroguia;
		$numerofactura=$ingreso->numerofactura;
		$ordendecompra=$ingreso->ordendecompra;
		$finiciotraslado=$ingreso->finiciotraslado;
		$movimiento=$ingreso->movimiento;
		$cuantagastos=$ingreso->cuantagastos;
		$cuentaporpagar=$ingreso->cuentaporpagar;
		$totalenletras=$ingreso->totalenletras;
		
		$subt=$totalconigv-$igv;
		$codigo=$ingreso->codigo;
		
View::content();
?>
<style type="text/css">
/*.container {
  width: 1124px;
}*/
/*.flotante{position:relative; width:350px; margin:0 auto; z-index:99999;} */
.simbolo
{
	position:absolute;
	float:left;
	margin-left:-15px !important;
}
.table th
{
	font-size:12px;
	text-align:center;
}
#items .item-row td{
	font-size:10px !important;
	padding-left:15px !important;
	}
#items .item-row input[type="text"]{
	font-size:10px !important;
	padding:0;
	}
#paid
{
	width:80% !important;
}
#glosa
{
	width:99% !important;
}
.page ul {
margin:0 !important;
}
</style>
<div class="card">
<h1><?php echo Session::get('DOC_NOMBRE')?> <?php //echo "id--->".Session::get('INVENTARIO_ID')?></h1>
</div>

<div class="card-body"> 
<table width="99%">
     <tr>
     	<th width="56" align="left" valign="top" class="meta-head">Moneda:</th>
        <td width="302" align="left" valign="top"><?php echo $moneda_letras?></td>
     	<th align="left" valign="top">Proveedor:</th>
        <td align="left" valign="top"> <?php echo $nombre?></td>
       </tr>
      <tr>
        <th align="left" valign="top">F. de Emision:</th>
        <td align="left" valign="top"><?php echo $femision?></td>
        <th width="69" align="left" valign="top" class="meta-head">Serie-Número:</th>
          <td width="255" align="left" valign="top"><?php echo $serie;?>-<?php echo $numero ?></td>
      </tr>
      	  <?php if(!empty($ingreso->cuentaporpagar)){?><tr>
        <th width="127" align="left" valign="top" class="meta-head">Cta. Gastos:</th>
        <td width="173" align="left" valign="top"><?php if(!empty($ingreso->cuantagastos)){
			$cg=$cc->find_first('codigo='.$ingreso->cuantagastos);
			echo $cuantagastos_name=$cg->codigo.'<span style=\"font-size:9px;\">('.$cg->descripcion.')</span>';
			}?>
         </td>
          
          <th width="114" align="left" valign="top" class="meta-head">Cta por Pagar:</th>
          <td width="180" align="left" valign="top"><?php if(!empty($ingreso->cuentaporpagar)){
			$cp=$cc->find_first('codigo='.$ingreso->cuentaporpagar);
			echo $cuentaporpagar_name=$cp->codigo.'<span style=\"font-size:9px;\">('.$cp->descripcion.')</span>';
			}?></td>
      </tr><?php }?>
      <tr>
     	<th align="left">Movimiento:</th>
        <td align="left"><?php //echo Form::text('movimiento','size="5"')?></td>
        <th align="left" class="meta-head">Monto Total:</th>
        <td align="left"><span class="simbolo"><?php echo $simbolo?></span></span><span class="due"><?php echo number_format($totalconigv+$igv,2,'.','')?></span></td>
       </tr>
    </table>
    <div><label>Glosa: </label>

<table id="items" class="table table-striped">
		  <tr>
		      
              <th width="42%">Concepto</th>
		      <th width="18%">Precio</th>
		  </tr>
          <?php
			if($DETALLE)
			{
				$n=0;
				$subtotal=0;
				foreach($detalles as $item){
						  $n++;
						  $subtotal=$subtotal+$item->importe;
					  ?>
				  <tr id="<?php echo $n?>" class="item-row">
				   <td>
						  <?php echo $item->concepto?>
					</td>
                    <td><span class="simbolo"><?php echo $simbolo?></span><?php echo number_format($item->preciounitario,2,'.','')?></td>
					  </tr>
				  
				  <?php
					  }/*FIN FOREACH*/
					}  
			?>
            <?php /*?><tr id="hiderow">
		    <td colspan="12"><a id="addrow" href="javascript:;" title="Agregar mas registros">Agragar Mas</a></td>
		  </tr><?php */?>
  </table>
          <table class="meta">
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line"><strong>Sub total: </strong></td>
		      <td width="10%" class="total-value"><span class="simbolo"><?php echo $simbolo?></span><span id="subtotal"><?php echo number_format($subtotal,2,'.','')?></span></td>
		  </tr>
		  <tr>

		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line"><strong>Total </strong></td>
		      <td class="total-value"><span class="simbolo"><?php echo $simbolo?></span><?php echo Form::text('paid_total','size="10"',number_format($subtotal,2,'.',''));?></td>
		  </tr>
		  <tr>
		      <td colspan="2" class="blank"> </td>
		      <td colspan="2" class="total-line balance"><strong>Total Neto: </strong> </td>
		      <td class="total-value balance"><span class="simbolo"><?php echo $simbolo?></span><span class="due"><?php echo number_format($subtotal-$igv,2,'.','')?></span></td>
		  </tr>
      <tr>
     	<td colspan="5"></td>
       </tr>
  </table>
    <div style="text-align:left; width: 68%; float: left;"id="moneda_en_letras"><?php echo $totalenletras?></div>

<div class="form-actions">

<?php if($ingreso->estadoingreso=='Editable'){?>
<?php echo Form::open()?>
<?php echo Form::hidden('ingreso.id')?>
<?php echo Form::hidden('ingreso.aclusuarios_id')?>
<?php echo Form::hidden('ingreso.tesmonedas_id')?>
<?php echo Form::hidden('ingreso.tesdatos_id')?>
<?php echo Form::hidden('ingreso.tesdocumentos_id')?>
<?php echo Form::hidden('ingreso.estadoingreso','','Pendiente')?>
<?php if(Session::get('DOC_CODIGO')=='09'){?>
<label>Auto Salida* <?php echo Form::select('ingreso.autosalida',array(""=>"No","1"=>"Si"))?><small style="font-style:italic;">La guia no llega a nuestra Empresa</small></label>
<?php }?>
<?php echo Html::linkAction("crear", 'Editar ','class="btn btn-xs btn-secondary"') ?>&nbsp;<?php echo Form::submit('Terminar ','class="btn btn-xs btn-primary"') ?>
<?php echo Form::close();?>

<?php }else{?><?php echo Html::linkAction("listado", 'Listado','class="btn btn-xs btn-secondary"') ?><?php }?>
</div>
        <div id="loading" style="display:none;"><img src="/img/spin.gif" /></div>
     <div style="clear:both"></div>
</div>
