<?php
$simbolo="S/. ";
$fechanew = new DateTime($fecha);
		$fechanew->modify('last day of this month');
		$fecha_fin=$fechanew->format('Y-m-d');
switch ($inventario->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}
View::content();?>
<div class="report-actions">
<a href="javascript:;" class="<?php echo $clp?> print">&nbsp;</a>
<a href="javascript:;" class="excel botonExcel">&nbsp;</a>
<form action="/utiles/excel" method="post" target="_blank" id="FormularioExportacion" class="form-inline">
<input type="hidden" id="datos_a_enviar-<?php echo $cld?>" name="datos_a_enviar"/>
<input type="hidden" id="nombre" name="nombre" value="Kardex-<?Php echo $ln->nombre?>-<?php echo ucwords(Sp::formatFecha('%B',$fecha))?>"/>
</form>
</div>
<?php echo $fecha,$fecha_fin;?>
<div class="<?php echo $cld?>">
<h1>FORMATO 12.1 REGISTRO DE INVENTARIO PERMANENTE ES UNIDADES FISICAS - RESUMEN</h1>
	<table width="100%" id="exportar_excel-<?php echo $cld?>" class="table table-bordered table-striped">
		<thead>
    	  <tr>
	    <th colspan="7" align="left">PERIODO: <?php echo Sp::formatFecha('%m / %Y',$fecha)?></th>
      </tr><tr>
	    <th colspan="7" align="left">RUC: <?php echo $empresa->ruc;?></th>
      </tr><tr>
	    <th colspan="7" align="left">APELLIDOS U NOMBRES. DENOMINACION O RAZON SOCIAL: <?php echo $empresa->nombre?></th>
      </tr>
		  <tr>
		    <th align="left">CODIGO</th>
		    <th align="left">DESCRIPCION</th>
		    <th align="left">MEDIDA</th>
		    <th align="left">STOCK INICIAL</th>
		    <th align="left">INGRESOS</th>
		    <th align="left">SALIDAS</th>
		    <th align="left">STOCK FINAL</th>
      </tr>
	</thead>
    	  <?php
		  $array_producto='';
		  $id_productoA=0;
		  
			  $n=0;
			  //$igv=0;
			  foreach($detalles as $item){
				   $i_coma=',';
				  if($n==0){$i_coma='';}
				  if($id_productoA!=$item->tesproductos_id)$array_producto.=$i_coma.'{id: '.$item->tesproductos_id.', name: "'.$item->getTesproductos()->detalle.'"}';
				  $id_productoA=$item->tesproductos_id;
				  $n++;
				  $SALDO_INICIAL=$item->getSaldo($item->tesproductos_id,0,0,$fecha);
				  $INGRESOS=$item->getTotalingresos_entrefechas($item->tesproductos_id,0,0,$fecha,$fecha_fin);
				  $SALIDAS=$item->getTotalsalidas_entrefechas($item->tesproductos_id,0,0,$fecha,$fecha_fin);
				  $STOCK=(float)$item->getSaldo($item->tesproductos_id,0,0,$fecha_fin);
			  ?>
		  <tr id="<?php echo $n?>">
           <td width="7%" align="left"> <?php echo $id_productoA?>-<?php echo $item->getTesproductos()->codigo?></td>
		   <td width="19%" class="item-name"><?php echo $item->getTesproductos()->nombre?> <?php //echo $item->getTesproductos()->detalle?> <?php echo $item->getTesproductos()->getTestipoproductos()->nombre?></td>
		   <td width="8%"><?php echo $item->getTesunidadesmedidas()->nombre?></td>
           <td width="10%"><?php echo number_format($SALDO_INICIAL,'2','.','');?></td>
           <td width="10%"><?php echo number_format($INGRESOS,'2','.','');?></td>
           <td width="9%"><?php echo number_format($SALIDAS,'2','.','');?></td>
		   <td width="8%">
		   <?php echo number_format($STOCK,'2','.','');?></td>
	      </tr>
		  <?php } ?>
	    </table>
</div>
<script type="text/javascript">
$(function() {
	
	
	$('.<?php echo $clp?>').live("click",function(e) {
		e.preventDefault();
		$('div.<?php echo $cld?>').printArea();
		return false;
	});
	
});
$(document).ready(function() {
	$(".botonExcel").click(function(event) {
		$("#datos_a_enviar-<?php echo $cld?>").val( $("<div>").append( $("#exportar_excel-<?php echo $cld?>").eq(0).clone()).html());
		$("#FormularioExportacion").submit();
});
});
</script>