<?php
$simbolo="S/. ";

switch ($inventario->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}
$inven=$INGR->getInventario(Session::get("TIPOPRODUCTO_ID"));

View::content();
echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<style type="text/css">
ul.token-input-list{ width:200px !important;}
</style>
<div class="card">
<h1><?php echo Session::get('NOMBRE_INVENTARIO')?> x Producto</h1>
</div>

<?php echo Sp::imprimir('INVENTARIO - ','P',array('P'=>"P"));?> 
<div class="form-actions">
<form class="form-inline">
<div class="input-prepend input-append">
  <span class="add-on" title="Buscar Producto!"><em><strong>Bucar Prducto</strong></em></span>
  <input type="text" id="demo-input-local_producto" name="blah" class="input-medium search-query" />
</div>
</form>
</div>
<div id="vista_p"></div>
<div class="card-body">
	 <table width="47%" border="0" align="center" class="table-bordered table-striped">
                <tr>
                    <th width="63" class="meta-head" align="left">Moneda</th>
                    <td width="72">SOLES</td>
                    <th width="58" class="meta-head" align="left">Número #</th>
                    <td width="68"><?php echo $inventario->numero?></td>
                </tr>
                <tr>
					<th align="left">F. Inventario</th>
                    <td><?php echo date('d/m/Y');?></td>
                    <th class="meta-head" align="left">Monto Total</th>
                    <td><span class="simbolo"><?php echo $simbolo?></span></span><span class="due">
					<?php echo number_format((float)$inven->totalconigv-(float)$inven->igv,2,'.','')?></span></td>
       </tr>
        </table>
			<hr />
	<table width="100%" border="0" cellpadding="0" cellspacing="0" class="table-bordered table-striped" id="items">
    <thead>
		  <tr>
		      <th width="7%" align="left">Codigo</th>
		      <th width="19%" align="left">Producto</th>
		      <th width="10%" align="left">Inicial</th>
		      <th width="10%" align="left">Ingresos</th>
              <th width="9%" align="left">Salidas</th>
		      <th width="8%" align="left" >Stock</th>
		      <th width="8%" align="left">Medida</th>
	      </tr>
	</thead>
    	  <?php
		  $array_producto='';
		  $id_productoA=0;
		  
			  $n=0;
			  //$igv=0;
			  foreach($detalles as $item){
				   $i_coma=',';
				  if($n==0){$i_coma='';}
				  if($id_productoA!=$item->tesproductos_id)$array_producto.=$i_coma.'{id: '.$item->tesproductos_id.', name: "'.(string)$item->getTesproductos()->detalle.'"}';
				  $id_productoA=$item->tesproductos_id;
				  $n++;
				  /* INGRESOS DECUARDO A LA LINEA DE PRODUCTO*/
				  $INGRESOS=number_format($item->getTesproductos()->getTotalingresos($item->tesproductos_id)-$item->getTesproductos()->getStockInicial($item->tesproductos_id,Session::get("INVENTARIO_ID")),2,'.','');
				  $STOCK=(float)$item->getTesproductos()->getStock($item->tesproductos_id);
			  ?>
		  <tr id="<?php echo $n?>" title="<?php echo $item->o.' ('.$item->id.')';?>">
           <td align="left"> <?php echo $item->getTesproductos()->codigo?> <?php if(!empty($item->prorollos_id))echo '<br />Nº ro'.$item->getProrollos()->numero.'* venta->'.$item->getProrollos()->numeroventa?></td>
		   <td class="item-name"><?php echo $item->getTesproductos()->nombre?> <?php echo $item->getTesproductos()->detalle?></td>
           <td><?php echo number_format($item->getTesproductos()->getStockInicial($item->tesproductos_id,Session::get("INVENTARIO_ID")),2,'.','')?></td>
           <td><?php   echo $INGRESOS;?></td>
           <td><?php echo number_format($item->getTesproductos()->getTotalsalidas($item->tesproductos_id),2,'.','')?></td>
		   <td>
		   <?php 
		   echo number_format($STOCK,'2','.',' ');?>
           </td>
		   <td><?php echo $item->getTesunidadesmedidas()->nombre?>
           <?php if(Auth::get('id')==3)
		   {
			   echo Html::linkAction('inventario_producto_detalle/'.$item->tesproductos_id,'ver');

			}?>
           </td>
	      </tr>
		  <?php } ?>
	    </table>

     <div style="clear:both"></div>
     <div class="form-actions" title="Regresar!">
    <?php echo Html::linkAction("listado/".Session::get('FAMILIA_ID'),'Regresar ','class="btn btn"') ?>
	</div>
    </div><script type="text/javascript">
        $(document).ready(function() {
            $("#demo-input-local_producto").tokenInput(
			[
                <?php echo $array_producto?>
            ],
			{
                minChars: 1,
                tokenLimit: 1,
				onAdd: function (item) {
					$("#vista_p").load("/<?php echo $module_name?>/<?php echo $controller_name?>/<?php echo $action_name?>_uno/" + item.id);
                },
				onDelete: function (item) {
                    $("#vista_p").html('');
                }
			});
			
        });
        </script>