<?php
$simbolo="S/. ";

switch ($inventario->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}
echo Session::get("TIPOPRODUCTO_ID");
$inven=$INGR->getInventario(Session::get("TIPOPRODUCTO_ID"));

View::content();
echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<style type="text/css">
/*.container {
  width: 1124px;
}*/
#items,input,tesarea,th,td{
	font-size:11px !important;
}
.item-row td{
	padding-left:15px !important;
	}
#paid
{
	width:80% !important;
}
.meta td{
	font-size:14px !important;
	
	}

ul.token-input-list{ width:200px !important;}
</style>
	<div class="card">
	<h1> <em>Reporte de <?php echo Session::get('NOMBRE_INVENTARIO')?> Por Lotes</em></h1>
    </div>
    <div style="clear:both"></div>
<form class="form-inline">
<div class="input-prepend input-append">
  <span class="add-on" title="Buscar Producto"><strong><em>Busque el producto</em></strong></span><em><strong>
  <input type="text" id="demo-input-local_producto" name="blah" class="input-medium search-query" />
  </strong></em>  </div>
</form>
<div id="vista_p"></div>
    <div class="card-body">
	 <table width="50%" border="0" align="center" cellpadding="0" cellspacing="0">
                <tr>
                    <th width="78" align="left">Moneda:</th>
                    <td width="59">SOLES</td>
                    <th width="60" align="left">Número #:</th>
                    <td width="74"><?php echo $inventario->numero?></td>
                </tr>
                <tr>
					<th align="left">F. Inventario:</th>
                    <td><?php echo date('d/m/Y');?></td>
                    <th align="left">Monto Total:</th>
                    <td><span class="simbolo"><?php echo $simbolo?></span></span><span class="due">
					<?php echo number_format((float)$inven->totalconigv-(float)$inven->igv,2,'.','')?></span></td>
       </tr>
    </table>
	<hr />
	<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
    <thead>
		  <tr>
		      <th width="6%">Codigo</th>
		      <th width="19%">Producto</th>
              <th width="13%">Color</th>
              <th width="15%">Lote</th>
		      <th width="10%">Inicial</th>
		      <th width="12%">Ingresos</th>
              <th width="10%">Salidas</th>
		      <th width="11%">Stock</th>
		      <th width="4%">Medida</th>
	      </tr>
	</thead>
    	  <?php 
			  $n=0;
			  $subtotal=0;
			  $subtotalD=0;
			  $array_producto='';
		  $id_productoA=0;
			  //$igv=0;
			  foreach($detalles as $item){
				  $i_coma=',';
				  if($n==0){$i_coma='';}
				  if($id_productoA!=$item->tesproductos_id)$array_producto.=$i_coma.'{id: '.$item->tesproductos_id.', name: "'.$item->getTesproductos()->detalle.'"}';
				  $id_productoA=$item->tesproductos_id;
				  
				  $n++;
				 // print_r($item->getTesproductos()->getTotalingresos($item->tesproductos_id,$item->tescolores_id,$item->lote));
				  $STOCK=(float)$item->getTesproductos()->getStockLote($item->tesproductos_id,$item->tescolores_id,$item->lote);
				  $inicial=$item->getTesproductos()->getStockInicialLote($item->tesproductos_id,Session::get("INVENTARIO_ID"),$item->lote);
				  $stock_ingreso=$item->getTesproductos()->getTotalingresos($item->tesproductos_id,$item->tescolores_id,$item->lote)-number_format($inicial,2,'.','');
				  $stock_salida=$item->getTesproductos()->getTotalsalidas($item->tesproductos_id,$item->tescolores_id,$item->lote);
			  ?>
		  <tr id="<?php echo $n?>" align="left">
           <td><?php //echo $item->getTesingresos()->getTesdocumentos()->nombre?><?php //echo $item->id?><?php echo $item->getTesproductos()->codigo?></td>
		   <td class="item-name">
                  <?php echo $item->getTesproductos()->nombre?> <?php echo $item->getTesproductos()->detalle?>
           </td>
           <td><?php if(Auth::get('id')==3){echo $item->tesproductos_id.'/**/'.$item->tescolores_id;}
		   echo $item->getTescolores()->nombre?></td>
           <td><?php echo $item->lote?></td>
           <td><?php echo number_format($inicial,2,'.','')?></td>
           <td><?php echo $stock_ingreso?></td>
           <td><?php echo $stock_salida?></td>
		   <td>
		   <?php 
		   echo number_format($STOCK,'2','.',' ');?>
           </td>
		   <td><?php echo $item->getTesunidadesmedidas()->nombre?></td>
	      </tr>
		  <?php }
		  ?>
	  </table>

     <div style="clear:both"></div> 
     <div class="form-actions" title="Regresar">
    <?php echo Html::linkAction("listado/".Session::get('FAMILIA_ID'),'Regresar ','class="btn btn"') ?>
	</div>
</div>
<script type="text/javascript">
        $(document).ready(function() {
            $("#demo-input-local_producto").tokenInput(
			[
                <?php echo $array_producto?>
            ],
			{
                minChars: 1,
                tokenLimit: 1,
				onAdd: function (item) {
					$("#vista_p").load("/<?php echo $module_name?>/<?php echo $controller_name?>/<?php echo $action_name?>_uno/" + item.id);
                },
                onDelete: function (item) {
                    $("#vista_p").html('');
                }
			});
			
        });
        </script>