<div class="card">
<h1>CAJAS DE HILO<span>CAJAS DE HILO EN ALMACEN</span></h1>
</div>
<div class="form-actions" title="Regresar!">
 <?php echo Html::linkAction("",'Regresar ','class="btn btn"') ?> 
 <?php echo html::linkAction('inventario_tipo_ingreso/3/1/ALMACEN SP','ALMACEN SP','class="btn btn-secondary"')?>
 <?php echo html::linkAction('inventario_tipo_ingreso/3/2/URDIDO','URDIDO','class="btn btn-secondary"')?>
 <?php echo html::linkAction('inventario_tipo_ingreso/3/3/CHENILLE','CHENILLE','class="btn btn-secondary"')?>
 <?php echo html::linkAction('inventario_tipo_ingreso/3/4/DEVOLUCION','DEVOLUCION','class="btn btn-secondary"')?>
 <?php echo html::linkAction('inventario_tipo_ingreso/3/5/OTROS','OTROS','class="btn btn-secondary"')?>
  <span class="btn btn-info print">Imprimir</span>

</div>
<div>
<h4>TIPO DE HILOS</h4>
<?php foreach($tipos as $tipo)
{
	$activo='';
	if($tipo->id==$id)$activo=' btn-success';
	echo Html::linkAction('reporte_cajas/'.$tipo->id,$tipo->nombre,'class="btn btn-mini'.$activo.'"').' ';
}?>
</div>
<br />
<div class="input-prepend input-append">
  <span class="add-on"><strong>Buscar :</strong></span>
 <input type="search" id="txtBuscar" autofocus="" placeholder="Digite el texto que desea encontrar y presione ENTER. Para cancelar la tecla ESCAPE." class="span7 input-medium search-query">
</div>
<div class="card-body">
<table width="99%" border="0" align="center" cellpadding="0" cellspacing="0"  id="CAJAS_R" class="table table-hover">
<caption>CAJAS DE HILADO EN ALMACEN</caption>
  <tr style="font-size:12px; color:#333; font-weight:bold;">
    <th width="9%" rowspan="2" align="left"># Caja</th>
    <th width="16%" rowspan="2" align="left">Producto</th>
	<th width="14%" rowspan="2" align="left">Color</th>
    <th width="12%" rowspan="2" align="left">Lote</th>
    <th colspan="2" align="left">P. INICIAL.</th>
    <th colspan="2" align="left">P. ACTUAL.</th>
    <th width="8%" rowspan="2" align="CENTER">DOC</th>
  </tr>
  <tr style="font-size:12px; color:#333; font-weight:bold;">
  	<th width="7%" align="left">Kg.</th>
  	<th width="14%" align="left">Bobinas</th>
  	<th width="6%" align="left">Kg</th>
  	<th width="14%" align="left">Bobinas</th>
  	</tr>
  <tbody>
 <?Php 
 $l_a=0;
 $peso=0;
 $conos=0;
 $a=0;
 $pa=0;
 foreach($cajas as $caja)
 {
	 $b=$caja->tescolores_id;
	 $pb=$caja->getTesdetalleingresos()->getTesproductos()->id;
?>
  
  <?php
  
   if($a!=$b){?>
  <tr>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td><span class="pesoneto_2"><?php echo number_format($peso,2,'.','')?></span></td>
    <td align="left" valign="top" class="pesoneto_2"><span class="conos_2"><?php echo number_format($conos,2,'.','')?></span></td>
    <td align="left" valign="top" class="conos_2">&nbsp;</td>
  <td width="0%"></td>
  </tr>
  <?php 
  $a=$caja->tescolores_id;
  $peso=0;
  $conos=0;
  }  
  	
if($pa!=$pb){
	//$a=0;
	$pa=$caja->getTesdetalleingresos()->getTesproductos()->id;
  }
	 $peso=$peso+$caja->stokpeso;
 	 $conos=$conos+$caja->stokbobinas;
  ?>
  <tr id="caja-<?php echo $caja->id?>">
    <td valign="top"><?php echo $caja->numerodecaja?></td>
    <td align="left" valign="top"><?php //echo $caja->getTesdetalleingresos()->getTesproductos()->nombrecorto?><?php echo $caja->getTesdetalleingresos()->getTesproductos()->detalle?></td>
	<td align="left" valign="top"><?php echo $caja->getTesdetalleingresos()->getTescolores()->nombre?></td>
    <td align="left" valign="top"><?php echo $caja->getTesdetalleingresos()->lote?></td>
    <td align="left" valign="top" class="pesoneto_1"><?php 	$pn=floatval($caja->pesoneto);	echo number_format($pn,2,'.','');?></td>
    <td align="left" valign="top" class="conos_1">
	<?php echo number_format($caja->conos,2,'.','')?>
    </td>
    <td align="left" valign="top" class="pesoneto_2">
	<?php echo number_format($caja->stokpeso,2,'.','')?>
    </td>
    <td align="left" valign="top" class="conos_2">
	<?php echo number_format($caja->stokbobinas,2,'.','')?>
    </td>
    <td align="right" valign="top">
	<?php echo $caja->getTesdetalleingresos()->getTesingresos()->serie?>-<?php echo $caja->getTesdetalleingresos()->getTesingresos()->numero?>
    </td>
  </tr>
 <?php 
 }?>
 </tbody>
 <tfoot><tr>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td></td>
  <td><span class="pesoneto_2"><?php echo number_format($peso,2,'.','')?></span></td
    ><td align="left" valign="top" class="pesoneto_2"><span class="conos_2"><?php echo number_format($conos,2,'.','')?></span></td>

    <td align="left" valign="top" class="conos_2">&nbsp;</td>
  <td></td>
  </tr>
 </tfoot>
</table>
</div>
<script type="text/javascript">

//cali rojas
//lewebmonster.com

$(function(){
	 
//funcion para buscar en una tabla con jQuery
	$.fntBuscarEnTabla=function(strCadena,strIDdeTabla)
	{
		//seleccionamos la tabla en la que vamos a buscar
		var $objTabla=$('#'+strIDdeTabla);
		//eliminamos la fila temporal que contiene una leyenda cuando
		//la busqueda no devuelve resultados
		$objTabla.find('#trFilaConMensaje').remove();
		
		//iteramos en todas las filas del body de la tabla
	   var T_P_1=0.00;
	   var T_C_1=0.00;
	   var T_P_2=0.00;
	   var T_C_2=0.00;
		$objTabla.find('tbody tr').each(function(iIndiceFila,objFila)
		{
	    	//obtenemos todas las celdas de la fila
	        var $objCeldas=$(objFila).find('td');
	        
	        //verificamos que la fila tenga celdas
	        if($objCeldas.length>0){
				var blnLaCadenaExiste=false;
				//recorremos todas las celdas de la fila actual
	            $objCeldas.each(function(iIndiceCelda,objCeldaFila){
	            	//limpiamos la cadena que el usuario esta buscando (de caracteres que puedan chocar con
	            	//codigo JavaScript, lo cual genera un error en runtime)
					var objRegEx=new RegExp(RegExp.escape(strCadena),'i');
					//comparamos si la cadena buscada esta en la celda
					if(objRegEx.test($(objCeldaFila).text())){
						//indicamos que hemos encontrado la cadena
						blnLaCadenaExiste=true;
						//salimos del bucle (el de las celdas o columnas)
						return false;
					}
				});
				//si la cadena fue encontrada, entonces mostramos el contenido de la fila,
				//sino, se oculta la fila por completo
				if(blnLaCadenaExiste===true)
				{
					$(objFila).show();
					
					if($(objFila).find('.pesoneto_1'))
					{
						var p1=$(objFila).find('.pesoneto_1').html();
						T_P_1=T_P_1+parseFloat(p1);
						var c1=$(objFila).find('.conos_1').html();
						T_C_1=T_C_1+parseFloat(c1);
						var p2=$(objFila).find('.pesoneto_2').html();
						T_P_2=T_P_2+parseFloat(p2);
						var c2=$(objFila).find('.conos_2').html();
						T_C_2=T_C_2+parseFloat(c2);
					}
					//alert(T_P_1+'/**/'+T_C_1+'/**/'+T_P_2+'/**/'+T_C_2);
				}else{ $(objFila).hide();}
			}
		});
	    
		/*AGREGAMOS UN TR */
		
		if($objTabla.find('tbody tr:visible').length>1){$('tfoot').append('<tr><td align="right" valign="top"></td> <td align="right" valign="top"></td>    <td align="right" align="left" valign="top"></td>	<td align="left" valign="top"></td>    <td align="left" valign="top">TOTAL </td>    <td align="right" valign="top">Ingresos => '+T_P_1.toFixed(2)+'</td>    <td align="right" valign="top">Conos => '+T_C_1.toFixed(2)+'</td>    <td align="right" valign="top">Salidas => '+T_P_2.toFixed(2)+'</td>    <td align="right" valign="top">Conos => '+T_C_2.toFixed(2)+'</td>    <td valign="top"></td> </tr>');}
		
	    //si no hay resultados agregamos una fila temporal para decirle al usuario que
	    //no hemos encontrado lo que busca
		if($objTabla.find('tbody tr:visible').length==0){
			//obtenemos la cantidad de columnas para hacer un colspan
			var iColumnas=$objTabla.find('tbody tr:first-child td').length;
			//agregamos al cuerpo de la tabla la fila con el mensaje			
				$('<tr>',{
					id: 'trFilaConMensaje'
				}).append(
					//agregamos a la fila una celda con el mensaje
					$('<td>',{
						colspan: iColumnas,
						align: 'center',
						html: '<em>No hay resultados, intente otra b&uacute;squeda</em>'
					})
				).appendTo($objTabla.find('tbody'));
		}
	}
	
//extendemos RegEx y agregamos un metodo que nos permita limpiar los caracteres
//que el usuario busca en la tabla, esto es para evitar errores de sintaxis en
//tiempo de ejecucion
	RegExp.escape=function(strCadena){
		var strCaracteresEspeciales=new RegExp("[.*+?|()\\[\\]{}\\\\]", "g");
		//devolvemos la cadena limpia
		return strCadena.replace(strCaracteresEspeciales, "\\$&");
	};
	
//hacemos la busqueda en el evento search del control de busqueda
	$('#txtBuscar').on('search',function(){
		$('tfoot').html('');
		//le decimos a la funcion que busque en la tabla tblTabla el
		//valor que contiene el campo actual
		$.fntBuscarEnTabla($(this).val(),'CAJAS_R');
		
	});
});

</script>