<?php View::content()?>
<?php if($detalles){?>
<script type="text/javascript">
$(document).ready(function() {
	
	$('.<?php echo $clp?>').live("click",function() {
		$('div.<?php echo $cld?>').printArea();
		return false;
	});
	$(".botonExcel").click(function(event) {
		$("#datos_a_enviar-<?php echo $cld?>").val( $("<div>").append( $("#exportar_excel-<?php echo $cld?>").eq(0).clone			()).html());
		$("#FormularioExportacion").submit();
	});
	
});</script>
<style type="text/css">
.ingreso{ background-color:#FCFAA9;}
.salida{ background-color:#E1978C;}
.saldo{ background-color:#80B134;}
</style>
<hr />
<span class="<?php echo $clp?> btn btn-primary"> Print </span>
<a href="javascript:;" class="btn btn-xs">Enviar a Excel<img src="/img/export_to_excel.gif" class="botonExcel" /></a>
<form action="/utiles/excel" method="post" target="_blank" id="FormularioExportacion" class="form-inline">
<input type="hidden" id="datos_a_enviar-<?php echo $cld?>" name="datos_a_enviar"/>
<input type="hidden" id="nombre" name="nombre" value="Kardex-<?Php echo $producto?>"/>
</form>
<div class="<?php echo $cld?>">



<table width="100%" border="0" cellspacing="1" cellpadding="0" class="table table-hover" id="exportar_excel-<?php echo $cld?>">
  <thead>
  <tr>
    <th colspan="12" align="center">KARDEX &nbsp;Producto:&nbsp;<?php echo $producto?>&nbsp;&nbsp;Color:&nbsp;<?php echo $color?>&nbsp;&nbsp;Lote:&nbsp;<?php echo $lote?>&nbsp;&nbsp;Fecha/Inicio:&nbsp;<?php echo Sp::formatFecha('%d/%m/%Y',$fecha_inicio)?>&nbsp;&nbsp;Fecha/Fin:&nbsp;<?php echo Sp::formatFecha('%d/%m/%Y',$fecha_fin)?></th>
  </tr>
  <tr>
    <th width="8%" rowspan="2" align="left">Fecha</th>
    <th width="9%" rowspan="2" align="left">Doc</th>
    <th width="8%" rowspan="2" align="left">Lote</th>
    <th width="12%" rowspan="2" align="left">Color</th>
    <th colspan="3">ENTRADAS</th>
    <th colspan="3">SALIDAS</th>
  </tr>
  <tr>
    <th width="12%" align="left">Cantidad</th>
    <th width="8%" align="left">Precio</th>
    <th width="14%" align="left">Total</th>
    <th width="11%" align="left">Cantidad</th>
    <th width="8%" align="left">Precio</th>
    <th width="10%" align="left">Total</th>
  </tr>
  </thead>
  <tbody>
  <?php 
  $precio=0;
  foreach($detalles as $detalle){
	  if($detalle->precio!=$precio)$precio=$detalle->precio;else $precio=$detalle->precio;
	  ?>
  <tr>
    <td><?php echo Sp::formatFecha('%d/%m/%Y',$detalle->fecha)?></td>
    <td><?php echo $detalle->documento?></td>
    <td><?php echo $detalle->lote?></td>
    <td><?php if(!empty($detalle->tescolores_id))echo $detalle->getTescolores()->nombre?></td>
   <td class="ingreso"><?php if($detalle->tipo=='ingreso')echo number_format((float)$detalle->cantidad,2,'.',' ').' Kg.'?></td>
    <td class="ingreso"><?php if($detalle->tipo=='ingreso')echo 'S/. '.number_format((float)$precio,2,'.',' ') ?></td>
    <td class="ingreso"><?php if($detalle->tipo=='ingreso')echo 'S/. '.number_format((float)$detalle->cantidad*$precio,2,'.',' ') ?></td>
    <td class="salida"><?php  if($detalle->tipo=='salida')echo number_format((float)$detalle->cantidad,2,'.',' ').' Kg.'?></td>
    <td class="salida"><?php  if($detalle->tipo=='salida')echo 'S/. '.number_format((float)$precio,2,'.',' ')?></td>
    <td class="salida"><?php  if($detalle->tipo=='salida')echo 'S/. '.number_format((float)$detalle->cantidad*$precio,2,'.',' ')?></td>
  </tr>
  <?php }?>
  </tbody>
</table>
</div>
<?php }else{echo '<h3> No hay Movimientos Para este producto </h3>';}?>