<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>Admin</b>SP-SC</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Inice sessión</p>
      <div class="social-auth-links text-center mb-3">
        <?php echo Html::link('admin/usuarios', 'Administración','class="btn btn-block btn-primary"') ?>
        
        <?php echo Html::link('santapatricia/index/bienvenida','Snata Patricia SAC','class="btn btn-block btn-info"') ?>
        <?php echo Html::link('santacarmela/index/bienvenida', 'Santa Carmela SAC','class="btn btn-block btn-success"') ?>
       
      </div>
      <!-- /.social-auth-links -->

    
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->