<div class="page-header">
    <h1>Ingresar Nuevo Acabado</h1>
</div>      
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('proacabados.id') ?>
<div class="control-group">
    <label class="control-label">Nombre del Acabado* : </label>
    <div class="controls">
        <?php echo Form::text('proacabados.nombre') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Tipo de acabado* : </label>
    <div class="controls">
        <?php echo Form::select('proacabados.tipo_acabado',array(1=>"Especiales",0=>'Normal')) ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Abreviatura* : </label>
    <div class="controls">
        <?php echo Form::text('proacabados.abr') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Detalle* : </label>
    <div class="controls">
        <?php echo Form::textarea('proacabados.descripcion') ?>
    </div>
</div>
<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
