<div class="page-header">
    <h1>
        Edición del Acabado
        <small><?php eh(strtoupper($proacabados->login)) ?></small>
    </h1>
</div>      
      
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('proacabados.id') ?>
<div class="control-group">
    <label for="usuario_login">Nombre del Acabado* : </label>
    <div class="controls">
        <?php echo Form::text('proacabados.nombre') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Tipo de acabado* : </label>
    <div class="controls">
        <?php echo Form::select('proacabados.tipo_acabado',array(1=>"Especiales",0=>'Normal')) ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_clave">Abreviatura* : </label>
    <div class="controls">
        <?php echo Form::text('proacabados.abr') ?>
    </div>
</div>
<div class="control-group">
    <label for="usuario_clave2">Detalle* : </label>
    <div class="controls">
        <?php echo Form::textarea('proacabados.descripcion') ?>
    </div>
</div>
<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
