<style type="text/css">
.ver{
margin:0 10% 0 10%; !important;
font-size:12px !important;
}
.title{
margin:0 30% 0 30%; !important;
font-size:25px !important;

}
.memo{
font-size:14px !important;
padding:10px 75px;

}
.ver .control-group {
margin:1px !important;
border:solid #CCC 1px;
}

.ver .control-group label{
	font-style:inherit;
	color:#666666;
	font-weight: bold;
}
.ver .control-group label strong{
	color:#000 !important;
	font-weight: bold !important;
}
.form-horizontal .control-group .controls{
	margin-top:5px;
	margin-left:220px !important;
	color:#333333 !important; 
}
</style> 
<div class="page-header">
    <h1>Detalle del Memo</h1>
</div>
<div id="mensajes_flash" >        
 <?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('memos.id') ?>
<?php echo Form::hidden('memos.aclusuarios_id','',Auth::get('id')) ?>
</div> 
<div class="ver">

    <h1 class="title">Memorándum</h1>


<table width="524" border="0">
  <tr>
    <td width="128">&nbsp;</td>
    <td width="380" class="memo"><?php echo $item->getAclempresas()->razonsocial?>    <?php echo $item->fecha?></td>
  </tr>
  <tr>
  <br />
    <td>De:</td>
    <td><?php echo $item->getAclusuarios()->getAcldatos()->nombre?> <?php echo $item->getAclusuarios()->getAcldatos()->appaterno?> <?php echo $item->getAclusuarios()->getAcldatos()->apmaterno?>
    <br />
   (<?php echo $item->getAclusuarios()->getAcldatos()->getPlacargos()->nombre?>)
    </td>
  </tr>
  <tr>
    <td>Para</td>
    <td><?php echo $item->getAcldatos()->nombre?> <?php echo $item->getAcldatos()->appaterno?> <?php echo $item->getAcldatos()->apmaterno?>
    <br />
    (<?php echo $item->getAcldatos()->getPlacargos()->nombre?>)
    </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Asunto</td>
    <td><?php echo $item->titulo?></td>
  </tr>
  <tr>
    <td></td>
    <td><?php echo nl2br($item->detalle)?></td>
  </tr>

</table> 
Atte:
<br />
<?php echo $item->getAclusuarios()->getAcldatos()->getPlacargos()->nombre?>
<br />
<br />
<br />
<?php echo Html::linkAction("", 'Regresar','class="btn btn-primary"') ?>


