<?php //Tag::css('scaffold')?>
<div class="page-header">
<h1>Listado general de rollos</h1>
</div>
<div class="form-actions">
	<?php echo Html::linkAction("crear/",'Crear registro')?>
</div>
<div class="page">
<?php if ($results->items) : ?>
<table border="0" cellpadding="0" cellspacing="0" class="table" style="font-size:9px;">
    <thead><tr align="center">
    <?php foreach (current($results->items)->fields as $field) : ?>
        <th><?php echo (current($results->items)->get_alias($field))?></th>
    <?php endforeach?>
	<th>Acciones</th>
    </tr></thead>
	<tbody>
    <?php foreach ($results->items as $item) : ?>
        <tr>
            <?php foreach ($item->fields as $field) : ?>
            <td align="center"><?php eh($item->$field)?></td>
            <?php endforeach?>
			<td>
			<?php echo Html::linkAction("ver/$item->id",'Ver')?> |
			<?php echo Html::linkAction("editar/$item->id",'Editar')?> |
			<?php echo Html::linkAction("borrar/$item->id",'Borrar', 'onclick="return confirm(\'¿Está seguro?\')"')?>
			</td>
        </tr>
    <?php endforeach?>
	</tbody>
</table>
<?php View::partial('paginators/extended', false, array('page' => $results ,'url' => Router::get('controller_path').'/rollos')); ?>

<?php else : // Si no hay items?>
<h2>No hay ningún registro</h2>
<?php endif ?>

</div>
<?php //var_dump($results)?>