
<div class="card"><h1>Resumen de los ultimos movimientos en el sisitema</h1></div>
<h4>Accesos directos</h4>
<div class="form-actions"><?Php /**/ echo Html::link($module_name."/tintoreria/rollos_venta",'Almacen de ventas de Rollos','class="btn btn-secondary"')?><?Php echo Html::link($module_name."/reportes/ventasmes",'Ventas del mes','class="btn btn-secondary"')?> <?Php echo Html::link($module_name."/reportes/codigodebarras",'Codigo de Barras','class="btn btn-secondary"')?></div>
<div class="card-body">
<div class="row-fluid">
            <ul class="thumbnails">
              <li class="span4">
                <div class="thumbnail">
                <?php echo Html::img('figuras/enviartodo.png','','style=" float:right;width: 50px; height: 50px;"')/*imagen o inicio*/ ?>
                  <div class="caption" id="ventas_semanal">
                    <h3>Ventas semanal <?Php echo date('M-Y');?></h3>
                    <ul class="nav nav-tabs">
                          <?php
					$fecha2 = strtotime ( '-1 day' , strtotime (date('Y-m-d')) );
					$fecha1 = strtotime ( '-5 day' , strtotime ( $fecha2 ) ) ;
					$fecha1 = date ( 'Y-m-d' , $fecha1 );
					for($i=$fecha1;$i<=$fecha2;$i = date("Y-m-d", strtotime($i ."+ 1 days")))
					{?>
					   <li <?Php if($i==$fecha2)echo 'class="active"'; ?>>
                       <?Php $dia=explode('-',$i); ?>
                         <?php echo Ajax::linkAction('semana_facturas/'.$i,$dia[2],'ventas_semanal')?></a>
                       </li>
					<?php }	?>
                          
                        </ul>
					<i class="PAGADO">Pagado</i> <i class="PENDIENTE">Pendiente</i> <i class="EDITABLE">Creando</i>
                    <table style="font-size:9px;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-condensed">
                      <tr>
                        <th width="74%">Empresa</th>
                        <th width="21%">Doc</th>
                        <th width="3%">Fecha</th>
                        <th width="2%">Total</th>
                      </tr>
                      <?Php foreach($ventasf as $venta){
					 	?>
                      <tr class="<?php echo strtoupper($venta->estado)?>">
                        <td><?php echo $venta->empresa?></td>
                        <td><?php echo intval($venta->numero)?></td>
                        <td><?php echo Sp::formatFecha("%d/%m/%y",$venta->fecha)?></td>
                        <td align="right"><?php if(!empty($venta->total))echo number_format($venta->total,2,'.','')?></td>
                      </tr>
                      <?Php }?>
                    </table>
                    <p><?php echo Html::link('santapatricia/ventas','Ver mas','class="btn btn-primary"')?></p>
                  </div>
                </div>
              </li>
              <li class="span4">
                <div class="thumbnail">
                <?php echo Html::img('figuras/enviartodo.png','','style=" float:right;width: 50px; height: 50px;"')/*imagen o inicio*/ ?>
                  <div class="caption" id="guias_semanal">
                    <h3>Guias semanal <?Php echo date('M-Y');?></h3>
                    <ul class="nav nav-tabs">
                          <?php
					$fecha2 = strtotime ( '-1 day' , strtotime (date('Y-m-d')) );
					$fecha1 = strtotime ( '-5 day' , strtotime ( $fecha2 ) ) ;
					$fecha1 = date ( 'Y-m-d' , $fecha1 );
					for($i=$fecha1;$i<=$fecha2;$i = date("Y-m-d", strtotime($i ."+ 1 days")))
					{?>
					    <li <?Php if($i==$fecha2)echo 'class="active"'; ?>>
                       <?Php $dia=explode('-',$i); ?>
                         <?php echo Ajax::linkAction('semana_guias/'.$i,$dia[2],'guias_semanal')?></a>
                       </li>
					<?php }	?>
                          
                        </ul>
					<i class="PAGADO">Pagado</i> <i class="PENDIENTE">Pendiente</i> <i class="EDITABLE">Creando</i>
                    <table style="font-size:9px;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-condensed">
                      <tr>
                        <th width="74%">Empresa</th>
                        <th width="21%">Doc</th>
                        <th width="3%">Fecha</th>
                        <th width="2%">Total</th>
                      </tr>
                      <?Php foreach($ventasg as $venta){
					 	?>
                      <tr class="<?php echo strtoupper($venta->estado)?>">
                        <td><?php echo $venta->empresa?></td>
                        <td><?php echo intval($venta->numero)?></td>
                        <td><?php echo Sp::formatFecha("%d/%m/%y",$venta->fecha)?></td>
                        <td align="right"><?php if(!empty($venta->total))echo number_format($venta->total,2,'.','')?></td>
                      </tr>
                      <?Php }?>
                    </table>
                    <p><?php echo Html::link('santapatricia/ventas','Ver mas','class="btn btn-primary"')?></p>
                  </div>
                </div>
              </li>
              <li class="span4">
                <div class="thumbnail">
                <?php echo Html::img('figuras/enviartodo.png','','style=" float:right;width: 50px; height: 50px;"')/*imagen o inicio*/ ?>
                  <div class="caption" id="guias_semanal">
                    <h3>Facturas <?Php echo date('M-Y');?></h3>
                    <i class="PAGADO">Pagado</i> <i class="PENDIENTE">Pendiente</i> <i class="EDITABLE">Creando</i>
                    <table style="font-size:9px;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-condensed">
                      <tr>
                        <th width="74%">Empresa</th>
                        <th width="21%">Doc</th>
                        <th width="3%">Fecha</th>
                        <th width="2%">Total</th>
                      </tr>
                      <?Php foreach($ventas as $venta){
					 	?>
                      <tr class="<?php echo strtoupper($venta->estado)?>">
                        <td><?php echo $venta->empresa?></td>
                        <td><?php echo intval($venta->numero)?></td>
                        <td><?php echo Sp::formatFecha("%d/%m/%y",$venta->fecha)?></td>
                        <td align="right"><?php if(!empty($venta->total))echo number_format($venta->total,2,'.','')?></td>
                      </tr>
                      <?Php }?>
                    </table>
                    <p><?php echo Html::link('santapatricia/ventas','Ver mas','class="btn btn-primary"')?></p>
                  </div>
                </div>
              </li>
            </ul>
            <ul class="thumbnails">
              <li class="span4">
                <div class="thumbnail">
                <?php echo Html::img('figuras/calidades.png','','style=" float:right;width: 50px; height: 50px;"')/*imagen o inicio*/ ?>
                <h3>Telas programadas en maquinas</h3>
                  <div class="caption" id="produccion">                   
                    <?php echo Ajax::linkAction('produccion','Actualizar','produccion')?>
                    <table style="font-size:9px;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-condensed">
                      <tr>
                        <th width="4%">Maquina</th>
                        <th width="74%">Producto</th>
                        <th width="22%">Metros</th>
                      </tr>
                      <?Php foreach($producciones as $prod){?>
                      <tr>
                        <td><?php echo $prod->maquina?></td>
                        <td><?php echo $prod->tela?></td>
                        <td><?php echo $prod->metros?></td>
                      </tr>
                      <?Php }?>
                    </table>
                    <p><?php echo Html::link('santapatricia/produccion','Ver mas','class="btn btn-primary"')?></p>
                  </div>
                </div>
              </li><li class="span4">
                <div class="thumbnail">
                <?php echo Html::img('figuras/enviarparte.png','','style=" float:right;width: 50px; height: 50px;"')//imagen o inicio ?>
                  <div class="caption" id="rollos">
                    <h3>Rollos para venta </h3>
                    <?php echo Ajax::linkAction('rollos','[Actualizar]','rollos')?>(ultimas modificaciones)
                    <table style="font-size:9px;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-condensed">
                      <tr>
                        <th width="52%">Tela</th>
                        <th width="46%">Color</th>
                        <th width="2%">Total</th>
                      </tr>
                      <?Php foreach($rollos as $rollo){?>
                      <tr>
                        <td><?php echo $rollo->tela?></td>
                        <td><?php echo $rollo->color?></td>
                        <td align="right"><?php echo number_format($rollo->metros,2,'.','')?></td>
                      </tr>
                      <?Php }?>
                    </table>
                    <p><?php echo Html::link('santapatricia/tintoreria/rollos_venta','Ver mas','class="btn btn-primary"')?></p>
                  </div>
                </div>
              </li>
            </ul>
            <ul class="thumbnails">
              <li class="span4">
                <div class="thumbnail">
                <?php echo Html::img('figuras/ver_procesos.png','','style=" float:right;width: 50px; height: 50px;"')/*imagen o inicio*/ ?>
                  <div class="caption">
                    <h3>Ordenes de compra</h3>
                    <?php echo Ajax::linkAction('rollos','[Actualizar]','rollos')?>(ultimas modificaciones)
                    <table style="font-size:9px;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-condensed">
                      <tr>
                        <th width="52%">Empresa</th>
                        <th width="46%">Ubicacion</th>
                        <th width="2%">Total</th>
                        <th width="2%">Fecha</th>
                      </tr>
                      <?Php foreach($ordenes as $orden){?>
                      <tr>
                        <td><?php echo $orden->nombre?></td>
                        <td><?php echo $orden->ubicacion?></td>
                        <td align="right"><?php echo number_format($orden->total,2,'.','')?></td>
                        <td><?php echo Sp::formatFecha("%d/%m/%y",$orden->fecha)?></td>
                      </tr>
                      <?Php }?>
                    </table>
                    <p><a href="#" class="btn btn-primary">Ingresar</a></p>
                  </div>
                </div>
              </li>
              <li class="span4">
                <div class="thumbnail">
                <?php echo Html::img('figuras/carrito.png','','style=" float:right;width: 50px; height: 50px;"')/*imagen o inicio*/ ?>
                  <div class="caption">
                    <h3>Compras o documentos de ingresos</h3>
                    Los 20 ultimos registrados <i class="PAGADO">Pagado</i> <i class="PENDIENTE">Pendiente</i> <i class="EDITABLE">Creando</i><?php echo Ajax::linkAction('compras','[Actualizar]','compras')?>
                    <table style="font-size:9px;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-condensed">
                      <tr>
                        <th width="74%">Empresa</th>
                        <th width="21%">Doc</th>
                        <th width="3%">Numero</th>
                        <th width="2%">Total</th>
                      </tr>
                      <?Php foreach($compras as $compra){
					 	?>
                      <tr class="<?php echo strtoupper($compra->estado)?>">
                        <td><?php echo $compra->nombre?></td>
                        <td><?php echo $compra->doc?></td>
                        <td><?php echo intval($compra->numero)?></td>
                        <td align="right"><?php if(!empty($compra->total))if(is_numeric($compra->total)) echo number_format($compra->total,2,'.','')?></td>
                      </tr>
                      <?Php }?>
                    </table>
                    <p><?php echo Html::link('santapatricia/ingresos','Ver mas','class="btn btn-primary"')?></p>
                  </div>
                </div>
              </li>
              <li class="span4">
                <div class="thumbnail">
                <?php echo Html::img('figuras/calendario.png','','style=" float:right;width: 50px; height: 50px;"')/*imagen o inicio*/ ?>
                  <div class="caption">
                    <h3>Calendario</h3>
                    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-condensed">
                     <thead>
                     <tr>
                        <th scope="col">Titulo</th>
                        <th scope="col">F/inicio</th>
                        <th scope="col">F/Fin</th>
                      </tr>
                      </thead>
                      <?php
                      $cumples_ar=array();
					  $a=0;
					  foreach($cumples as $cumple)
					  {
						  $cumples_ar[$a]['title']=$cumple->title;
						  $cumples_ar[$a]['fecha_i']=Sp::formatFecha($cumple->fecha_inicio,'%d-%m-%Y');
						  $cumples_ar[$a]['fecha_f']=Sp::formatFecha($cumple->fecha_inicio,'%d-%m-%Y');
						  $a++;
					  }
					  function orden($a,$b)
					  {
						  return strtotime($a['fecha_i']) - strtotime($b['fecha_i']);
					  }
					  usort($cumples_ar, 'orden');						
					 foreach($cumples_ar as $val){
						  
						  ?>
                      <tr style="color:#F60;">
                        <td><i class="icon-gift"></i> <?php echo $val['title']?></td>
                        <td><?Php echo Sp::formatFecha('%B %A',$val['fecha_i'])?></td>
                        <td><?Php echo $val['fecha_f']?></td>
                      </tr>
                      <?php }?>
                      <?php foreach($diarios as $dia){?>
                      <tr style="color:#900;">
                        <td><i class="icon-tags"></i><?php echo $dia->title?></td>
                        <td><?Php echo $dia->fecha_inicio?></td>
                        <td><?Php echo $dia->fecha_fin?></td>
                      </tr>
                      <?php }?>
                      <?php foreach($semanales as $semanal){?>
                      <tr style="color:#F60;">
                        <td><i class="icon-tag"></i><?php echo $semanal->title?></td>
                        <td><?Php echo $semanal->fecha_inicio?></td>
                        <td><?Php echo $semanal->fecha_fin?></td>
                      </tr>
                      <?php }?>
                      <?php foreach($mensuales as $mensual){?>
                      <tr style="color:#060;">
                        <td><i class="icon-tags"></i><?php echo $mensual->title?></td>
                        <td><?Php echo $mensual->fecha_inicio?></td>
                        <td><?Php echo $mensual->fecha_fin?></td>
                      </tr style="background-color:#FC3;">
                      <?php }?>
                      <?php foreach($anuales as $anual){?>
                      <tr style="color:#333;">
                        <td><i class="icon-tags"></i><?php echo $anual->title?></td>
                        <td><?Php echo $anual->fecha_inicio?></td>
                        <td><?Php echo $anual->fecha_fin?></td>
                      </tr>
                      <?php }?>
					  <?php foreach($eventos as $evento){?>
                      <tr style="color:#00F;">
                        <td><i class="icon-tag"></i><?php echo $evento->title?></td>
                        <td><?Php echo $evento->fecha_inicio?></td>
                        <td><?Php echo $evento->fecha_fin?></td>
                      </tr>
                      <?php }?>
                    </table>
                    <p><?php echo Html::link('santapatricia/calendarios','Ver mas', 'class="btn btn-info"')?></p>
                  </div>
                </div>
              </li>
            </ul>
</div>
</div>
