<h3>Compras o documentos de ingresos</h3>
                    Los 20 ultimos registrados <i class="PAGADO">Pagado</i><i class="PENDIENTE">Pendiente</i><i class="EDITABLE">Creando</i><?php echo Ajax::linkAction('compras','[Actualizar]','compras')?>
                    <table style="font-size:9px;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-condensed">
                      <tr>
                        <th width="74%">Empresa</th>
                        <th width="21%">Doc</th>
                        <th width="3%">Numero</th>
                        <th width="2%">Total</th>
                      </tr>
                      <?Php foreach($compras as $compra){
					 	?>
                      <tr class="<?php echo strtoupper($compra->estado)?>">
                        <td><?php echo $compra->nombre?></td>
                        <td><?php echo $compra->doc?></td>
                        <td><?php echo intval($compra->numero)?></td>
                        <td align="right"><?php if(!empty($compra->total))echo number_format($compra->total,2,'.','')?></td>
                      </tr>
                      <?Php }?>
                    </table>
                    <p><a href="#" class="btn btn-primary">Ingresar</a></p>