<?php View::content();?>
<br />
<br />

<div class="hoja">
	<div class="caja3">
<div align="center">
<img id="image" src="/img/logoSP.png" alt="logo">
</div>
<br />
<h4 align="center">VISION</h4>
 <div align="left">


Ser una empresa líder, 
proveedora de soluciones de calidad en todos los sectores, 
con los que nos encontramos comprometidos, 
dando o proporcionando asesoría con personal motivado y calificado.

</div>
<br />
<h4 align="center">MISION</h4>
<div align="left">

Proveer y facilitar a nuestros clientes productos textiles de calidad, 
acorde con la tendencia y  necesidades de los mercados que ofertamos 
(HOTELES, OFICINAS, CUEROS, DEPORTES, RESTAURANTES) 
generando valor a nuestros clientes y para nuestra empresa.
</div>
<br />
<h4 align="center">VALORES</h4>
<div align="center">
<div align="left">

-	Satisfacción plena de nuestros productos y clientes, 
proporcionando garantía a nuestros productos con entrega a tiempo, 
soluciones inteligentes acorde a las necesidades así como servicios de calidad.
</div>
<br />
<div align="left">
-	Constante superación: 
Búsqueda de soluciones en cuanto  a productos y servicios 
a fin de cubrir las necesidades del cliente y el desarrollo de la empresa.
</div>
<br />
<div align="left">
-	Medio Ambiente: Cuidado del medio ambiente como constante, 
tanto en reciclado de mermas y desperdicios generales en la actividad productiva; 
así como de los productos y servicios textiles ofrecidos a nuestros clientes.
</div>
</div>
</div>
</div>