<h3>Rollos para venta </h3>
                    <?php echo Ajax::linkAction('rollos','[Actualizar]','rollos')?>(ultimas modificaciones)
                    <table style="font-size:9px;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-condensed">
                      <tr>
                        <th width="52%">Tela</th>
                        <th width="46%">Color</th>
                        <th width="2%">Total</th>
                      </tr>
                      <?Php foreach($rollos as $rollo){?>
                      <tr>
                        <td><?php echo $rollo->tela?></td>
                        <td><?php echo $rollo->color?></td>
                        <td align="right"><?php echo number_format($rollo->metros,2,'.','')?></td>
                      </tr>
                      <?Php }?>
                    </table>