
                    <h3>Las ultimas 20 facturas</h3><i class="PAGADO">Pagado</i> <i class="PENDIENTE">Pendiente</i> <i class="EDITABLE">Creando</i><?php echo Ajax::linkAction('ventas','[Actualizar]','ventas')?>
                    <table style="font-size:9px;" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-condensed">
                      <tr>
                        <th width="50%">Empresa</th>
                        <th width="46%">Doc</th>
                        <th width="2%">Fecha</th>
                        <th width="2%">Total</th>
                      </tr>
                      <?Php foreach($ventas as $venta){
					 	?>
                      <tr class="<?php echo strtoupper($venta->estado)?>">
                        <td><?php echo $venta->empresa?></td>
                        <td><?php echo intval($venta->numero)?></td>
                        <td><?php echo Sp::formatFecha("%d/%m/%y",$venta->fecha)?></td>
                        <td align="right"><?php echo number_format($venta->total,2,'.','')?></td>
                      </tr>
                      <?Php }?>
                    </table>