<div class="card">
    <h1><?php echo $titulo?><span>Listado de ordenes de compras</span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>

<div class="form-actions">
    <?php echo Html::linkAction("cargar/0", 'Ingresar o Crear Orden','class="btn btn-xs btn-primary"') ?> <?php echo Html::linkAction("", ' Selecione Origen','class="btn btn-xs btn-secondary"') ?>
</div>

<?php echo Sp::imprimir('Ordenes de compras - ','P');?> 
<div id="ver_resultado"></div>
<div class="menu">
<ul>
<li>
<a href="javascript:;">Año 
<select id="anio">
<?php
for($i=2011;$i<=2020;$i++)
{
	$selec='';
	if($anio==$i){
	$selec=' selected="selected"';
	}
	echo '<option value="'.$i.'" '.$selec.'>'.$i.'</option>';
}
?>
</select>
</a>
</li>
</ul> 
<?php 
$mes_actual=date('Y-m');
foreach($meses as $clave => $mes):
if($anio.'-'.$clave<=$mes_actual){
$class='';
if($mes_activo==$clave)$class=' active';
echo '<ul>';
echo '<li><a class="enviar'.$class.'" id="mes-'.$mes.'" href="javascript:;" data-id="'.$anio.'-'.$clave.'-01">'.$mes.'</a></li>'; 
echo '</ul>';
}
endforeach;?>

</div>
<div class="clear"></div>
<div class="input-prepend input-append">
  <span class="add-on">Buscar :</span>
 <input type="search" id="txtBuscar" autofocus="" placeholder="Digite el texto que desea encontrar y presione ENTER. Para cancelar la tecla ESCAPE." class="span7 input-medium search-query">
</div>
<div class="card-body">
<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">
  <caption>Listado de Ordenes de compra</caption>
  <thead>
  <tr>
  	<th width="25">Nº</th>
    <th width="50">Numero</th>
    <th width="245">De </th>
    <th width="241">Para</th>
    <th width="67">Igv</th>
    <th width="52">Total</th>
    <th width="60">Acciones </th>
  </tr>
 </thead>
 <tbody>
<?php $n=0;
foreach($ordenes as $item){ 
$n++;
switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $n?></td>
    <td><?php echo $item->codigo?></td>
    <td><?php if($item->origenorden=='interno'){echo $empresa->razonsocial;}else{echo $item->getTesdatos()->razonsocial;}?></td>
    <td><?php if($item->origenorden!='interno'){echo $empresa->razonsocial;}else{echo $item->getTesdatos()->razonsocial;}?></td>
    <td><?php echo $simbolo; echo number_format($item->igv,2,'.','');?></td>
    <td><?php echo $simbolo; echo number_format($item->totalconigv,2,'.','');?></td>
   <td>
   <?php echo Html::linkAction('cargar/'.$item->id.'/',Html::img("figuras/editar.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'')?>
   <?php echo Html::linkAction('cargar/'.$item->id.'/ver',Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'),'')?>
    </td>
  </tr>
<?php }?>
</tbody>
</table>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$('#txtBuscar').on('search',function(){
		//le decimos a la funcion que busque en la tabla tblTabla el
		//valor que contiene el campo actual
		$.fntBuscarEnTabla($(this).val(),'exportar_excel');
		
	});
	$(".ver").click(function(){
	var op=$(this).attr('data-id');
	document.location = "/<?php echo $module_name?>/<?php echo $controller_name?>/index/"+op;
	});	
	$("#anio").change(function(event){
    	var id = $("#anio").find(':selected').val();
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/<?php echo $origen?>/'+id;
     });
	$(".enviar").click(function()
	{
		var fecha = $(this).attr('data-id');
		var F=fecha.split('-');
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/<?php echo $origen?>/'+F[0]+'/'+F[1];
	});
});
</script>