<?php echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<div class="card">
    <h1><em>Crear Letra <span></span></em></h1>
</div>

<div class="form-actions">
<?php echo Menu::menuLetras($action_name);?>
</div>
<div id="mensajes_flash" >        
    <?php View::content();
	
	?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>
<?php echo Form::open(NULL,'POST','class="form-horizontal"')?>
      <?php echo Form::hidden('salida.npedido','size="10" readonly="readonly"');?>
  <div class="control-group">
    <label class="control-label" for="salida_serie">Numero:</label>
    <div class="controls">
      <?php echo Form::hidden('salida.serie','size="4"','LTR');?><?php echo Form::text('salida.numero','size="10"');?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="salida_tesmonedas_id">Moneda:</label>
    <div class="controls">
      <?php echo Form::dbSelect('salida.tesmonedas_id','simbolo,nombre',array("tesmonedas",'find','conditions: aclempresas_id='.Session::get('EMPRESAS_ID')));?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="CL">Cliente</label>
    <div class="controls">
    	<div style="float:left; width:70%;"><input id="CL" /></div>
      <?php echo Form::hidden('salida.tesdatos_id');?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="salida_femision">Fecha de Emision:</label>
    <div class="controls">
      <?php echo Calendar::selector('salida.femision');//finiciotraslado?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="salida_femision">Fecha de vencimiento:</label>
    <div class="controls">
      <?php echo Calendar::selector('salida.fvencimiento');//finiciotraslado?>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="CL">Total </label>
    <div class="controls">
      <?php echo Form::text('salida.totalconigv','class="qty"');?>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
       <button type="submit" class="btn btn-primary">Crar</button> <?php echo Html::linkAction('','Cancelar','class="btn"')?>
    </div>
  </div>
<?php echo Form::close();?>
</div>
<script type="text/javascript">
$(document).ready(function()
{
	$("#CL").tokenInput("/<?php echo $module_name?>/salidas/buscarcliente", 
		{
			tokenLimit: 1,
			minChars: 2,
	
			onAdd: function (item){
			   var VAL=item.id;
			   $("#salida_tesdatos_id").val(VAL);
				//$("#BC").hide();
			   //GrabarCliente();
			},
			onDelete: function (item) {
			}
		});
		
		
});
</script>
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Nuevo </h3>
  </div>
  <div class="modal-body" id="otro">
  </div>
  <div class="modal-footer">
  </div>
</div>
