<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>

<div class="card">
    <h1>Letras Internas<span><?php echo $empresa->razonsocial?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="form-actions">

<?php echo Html::linkAction('internas_registradas','Internas registradas','class="btn btn-xs "');?> 
<?php echo Html::linkAction('letra_adelanto','Crear Letra por Adelanto','class="btn btn-xs btn-info"')?> 
<?php echo Sp::imprimir('Letras semanal - ','P',array("W"=>1,"P"=>1,"EX"=>1));?> 
</div>

<div id="ver_resultado"></div>
<div class="card-body">

<table id="exportar_excel" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">

<caption>Letras Internas!</caption>

  <tr>
  	<td width="51">Nº</td>
    <td width="176">Proveedor</td>
	<td width="170">Número Doc.</td>
	<td width="106">F. Emision</td>
    <td width="137">F. Vto.</td>
    <td width="125">Monto</td>
    <td width="157">Acciones</td>
  </tr>
<?php $number=0;
foreach($letras as $item){ 
$simbolo="S/. ";

switch ($item->getTessalidasinternas()->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

$number++;?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $number?> <?php echo $item->tesmonedas_id?></td>
  	<td height="20"><?php echo $item->getTessalidasinternas()->getTesdatos()->razonsocial?></td>
	<td height="20"><?php echo $item->getTessalidasinternas()->numero?></td>
	<td height="20" align="center"><?php echo Sp::formatFecha('%d / %m / %Y',$item->getTessalidasinternas()->femision)?><?php //echo $item->getTesingresos()->femision?></td>
    <td align="center"><?php echo Sp::formatFecha('%d / %m / %Y',$item->getTessalidasinternas()->fvencimiento)?><?php //echo $item->getTesingresos()->fvencimiento?></td>
    <td align="right" valign="top">
    <?php echo $simbolo?>  <?php echo number_format($item->getTessalidasinternas()->total,2,'.',' ')?>
	    </td>
    <td align="center"><?php echo Html::linkAction('letrai/'.$item->id.'/',Html::img("figuras/ver.png",'VER','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Clic! para Imprimir la LETRA INTERNA ! !"','')?>
    <?php echo Html::linkAction('editar_interna/'.$item->id.'/',Html::img("figuras/editar.png",'VER','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar  !"','')?>
    <?php echo Html::linkAction('registrar_interno/'.$item->id.'/internas_registradas',Html::img("figuras/facturar.png",'VER','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar  !"','')?>
    <?php echo Html::linkAction('eliminar_letras_i/'.$item->id,' Eliminar','title="Eliminar !"','')?>
	
	
    </td>
  </tr>
<?php }?>
</table>
</div>