<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
.rojo{
	color:#FF0000;}
	
.verde{
	color:#090;}
</style>
<div class="card">
    <h1><em>Letras Pendientes de Cobro !<span><?php echo $empresa->razonsocial?></span></em></h1>
</div>
<div class="form-actions">
<?php echo Menu::menuLetras($action_name);?>
</div>

<div class="form-actions"> 
<?php echo Html::linkAction('listadoporestado','Listado Por estado','class="btn "');?> <?php echo Sp::imprimir('Letras semanal - ','P');?>
</div>
<div class="input-prepend input-append">
  <span class="add-on">Buscar :</span>
 <input type="search" id="txtBuscar" autofocus="" placeholder="Digite el texto que desea encontrar y presione ENTER. Para cancelar la tecla ESCAPE." class="span7 input-medium search-query">
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>
<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
  <thead>
  <caption style="color:#333; font-weight:bold;">Letras por cobrar segun Fecha de Vencimiento</caption>
  <tr>
  	<th width="17">Nº</th>
    <th width="189">Proveedor</th>
    <th width="67">Número Doc.</th>
    <th width="61">Numero unico</th>
    <th width="101">Fecha de Vencimiento</th>
    <th width="57">Banco</th>
    <th width="96">Total</th>
    <th width="60">Estado </th>
  </tr>
  </thead>
<?php $number=0;
$semana=0;
$a=0;
$x=0;
$y=0;
$T_soles=0;
$T_dolares=0;
foreach($letras as $item){ 
$simbolo="S/. ";
/*echo "<pre>";
print_r($item);
echo "</pre>";*/
/*campos*/
$razon_social='';
$numero='';
$totalconigv=00;
$estadoingreso='';
$fecha_vencimiento='';
if($item->origen==1){
$fecha_vencimiento=$item->fvencimiento;
$razon_social=$item->razonsocial;

	$x=$item->numero;	
	$y=strlen($x);
	if($y>=6){$x=substr($x, 0, -2);}
	if(!empty($item->nrenovacion))$x.=$item->nrenovacion; else $x.="00";
	$numero = $x;
$totalconigv=$item->getTessalidas()->totalconigv;
$estadoingreso=$item->estadoletras;
$moneda_id=$item->getTessalidas()->tesmonedas_id;
}
if($item->origen==0){
$item->getTessalidasinternas()->id;
$fecha_vencimiento=$item->fvencimiento;
$razon_social=$item->razonsocial;
$numero=$item->getTessalidasinternas()->numero;
$totalconigv=$item->monto;
$estadoingreso=$item->estadoletras;
$moneda_id=$item->getTessalidasinternas()->tesmonedas_id;
}
//echo $fecha_vencimiento;
$T_letras=$item->Totalletrasporsemana($item->semana,$fecha_vencimiento);

$number++;?>
<?php 
$b=$item->semana;
if($a!=$b){

$number=1;
$T_soles=0;
$T_dolares=0;
?>
<thead>
<tr id="<?php echo $item->id?>">
  	<td height="20" colspan="9"><h4>Semana Nº <?php echo $item->semana?></h4></td>
</tr>
</thead>
<?php 
}
$a=$item->semana;

switch ($moneda_id)
{
	case 1: $simbolo='S/. '; $T_soles=$T_soles+$item->monto; break;
	case 2: $simbolo='$. '; $T_dolares=$T_dolares+$item->monto;break;
	case 4: $simbolo='S/. ';$T_soles=$T_soles+$item->monto; break;
	case 5: $simbolo='$. ';$T_dolares=$T_dolares+$item->monto;break;
	case 0: $simbolo='S/. ';$T_soles=$T_soles+$item->monto; break;
}
/*pintar las fechas*/
$class='';
$dias='';

if($fecha_vencimiento<date("Y-m-d")){$class=' class="rojo" ';$dias=", hace ".$item->dd." dia(s)";}
if($fecha_vencimiento==date("Y-m-d"))$class=' class="verde" ';



?>
  <tr id="<?php echo $item->id?>" title="<?php echo $item->origen?> (<?Php echo $item->id?>)">
  	<td height="20"><?php echo $number?></td>
  	<td height="20"><?php echo $razon_social?></td>
    <td><?php echo $numero?></td>
    <td><?php echo $item->numerounico?></td>
    <td<?Php echo $class?>><?php echo Sp::formatFecha('%d/%m/%Y',$fecha_vencimiento)?><?php echo $dias;?></td>
    <td><?php echo $item->banco?></td>
    <td><?php if($totalconigv!='NaN.00' && !empty($totalconigv))echo $simbolo.number_format($totalconigv,2,'.','');else echo('S/ 00.00')?></td>
   <td>
   <?php //echo $item->semana?><?php echo $estadoingreso?><?php if(!empty($item->numerounico)){}else{echo " Sin # único";}?>
    <?php //echo $number."==".$T_letras;echo "<br />"; echo $T_soles; echo "<br />"; echo $T_dolares; echo "<br />"; echo $item->getTesingresos()->tesmonedas_id;?>
    </td>
  </tr>
  <?Php if($number==$T_letras){?>
  <tr>
  <td colspan="3">Total de la semana <?php echo $item->semana?></td>
  <td colspan="3">Total en S/. <?php echo number_format($T_soles,2,'.',' ')?></td>
  <td colspan="3">Total en $/. <?php echo number_format($T_dolares,2,'.',' ')?></td>
  </tr>
  <tr>
  <td colspan="9">&nbsp;</td>
  </tr>
  <?php }?>
<?php 
	}?>
</table>
</div>