<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>
<div class="card">
    <h1><em>Letras Vencidas</em><span><?php echo $empresa->razonsocial?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>

<div class="form-actions">
<?php echo Menu::menuLetras($action_name);?>
</div>
<div id="ver_resultado"></div>
<div class="form-actions">
<?php echo Sp::imprimir('Letras semanal - ','P',array("W"=>1,"P"=>1,"EX"=>1));?> 
</div>
<div class="card-body">
<?php echo Form::open($module_name.'/letrassalidas/pagar','POST');?>
<table width="99%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">
<caption>Letras para Protestar</caption>
  <tr>
  	<th width="17" align="left">Nº</th>
    <th width="199" align="left">Proveedor</th>
    <th width="96" align="left">Número Doc.</th>
    <th width="95" align="left">Numero unico</th>
	<th width="109" align="left">F. Emision</th>
    <th width="171" align="left">F. Vto</th>
    <th width="90" align="left">Banco</th>
    <th width="77" align="right">Total</th>
    <th width="59" align="right">Acciones</th>
  </tr>
<?php $number=0;
foreach($letras as $item){ 
$simbolo="S/. ";

switch ($item->getTessalidas()->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

$number++;?>
  <tr id="<?php echo $item->id?>">
  	<td height="20" align="left"><?php echo $number?></td>
  	<td height="20" align="left"><?php echo $item->getTessalidas()->getTesdatos()->razonsocial?></td>
    <td align="left"><?php 
	$a=$item->numerodeletra;	
	$b=strlen($a);
	if($b>=6){$a=substr($a, 0, -2);}
	if(!empty($item->nrenovacion))$a.=$item->nrenovacion; else $a.="00";
	echo $a?></td>
    <td align="left"><?php echo $item->numerounico?></td>
	<td align="left"><?php echo Sp::formatFecha('%d / %m / %Y',$item->getTessalidas()->femision)?><?php //echo $item->getTesingresos()->femision?></td>
		<?php //echo Sp::formatFecha('%d / %m / %Y',$femision)?>
    <td align="left"><span style="color:#F00"> <?php echo Sp::formatFecha('%d / %m / %Y',$item->getTessalidas()->fvencimiento)?> Hace <?php echo Sp::Ndias(date("Y-m-d"),$item->getTessalidas()->fvencimiento)?> dias </span></td>
    <td align="left"><?php echo $item->banco.' ('.$item->estadoletras.')'?></td>
    <td align="right"><?php if($item->getTessalidas()->totalconigv!='NaN.00' && !empty($item->getTessalidas()->totalconigv))echo $simbolo.number_format($item->getTessalidas()->totalconigv,2,'.','');else echo('S/ 00.00')?></td>
  	
   <td align="right">
	<?php if($item->estadoletras=='PROTESTADA'){ echo Html::img("figuras/protestar_i.png",'Editar','style="width: 30px;margin-left:1px;margin-right:1px;"');}else{echo Html::linkAction('protestar/'.$item->id.'/',Html::img("figuras/protestar.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Haga Clik para Protestar la Letra"','');}?>
    
	<?php echo Html::linkAction('pagadobanco/'.$item->id.'/'.$action_name,Html::img("figuras/pagar.png",'Editar','style="width: 30px;margin-left:1px;margin-right:1px;"'),'title="Clic !, si el Cliente Canceló la LETRA !"','')?>
   
    <label class="checkbox" style="float:left; width:90px;">
          <input type="checkbox" name="itemSelect[]" value="<?php echo $item->id?>" class="sele"> Seleccionar
        </label>
    </td>
  </tr>
<?php }?>
</table>

  <?php echo Form::hidden('facturas.ids');?>
<?Php echo Form::close();?>
</div>
<script type="text/javascript">
$(document).ready(function(){
	
	$('.sele').click(function(){
		var selectedItems = new Array();
		
		$("input[@name='itemSelect[]']:checked").each(function(){
			selectedItems.push($(this).val());
		});
		$("#facturas_ids").val(selectedItems);
	});
});
</script> 