<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}.rojo{
	color:#FF0000;}
	.verde{
	color:#090;}
</style>
<div class="card">
    <h1>listado del Mes <span><?php echo $empresa->razonsocial?></span></h1>
</div>

<div class="form-actions">
<?php //echo Html::linkAction("cargaringreso/0", 'Nueva '.Session::get('DOC_NOMBRE'),'class="btn btn-primary"') ?>&nbsp;<?php echo Html::linkAction("", 'Volver ','class="btn"') ?>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="form-actions">
<?php echo Sp::imprimir('Letras por Cobrar - ','P');?>
</div>
<div id="ver_resultado"></div>
<div class="card-body">
<table width="90%" align="center" class="table table-bordered table-striped">
  <thead>
  <tr>
  	<th width="26">Nº</th>
    <th width="292">Proveedor</th>
    <th width="56">Nro Doc.</th>
    <th width="93">Nro unico</th>
    <th width="119">F.de Vto</th>
    <th colspan="2">Estado</th>
    <th width="106">Total</th>
  </tr>
  </thead>
<?php $number=0;
$semana=0;
$a=0;
$T_soles=0;
$T_dolares=0;
foreach($obligaciones as $item){ 
$class='';
if($item->fvencimiento<date("Y-m-d"))$class=' class="rojo" ';
if($item->fvencimiento==date("Y-m-d"))$class=' class="verde" ';
$simbolo="S/. ";
$T_letras=$item->Totalporsemana($item->semana,$item->fvencimiento);
$number++;?>
<?php 
$b=$item->semana;
if($a!=$b){

$number=1;
$T_soles=0;
$T_dolares=0;
?>
<thead>
<tr id="<?php echo $item->id?>">
  	<td height="20" colspan="8"><h4>Semana Nº <?php echo $item->semana?></h4></td>
</tr>
</thead>
<?php 
}
$a=$item->semana;
switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. ';$T_soles=$T_soles+$item->totalconigv; break;
	case 2: $simbolo='$. ';$T_dolares=$T_dolares+$item->totalconigv;break;
	case 4: $simbolo='S/. ';$T_soles=$T_soles+$item->totalconigv; break;
	case 5: $simbolo='$. ';$T_dolares=$T_dolares+$item->totalconigv;break;
	case 0: $simbolo='S/. ';$T_soles=$T_soles+$item->totalconigv; break;
}
?>
<tbody>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $number?></td>
  	<td height="20"><?php echo $item->getTesdatos()->razonsocial?></td>
    <td><?php echo $item->getTesdocumentos()->abr;?> <?php if(!empty($item->serie))echo $item->serie.'-';?><?php echo $item->numero?></td>
    <td><?php echo $item->numerounico?></td>
    <td<?php echo $class?>><?php echo Sp::formatFecha('%d/%m/%Y',$item->fvencimiento)?></td>
    <td colspan="2"><?php echo $item->estadoingreso?></td>
    <td><?php if($item->totalconigv!='NaN.00' && !empty($item->totalconigv))echo $simbolo.number_format($item->totalconigv,2,'.','');else echo('S/ 00.00')?><br /><?php //echo $number."==".$T_letras ?></td>
  </tr>
  </tbody>
  <?Php if($number==$T_letras){?>
  <tr>
  <td colspan="2">Total de la semana <?php echo $item->semana?></td>
  <td colspan="3">Total en S/.<?php echo number_format($T_soles,2,'.',' ')?></td>
  <td colspan="3">Total en $/.<?php echo number_format($T_dolares,2,'.',' ')?></td>
  </tr>
  <tr>
  <td colspan="8">&nbsp;</td>
  </tr>
  <?php }?>
<?php 
	}?>
</table>
</div>