<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>
<div class="card">
    <h1><em>Editar Letra</em><span><?php echo $empresa->razonsocial?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>
<div class="form-actions">
<?php //echo Menu::menuLetras($action_name);?>
</div>
<?php echo Form::open(NULL,'POST','class="form-horizontal"')?>
<?php 
echo Form::hidden('salidas.id');
echo Form::hidden('salidas.tesdocumentos_id');
echo Form::hidden('salidas.tesdatos_id');
echo Form::hidden('salidas.tesmonedas_id');
echo Form::hidden('salidas.aclusuarios_id');
echo Form::hidden('salidas.userid','',Auth::get('id'));
echo Form::hidden('letras.id');
echo Form::hidden('letras.tessalidasinternas_id');
?>
  <div class="control-group">
    <label class="control-label" for="salida_serie">Fecha de vencimiento:</label>
    <div class="controls">
      <?php echo Calendar::selector('salidas.fvencimiento');//finiciotraslado?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="salida_serie">Monto:</label>
    <div class="controls">
      <?php echo Form::text('letras.monto','size="10" class="qty"');?>
    </div>
  </div>
   
  <div class="control-group">
    <label class="control-label" for="salida_tesmonedas_id">Moneda:</label>
    <div class="controls">
      <?php echo Form::dbSelect('salidas.tesmonedas_id','simbolo,nombre',array("tesmonedas",'find','conditions: aclempresas_id='.Session::get('EMPRESAS_ID')));?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="CL">Cliente</label>
    <div class="controls">
      <?php echo $salidas->getTesdatos()->razonsocial;?>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
       <button type="submit" class="btn btn-xs btn-primary">Modificar</button> <?php echo Html::linkAction('','Cancelar','class="btn btn-xs" title="Editar  !"','')?>
    </div>
  </div>
<?php echo Form::close();?>
</div>