<?php
$code='';
$simbolo="S/. ";
$igv=18;

switch ($monedas)
{
	case 1: $simbolo='S/. ';$moneda_letras='SOLES'; break;
	case 2: $simbolo='$. ';$moneda_letras='DOLARES';  break;
	case 4: $simbolo='S/. ';$moneda_letras='SOLES';  break;
	case 5: $simbolo='$. ';$moneda_letras='DOLARES';  break;
	case 0: $simbolo='S/. ';$moneda_letras='SOLES';  break;
}


View::content();
echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<script type="text/javascript">	
	
/*
CONVERTIR NUMERO SEN LETRAS
*/
// Función modulo, regresa el residuo de una división 
function mod(dividendo , divisor) 
{ 
  resDiv = dividendo / divisor ;  
  parteEnt = Math.floor(resDiv);            // Obtiene la parte Entera de resDiv 
  parteFrac = resDiv - parteEnt ;      // Obtiene la parte Fraccionaria de la división
  modulo = Math.round(parteFrac * divisor);  // Regresa la parte fraccionaria * la división (modulo) 
  return modulo; 
} // Fin de función mod

// Función ObtenerParteEntDiv, regresa la parte entera de una división
function ObtenerParteEntDiv(dividendo , divisor) 
{ 
  resDiv = dividendo / divisor ;  
  parteEntDiv = Math.floor(resDiv); 
  return parteEntDiv; 
} // Fin de función ObtenerParteEntDiv

// function fraction_part, regresa la parte Fraccionaria de una cantidad
function fraction_part(dividendo , divisor) 
{ 
  resDiv = dividendo / divisor ;  
  f_part = Math.floor(resDiv); 
  return f_part; 
} 
function string_literal_conversion(number) 
{   
   centenas = ObtenerParteEntDiv(number, 100); 
   
   number = mod(number, 100); 

   decenas = ObtenerParteEntDiv(number, 10); 
   number = mod(number, 10); 

   unidades = ObtenerParteEntDiv(number, 1); 
   number = mod(number, 1);  
   string_hundreds="";
   string_tens="";
   string_units="";

   if(centenas == 1){
      string_hundreds = "ciento ";
   } 
   
   
   if(centenas == 2){
      string_hundreds = "doscientos ";
   }
    
   if(centenas == 3){
      string_hundreds = "trescientos ";
   } 
   
   if(centenas == 4){
      string_hundreds = "cuatrocientos ";
   } 
   
   if(centenas == 5){
      string_hundreds = "quinientos ";
   } 
   
   if(centenas == 6){
      string_hundreds = "seiscientos ";
   } 
   
   if(centenas == 7){
      string_hundreds = "setecientos ";
   } 
   
   if(centenas == 8){
      string_hundreds = "ochocientos ";
   } 
   
   if(centenas == 9){
      string_hundreds = "novecientos ";
   } 
   
 
   if(decenas == 1){
       if(unidades == 1){
         string_tens = "once";
      }
      
      if(unidades == 2){
         string_tens = "doce";
      }
      
      if(unidades == 3){
         string_tens = "trece";
      }
      
      if(unidades == 4){
         string_tens = "catorce";
      }
      
      if(unidades == 5){
         string_tens = "quince";
      }
      
      if(unidades == 6){
         string_tens = "dieciseis";
      }
      
      if(unidades == 7){
         string_tens = "diecisiete";
      }
      
      if(unidades == 8){
         string_tens = "dieciocho";
      }
      
      if(unidades == 9){
         string_tens = "diecinueve";
      }
   } 
   
   if(decenas == 2){
      string_tens = "veinti";
   }
   if(decenas == 3){
      string_tens = "treinta";
   }
   if(decenas == 4){
      string_tens = "cuarenta";
   }
   if(decenas == 5){
      string_tens = "cincuenta";
   }
   if(decenas == 6){
      string_tens = "sesenta";
   }
   if(decenas == 7){
      string_tens = "setenta";
   }
   if(decenas == 8){
      string_tens = "ochenta";
   }
   if(decenas == 9){
      string_tens = "noventa";
   }

   if (decenas == 1) 
   { 
      string_units="";   
   } 
   else 
   { 
      if(unidades == 1){
         string_units = "un";
      }
      if(unidades == 2){
         string_units = "dos";
      }
      if(unidades == 3){
         string_units = "tres";
      }
      if(unidades == 4){
         string_units = "cuatro";
      }
      if(unidades == 5){
         string_units = "cinco";
      }
      if(unidades == 6){
         string_units = "seis";
      }
      if(unidades == 7){
         string_units = "siete";
      }
      if(unidades == 8){
         string_units = "ocho";
      }
      if(unidades == 9){
         string_units = "nueve";
      }
       
   } 

if (centenas == 1 && decenas == 0 && unidades == 0) 
{ 
   string_hundreds = "cien " ; 
}  
if (decenas == 1 && unidades ==0) 
{ 
   string_tens = "diez " ; 
} 

if (decenas == 2 && unidades ==0) 
{ 
  string_tens = "veinte " ; 
} 
if (decenas >=3 && unidades >=1) 
{ 
   string_tens = string_tens+" y "; 
} 
final_string = string_hundreds+string_tens+string_units;


return final_string ; 

} 

function covertirNumLetras(number)
{
   
  var millions_final_string='';
  var thousands_final_string='';
  //number = number_format (number, 2);
   //alert(number)
   number1=number.toString(); 
   //settype (number, "integer");
   cent = number1.split(".");   
   centavos = cent[1];
   
   
   if (centavos == 0 || centavos == undefined){
   centavos = "00";}

   if (number == 0 || number == "") 
   { // if amount = 0, then forget all about conversions, 
      centenas_final_string=" cero "; // amount is zero (cero). handle it externally, to 
      // function breakdown 
  } 
   else 
   { 
   
     millions  = ObtenerParteEntDiv(number, 1000000); // first, send the millions to the string 
      number = mod(number, 1000000);           // conversion function 
      
     if (millions != 0)
      {                      
      // This condition handles the plural case 

         if (millions == 1) 
         {              // if only 1, use 'millon' (million). if 
            descriptor= " millon ";  // > than 1, use 'millones' (millions) as 
            } 
         else 
         {                           // a descriptor for this triad. 
              descriptor = " millones "; 
            } 
      } 
      else 
      {    
         descriptor = " ";                 // if 0 million then use no descriptor. 
      } 
      millions_final_string = string_literal_conversion(millions)+descriptor; 
          
      
      thousands = ObtenerParteEntDiv(number, 1000);  // now, send the thousands to the string 
        number = mod(number, 1000);            // conversion function. 
      //print "Th:".thousands;
     if (thousands != 1) 
      {                   // This condition eliminates the descriptor 
         thousands_final_string =string_literal_conversion(thousands) + " mil "; 
       //  descriptor = " mil ";          // if there are no thousands on the amount 
      } 
      if (thousands == 1)
      {
         thousands_final_string = " mil "; 
     }
      if (thousands < 1) 
      { 
         thousands_final_string = " "; 
      } 
  
      // this will handle numbers between 1 and 999 which 
      // need no descriptor whatsoever. 

     centenas  = number;                     
      centenas_final_string = string_literal_conversion(centenas) ; 
      
   } 
   cad = millions_final_string+thousands_final_string+centenas_final_string; 
   
   /* Convierte la cadena a Mayúsculas*/
   cad = cad.toUpperCase();       

   if (centavos.length>2)
   {   
      if(centavos.substring(2,3)>= 5){
         centavos = centavos.substring(0,1)+(parseInt(centavos.substring(1,2))+1).toString();
      }   else{
        centavos = centavos.substring(0,2);
       }
   }

   /* Concatena a los centavos la cadena "/100" */
   if (centavos.length==1)
   {
      centavos = centavos+"0";
   }
   centavos = centavos+ "/100"; 


   /* Asigna el tipo de moneda, para 1 = PESO, para distinto de 1 = PESOS*/
   if (number == 1)
   {
      moneda = " <?php echo $monedas_nombre?> ";  
   }
   else
   {
      moneda = " <?php echo $monedas_nombre?>  ";  
   }
   /* Regresa el número en cadena entre paréntesis y con tipo de moneda y la fase M.N.*/
  return ('SON: '+cad+' Y '+centavos+" centimos "+moneda);
}
/*INICIO 09*/
<?php $code.='
$(document).ready(function()
		{	
			bind();  
			$("input").click(function(){
    		$(this).select();
			});';
$code.='$("#paid").blur(function(){update_balance();});
		$("#paid_total").blur(function(){update_balance();});';
   /*
  Para grabar el tr - id buscando la clase :save y mandando todo el contenido del tr:
  */
$code.='$("#addrow").click(function()
		{
			var ID = $(".item-row:last").attr("id");
			//alert(ID);
			grabarDetalle(ID);
			var IDnew=Number(ID)+Number(1);
			var tr=\'';
			$code.='<tr id="\'+IDnew+\'" class="item-row">';
			$code.='<td><div class="delete-wpr"><input id="codigo-\'+IDnew+\'" name="codigo-\'+IDnew+\'" type="text" readonly="readonly" size="10"><a id="del-\'+IDnew+\'" class="delete" href="javascript:;" title="Elimar registro" data-id="0" style="">X</a></div></td>';
			$code.='<td class="item-name"><input id="productos_id-\'+IDnew+\'" name="productos_id-\'+IDnew+\'" type="hidden" class="productos_id" readonly="readonly"><span id="ver-name\'+IDnew+\'" style="display:none;"><input id="productoname-\'+IDnew+\'" name="productoname-\'+IDnew+\'" type="text" value="" readonly="readonly"></span><span id="ver\'+IDnew+\'" class="ver"><input id="producto\'+IDnew+\'" name="producto\'+IDnew+\'" type="text" class="producto" placeholder="Producto" size="30" readonly="readonly"></span></td>';
			$code.='<td><input id="tesunidadesmedidas\'+IDnew+\'" name="tesunidadesmedidas\'+IDnew+\'" type="text" value=""><input class="unidad" id="tesunidadesmedidas_id-\'+IDnew+\'" name="tesunidadesmedidas_id-\'+IDnew+\'" type="hidden" value=""></td>';
			$code.='<td><input id="tescolores\'+IDnew+\'" name="tescolores\'+IDnew+\'" type="text" value=""><input class="color" id="tescolores_id-\'+IDnew+\'" name="tescolores_id-\'+IDnew+\'" type="hidden" value=""></td>';
			$code.='<td> <input id="lote\'+IDnew+\'" class="save" name="lote\'+IDnew+\'" type="text" value="" size="10"/></td>';
			$code.='<td> <input data-id="0" class="save cajas" id="empaque\'+IDnew+\'" name="empaque\'+IDnew+\'" type="text" value="" size="10"/> <div class="flotante" id="cajas-\'+IDnew+\'"></div></td>';
			$code.='<td> <input id="bobinas\'+IDnew+\'" name="bobinas\'+IDnew+\'" type="text" value="" size="10"/></td>';
			$code.='<td> <input id="pesoneto\'+IDnew+\'" class="save" name="pesoneto\'+IDnew+\'" type="text" value="" size="10"/></td>';
			$code.='<td> <input id="pesobruto\'+IDnew+\'" class="save" name="pesobruto\'+IDnew+\'" type="text" value="" size="10"/></td>';
			$code.='<td><span class="simbolo"><?php echo $simbolo;?></span><input id="precio-\'+IDnew+\'" type="text"  size="10" class="save"/></td>';
			$code.='</tr>';
			
			$code.='\';
    		$(".item-row:last").after(tr);
    		if ($(".delete").length > 1) $(".delete").show();else $(".delete").hide();
			bind();
  		});';
/* ------- FIN contenido del tr: ------- */
$code.='$(".delete").live("click",function()
		{
		  var row =$(this).parents(".item-row")
		  var id=row.find(\'.delete\').attr(\'data-id\');
		  EliminarDetalle(id);
			$(this).parents(\'.item-row\').remove();
		  	update_total();
			if ($(".delete").length < 2) $(".delete").hide();
	    });';
/**/
  
  		//$("#pre_descripcion").blur(function(){$("#observacion").val($(this).val());GRABAR();});

$code.='$("#paid").blur(function(){$("#descuento").val($(this).val());GRABAR();});';
$code.='$("#glosa").change(function(){GRABAR();});';
$code.='$("#femision").change(function(){GRABAR();});'; 
$code.='$("#numero").blur(function(){GRABAR();});';
$code.='$(".grabar_form").blur(function(){GRABAR();});';
$code.='$("#monedas").change(function()
		{
			GRABAR();
			var op = $("#monedas option:selected").val();
			if(op==1)
			{
			$(".simbolo").html("S/. ");
			}
			if(op==2)
			{
			$(".simbolo").html("$. ");
			}
		});';

$code.='});';
/*fin de Documento ready*/
$code.='function roundNumber(number,decimals)
		{
  			var newString;// The new rounded number
  			decimals = Number(decimals);
  			if (decimals < 1) 
			{
    			newString = (Math.round(number)).toString();
  			}else
			{
    			var numString = number.toString();
    			if (numString.lastIndexOf(".") == -1)
				{// If there is no decimal point
      				numString += ".";// give it one at the end
    			}
    			var cutoff = numString.lastIndexOf(".") + decimals;// The point at which to truncate the number
    			var d1 = Number(numString.substring(cutoff,cutoff+1));// The value of the last decimal place that we\'ll end up with
    			var d2 = Number(numString.substring(cutoff+1,cutoff+2));// The next decimal, after the last one we want
    			if (d2 >= 5)
				{// Do we need to round up at all? If not, the string will just be truncated
      				if (d1 == 9 && cutoff > 0)
					{// If the last digit is 9, find a new cutoff point
        				while (cutoff > 0 && (d1 == 9 || isNaN(d1))) {
          				if (d1 != ".")
						{
            				cutoff -= 1;
            				d1 = Number(numString.substring(cutoff,cutoff+1));
         				} else {
            				cutoff -= 1;
          				}
        			}
      			}
      			d1 += 1;
    		} 
    		if (d1 == 10)
			{
      			numString = numString.substring(0, numString.lastIndexOf("."));
      			var roundedNum = Number(numString) + 1;
      			newString = roundedNum.toString() + \'.\';
    		}else
			{
				newString = numString.substring(0,cutoff) + d1.toString();
		    }
  		}
  		if (newString.lastIndexOf(".") == -1) 
		{// Do this again, to the new string
    		newString += ".";
  		}
  		var decs = (newString.substring(newString.lastIndexOf(".")+1)).length;
  		for(var i=0;i<decimals-decs;i++) newString += "0";
  		//var newNumber = Number(newString);// make it a number if you like
		return newString; // Output the result to the form field (change for your purposes)
		}';
/*FIN DE REDONDEO*/
$code.='function update_total()
		{
  			var total = 0.00;
  			$(\'.price\').each(function(i)
  			{
    			price = $(this).html();
    			alert (\'precio: \'+price+\' ->>>>\'+i);
				if(!isNaN(price)) total =parseFloat(total)+parseFloat(price);
  				 alert (\'el total es : \'+total+\' ->>>>\');
   			});
			total = roundNumber(total,2);
			//alert (\'el total es : \'+total+\' ->>>>\');
			var igv= total*'.$igv.';
			var totalconigv=(parseFloat(total)+parseFloat(igv));
			//alert(\'el igv es: \'+igv);
			$("#paid").val(igv.toFixed(2));
			$("#igv").val(igv.toFixed(2));
			$("#totalconigv").val(totalconigv);
			$(\'#subtotal\').html(total);
			$(\'#paid_total\').val(total);
			update_balance();
		}';

$code.='function update_balance()
{
 // alert ($("#paid").val());
  var igv= parseFloat( $("#paid_total").val())*'.$igv.';
	var totalconigv=(parseFloat($("#paid_total").val())+parseFloat(igv));
	var due=roundNumber(totalconigv,2);
	var IGV=roundNumber(igv,2);
	$("#paid").val(IGV);
	$("#igv").val(IGV);
	$("#totalconigv").val(due);
  $("#totalconigv").val(due);
  //alert (\'===: \'+due);
	$(\'.due\').html(due);
	GRABAR();
}';

$code.='function update_price(ID)
{
  //var ID = $(this).attr(\'id\');
  var I=ID.split(\'-\');
  alert (\'id del tr que se manda a grabar->>>\'+ID);
  var row = $(this).parents(\'.item-row\');
  //alert(row.find(\'.cost\').val());
  //var price = row.find(\'.cost\').val() * row.find(\'.qty\').val();
  //alert($("#precio-"+I[1]).val()+\'-----------------\'+$("#cantidad-"+I[1]).val());
  var price = (parseFloat($("#precio-"+I[1]).val())*parseFloat($("#cantidad-"+I[1]).val()));
  price = roundNumber(price,2);
  //alert(price);
  isNaN(price) ? $("#total-"+I[1]).html("N/A") : $("#total-"+I[1]).html(price);
  update_total();
  grabarDetalle(I[1]);
}';
$code.='
function bind(){
  if ($(".delete").length > 1) $(".delete").show();else $(".delete").hide();
  $(".cost").blur(function(){update_price();});
  $(".qty").blur(function(){update_price();});
  $(".producto").click(buscarProducto());
  $(".unidad").click(buscarUnidad());
  $(".color").click(buscarColor());
  $(".caja").blur(Mostrar());
  $(".save").blur(function(){Detalle($(this).attr("id"));});
}';

/*BUSCAR PRODUCTO*/
	/*  */		
$code.='function buscarProducto()
{
	var row = $(this).parents(\'.item-row:last\');
	var ID = $(\'.item-row:last\').attr(\'id\');
	$("#productos_id-"+ID).val();
	if($("#productos_id-"+ID).val()!=\'\'){
	$("#producto"+ID).tokenInput("/'.$module_name.'/ingresos/producto/", 
		{
		tokenLimit: 1,
		minChars: 1,
		
		prePopulate: [ 
		             {id: $("#productos_id-"+ID).val(), name: ""+$("#producto"+ID).val()+""},
					],
		onAdd: function (item) {
		   var VAL=item.id;
		   var row =$(this).parents(\'.item-row\')
		   row.find(\'.productos_id\').val(VAL[\'id\']);
		   row.find(\'.pro_descripcion\').val(VAL[\'detalle\']);
		   row.find(\'.cost\').val(VAL[\'precio\']);
		   row.find(\'.delete\').attr("data-id",0);
		   $(\'#codigo-\'+ID).val(VAL[\'codigo\']);
		   $(\'#ver\'+ID).hide();
		   $(\'#ver-name\'+ID).show();
		   $(\'#productoname-\'+ID).val(VAL[\'detalle\']);
		},
		onDelete: function (item) {
			var row =$(this).parents(\'.item-row\')
		   row.find(\'.productos_id\').val(\'\');
		   row.find(\'.pro_descripcion\').val(\'\');
		   row.find(\'.cost\').val(\'\');
		   row.find(\'.qty\').val(\'\');
		   var id=row.find(\'.delete\').attr(\'data-id\');
		  	EliminarDetalle(id);
		}
	});
	}else
	{
		$("#producto"+ID).tokenInput("/'.$module_name.'/ingresos/producto/", 
		{			
		tokenLimit: 1,
		minChars: 1,
		onAdd: function (item) {
		   var VAL=item.id;
		   var row =$(this).parents(\'.item-row\')
		   row.find(\'.productos_id\').val(VAL[\'id\']);
		   row.find(\'.pro_descripcion\').val(VAL[\'detalle\']);
		   row.find(\'.cost\').val(VAL[\'precio\']);
		   row.find(\'.delete\').attr("data-id",0);
		   $(\'#codigo-\'+ID).val(VAL[\'codigo\']);
		   $(\'#ver\'+ID).hide();
		   $(\'#ver-name\'+ID).show();
		   $(\'#productoname-\'+ID).val(VAL[\'detalle\']);
		},
		onDelete: function (item) {
			var row =$(this).parents(\'.item-row\')
		   row.find(\'.productos_id\').val(\'\');
		   row.find(\'.pro_descripcion\').val(\'\');
		   row.find(\'.cost\').val(\'\');
		   row.find(\'.qty\').val(\'\');
		   var id=row.find(\'.delete\').attr(\'data-id\');
		  	EliminarDetalle(id);
		}
	});
	}
}';
/*BUSCAR PRODUCTO*/
	/*  */		
$code.='function buscarUnidad()
{
	var row = $(this).parents(\'.item-row:last\');
	var ID = $(\'.item-row:last\').attr(\'id\');
	//alert($("#tesunidadesmedidas"+ID).val());
	if($("#tesunidadesmedidas"+ID).val()!=\'\'){
	$("#tesunidadesmedidas"+ID).tokenInput("/'.$module_name.'/ingresos/medidas/", 
		{			
		tokenLimit: 1,
		minChars: 1,
		prePopulate: [ 
		             {id: $("#tesunidadesmedidas_id-"+ID).val(), name: ""+$("#tesunidadesmedidas"+ID).val()+""},
					],
		onAdd: function (item) {
		   var VAL=item.id;
		   $("#tesunidadesmedidas_id-"+ID).val(item.id);
		   $("#tesunidadesmedidas"+ID).val(item.name);
		   grabarDetalle(ID);
		},
		onDelete: function (item) {
		  $("#tesunidadesmedidas_id-"+ID).val(\'\');
		   $("#tesunidadesmedidas"+ID).val(\'\');
		}
	});
	}else
	{
	$("#tesunidadesmedidas"+ID).tokenInput("/'.$module_name.'/ingresos/medidas/", 
		{
			
		tokenLimit: 1,
		minChars: 1,
		onAdd: function (item) {
		   var VAL=item.id;
		   $("#tesunidadesmedidas_id-"+ID).val(item.id);
		   $("#tesunidadesmedidas"+ID).val(item.name);
		   grabarDetalle(ID);
		},
		onDelete: function (item) {
		  $("#tesunidadesmedidas_id-"+ID).val(\'\');
		   $("#tesunidadesmedidas"+ID).val(\'\');
		}
	});
	}
}';

/*envio dew Formulario PROFORMAS*/
$code.='function GRABAR()
{
     if($("#cliente_id").val()){
	 $.ajax({
            type:"POST",
            url:"/'.$module_name.'/ingresos/grabar/1",
            data:$("#inventarios").serialize(),
            beforeSend:function(){
              $("#loading").show();
          	},
            success:function(response){
                $("#loading").hide();
				$("#id").val(response);
				//alert(response);
            }
 
          	});
	 }else
	 {
		 return FALSE;
	}
 
      };';

/*GRABAR DETALLE DE PROFORMAS*/

$code.='function grabarDetalle(tr_id) 
{
  //alert(tr_id);
  var producto_id=$(\'#productos_id-\'+tr_id).val();
  var pro_descripcion=$(\'#pro_descripcion-\'+tr_id).val();
  var costo=isNaN($(\'#precio-\'+tr_id).val())? 0 : $(\'#precio-\'+tr_id).val();
  //var cantidad=isNaN($(\'#cantidad-\'+tr_id).val())? 0 : $(\'#cantidad-\'+tr_id).val();
  var lote=$(\'#lote\'+tr_id).val();
  var empaque=isNaN($(\'#empaque\'+tr_id).val())? 0 : $(\'#empaque\'+tr_id).val();
  var bobinas=isNaN($(\'#bobinas\'+tr_id).val())? 0 : $(\'#bobinas\'+tr_id).val();
  var pesoneto=isNaN($(\'#pesoneto\'+tr_id).val())? 0 : $(\'#pesoneto\'+tr_id).val();
  var pesobruto=isNaN($(\'#pesobruto\'+tr_id).val())? 0 : $(\'#pesobruto\'+tr_id).val();
  var price = isNaN($(\'#total-\'+tr_id).html())? 0 : $(\'#total-\'+tr_id).html();
  var id_detalle=$(\'#del-\'+tr_id).attr("data-id");
  var unidadmedida_id=$(\'#tesunidadesmedidas_id-\'+tr_id).val();
  var colores_id=$(\'#tescolores_id-\'+tr_id).val();
  var total=isNaN(price)? 0 : price;
  var cantidad=pesoneto;
 //alert(\'ID del PRODUCTO\'+producto_id);
 //alert(\'id del detalle es 0 cuando es nuevo--->\'+id_detalle);
// alert(\'id del tr que se graba-->\'+tr_id);
  
  if(producto_id!=\'\' && unidadmedida_id!=\'\')
  {
	  var dataString =\'id_detalle=\'+id_detalle+\'&tesunidadesmedidas_id=\'+ unidadmedida_id+\'&productos_id=\'+ producto_id+\'&pro_descripcion=\'+pro_descripcion+\'&cantidad=\'+cantidad+\'&precio=\'+costo+\'&total=\'+total+\'&lote=\'+lote+\'&empaque=\'+empaque+\'&bobinas=\'+bobinas+\'&pesoneto=\'+pesoneto+\'&pesobruto=\'+pesobruto+\'&colores_id=\'+ colores_id+\'&precio=\'+price;
	 //alert(dataString);
	  $.ajax({
            type:"POST",
            url:"/'.$module_name.'/ingresos/grabarDetalle/1",
            data:dataString,
            beforeSend:function(){
              $("#loading").show();
            },
            success:function(response){
                $("#loading").hide();
				//alert(\'id del detalle grabado\'+response);
				$(\'#del-\'+tr_id).attr("data-id", response);
				$(\'#empaque\'+tr_id).attr("data-id", response);
            }
 
         });
  }
  
}';
$code.='function EliminarDetalle(id)
{
	if(id!=0){
	$.ajax({
            type:"POST",
            url:"/'.$module_name.'/ingresos/eliminarDetalle/"+id,
            beforeSend:function(){
              $("#loading").show();
            },
            success:function(response){
				alert(\'Se elimino de la base de dato\');
            }
 
         });
	}else
	{
		return false;
	}
}';


$code.='function Detalle(id){
	  if(id){
	  var idletras=id;
	  //alert(id);
	  var ID=idletras.split("");
	  var n=idletras.length;
	  grabarDetalle(ID[n-1]);
	  }else
	  {
		  return FALSE;
	  }
}';
/*cajas*/
$code.='function Mostrar(){
	$(".cajas").blur(function(e){
	  //e.preventDefault();
	  var idletras=$(this).attr("id");
	  //alert(idletras);
	  var ID=idletras.split("");
	  var n=idletras.length;
	  grabarDetalle(ID[n-1]);
	  var numerocajas=$(this).val();
	  var id_detalle=$(this).attr("data-id");
	  alert(id_detalle);
	  var dataString ="id_detalle="+id_detalle;
	  //alert(numerocajas);
	  if(numerocajas!="")
	  {
	  $.ajax({
            type:"POST",
            url:"/'.$module_name.'/cajas/crear/"+numerocajas+"/"+ID[n-1],
            data:dataString,
            beforeSend:function(){
              $("#loading").show();
            },
            success:function(response){
                $("#loading").hide();
				$("#cajas-"+ID[n-1]).html(response);
				$("#cajas-"+ID[n-1]).show();
				$("#cajas-"+ID[n-1]).dialog({
					title: "Ingrese las Etiquetas de las Cajas",
					width: 600,
					height: 460,
					modal: true,
					buttons: 
					{
					Ok: function() {
					$( this ).dialog( "close" );
					}
					}
				});
				
            }
 
         });
	  }
	});
}';
/*Buscar COLOR*/

$code.='function buscarColor()
{
	var row = $(this).parents(".item-row:last");
	var ID = $(".item-row:last").attr("id");
	//alert($("#tesunidadesmedidas"+ID).val());
	if($("#tescolores"+ID).val()!=""){
	$("#tescolores"+ID).tokenInput("/'.$module_name.'/ingresos/colores/", 
		{
			
		tokenLimit: 1,
		minChars: 1,
		prePopulate: [ 
		             {id: $("#tescolores_id-"+ID).val(), name: ""+$("#tescolores"+ID).val()+""},
					],
		onAdd: function (item) {
		   var VAL=item.id;
		   $("#tescolores_id-"+ID).val(item.id);
		   $("#tescolores"+ID).val(item.name);
		   grabarDetalle(ID);
		},
		onDelete: function (item) {
		  $("#tescolores_id-"+ID).val("");
		   $("#tescolores"+ID).val("");
		}
	});
	}else
	{
	$("#tescolores"+ID).tokenInput("/'.$module_name.'/ingresos/colores/", 
		{
			
		tokenLimit: 1,
		minChars: 1,
		onAdd: function (item) {
		   var VAL=item.id;
		   $("#tescolores_id-"+ID).val(item.id);
		   $("#tescolores"+ID).val(item.name);
		   grabarDetalle(ID);
		},
		onDelete: function (item) {
		  $("#tescolores_id-"+ID).val("");
		   $("#tescolores"+ID).val("");
		}
	});
	}	
}';
echo $code;
?>
/*FIN*/
</script>
<div class="card">
<h1>Ingreso de Hilo a Almacen <?php //echo "id--->".Session::get('INVENTARIO_ID')?></h1>
</div>

<div class="card-body"> 
<?php 
/* ID DE LOS INGRESOS ES INVENTARIO*/
echo Form::open('','post','id="inventarios"');?>
    <?php echo Form::hidden('id')?>
    <?php echo Form::hidden('totalenletras')?>
    <?php echo Form::hidden('estadoingreso','','INGRESO')?>
    
<table>
     <tr>
     	<th width="56" align="left" valign="top" class="meta-head">Moneda:</th>
        <td width="302" align="left" valign="top"><?php echo Form::dbSelect('monedas','nombre',array('tesmonedas','find','aclempresas_id='.Session::get("EMPRESAS_ID")))?><?php echo Form::hidden('cliente_id','',2600)?></td>

       </tr>
      <tr>
      	<th align="left" valign="top"><span class="meta-head">Serie-Número:</span></th>
      	<td align="left" valign="top"><?php echo Form::text('serie','size="4"','P001')?>-<?php echo Form::text('numero','size="5"');?></td>

      	</tr>
      <tr>
        <th align="left" valign="top">F.de Emision:</th>
        <td align="left" valign="top"><?php echo Calendar::selector('femision');?></td>
      </tr>
      <tr>
      	<th align="left" class="meta-head">F. de Traslado(Guias):</th>
      	<td align="left"><?php echo Calendar::selector('finiciotraslado');?></td>
      	</tr>
      <tr>
        <th width="116" align="left" class="meta-head">Fact.Referencia(Guias):</th>
        <td width="333" align="left"><?php echo Form::text('numerofactura','size="15" class="grabar_form"')?></td>
      </tr>
    </table>
    
    <div><label><strong>Glosa:</strong></label>
    
  <?php 
  $placeholder='Glosa, Comentario u Observacion del Documento!';
  if(Session::get('DOC_CODIGO')=='09')
  {
	  $placeholder='Glosa, Comentario u Observacion del Documento!';
	  //$placeholder="HILOS: 75/34 POL PA. PESM.TEXT.CRUDO, ANCHO: 1.56 m, #HILOS: 12800, METROS: 1500, TOTAL: 325.20, PLEGADORES: 11 Y 113";
  }
  if(Session::get('DOC_CODIGO')=='09' || Session::get('DOC_CODIGO')=='01')echo Form::textArea('glosa','placeholder="'.$placeholder.'"');?></div>
	 <?php echo Form::hidden('totalconigv');?>
            <?php echo Form::hidden('igv');?>
        <?php echo Form::close();
		echo Session::get('DOC_CODIGO')?>
<table width="102%" class="table table-striped" id="items">
<tr>
		      <th width="7%">Codigo</th>
		      <th width="19%">Producto</th>
		      <th width="11%">Medida</th>
		      <th>Color</th>
              <th width="7%">Lote</th>
		      <th width="7%">C/B</th>
		      <th width="8%">Bobinas</th>
              <th width="8%">P/N</th>
		      <th width="8%">P/B</th>
		      <th width="9%">Precio</th>
		  </tr>
          <?php
			if($DETALLE)
			{
				$n=0;
				$subtotal=0;
				foreach($detalles as $item){
						  $n++;
						  $subtotal=$subtotal+$item->importe;
					  ?>
				  <tr id="<?php echo $n?>" class="item-row">
				   <td>
						  <div class="delete-wpr">
						  <?php echo Form::text('codigo-'.$n,'size="8" readonly="readonly"',$item->getTesproductos()->codigo)?>
						  <a id="del-<?php echo $n?>" class="delete" href="javascript:;" title="Elimar registro" data-id="<?php echo $item->id?>">X</a>
						  </div>
					</td>
					  <td class="item-name">
						  <?php echo Form::hidden('productos_id-'.$n,'class="productos_id" readonly="readonly"',$item->tesproductos_id)?>
						  <span id="ver-name<?php echo $n?>" style="display:none;"><?php echo Form::text('productoname-'.$n,'readonly="readonly"')?></span>
						  <span id="ver<?php echo $n;?>" class="ver"><?php echo Form::text('producto'.$n,'class="producto" placeholder="Producto" size="30" readonly="readonly"',$item->getTesproductos()->nombre)?></span>
					  </td>
					  <td><?php echo Form::hidden('tesunidadesmedidas_id-'.$n,'readonly="readonly"',$item->tesunidadesmedidas_id)?> <?php echo Form::text('tesunidadesmedidas'.$n,'class="unidad" size="10"',$item->getTesunidadesmedidas()->nombre)?></td>
					  <td><?php echo Form::hidden('tescolores_id-'.$n,'readonly="readonly"',$item->tescolores_id)?> <?php echo Form::text('tescolores'.$n,'class="color" size="10"',$item->getTescolores()->nombre)?></td>
					  <td> <?php echo Form::text('lote'.$n,'class="save" size="10"',$item->lote)?></td>
					  <td> <?php echo Form::text('empaque'.$n,'class="save cajas" data-id="'.$item->id.'" size="10"',$item->empaque)?><div class="flotante" id="cajas-<?php echo $n?>"></div></td>
					  <td> <?php echo Form::text('bobinas'.$n,'class="save" size="10"',$item->bobinas)?></td>
					  <td> <?php echo Form::text('pesoneto'.$n,'class="save" size="10"',$item->pesoneto)?></td>
					  <td> <?php echo Form::text('pesobruto'.$n,'class="save" size="10"',$item->pesobruto)?></td>
                      <td><span class="simbolo"><?php echo $simbolo;?></span><input id="precio-<?php echo $n?>" type="text"  size="8" class="save" value="<?php echo $item->preciounitario?>"/></td>
				  </tr>
				  
				  <?php
					  }/*FIN FOREACH*/
					if($n==0)
						{  $n=1; ?>
						  <tr id="1" class="item-row">
							 <td class="item-name">
								  <div class="delete-wpr">
								  <?php echo Form::text('codigo-1','class="productos_id" size="8" readonly="readonly"')?>
								  <a id="del-1" class="delete" href="javascript:;" title="Elimar registro" data-id="0">X</a>
								  </div>
							</td>
							  <td class="item-name">
								 <?php echo Form::hidden('productos_id-1','class="productos_id" readonly="readonly"')?>
								  <span id="ver-name1" style="display:none;"><?php echo Form::text('productoname-1','readonly="readonly"')?></span>
								  <span id="ver1" class="ver"><?php echo Form::text('producto1','class="producto" placeholder="Producto" size="30"')?></span>
							  </td>
							  <td><?php echo Form::hidden('tesunidadesmedidas_id-1')?> <?php echo Form::text('tesunidadesmedidas1','class="unidad"')?></td>
					  <td width="16%"><?php echo Form::hidden('tescolores_id-'.$n,'readonly="readonly"')?> <?php echo Form::text('tescolores'.$n,'class="color" size="10"')?></td>
					  <td> <?php echo Form::text('lote'.$n,'class="save" size="10"')?></td>
					  <td> <?php echo Form::text('empaque'.$n,'data-id="0" class="save cajas" size="10"')?><div class="flotante" id="cajas-<?php echo $n?>"></div></td>
					  <td> <?php echo Form::text('bobinas'.$n,'class="save" size="5" ')?></td>
					  <td> <?php echo Form::text('pesoneto'.$n,'class="save" size="5"')?></td>
					  <td> <?php echo Form::text('pesobruto'.$n,'class="save" size="5"')?></td>
                      <td><span class="simbolo"><?php echo $simbolo;?></span><input id="precio-<?php echo $n?>" type="text"  size="8" class="save"/></td>
							 
						  </tr>
				  <?php
						}?>
				  <?php 
				  }else{
					 $n=1; ?>

				  <tr id="1" class="item-row">
					 <td>
						  <div class="delete-wpr">
						  <?php echo Form::text('codigo-1','class="productos_id" readonly="readonly"')?>
						  <a id="del-1" class="delete" href="javascript:;" title="Elimar registro" data-id="0">X</a>
						  </div>
					</td>
					  <td>
						 <?php echo Form::hidden('productos_id-1','class="productos_id" readonly="readonly"')?>
						  <span id="ver-name1" style="display:none;"><?php echo Form::text('productoname-1','readonly="readonly"')?></span>
						  <span id="ver1" class="ver"><?php echo Form::text('producto1','class="producto" placeholder="Producto" size="30"')?></span>
					  </td>
					  <td><?php echo Form::hidden('tesunidadesmedidas_id-1')?> <?php echo Form::text('tesunidadesmedidas1','class="unidad"')?></td>
					  <td><?php echo Form::hidden('tescolores_id-'.$n,'readonly="readonly"')?> <?php echo Form::text('tescolores'.$n,'class="color" size="10"')?></td>
					  <td> <?php echo Form::text('lote'.$n,'class="save" size="10"')?></td>
					  <td> <?php echo Form::text('empaque'.$n,'data-id="0" size="8" class="save cajas"')?><div class="flotante" id="cajas-<?php echo $n?>"></div></td>
					  <td> <?php echo Form::text('bobinas'.$n,'class="save" size="8"')?></td>
					  <td> <?php echo Form::text('pesoneto'.$n,'class="save" size="8"')?></td>
					  <td> <?php echo Form::text('pesobruto'.$n,'class="save" size="8"')?></td>
                      <td><span class="simbolo"><?php echo $simbolo;?></span><input id="precio-<?php echo $n?>" type="text"  size="8" class="save"/></td>
					  
				  </tr>
			<?php }  
			?>
            <tr id="hiderow">
		    <td colspan="12"><a id="addrow" href="javascript:;" title="Agregar mas registros">Agragar Mas</a></td>
		  </tr>
  </table>

    <div style="text-align:left; width: 68%; float: left;"id="moneda_en_letras"><?php echo $totalenletras?></div>
<div class="form-actions">
    <?php echo Html::linkAction("ver_i/".$origen, 'Terminar ','class="btn btn-xs btn-primary grabar_form" onclik="grabar()"') ?>&nbsp;<?php echo Html::linkAction("listado/".$origen, 'Cancelar ','class="btn btn-xs btn"') ?>
</div>
        <div id="loading" style="display:none;"><img src="/img/spin.gif" /></div>
     <div style="clear:both"></div>
</div>
