<?php
echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<?php $simbolo="S/. "?>
<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>
<div class="card">
    <h1>Nota de Pedidos Almacen</h1>
</div>
<div class="form-actions">
<em>Seleccione el Origen del Pedido:</em> <?php echo Form::select('origen',array('Produccion'=>'Produccion','Muestra'=>'Muestra','Chenille'=>'Chenille'));?>
<em>Cambie de estado:</em>
<select id="estado">
<option id=''>Seleccione un estado</option>
<?php foreach($estados as $e):
$selec="";
if($estado==$e->estadonota)$selec=' selected="selected"';
?>
<option value="<?php echo $e->estadonota?>"<?php echo $selec?>><?php echo $e->estadonota?></option>
<?php endforeach;?>
</select>
<?php echo Html::linkAction("cargarnota/0/crear/".$origen, 'Crear Nota','class="btn btn-primary"');?>
</div>

<?php //echo Sp::imprimir('Pedidos de Produccion- ','P');?> 
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div><div class="menu">
<ul>
<li>
<a href="javascript:;">Año 
<select id="anio">
<?php
for($i=2011;$i<=2020;$i++)
{
	$selec='';
	if($anio==$i){
	$selec=' selected="selected"';
	}
	echo '<option value="'.$i.'" '.$selec.'>'.$i.'</option>';
}
?>
</select>
</a>
</li>
</ul> 
<?php 
$mes_actual=date('Y-m');
foreach($meses as $clave => $mes):
if($anio.'-'.$clave<=$mes_actual){
$class='';
if($mes_activo==$clave){$class=' active';$name_mes=$mes;}
echo '<ul>';
echo '<li><a class="enviar'.$class.'" id="mes-'.$mes.'" href="javascript:;" data-id="'.$anio.'-'.$clave.'-01">'.$mes.'</a></li>'; 
echo '</ul>';
}
endforeach;?>
</div>
<div id="ver_resultado"></div>  
<div class="card-body">
<?php if($estado=='Pendiente'){
echo Form::open($module_name.'/notadepedido/imprimir/Produccion');
echo Form::hidden('ids');
echo Form::submit('IMPRIMIR','class="btn btn-info"');echo "<em class='text-info'>*Puede imprimir todo o seleccionar los que desea imprimir</em>";
echo Form::close();
}?>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped" id="exportar_excel">
  <thead>
  <tr>
  	<th width="19" align="left">Nº</th>
    <th width="287" align="left">Creador</th>
    <th width="115" align="left">Fecha</th>
    <th width="206" align="left">Hilo-Urdido</th>
    <th width="100" align="left">Estado</th>
    <th width="85" align="left">Origen</th>
    <th width="81" align="right">Total</th>
    <th width="67">Imprimir</th>
    <th width="139" align="center">Acciones</th>
  </tr>
 </thead>
<?php
$numeros_pedidos='';
$n=0;
foreach($notas as $item){ 
	/*agregar para el buscador*/
	$coma=',';
	if($n==0)$coma='';
	$numeros_pedidos.=$coma;
	$numeros_pedidos.='{id:"'.$item->codigo.'",name:"'.$item->codigo.' '.Sp::formatFecha('%d/%m/%Y',$item->fecha_at).'"}';
	$or='';
	if($item->origen=='Muestra')$or='crearm';
	$n++;	
	/**/
	$url='crear';
	if($origen=='Chenille' && Session::get('tipo_nota')=='salida')$url='crear_s_ch';
	?>
  <tr id="<?php echo $item->id?>">
  	<td><?php echo $item->codigo?></td>
   <td>
    <?php 
	echo $item->getAclusuarios()->getAcldatos()->nombre?>
    </td>
    <td><?php echo Sp::formatFecha('%d/%m/%Y',$item->fecha_at)?></td>
    
    <td><?php echo $item->observacion?></td> 
    <td><?php echo $item->estadonota?></td>
    <td><?php echo $origen?></td>
    <td align="right"><?php echo number_format($item->total,2,'.','')?></td>
    <td align="center">         
    <input type="checkbox" name="itemSelect[]" value="<?php echo $item->id?>" class="sele" title="Seleccionar el Pedido para Imprimir"/>
    </td>
    <td align="center">
    <?php 
	if($item->total==0)echo Html::linkAction("eliminar/$item->id/Produccion/".$estado,Html::img("figuras/eliminar.png",'Eliminar','style="width: 20px;margin-left:1px;margin-right:1px;"'));
	
	if($estado!='Pendiente')echo Html::linkAction('cargarnota/'.$item->id.'/'.$url.'/'.$origen,Html::img("figuras/editar.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar la hoja de ruta del plegador"');
	
	if($item->tipo=='salida' && $estado!='Pendiente')echo Html::linkAction("cargarnota/$item->id/revisar/".$origen,Html::img("figuras/visto_bueno.png",'Visto Bueno','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Entregar el Pedido"');
	
	echo Html::linkAction("cargarnota/$item->id/ver/".$origen,Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Visualizar el Pedido!"');
	
	if($item->imprimir=='1' && $item->estadonota!='Entregado'){ echo Html::linkAction("terminar/".$item->id."/Entregado/".$origen.'/'.$estado,'Terminar <i class="icon-ok"></i>','title="Visualizar el Pedido!" class="btn btn-info"'); }
	?>
   </td>
  </tr>
<?php }?>
</table>
<?php //echo $numeros_pedidos;?>
</div>
<div class="form-actions">
<?php if($origen=='Produccion')
	{
		echo 'Estas notas se crean desde la Hoja de ruta.';
	}elseif($origen=='Muestra')
	{
		echo Html::linkAction("cargarnota/0/crearm/".$origen, 'Crear Nota','class="btn btn-primary"');
	}elseif($origen=='Chenille' && Session::get('tipo_nota')=='salida')
	{
		echo Html::linkAction("cargaringreso/0/crear_s_ch/".$origen, 'Crear Nota','class="btn btn-primary"');
	}elseif($origen=='Chenille' && Session::get('tipo_nota')=='ingreso')
	{
		echo Html::linkAction("cargaringreso/0/ingreso_hilo/".$origen, 'Crear Nota','class="btn btn-primary"');
	}else{
		echo Html::linkAction("cargarnota/0/crear/".$origen, 'Crear Nota','class="btn btn-primary"');
				}?>
</div>

<script type="text/javascript">
$(document).ready(function()
{

	$("#numero").tokenInput(
	[
	<?php echo $numeros_pedidos;?>
	], 
	{
	  tokenLimit: 1,
	  minChars: 1,
	  onAdd: function (item) {
		},
	onDelete: function (item) {
		}
	});

	$("#anio").change(function(event){
    	var id = $("#anio").find(':selected').val();
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/<?php echo $origen?>/<?php echo $estado?>/'+id;
     });
	$(".enviar").click(function()
	{
		var fecha = $(this).attr('data-id');
		var F=fecha.split('-');
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/<?php echo $origen?>/<?php echo $estado?>/'+F[0]+'/'+F[1];
	});



	$("#origen").change(function(){
        var op = $("#origen option:selected").val();
        document.location = "/<?php echo $module_name?>/notadepedido/listado/"+op;
    });
		
	$("#estado").change(function(){
        var op = $("#estado option:selected").val();
        document.location = "/<?php echo $module_name?>/notadepedido/produccion/Produccion/"+op;
    });
	$('.sele').click(function()
	{
		var selectedItems = new Array();
		$("input[@name='itemSelect[]']:checked").each(function(){
			selectedItems.push($(this).val());
		});
		$("#ids").val(selectedItems);
	});
	
/*unir pedido*/
$('.unirpedido').click(function(){
	var pedido_id=$(this).attr('data-id');
	//alert(pedido_id);
	$("#pid").val(pedido_id);
	$( "#dialog-unir" ).dialog( "open" );
});	
				
});

</script>