<?php
$simbolo="S/. ";
View::content();
?>

<div class="form-actions">
<?php echo Html::linkAction("listado/".$origen, 'Listado de Pedidos','class="btn btn-xs btn-secondary"');?> <span class="print_h  btn btn-primary"> Print </span>
</div>
<div class="hoja">
	<div class="caja3">
	  <table width="100%" class="table-bordered">
	    <thead>
    <tr>
    	<th colspan="5" rowspan="4" align="left" valign="top"><img id="image" src="/img/logoSP.png" alt="logo"><?php echo date("H:i:s");?></th>
    	<th width="12%" align="left" valign="top">N.Pedido: </th>
    	<th colspan="2" align="left" valign="top"><?php echo $pedido->codigo;?></th>
    	</tr>
    <tr>
    	<th align="left" valign="top">Fecha:</th>
    	<th colspan="2" align="left" valign="top"><?php echo Sp::formatFecha('%d/%m/%Y',$pedido->fecha_at)?></th>
    	</tr>
    <tr>
    	<th align="left" valign="top"><span class="meta-head">Tipo:</span></th>
    	<th colspan="2" align="left" valign="top"><?php echo $pedido->tipo;?></th>
    	</tr>
    <tr>
    	<th align="left" valign="top">Estado: </th>
    	<th colspan="2" align="left" valign="top"><?php echo $pedido->estadonota;?></th>
    	</tr>
        <tr>
          <th width="11%" align="left" valign="top" class="meta-head">De:</th>
          <td colspan="7" valign="top"><?php echo $pedido->getAclusuarios()->getAcldatos()->nombre?><?php echo $pedido->getAclusuarios()->getAcldatos()->appaterno?><?php echo $pedido->getAclusuarios()->getAcldatos()->apmaterno?></td>
          </tr>
        <tr>
          <th align="left" valign="top">Detalle:</th>
          <td colspan="7" valign="top"><?php echo $pedido->descripcion;?></td>
          </tr>
        <tr>
        	<th align="left" valign="top">Mensaje:</th>
        	<td colspan="7" valign="top"><?php echo $pedido->observacion;?></td>
        	</tr>
        <tr>
    	<th align="left" valign="top">Cliente:</th>
    	<th colspan="7" align="left" valign="top"><?php if(!empty($pedido->tesdatos_id))echo $pedido->getTesdatos()->razonsocial.' ruc: '.$pedido->getTesdatos()->ruc.' ('.$pedido->getTesdatos()->departamento.' '.$pedido->getTesdatos()->provincia.' '.$pedido->getTesdatos()->distrito.' '.$pedido->getTesdatos()->direccion.')';?></th>
        </tr>
        <tr>
          	  <th valign="top" align="left">Origen:</th>
          	  <th colspan="7" valign="top" align="left"><?php echo $pedido->origen;?></th>
          	  </tr>
		 <tr>
          	  <th colspan="8" align="left" valign="top"><hr /></th>
              </tr>
		 <tr>
		 	<th valign="top" align="left">Item</th>
		 	<th colspan="2" align="left" valign="top">Codigo-Producto</th>
		 	<th width="18%" align="left" valign="top">Descripcion</th>
		 	<th width="14%" valign="top" align="center">Color</th>
		 	<th width="12%" valign="top">Cantidad</th>
		 	<th width="9%" valign="top">Medida</th>
	 	</tr>
      </thead>
     <tbody> 
		  <?php 
			  $n=0;
			  $totalP=0;
			  $totalC=0;
			  foreach($detalles as $item){
				 $maq='';
				 $descripcion=$item->descripcion;
				 if($item->getRollotrama($item->id))
		 		{
				 $rollo=$item->getRollotrama($item->id);
				 echo $maq="M-".$rollo->getProproduccion()->getPromaquinas()->numero;
				 $descripcion=$rollo->getTesproductos()->nombre;
				}
				  $n++;
			  ?>  
		  <tr id="<?php echo $n?>" title="<?php if(Auth::get('id')==3)echo $item->id; ?>" class="item-row">
          	 <td valign="top"><?php echo $n;?></td>
             <td colspan="2" valign="top"><?php echo $item->id;if(empty($item->getTesproductos()->codigo_ant))echo $item->getTesproductos()->codigo; else echo $item->getTesproductos()->codigo_ant;?><?php //echo $item->getTesproductos()->nombre?> <?php echo $item->getTesproductos()->detalle?></td>
		     <td valign="top" class="description"><?php echo $descripcion?><?Php echo $item->tescajas_id?></td>
		 	 <td align="center"><?php if(!empty($item->tescolores_id))echo $item->getTescolores()->nombre;?></td>
		      <td align="right" valign="top">
              <?php echo number_format($item->cantidad,2,'.','');?>
              <?php $totalC=$totalC+$item->cantidad;?>
              </td>
              <td align="center" valign="top">
              <?php echo $item->getTesunidadesmedidas()->simbolo?>
              </td>
		  </tr>
		  
		  <?php
			  }/*FIN FOREACH*/?>
              </tbody>
	  </table>
     </div>
</div>