<?php
$simbolo="S/. ";

switch ($ingreso->tesmonedas_id)
{
	case 1: $simbolo='S/. ';$moneda_letras='SOLES'; break;
	case 2: $simbolo='$. ';$moneda_letras='DOLARES';  break;
	case 4: $simbolo='S/. ';$moneda_letras='SOLES';  break;
	case 5: $simbolo='$. ';$moneda_letras='DOLARES';  break;
	case 0: $simbolo='S/. ';$moneda_letras='SOLES';  break;
}

$id=$ingreso->id;
		$numero=$ingreso->numero;
		$glosa=$ingreso->glosa;
		$serie=$ingreso->serie;
		$numero=$ingreso->numero;
		$codigo=$ingreso->codigo;//fvencimiento
		$femision=$ingreso->femision;
		$fvencimiento=$ingreso->fvencimiento;
		$monedas=$ingreso->tesmonedas_id;
		$monedas_nombre=$ingreso->getTesmonedas()->nombre;
		$cliente_id=$ingreso->tesdatos_id;
		/*nombre del cliente*/
		$nombre=$ingreso->getTesdatos()->razonsocial." ruc: ".$ingreso->getTesdatos()->ruc." (".$ingreso->getTesdatos()->departamento.' - '.$ingreso->getTesdatos()->provincia.' - '.$ingreso->getTesdatos()->distrito.' - '.$ingreso->getTesdatos()->direccion.')';
		/**/
		$totalconigv=$ingreso->totalconigv;
		$igv=$ingreso->igv;
		$paid=$ingreso->igv;
		$fregistro=$ingreso->fregistro;
		$npedido=$ingreso->npedido;
		$numeroguia=$ingreso->numeroguia;
		$numerofactura=$ingreso->numerofactura;
		$ordendecompra=$ingreso->ordendecompra;
		$finiciotraslado=$ingreso->finiciotraslado;
		$movimiento=$ingreso->movimiento;
		$cuantagastos=$ingreso->cuantagastos;
		$cuentaporpagar=$ingreso->cuentaporpagar;
		$totalenletras=$ingreso->totalenletras;
		
		$subt=$totalconigv-$igv;
		$codigo=$ingreso->codigo;
		
View::content();
?>

<?php //echo $simbolo.$totalconigv.$igv.$cliente_id.$nombre.$cuantagastos.$cuantagastos_name.$cuentaporpagar.$cuentaporpagar_name.$module_name?>

<style type="text/css">
/*.container {
  width: 1124px;
}*/
/*.flotante{position:relative; width:350px; margin:0 auto; z-index:99999;} */
.simbolo
{
	position:absolute;
	float:left;
	margin-left:-15px !important;
}
.table th
{
	font-size:12px;
	text-align:center;
}
#items .item-row td{
	font-size:10px !important;
	padding-left:15px !important;
	}
#items .item-row input[type="text"]{
	font-size:10px !important;
	padding:0;
	}
#paid
{
	width:80% !important;
}
#glosa
{
	width:99% !important;
}
.page ul {
margin:0 !important;
}
</style>
<div class="card">
<h1>Hilo!<?php //echo "id--->".Session::get('INVENTARIO_ID')?></h1>
</div>
<div class="hoja">
<div class="caja3">
   <table class="table-bordered table-striped" width="100%" border="0" cellspacing="1" cellpadding="0" id="exportar_excel">
    <tbody>
    <tr>
     	<th width="88" align="left" valign="top" class="meta-head">F. de Emision:</th>
        <td width="455" align="left" valign="top"><?php echo $femision;?></td>

       </tr>
      <tr>
        <th align="left" valign="top"><span class="meta-head">Serie-Nro:</span></th>
        <td align="left" valign="top"><?php echo $serie?>-<?php echo $numero?></td>

      </tr>
      <tr>
        <th width="88" align="left" class="meta-head">Moneda:</th>
        <td width="455" align="left"><?php echo $monedas_nombre?></td>

      </tr>
      <tr>
     	<th align="left">Proveedor:</th>
        <td align="left"><?php echo $nombre?></td>

       </tr>
          </tbody>
    </table>
    <div><label><strong>Glosa:</strong>
<?php if(!empty($ingreso->glosa)){ echo $ingreso->glosa; }?></label>
    </div>
        <?php /*?><?php
		echo Session::get('DOC_CODIGO')?><?php */?>
<table class="table-bordered table-striped" width="100%" border="0">
		  
   <?php $q=0;foreach($detalles  as $item){
$importe=$item->importe;
	
	 if($q==0){?>
   <thead>
   <tr>
		      <th colspan="11" align="left"><hr /></th>
		      <?php  if(!empty($item->empaque)){ ?> <?php }?>
		     <?php  if(!empty($item->bobinas)){ ?> <?php }?>
             <?php  if(!empty($item->pesoneto)){ ?> <?php }?>
		     <?php  if(!empty($item->pesobruto)){ ?> <?php }?>
		     <?php  if(!empty($item->preciounitario)){ ?>
		     <?php }?>
	        </tr>
   <tr>
   	<th width="12%" align="left">Codigo</th>
   	<th width="21%" align="left">Producto</th>
   	<th width="9%" align="left">Medida</th>
   	<th width="5%" align="left">Lote</th>
   	<th width="10%" align="left">Empaque</th>
   	<th width="10%" align="left">Bobinas</th>
   	<th width="4%" align="left">P/N</th>
   	<th width="6%" align="left">P/B</th>
   	<th width="5%" align="left">C/U</th>
   	<th width="10%" align="left">Cantidad</th>
   	<th width="8%" align="left">Precio</th>
   	</tr>
     </thead>
     <?php }
	 $q++;
	 ?>
     <tbody>
            <tr id="1">
				   <td>
					<?php echo $item->getTesproductos()->prefijo?><?php echo $item->getTesproductos()->codigo?>  
				</td>
					  <td class="item-name"><?php echo $item->getTesproductos()->detalle?>  
					  </td>
					  <td><?php echo $item->getTesunidadesmedidas()->nombre?></td>
					  <td> <?php echo $item->lote?></td>
					 	<?php  if(!empty($item->empaque)){ ?> <td> <?php echo $item->empaque?></td><?php }?>
						<?php  if(!empty($item->bobinas)){ ?>  <td> <?php echo $item->bobinas?></td><?php }?>
						<?php  if(!empty($item->pesoneto)){ ?>  <td> <?php echo $item->pesoneto?></td><?php }?>
						<?php  if(!empty($item->pesobruto)){ ?>  <td> <?php echo $item->pesobruto?></td><?php }?>
						<?php  if(!empty($item->preciounitario)){ ?>  <td><span class="simbolo"><?php echo $simbolo?></span><?php echo $item->preciounitario?></td><?php }?>
					  <td><?php echo $item->cantidad?></td>
					  <td><span class="simbolo"><?php echo $simbolo?></span><span id="total-1" class="price">
					  <?php $importe=0; if($item->importe!='null')$importe=$item->importe;echo number_format($importe,2,'.','')?></span></td>
		    </tr>
		<?php }?>
  </tbody>
      <tr>
     	<td colspan="5"></td>
       </tr>
  </table>
  </div>
  </div>
    <div style="text-align:left; width: 68%; float: left;"id="moneda_en_letras"><?php echo $totalenletras?></div>
<div class="hoja">
<div class="caja3">
<?php if($ingreso->estadoingreso=='Editable'){?>
<?php echo Form::open()?>
<?php echo Form::hidden('ingreso.id')?>
<?php echo Form::hidden('ingreso.aclusuarios_id')?>
<?php echo Form::hidden('ingreso.tesmonedas_id')?>
<?php echo Form::hidden('ingreso.tesdatos_id')?>
<?php echo Form::hidden('ingreso.tesdocumentos_id')?>
<?php echo Form::hidden('ingreso.estadoingreso','','INGRESO-CH')?>
<?php if(Session::get('DOC_CODIGO')=='09'){?>
<label>Auto Salida* <?php echo Form::select('ingreso.autosalida',array(""=>"No","1"=>"Si"))?><small style="font-style:italic;">La guia no llega a nuestra Empresa</small></label>
<?php }?>
<?php echo Html::linkAction("ingreso_hilo/".$origen, 'Editar ','class="btn btn-xs btn-secondary"') ?>&nbsp;<?php echo Form::submit('Terminar ','class="btn btn-xs btn-primary"') ?>
<?php echo Form::close();?>

<?php }else{?><?php echo Html::linkAction("listado/".$origen, 'Listado','class="btn btn-xs btn-secondary"') ?><?php }?>
</div>
</div>
<div id="loading" style="display:none;"><img src="/img/spin.gif" /></div>
     <div style="clear:both"></div>
</div>
