<div class="card">
    <h1>Reporte de Compras por Proveedor</h1>
</div>
<div class="form-actions">
<?php echo Menu::menuReportes($action_name);?>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<?php echo Sp::imprimir('Compras ','P');?>
<div class="input-prepend input-append">
  <span class="add-on" title="Buscar Proveedor"><strong>Busque el Proveedor</strong></span>
  <input type="text" id="demo-input-datos" name="blah" class="input-medium search-query" />
</div>
<div class="card-body" id="uno">
<table id="exportar_excel" width="75%" align="center" class="table-striped">
<?php $number=0;
$a=0;
$array_datos='';
foreach($compras as $item){ 

$simbolo="S/. ";
$number++;
switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}
$b=$item->datos_id;
if($b!=$a)
{
$a=$item->datos_id;
$i_coma=',';
if($number==1){$i_coma='';}
$array_datos.=$i_coma.'{id: '.$item->datos_id.', name: "'.$item->razonsocial.'"}';
if($number!=1){
?>
<tr>
<th colspan="7">&nbsp;</th>
</tr>
<?php }?>
<tr>
<th colspan="7" style="color:#000; font-size:14px; border-bottom:#666 inset 2px;"><?php echo $item->razonsocial?></th>
</tr>
<tr>
  	<th width="17" align="left">Nº</th>
	<th width="87" align="left">F. Emisison Doc.</th>
    <th width="48" align="left">Doc</th>
    <th width="116" align="left">Número Doc.</th>
    <th width="49" align="left">Sub-total</th>
    <th width="27" align="left">Igv</th>
    <th width="37" align="left">Total</th>
  </tr>
<?php 
}

?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $number?></td>
	<td height="20"><?php echo Sp::formatFecha('%d / %m / %Y',$item->femision)?><?php //echo $item->femision?></td>
    <td><?php echo $item->getTesdocumentos()->abr?></td>
  	<td height="20"><?php if(!empty($item->serie))echo $item->serie.'-'?><?php echo $item->numero?></td>
    <td align="left"><?php if($item->totalconigv!='NaN.00' || !empty($item->totalconigv))echo $simbolo.number_format($item->totalconigv-$item->igv,2,'.','');else echo('S/ 00.00');?></td>
    <td align="left"><?php if(!empty($item->igv))echo $simbolo.number_format($item->igv,2,'.','');else echo('S/ 00.00')?></td>
    <td align="left"><?php if(!empty($item->totalconigv))echo $simbolo.number_format($item->totalconigv,2,'.','');else echo('S/ 00.00')?></td>
  </tr>
<?php }?>
</table>
</div>
<script type="text/javascript">
$(document).ready(function()
{
	$("#demo-input-datos").tokenInput([<?php echo $array_datos?>],
		{
		  minChars: 1,
		  tokenLimit: 1,
		  onAdd:function(item){
			$("#uno").load("/<?php echo $module_name?>/<?php echo $controller_name?>/<?php echo $action_name?>_uno/" + item.id);
		  },
		  onDelete: function (item) {
			  $("#uno").load("/<?php echo $module_name?>/<?php echo $controller_name?>/<?php echo $action_name?>_uno/0");
		  }
	});
	$(".botonExcel").click(function(event)
	{
		$("#datos_a_enviar").val( $("<div>").append( $("#exportar_excel").eq(0).clone()).html());
		$("#FormularioExportacion").submit();
	});
});
</script>
<?php echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>