<?php View::content();
$vend_array=array();
$adel_array=array();
$pa_array=array();
foreach($vendedores as $vend)
{
	$vend_array[$vend->id]['S']=0;
	$vend_array[$vend->id]['D']=0;
	$adel_array[$vend->id]['S']=0;
	$adel_array[$vend->id]['D']=0;
	$pa_array[$vend->id]['S']=0;
	$pa_array[$vend->id]['D']=0;
}

?>
<table id="exportar_excel" width="95%" border="0" cellspacing="0" cellpadding="0" class="table-hover table-bordered" align="center">
<thead>
      <tr>
        <th colspan="7"><?php echo $empresa->razonsocial?></th>
      </tr>
      <tr>
        
        <th colspan="4">ESTADO DE CUENTAS DE CLIENTES AL</th>
        <th colspan="2"><?Php echo date("d/m/Y")?></th>
        <th width="96"><?Php echo date("H:i:s");?></th>
      </tr>
      <tr>
        <th width="103" align="left">FECHA</th>
        <th width="259" align="left">Nº DOC</th>
        <th>MOND</th>
        <th width="102" align="right">IMPORTE</th>
        <th width="103" align="right">ABONO</th>
        <th width="97" align="right">SALDO</th>
        <th align="right">P/A</th>
      </tr>
      </thead>
 <tbody>
<?php $number=0;
$a=0;
$T_SALDOS_s=0;
$T_SALDOS_d=0;
$array_datos='';
$total_soles=0;
$total_dolares=0;
$total_soles_abono=0;
$total_dolares_abono=0;
$total_soles_saldo=0;
$total_dolares_saldo=0;
$moneda_a=0;
$contador_parcial=0;
$direccion_a='';$contadordireccion=0;
foreach($ventas as $item){ 

$direccion_b=$item->direccion_entrega;



$maximo=count($ventas);
$simbolo="S/. ";
$number++;
switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. ';break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. ';break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. ';break;
}
/* muestra el total de abono */
$abono=0;
if($item->origen=='ruc')$abono=$item->getAbonos_factura($item->id,'tessalidas_id');
if($item->origen=='interna')$abono=$item->getAbonos_factura($item->id,'tessalidasinternas_id');

$b=$item->datos_id;
if($b!=$a)
{
	$contadordireccion=0;
	$contador_parcial=0;
/*reinicia la moneda a cero*/$moneda_a=0;
$a=$item->datos_id;
$i_coma=',';
if($number==1){$i_coma='';}
$array_datos.=$i_coma.'{id: '.$item->datos_id.', name: "'.$item->razonsocial.'"}';
if($number!=1){
?>
	<tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td align="right"><?php //echo "M=".$item->tesmonedas_id?></td>
        <td align="right"><b><?php if($total_dolares==0)echo number_format($total_soles,2,'.','');else echo number_format($total_dolares,2,'.','');?></b></td>
        <td align="right"><b><?php if($total_dolares_abono==0)echo number_format($total_soles_abono,2,'.','');else echo number_format($total_dolares_abono,2,'.','');?></b></td>
        <td align="right"><b>
		<?php 
		
		if($total_dolares_saldo==0)
		{
			$T_SALDOS_s=$T_SALDOS_s+($total_soles_saldo);
			$vend_array[$vendedor_id]['S']=$vend_array[$vendedor_id]['S']+($total_soles_saldo);
			echo number_format($total_soles_saldo,2,'.','');
		}else{
			$T_SALDOS_d=$T_SALDOS_d+($total_dolares_saldo);
			$vend_array[$vendedor_id]['D']=$vend_array[$vendedor_id]['D']+($total_dolares_saldo);
			echo number_format($total_dolares_saldo,2,'.','');
		}?></b>
        </td>
        <td>&nbsp;</td>
      </tr>
   <?php }
    $vendedor_id=$item->getTesdatos()->tesvendedores_id;
   ?>
      
  <?php 
$total_soles=0;$total_dolares=0;$total_soles_abono=0;$total_dolares_abono=0;$total_soles_saldo=0;$total_dolares_saldo=0;  }?> 
  <?php /*validar la moneda*/
  $moneda_b=$item->tesmonedas_id;
  if($moneda_a!=$moneda_b){
	 $moneda_a=$item->tesmonedas_id;
  ?>   
      <?php if($item->tesmonedas_id==2 or $item->tesmonedas_id==5){
		  /*valida la suma de los totales si en 0 no mostrar*/
		  $suma=$total_soles+$total_dolares+$total_soles_abono+$total_dolares_abono+$total_soles_saldo+$total_dolares_saldo;
		  if($suma!=0){?>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
        		<td align="right"><?php //echo "M=".$item->tesmonedas_id?></td>
                <td align="right"><b><?php if($total_dolares==0)echo number_format($total_soles,2,'.','');else echo number_format($total_dolares,2,'.','');?></b></td>
                <td align="right"><b><?php if($total_dolares_abono==0)echo number_format($total_soles_abono,2,'.','');else echo number_format($total_dolares_abono,2,'.','');?></b></td>
                <td align="right"><b><?php 
                if($total_dolares_saldo==0)
                {
                    $T_SALDOS_s=$T_SALDOS_s+($total_soles_saldo);
                    $vend_array[$vendedor_id]['S']=$vend_array[$vendedor_id]['S']+($total_soles_saldo);
                    echo number_format($total_soles_saldo,2,'.','');
                }else{
                    $T_SALDOS_d=$T_SALDOS_d+($total_dolares_saldo);
                    $vend_array[$vendedor_id]['D']=$vend_array[$vendedor_id]['D']+($total_dolares_saldo);
                    echo number_format($total_dolares_saldo,2,'.','');
                }?></b></td>
                <td>&nbsp;</td>     
      </tr>
      <?php 
		  }
	  $total_soles=0;$total_dolares=0;$total_soles_abono=0;$total_dolares_abono=0;$total_soles_saldo=0;$total_dolares_saldo=0;
	  }?>
      <tr class="no_imprimir">
        <th colspan="7" align="left" style="border-bottom:#999 double 1px;"></th>
      </tr>
   <?php }
   
   	  /*if(number_format($item->total-$abono,2,'.','')!=0){*/
	  ?>
	  <?php if($contador_parcial==0){?> 
      <tr>
      	<th colspan="7" align="left" >COD: <?php echo (int)$item->codigo.'-'.$item->sufijo?>&nbsp;&nbsp;&nbsp;<?php echo $item->razonsocial;?>
        </th>
       </tr>	  
    
	  <?php }?>
      <?php /*validar la direccion*/
	 if($direccion_a!=$direccion_b){
		  $contadordireccion++; 
		  $direccion_a=$item->direccion_entrega;
		 
	  ?>
      <tr class="<?php echo $item->datos_id?>direccion_ocultar">
        <td>&nbsp;</td>
      	<td colspan="6" align="left" style="color:#666; font-size:8px;"><?php echo $item->direccion_entrega;?> </td>
       </tr>
       <?php  }?>

      <tr title="(<?php echo $item->origen?>-<?php echo $item->id?>) estado : <?php echo $item->estadosalida?> semana: <?php echo $item->semana?> ">
        
        <td align="center"><?php echo Sp::formatFecha('%d/%m/%y',$item->fecha)?></td>
        <td align="left">
		<?php if($item->estadosalida=='TERMINADO'){echo "(CJ)";if(!empty($item->total));}?>
		<?php 
		$TD=$item->getTesdocumentos()->abr;
		if($item->getTesdocumentos()->abr=='FA')$TD='VT';
		if($item->getTesdocumentos()->abr=='GR')$TD='VT';
		
		echo $TD.' '; if(!empty($item->numerofactura)){echo $item->numerofactura;}else{?><?php echo $item->numeroguia;}?></td>
        <td align="center" valign="top"><?php echo $item->getTesmonedas()->abr?></td>
        <td align="right"><?php 
		//echo $vendedor_id.' *--*';		
	  switch ($item->tesmonedas_id)
		{
			case 1: 
					if($item->tesdocumentos_id!=13){
					$total_soles=$total_soles+$item->total;
					$total_soles_abono=$total_soles_abono+$abono;
					$total_soles_saldo=$total_soles_saldo+($item->total-$abono);
					}else 
					{
					$total_soles=$total_soles-$item->total;
					$total_soles_saldo=$total_soles_saldo-$item->total;
					}
					if(!empty($item->pa))$adel_array[$vendedor_id]['S']=$adel_array[$vendedor_id]['S']+number_format($item->pa,2,'.','');					
			break;
			case 2: 
					if($item->tesdocumentos_id!=13){
					$total_dolares=$total_dolares+$item->total;
					$total_dolares_abono=$total_dolares_abono+$abono;
					$total_dolares_saldo=$total_dolares_saldo+($item->total-$abono);
					}else
					{
					$total_dolares=$total_dolares-$item->total;
					$total_dolares_saldo=$total_dolares_saldo-$item->total;
					}			
					if(!empty($item->pa))$adel_array[$vendedor_id]['D']=$adel_array[$vendedor_id]['D']+number_format($item->pa,2,'.','');
			break;
			case 4: 
					if($item->tesdocumentos_id!=13){
					$total_soles=$total_soles+$item->total;
					$total_soles_abono=$total_soles_abono+$abono;
					$total_soles_saldo=$total_soles_saldo+($item->total-$abono);
					}else
					{
					$total_soles=$total_soles-$item->total;
					$total_soles_saldo=$total_soles_saldo-$item->total;
					}
					
					if(!empty($item->pa))
					{
						$adel_array[$vendedor_id]['S']=$adel_array[$vendedor_id]['S']+number_format($item->pa,2,'.','');
					}		
			break;
			case 5: 
					if($item->tesdocumentos_id!=13){
					$total_dolares=$total_dolares+$item->total;
					$total_dolares_abono=$total_dolares_abono+$abono;
					$total_dolares_saldo=$total_dolares_saldo+($item->total-$abono);
					}else
					{
					$total_dolares=$total_dolares-$item->total;
					$total_dolares_saldo=$total_dolares_saldo-$item->total;
					}
					if(!empty($item->pa))$adel_array[$vendedor_id]['D']=$adel_array[$vendedor_id]['D']+number_format($item->pa,2,'.','');
			break;
			case 0: 
					if($item->tesdocumentos_id!=13){
					$total_soles=$total_soles+$item->total;
					$total_soles_abono=$total_soles_abono+$abono;
					$total_soles_saldo=$total_soles_saldo+($item->total-$abono);
					}else
					{
					$total_soles=$total_soles-$item->total;
					$total_soles_saldo=$total_soles_saldo-$item->total;
					}
					if(!empty($item->pa))$adel_array[$vendedor_id]['S']=$adel_array[$vendedor_id]['S']+number_format($item->pa,2,'.','');
		    break;
		}
		if(!empty($item->total))echo number_format($item->total,2,'.','');else echo number_format($item->total_a,2,'.','');?></td>
        <td align="right"><?php echo number_format($abono,2,'.','')?></td>
        <td align="right"><?php echo number_format($item->total-$abono,2,'.','')?></td>
        <td align="right">
		<?php 
		if(!empty($item->pa))
		{
			/*$igv=$item->pa*Session::get('IGV');
			echo number_format($item->pa+$igv,2,'.','');*/
			echo number_format($item->pa,2,'.','');
		}?>
        </td>
      </tr>
      <?php 
	  /*}*/
	  if($number==$maximo){?>
      <tr>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th align="right">&nbsp;</th>
        <th align="right"><?php if($total_dolares==0)echo number_format($total_soles,2,'.','');else echo number_format($total_dolares,2,'.','');?></th>
        <th align="right"><?php if($total_dolares_abono==0)echo number_format($total_soles_abono,2,'.','');else echo number_format($total_dolares_abono,2,'.','');?></th>
        <th align="right">
		<?php 
		if($total_dolares_saldo==0)
		{
			$T_SALDOS_s=$T_SALDOS_s+($total_soles_saldo);
			$vend_array[$vendedor_id]['S']=$vend_array[$vendedor_id]['S']+($total_soles_saldo);
			echo number_format($total_soles_saldo,2,'.','');
		}else{
			$T_SALDOS_d=$T_SALDOS_d+($total_dolares_saldo);
			$vend_array[$vendedor_id]['D']=$vend_array[$vendedor_id]['D']+($total_dolares_saldo);
			echo number_format($total_dolares_saldo,2,'.','');
		}?>
        </th>
        <th>&nbsp;</th>
      </tr>
      <?php }?>
	<?Php if($contadordireccion<=1){?>
	  <script type="text/javascript">
	  $(document).ready(function(){
		  	$(".<?php echo $item->datos_id?>direccion_ocultar").hide();
		});
       </script>
	<?Php }
	if($contadordireccion>=2){?>
	<script type="text/javascript">
	  $(document).ready(function(){
		  	$(".<?php echo $item->datos_id?>direccion_ocultar").show();
		});
       </script>
	
	<?php }?>
 <?php $contador_parcial++;
 
 } ?>
 
  <tr>
  <td colspan="7" align="center">
  <b>*--*</b>
  </td>
  </tr>
  <tr>
  <td colspan="7" align="center" style="border-bottom:#CCCCCC solid 1px;">
  <b>RESUMEN DE SALDOS</b>
  </td>
  
  </tr>
  <tr style="border-bottom:#CCCCCC solid 1px !important; ">
    <td scope="col">&nbsp;</td>
    <td colspan="2" align="right" scope="col"><b>SALDO POR COBRAR</b></td>
    <td colspan="2" align="right" scope="col"><b>P/A FACTURADOS</b></td>
    <td colspan="2" align="right" scope="col"><b>P/A SIN FACTURAR</b></td>
    </tr>
  <tr  style="border-bottom:#CCCCCC solid 1px !important;">
    <td align="center"><b>VENDEDOR</b></td>
    <td width="259" align="right"><b>SOLES</b></td>
    <td width="101" align="right"><b>DOLAR</b></td>
    <td width="102" align="right"><b>SOLES</b></td>
    <td width="103" align="right"><b>DOLAR</b></td>
    <td width="97" align="right"><b>SOLES</b></td>
    <td width="96" align="right"><b>DOLAR</b></td>
  </tr>
  <?php 
  $tg_saldo_s=0;
  $tg_saldo_d=0;
  $tg_facturas_s=0;
  $tg_facturas_d=0;
  $tg_pagos_s=0;
  $tg_pagos_d=0;
  foreach($vendedores as $vend):?>
  <tr>
    <td align="right"><?php echo $vend->nombre?></td>
    <td align="right"><?php $tg_saldo_s=$tg_saldo_s+number_format($vend_array[$vend->id]['S'],2,'.','');echo number_format($vend_array[$vend->id]['S'],2,'.','');?></td>
    <td align="right"><?php $tg_saldo_d=$tg_saldo_d+number_format($vend_array[$vend->id]['D'],2,'.','');echo number_format($vend_array[$vend->id]['D'],2,'.','');?></td>
    <td align="right"><?php $tg_facturas_s=$tg_facturas_s+number_format($adel_array[$vend->id]['S'],2,'.','');echo number_format($adel_array[$vend->id]['S'],2,'.','');?></td>
    <td align="right"><?php $tg_facturas_d=$tg_facturas_d+number_format($adel_array[$vend->id]['D'],2,'.','');echo number_format($adel_array[$vend->id]['D'],2,'.','')?></td>
    <td align="right"><?php $tg_pagos_s=$tg_pagos_s+number_format($vend->total_sp,2,'.',''); echo number_format($vend->total_sp,2,'.','')?></td>
    <td align="right"><?php $tg_pagos_d=$tg_pagos_d+number_format($vend->total_dp,2,'.','');echo number_format($vend->total_dp,2,'.','')?></td>
  </tr>
  <?php endforeach;?>
  </tbody>
  <tfoot>
  <tr>
  	<td align="right"><b>TOTAL GENERAL :</b></td>
  	<td align="right"><b><?Php echo number_format($tg_saldo_s,2,'.','')?></b></td>
  	<td align="right"><b><?Php echo number_format($tg_saldo_d,2,'.','')?></b></td>
  	<td align="right"><b><?Php echo number_format($tg_facturas_s,2,'.','')?></b></td>
  	<td align="right"><b><?Php echo number_format($tg_facturas_d,2,'.','')?></b></td>
  	<td align="right"><b><?Php echo number_format($tg_pagos_s,2,'.','')?></b></td>
  	<td align="right"><b><?Php echo number_format($tg_pagos_d,2,'.','')?></b></td>
  </tr>
 </tfoot>
</table>