
<style type="text/css">
.span_float
{
	float:right !important;
	margin-left:0px;
	margin-right:-5px;
}
</style>
<div class="card">
	<h1>Reporte Valorado  <span> Rporte valorado de las muestras por articulo</span></h1>
    </div>
    <div class="form-actions" title="Regresar!">
    <?php echo Menu::menuReportes($action_name);?>
	</div>

<?php View::content();?>
<br />
Cambie de Año 
<select id="anio">
<?php
for($i=2011;$i<=2020;$i++)
{
	$selec='';
	if($anio==$i){
	$selec=' selected="selected"';
	}
	echo '<option value="'.$i.'" '.$selec.'>'.$i.'</option>';
}
?>
</select> 
<div class="menu">
<?php 
$mes_actual=date('Y-m');
foreach($meses as $clave => $mes):
if($anio.'-'.$clave<=$mes_actual){
$class='';
if($mes_activo==$clave)$class=' active';
echo '<ul>';
echo '<li><a class="enviar'.$class.'" id="mes-'.$mes.'" href="javascript:;" data-id="'.$anio.'-'.$clave.'-01">'.$mes.'</a></li>'; 
echo '</ul>';
}
endforeach;
echo '<ul>';
echo '<li><a class="enviar" id="mes-0" href="javascript:;" data-id="'.$anio.'-0-01">TODOS</a></li>'; 
echo '</ul>';
?>
</div>
<?php echo Sp::imprimir('Valorado Muestras - ','P');?>
<div class="card-body">
<div id="ver">
  <table id="exportar_excel" width="80%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
    <thead>
    <tr>
      <th width="4%" align="left">Num</th>
      <th width="7%" align="left">Fecha</th>
      <th width="7%" align="left">Guia</th>
      <th width="28%" align="left">Cod Cliente</th>
      <th width="16%" align="left">Articulo</th>
      <th width="7%" align="right">Mts</th>
      <th width="14%" align="right">Pre/unit</th>
      <th width="17%" align="right">TOTAL S./</th>
    </tr>
    </thead>
    <tbody>
      <?php 
	$contador=0;
	$a=0;
	/*contador para la suma */
	$n=0;
	$m=1;
	/*suma de totales*/
	$total_kilos=0;
	$total_metros=0;
	foreach($muestras as $item){
		$contador++;
		$maximo=count($muestras);
		$b=$item->id;
		$articulo=$item->codigo_ant;
		if(empty($item->codigo_ant))$articulo=$item->codigo;
		if($a!=$b){$n++;$m=1;}else{$m++;}
	//PARA MOSTRAR EL TOTAL ANTERIOR
if($a!=$b)
{
		if($a!=0)
		{?>
	<tr class="total">
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th colspan="2" align="right"><?php //echo $final;?></th>
      <th align="right" style="border-top:#333 1px solid;"><?php echo number_format($total_metros,2,'.','')?></th>
      <th align="right" style="border-top:#333 1px solid;">&nbsp;</th>
      <th align="right" style="border-top:#333 1px solid;"><?php echo number_format($total_kilos,2,'.','')?></th>
      
    </tr>
    <tr class="total">
      <td colspan="8">&nbsp;</td>
    </tr>
	
<?php $total_metros=0;$total_kilos=0;
	}
}	
		?>
    <tr>
      <td><?php echo $contador?>-<?php echo $n?>.<?Php echo $m;?></td>
      <td><?php echo Sp::formatFecha('%d/%m/%y',$item->fecha)?><?Php //echo $a.'=='; echo $b.'/**/'?><?php if($a!=$b)echo $articulo?></td>
      <td><?php echo $item->nu_guia; //echo $item->estadoitem;?></td>
      <td><?php echo $item->piezza?><?php if($a!=$b)echo $item->cliente; //echo $item->estadoitem;?></td>
      <td><?php if($a!=$b)echo $item->articulo; //echo $item->estadoitem;?></td>
      <td align="right"><?php if(!empty($item->mts))echo number_format($item->mts,2,'.','')?></td>
      <td align="right"><?php if(!empty($item->preunit))echo number_format($item->preunit,2,'.','')?></td>
      <td align="right"><?php if(!empty($item->importe))echo number_format($item->importe,2,'.','')?></td>
    </tr>
    <?Php 
	$total_kilos=$total_kilos+$item->importe;
	$total_metros=$total_metros+$item->mts;
	?>
    <?Php if($contador==$maximo){?>
    <tr>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th colspan="2" align="right"><?php //echo $final;?></th>
      <th align="right" style="border-top:#333 1px solid;"><?php echo number_format($total_metros,2,'.','')?></th>
      <th align="right" style="border-top:#333 1px solid;"></th>
      <th align="right" style="border-top:#333 1px solid;"><?php echo number_format($total_kilos,2,'.','')?></th>
    </tr>
    <?php }?>
    <?Php if($a!=$b)
	{
	$a=$item->id;
	//$final='TOTAL '.$item->descripcion;
	?>
	<?php 
	}
	
	//$m++;
	
	}?>
    
    </tbody>
  </table>
</div>
<br>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$("#anio").change(function(event){
    	var id = $("#anio").find(':selected').val();
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?php echo $action_name?>/'+id;
     });
	$(".enviar").click(function()
	{
		var fecha = $(this).attr('data-id');
		var F=fecha.split('-');
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?php echo $action_name?>/'+F[0]+'/'+F[1];
	});
	$(".botonExcel").click(function(event)
	{
		$("#datos_a_enviar").val( $("<div>").append( $("#exportar_excel").eq(0).clone()).html());
		$("#FormularioExportacion").submit();
	});
});
</script>