<?Php View::content();?>
<?php /*,"PDF"=>"1"*/echo Sp::imprimir('Reporte de Movimientos','P',array('W'=>"1",'P'=>"1"));?>
<div class="card-body">
<?php
if($id!=0){
$ultimos;  
	?>

<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered">
  <tr>
    <th colspan="9" scope="col"><?PHp echo Session::get('EMPRESAS_NOMBRE')?><?Php echo date('d/m/Y H:i:m')?><b><br />Ultimos Movimientos!</b></th>
    </tr>
    <tr>
    <th colspan="2" align="left" scope="col"><b>CODIGO CLIENTE:</b></th>
    <th colspan="2" align="left" scope="col"><b><?php echo $dato->codigo_ant?></b></th>
    <th width="11%" align="left" scope="col"><b>TELEFONO:</b></th>
    <th width="2%" align="left" scope="col">&nbsp;</th>
    <th width="13%" align="left" scope="col"><b><?php echo $dato->telefono?></b></th>
    <th width="19%" align="left" scope="col">&nbsp;</th>
    <th width="3%" align="left" scope="col">&nbsp;</th>
  </tr>
  <tr>
    <th colspan="2" align="left" scope="col"><b>NOMBRE/<?php echo utf8_decode("RAZÓN")?> SOCIAL:</b></th>
    <th colspan="6" align="left" scope="col"><b><?php echo $dato->razonsocial?></b></th>
    <th align="left" scope="col">&nbsp;</th>
  </tr>
  <tr>
    <th colspan="2" align="left" scope="col"><b>DIRECCION:</b></th>
    <th colspan="6" align="left" scope="col"><b><?php echo $dato->direccion?></b></th>
    <th align="left" scope="col">&nbsp;</th>
  </tr>
  <tr>
    <th colspan="2" align="left" scope="col"><b>CONTACTO:</b></th>
    <th colspan="6" align="left" scope="col"><b><?php echo $contacto->contacto?></b></th>
    <th align="left" scope="col">&nbsp;</th>
  </tr>
  <tr>
    <th colspan="3" scope="col">&nbsp;</th>
    <th colspan="2" align="center" scope="col">&nbsp;</th>
    <th align="center" scope="col">&nbsp;</th>
    <th colspan="2" align="center" scope="col">&nbsp;</th>
    <th align="right" scope="col">&nbsp;</th>
  </tr>
  <tr>
    <th width="8%" align="left" scope="col">FECHA</th>
    <th width="22%" align="left" scope="col">DOC.REF</th>
    <th width="6%" align="center" scope="col">MOV</th>
    <th width="16%" align="right" scope="col">ABONO S/.</th>
    <th align="right" scope="col">CARGO S/.</th>
    <th align="right" scope="col">&nbsp;</th>
    <th align="right" scope="col">ABONO $/</th>
    <th align="right" scope="col">CARGO $/</th>
    <th align="right" scope="col">&nbsp;</th>
  </tr>
  <?php 
	/*mov_s,id_doc_s,sid,femision_s,as numero_s,monto_s,estado_s,mov_d,id_doc_d,did,femision_d,numero_d,monto_d,estado_d*/
	$total_abono_s=0;
	$total_cargo_s=0;
	$c=0;
	foreach($detalles as $item)
	{
	$c++;
	
	if(!empty($item->monto_s) || (int)$item->monto!=0){
	?>
  <tr title="<?php if(Auth::get('id')==3){echo $item->tabla." id=".$item->sid.' estado: '.$item->estado_s;}?>">
    <td align="left"><?Php echo Sp::formatFecha("%d/%m/%y",$item->femision_s)?></td>
    <td align="left"><?Php 
	$numero_documento=$item->numero_s;
	if($item->mov_s=='LTR')$numero_documento=$item->numero_doc;
	if($item->tabla=='tesabonos 14' && $item->mov_s=='NC')$numero_documento=$item->getNumeroNC($item->sid);
	echo $numero_documento;?></td>
    <td align="center"><?Php if($item->estado_s=='ANULADO')echo "AN";else echo $item->mov_s?> <?php //echo $item->moneda;?></td>
    <td align="right">
	<?Php 
	if($item->moneda==1 || $item->moneda==4)
	{
	if($item->mov_s!='AB' && $item->mov_s!='NC' && $item->id_doc_s!=0)
	{
		if($item->tabla=='tessalidas' || $item->tabla=='tessalidasinternas')
		{
			if($item->estado_s=='ADELANTADO')
			{
				//$PEN=$item->monto_s-$item->getDetalleAbono($item->sid,$item->tabla);echo '('.number_format($PEN,2,'.','').')';
			}
			
		}
	}?>
    <?Php 
	if($item->mov_s=='AB' || $item->id_doc_s==0)
	{
		$total_abono_s=$total_abono_s+$item->monto_s;
		if(!empty($item->monto_s) || (int)$item->monto!=0){if($item->estado_s=='ANULADO')echo "00.00";else echo number_format($item->monto_s,2,'.',''); }
		
	}
	}
	 ?>
    </td>
    <td align="right"><?Php 
	if($item->moneda==1 || $item->moneda==4)
	{
	if($item->mov_s!='AB' && $item->id_doc_s!=0)
	{
		if($item->estado_s!='ANULADO')
		{
			if(!empty($item->totalconigv))$total_cargo_s=$total_cargo_s+$item->totalconigv;
		}
		
		if(!empty($item->totalconigv))
		{
			if($item->estado_s=='ANULADO')
			{echo "0.00";
			}else{
				if($item->mov_s=='NC')
				{echo '(-'.number_format($item->totalconigv,2,'.','').')*';
				}else{echo number_format($item->totalconigv,2,'.','');
				}
			}
		}else{
		echo "0.00";
	    }
	}
	}
	?>
    </td>
    <td align="right">
	<?php
	if($item->moneda==1 || $item->moneda==4)
	{
    if($item->estado_s=='Pendiente')echo "P";
	if($item->estado_s=='ADELANTADO')echo "AD";
	/*if($item->mov_s!='AB' && $item->mov_s!='NC' && $item->id_doc_s!=0)
	{
		if($item->estado_s!='ANULADO')
		{
			//$total_cargo_s=$total_cargo_s+number_format($item->monto_s,2,'.','');
		}
		if(empty($item->totalconigv) or $item->totalconigv<=0.5)
		{
			if(!empty($item->monto_s))echo "(".number_format($item->monto_s,2,'.','').")";
		}
	 }*/
	}?>
    </td>
    <td align="right">
	<?Php
	if($item->moneda==2 || $item->moneda==5){
    if($item->mov_s!='AB' && $item->mov_s!='NC' && $item->id_doc_s!=0)
	{
		if($item->tabla=='tessalidas' || $item->tabla=='tessalidasinternas')
		{
			if($item->estado_s=='ADELANTADO')
			{
				//$PEN=$item->monto_s-$item->getDetalleAbono($item->sid,$item->tabla);echo '('.number_format($PEN,2,'.','').')';
			}
			//if($item->estado_s=='ANULADO')echo 00;
		}
	}?>
    <?Php 
	if($item->mov_s=='AB' || $item->id_doc_s==0)
	{
		$total_abono_s=$total_abono_s+$item->monto_s;
		if(!empty($item->monto_s) || (int)$item->monto!=0){if($item->estado_s=='ANULADO')echo "0.00";else echo number_format($item->monto_s,2,'.','');}
		
	}
	}?>
    </td>
    <td align="right">
	<?Php 
	if($item->moneda==2 || $item->moneda==5){
	if($item->mov_s!='AB' && $item->id_doc_s!=0)
	{
		if($item->estado_s!='ANULADO')
		{
			if(!empty($item->totalconigv))$total_cargo_s=$total_cargo_s+$item->totalconigv;
		
		if(!empty($item->totalconigv))
		{
			if($item->estado_s=='ANULADO')
			{echo "0.00";
			}else{
				if($item->mov_s=='NC')
				{echo '(-'.number_format($item->totalconigv,2,'.','').')*';
				}else{echo number_format($item->totalconigv,2,'.','');
				}
			}
		}else{
		echo "0.00";
	    }
		}else{
			echo "00.0";
			}
	}
	}?>
    </td>
    <td align="right">
	<?php 
	if($item->moneda==2 || $item->moneda==5){
	if($item->estado_s=='Pendiente')echo "P";
	if($item->estado_s=='ADELANTADO')echo "AD";
	/*if($item->mov_s!='AB' && $item->mov_s!='NC' && $item->id_doc_s!=0)
	{
		if($item->estado_s!='ANULADO')
		{
			//$total_cargo_s=$total_cargo_s+number_format($item->monto_s,2,'.','');
		}
		if(empty($item->totalconigv) or $item->totalconigv<=0.5)
		{
			if(!empty($item->monto_s))echo "(".number_format($item->monto_s,2,'.','').")";
		}
	}*/
	}?>
    </td>
  </tr>
  <?php 
	}
  }?>
  <tr>
    <td colspan="3"><b>PENDIENTE DE COBRANZA =&gt;</b></td>
    <td align="right"><b>
      <?php
	 if(Auth::get('id')==3){ 
		echo "Cargos :".$cargos_s.'<br />'; 
	 	echo "Abonos :".$abonos_s.'<br />'; 
	 	echo "Anulados :".$NC_anulados_s.'<br />'; 
	 }
    $resta_s=$cargos_s-($abonos_s-$NC_anulados_s);
	if($resta_s<0)echo number_format($resta_s,2,'.','');else echo '0.00';
	
	?></b></td>
    <td align="right"><b><?php if($resta_s>0)echo number_format($resta_s,2,'.','');else echo '0.00';?></b></td>
    <td align="right">&nbsp;</td>
    <td align="right"><b>
	<?php if(Auth::get('id')==3){ 
		echo "Cargos :".$cargos_d.'<br />'; 
	 	echo "Abonos :".$abonos_d.'<br />'; 
	 	echo "Anulados :".$NC_anulados_d.'<br />'; 
	 }
	$resta_d=$cargos_d-($abonos_d-$NC_anulados_d);
	if($resta_d<0)echo number_format($resta_d,2,'.','');else echo "0.00";
	?></b></td>
    <td align="right"><b><?php if($resta_d>1)echo number_format($resta_d,2,'.','');else echo '0.00';?></b></td>
    <td align="right">&nbsp;</td>
  </tr>
  <tr>
  <td colspan="3"><b>PENDIENTE DE ENTREGA (MERCADERIA) =&gt;</b></td>
    <td align="right"><?php  
	$adelanto_s=($adelantos['S']+($adelantos['S']*Session::get('IGV')));
	echo number_format($adelanto_s,2,'.','');
	?></td>
    <td align="right">&nbsp;</td>
    <td align="right">&nbsp;</td>
    <td align="right"><?php 
	$adelanto_d=($adelantos['D']+($adelantos['D']*Session::get('IGV')));
	echo number_format($adelanto_d,2,'.','');
	?></td>
	
	
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="9">&nbsp;</td>
    
  </tr>
  <tr>
    <th colspan="9">&nbsp;</th>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><b><?Php echo utf8_decode("AÑO")?></b></td>
    <td><b>MES</b></td>
    <td>&nbsp;</td>
    <td align="right"><b>SOLES S/</b></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td align="right"><b> DOLARES $/</b></td>
    <td>&nbsp;</td>
  </tr><?php 
$letras_v_s=0;
$letras_v_d=0;

$total_letras_s=0;
$total_letras_d=0;
$n=0;
$c_de_l=0;
foreach($letras as $letra)
{
	if($letra->moneda==1 || $letra->moneda==4)$total_letras_s=$total_letras_s+$letra->monto_total;
	if($letra->moneda==2 || $letra->moneda==5)$total_letras_d=$total_letras_d+$letra->monto_total;

if($letra->y_m<date("Y-m"))
{
	if($letra->moneda==1 || $letra->moneda==4)$letras_v_s=$letras_v_s+$letra->monto_total;
	if($letra->moneda==2 || $letra->moneda==5)$letras_v_d=$letras_v_d+$letra->monto_total;
}
if($n==0){?>
  <tr>
    <td>&nbsp;</td>
    <td colspan="2"><b>LETRAS ANTERIORES</b></td>
    <td>&nbsp;</td>
    <td align="right"><?Php echo number_format($letras_v_s,2,'.','')?></td>
    <td>&nbsp;</td>
    <td></td>
    <td align="right"><?Php echo number_format($letras_v_d,2,'.','')?></td>
    <td>&nbsp;</td>
  </tr>
 <?php }
 $n++;
 
 if($letra->y_m>=date("Y-m")){?>
  <tr>
    <td></td>
    <td><?php echo Sp::formatFecha('%Y',$letra->fecha);?></td>
    <td><?php echo Sp::formatFecha('%m',$letra->fecha);?></td>
    <td>&nbsp;</td>
    <td align="right"><?Php if($letra->moneda==1 || $letra->moneda==4)echo number_format($letra->monto_total,2,'.','')?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td align="right"><?Php if($letra->moneda==2 || $letra->moneda==5)echo number_format($letra->monto_total,2,'.','')?></td>
    <td>&nbsp;</td>
  </tr>
  <?php 
 	}
 }?> 
  <tr>
    <td colspan="4"><b>CREDITO TOTAL =&gt;</b></td>
    <td align="right"><b><?php echo number_format($total_letras_s,2,'.','')?></b></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td align="right"><b><?php echo number_format($total_letras_d,2,'.','')?></b></td>
    <td>&nbsp;</td>
  </tr> 
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>  
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  
  
  <tr>
    <td colspan="9">ACC=Abono en Cuenta Corriente, VT=Venta, ND=Nota Debito, NC=Nota de Credito. GF=Gastos Financ. PT=Letra Protestada, AN=Anulado, NA=Nota Abono, DV=Devolocion, EFE=Efectivo, CHK=Cheque, LTR=Letra.
     <br /> *Este monto no es calculable hasta su aplicacion.</td>
    </tr>
</table>

<?php }?>
</div>