<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead>
  <tr>
    <th colspan="2" scope="col">Reporte de Movimientos Proveedoes</th>
  </tr>
  <tr>
    <th colspan="2" scope="col">Nombre: Ruc: Fechas:</th>
  </tr>
  </thead>
  <tr>
    <td><table width="99%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th scope="col">Numero</th>
        <th scope="col">Fecha</th>
        <th scope="col">Cago</th>
        <th scope="col">Abono</th>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
    <td><table width="99%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th scope="col">Numero</th>
        <th scope="col">Fecha</th>
        <th scope="col">Cargo</th>
        <th scope="col">Abono</th>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </table></td>
  </tr>
</table>
