<?php View::content() ?>
<?php echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<br />
<div class="card">
    <h1>Salida-Rollos a Tintoreri!<span><?php echo Session::get('DOC_NOMBRE').'->'.Session::get('DOC_ID').'->'.Session::get('CAMBIO_ID')?></span></h1>
</div>
<div class="form-actions"><?php if($val==999)echo Html::linkAction('salidas_i','Cancelar','class="btn"');else echo Html::linkAction('salidas','Cancelar','class="btn"');?></div>
<div class="card-body">
<div id="ver_resultado"></div>
<div class="span1"></div><div class="span8">
<?php echo Form::open(NULL,'POST','class="form-horizontal"')?>
  <div class="control-group">
    <label class="control-label" for="salida_serie">Serie - Numero</label>
    <div class="controls">
      <?php echo Form::text('salida.serie','size="4"');?>-<?php echo Form::text('salida.numero','size="10"');?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="salida_serie">Numero de Pedido</label>
    <div class="controls">
      <?php echo Form::text('salida.npedido','size="10"');?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="salida_tesmonedas_id">Moneda:</label>
    <div class="controls">
      <?php echo Form::dbSelect('salida.tesmonedas_id','simbolo,nombre',array("tesmonedas",'find','conditions: aclempresas_id='.Session::get('EMPRESAS_ID')));?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="salida_hilodestino">Destino:</label>
    <div class="controls">
    <select><option>TINTORERIA-TI</option></select>
      <?php //echo Form::dbSelect('salida.hilodestino_id','nombre,abr',array("hilodestino",'find'));?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="CL">Proveedor</label>
    <div class="controls">
    	<input id="CL" />
      <?php echo Form::hidden('salida.tesdatos_id')?>
    </div>
  </div>
  
  <div class="control-group">
  <label class="control-label" for="salida_tesdatosdirecciones_id">Direccion de Fiscal:</label>
  <div class="controls" id="direccion_fiscal">
  
  </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="salida_direccion_entrega">Direccion de Entrega</label>
    <div class="controls">
      <?php echo Form::text('salida.direccion_entrega','class="span10"');//finiciotraslado?><span id="script_autocargar"></span>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="salida_femision">Fecha de Emision:</label>
    <div class="controls">
      <?php echo Calendar::selector('salida.femision');//finiciotraslado?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="salida_direccion_entrega">Fecha de Traslado</label>
    <div class="controls">
      <?php echo Calendar::selector('salida.finiciotraslado');//finiciotraslado?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Transportista: <?php echo Ajax::link($module_name.'/transportistas/crear_externo','Transportista Externo!','otro','ventana')?></label>
    <div class="controls">
      <?php echo Form::text('prodetalletransportes.protransportistas_id')?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Transporte: <?php echo Ajax::link($module_name.'/transportes/crear_externo','Transporte Externo!','otro','ventana')?></label>
    <div class="controls">
      <?php echo Form::text('prodetalletransportes.protransportes_id')?>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
       <div class="form-actions"><button type="submit" class="btn btn-primary">Generar</button> </div>
    </div>
  </div>
<?php echo Form::close();?>
</div>
<div class="clear"></div>
</div>
<script type="text/javascript">
$(document).ready(function()
{
	$("#CL").tokenInput("/<?php echo $module_name?>/salidas/buscarproveedor", 
		{
			tokenLimit: 1,
			minChars: 2,
	
			onAdd: function (item){
			   $("#salida_tesdatos_id").val(item.id);
			   $( "#direccion_fiscal" ).load( "/<?php echo $module_name?>/salidas/direcciones_clientes/"+item.id );
			   //$("#BC").hide();
			   //GrabarCliente();
			},
			onDelete: function (item) {
			}
		});
		
		/*transporte*/
		$("#prodetalletransportes_protransportes_id").tokenInput("/<?php echo $module_name?>/salidas/transportes", 
		{
			tokenLimit: 1,
			minChars: 2,
		});
		
		/*transportistas*/
		
		$("#prodetalletransportes_protransportistas_id").tokenInput("/<?php echo $module_name?>/salidas/transportistas", 
		{
			tokenLimit: 1,
			minChars: 2,
	    });
		$('.ventana').live("click",function(){
		$("#myModal").modal("show");});
});
</script>
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Nuevo </h3>
  </div>
  <div class="modal-body" id="otro">
  </div>
  <div class="modal-footer">
  </div>
</div>
