
<div class="card">
<h1>Rollos para Venta <span>Listado de rollos en almacen de ventas</span></h1>
</div>

<div class="form-actions">
<?php echo Menu::menuControl($action_name);?>
</div>
<?php View::content()?>

<div class="input-prepend input-append">
 <span class="add-on">Buscar :</span>
 <input type="search" id="txtBuscar" autofocus="" placeholder="Digite el texto que desea encontrar y presione ENTER. Para cancelar la tecla ESCAPE." class="span7 input-medium search-query">
 <?php 
  echo Form::dbSelect('anchos','ancho',array('prorollos','getMetros','VENTA'),'Seleccione el ancho','',$ancho)?>

<a href="javascript:;" id="ver-anchos" class="btn">Filtrar</a>
</div>
<?php echo Sp::imprimir('Rollos en Venta - ','P',array('P'=>'1','EX'=>1));?> 
<div id="ver"></div>
<div class="card-body">
<table width="100%" border="0" cellpadding="0" cellspacing="0" class="table table-bordered table-striped" id="exportar_excel">
<thead>
  <tr>

    <th width="114" align="left">N. Rollo.</th>
    <th width="40" align="left">N. Vta.</th>
    <th width="101" align="left">Art.</th>
    <th width="31" align="left">Color</th>
    <th width="43" align="left">MTS</th>
    <th width="47" align="left">Peso</th>
    <th width="47" align="left">Ancho</th>
    <th width="47" align="left">A.Util</th>
    <th width="47" align="left">Ubi.</th>
    <th width="268" align="left">Ingresar Datos!</th>
    <th width="174" align="left">A Reproceso</th>
  </tr>
</thead>
<tbody>
  <?php $n=0;foreach($rollos as $item){$n++;
?>
  <tr title="<?php //echo $item->getTesdetalleingresos()->getTesingresos()->getTesdatos()->razonsocial?>">
    <td><?php if(empty($item->codigo)){
	if(empty($item->getTesproductos()->codigo_ant))$COD=$item->getTesproductos()->codigo; else $COD=$item->getTesproductos()->codigo_ant;
	}else
	{
		$COD=$item->codigo;
	}
	echo $COD?>-<?php if(!empty($item->tescolores_id))echo $item->getTescolores()->codigo?>-<?php echo $item->calidad?>-<?php echo $item->numeroventa;?></td>
    <td><?php echo $item->numeroventa;?></td>
    <td><?php echo $item->getTesproductos()->nombre?><?php //echo $item->getTesproductos()->detalle?></td>
    
    <td width="31"><?php if(is_numeric($item->color)){echo $item->getTescolores()->nombre;}else{ echo $item->color;}?> <?php //echo $item->tescolores_id?></td>
    <td><?php if(!empty($item->metros))echo number_format($item->metros,2,'.',' ');?></td>
    <td><?php if(!empty($item->peso))echo number_format($item->peso,2,'.',' ')?></td>
    <td><?php if(!empty($item->ancho))echo number_format($item->ancho,2,'.',' ')?></td>
    <td><?php if(!empty($item->anchoutil))echo number_format($item->anchoutil,2,'.',' ')?></td>
    <td><?php if(!empty($item->ubicacion))echo$item->ubicacion?></td>
    <?php /*?><td><?php if(!empty($item->tesordendecompras_id))echo $item->getTesordendecompras()->numero_interno;else echo "Sin O.C.";?></td><?php */?>
    <td>No. de Rollos? <?php echo Form::hidden('producto_id-'.$item->id,'',$item->tesproductos_id);echo Form::text('numero-'.$item->id,'size="1" placeholder="rollos" ')?> <span id="<?php echo $item->id?>" class="btn btn-primary enviar"> Generar</span></td>
    <td><?Php echo Html::linkAction('enviar_reprocesos/'.$item->id,'A Reproceso','class="btn btn-warning"');?><?Php echo Html::linkAction('modificar_rollos/'.$item->id,'Editar','class="btn btn-info"');?>
    <?php if(Auth::get('id')==3){
		if(!empty($item->prorollos_id))echo Html::link("$module_name/rollos/unirollos/$item->prorollos_id/","Unir","class='btn btn-info'");
		} ?>
    </td>
  </tr>
  <?php }?>
</tbody>
</table>
</div>
<script type="text/javascript">
$(document).ready(function()
{
		
//hacemos la busqueda en el evento search del control de busqueda
	$('#txtBuscar').on('search',function(){
		//le decimos a la funcion que busque en la tabla tblTabla el
		//valor que contiene el campo actual
		$.fntBuscarEnTabla($(this).val(),'exportar_excel');
		
	});

});
</script>
<script type="text/javascript">
$(document).ready(function()
{
$(".enviar").live("click",function(){
	
	var id =$(this).attr('id');
	var numero = $("#numero-"+id).val();/*producto_id*/
	var producto_id = $("#producto_id-"+id).val();
	if(confirm("Esta por generar "+numero+" rollos del rollo principal "+" ("+id+")")){
	if(numero>1){
	$.ajax({
            type:"POST",
            url:"/<?php echo $module_name?>/tintoreria/divir_venta/"+id+"/"+numero,
            beforeSend:function(){
              $("#loading").show();
            },
            success:function(response){
                $("#loading").hide();
				alert(response);
				url = "/<?php echo $module_name?>/tintoreria/ver_divir_venta/"+id+'/'+producto_id+'/'+response;  
				$(location).attr('href',url); 
            }
 
          	});
		
	}else
	{
		alert('Ingreso un numero mayor a 1');
	}
	}else
	{
		return false;
	}
	});
});
</script>
<script type="text/JavaScript">
$(document).ready(function(){
  $("#ver-anchos").click(function(event){
    var anchos = $("#anchos").find(':selected').val();
    location.href = '/<?php echo $module_name?>/tintoreria/rollos_venta/'+anchos;
  });
});
</script>