<div class="card">
    <h1><?php echo $titulo?><span> Salida de Rollos <?php echo Session::get('DOC_NOMBRE')?></span></h1>
</div>
<div class="form-actions">
<?php echo Menu::menuControl($action_name);?> <?php echo Html::linkAction($url."/", 'Nueva '.Session::get('DOC_NOMBRE'),'class="btn btn-primary"') ?>
</div>
<div class="menu">
<ul><li><a>Año 
<select id="anio">
<?php
for($i=2011;$i<=2020;$i++)
{
	$selec='';
	if($anio==$i){
	$selec=' selected="selected"';
	}
	echo '<option value="'.$i.'" '.$selec.'>'.$i.'</option>';
}
?>
</select> 
</a></li></ul>
<?php 
$mes_actual=date('Y-m');
foreach($meses as $clave => $mes):
if($anio.'-'.$clave<=$mes_actual){
$class='';
if($mes_activo==$clave)$class=' active';
echo '<ul>';
echo '<li><a class="enviar'.$class.'" id="mes-'.$mes.'" href="javascript:;" data-id="'.$anio.'-'.$clave.'-01">'.$mes.'</a></li>'; 
echo '</ul>';
}
endforeach;?>
</div>
<div class="input-prepend input-append">
  <span class="add-on">Buscar :</span>
 <input type="search" id="txtBuscar" autofocus="" placeholder="Digite el texto que desea encontrar y presione ENTER. Para cancelar la tecla ESCAPE." class="span7 input-medium search-query">
</div>
<?php echo Sp::imprimir('Salidas Telas - ','P',array('P'=>'1'));?> 

<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>
<table id="exportar_excel" width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
<caption>Guias de salida (Telas-Rollos)</caption>
  <tr>
	<th width="67" align="left">Fecha.</th>
    <th width="84" align="left">Número Doc.</th>
    <th width="138" align="left">Proveedor</th>
    <th width="209" align="left">Productos </th>
    <th width="60" align="center">Acciones</th>
  </tr>
<?php $number=0;
foreach($salidas as $item){ 
$simbolo="S/. ";

switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

$number++;?>
  <tr id="<?php echo $item->id?>">
  <td height="20"><?php echo Sp::formatFecha('%d / %m / %Y',$item->femision)?></td>
  	<td height="20"><?php echo $item->serie?>-<?php echo $item->numero?></td>
    <td><?php echo $item->getTesdatos()->razonsocial?></td>
    <td>
    <small style="color:#666; font-size:10px !important; font-style:italic; ">
	<?php
    
	$n=0;$m=0;
	foreach($item->getTesdetallesalidas() as $det)
	{
		if($det->tesproductos_id!=0){$n++;
		echo $det->getTesproductos()->nombre;if(count($item->getTesdetallesalidas())>$n){echo ", ";}
		}else{
			echo $det->concepto;
			}
	}
	?>
    </small>
    </td>
   
   <td align="center"> 
   	<?php if($item->estadosalida=="Editable")echo Html::linkAction('cargarsalida/'.$item->id.'/',Html::img("figuras/editar.png",'EDITAR','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar Guia - 002 - Hilos"')?>
	<?php echo Html::linkAction('cargarsalida/'.$item->id.'/versalida',Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Ver e Imprimir Guia - 002 - Hilos"')?>
    <?php /*if(Auth::get('id')==3 || Auth::get('id')==12){*/echo Html::linkAction("cargarsalida/".$item->id."/crearprocesos",Html::img("figuras/procesos.png",'Procesos','style="width: 20px;margin-left:1px;margin-right:1px;"'), 'onclick="return confirm(\'¿Está seguro?\')" title="Procesos Editar"');/*}*/?>
    <?php //echo Html::linkAction("ver/$item->id/$page",Html::img("figuras/ver.png",'Eliminar','style="width: 20px;margin-left:1px;margin-right:1px;"'));?>
	<?php if($item->estadosalida!='ANULADO')echo Html::linkAction("anularguias/$item->id/",'X','class="btn btn-danger" title="Anular" onclick="return confirm(\'¿Está seguro de anular esta Guia ?\')"'); else echo "Anulado";?>
    </td>
  </tr>
<?php }?>
</table>
</div>
<script type="text/javascript">
$(document).ready(function() {

	$('#txtBuscar').on('search',function(){
		//le decimos a la funcion que busque en la tabla tblTabla el
		//valor que contiene el campo actual
		$.fntBuscarEnTabla($(this).val(),'exportar_excel');
		
	});
	$("#anio").change(function(event){
    	var id = $("#anio").find(':selected').val();
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/'+id;
     });
	$(".enviar").click(function()
	{
		var fecha = $(this).attr('data-id');
		var F=fecha.split('-');
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/'+F[0]+'/'+F[1];
	});
	
});
</script>