<br />
<br />
<br />
<table width="255" border="0" cellspacing="1">
  <tr>
    <td width="169" align="right">01:30:25</td>
    <td width="79">&nbsp;</td>
  </tr>
</table>
<table width="113%" border="0" cellspacing="1">
  <tr>
    <td align="right">&nbsp;</td>
    <td>&nbsp;</td>
    <td width="331" rowspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td width="141" height="10" align="right"><?php echo $femision;?></td>
    <td width="219" align="right"><?php echo $finiciotraslado?></td>
  </tr>
</table>
<br />
<br />

<table width="113%" border="0" cellspacing="0">
  <tr>
    <td width="50" align="right">&nbsp;</td>
    <td width="328" align="lefth">los alfareros 136 urbanizacion el artezano ate</td>
    <td width="317" align="lefth">los alfareros 136 el artesano - ate</td>
  </tr>

</table>
<br />
<br />

<table width="113%" border="0" cellspacing="1">
  <tr>
    <td width="43" height="28">&nbsp;</td>
    <td width="221" valign="bottom">maritza</td>
    <td width="10">&nbsp;</td>
    <td width="112" valign="bottom">001246-25</td>
    <td width="40">&nbsp;</td>
    <td width="256" valign="bottom">camioneta foton pickup</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>la molina</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>ate</td>
    <td>&nbsp;</td>
    <td>1044220498</td>
    <td>&nbsp;</td>
    <td>007528398</td>
  </tr>
</table>
<br />
<table width="106%" border="0" cellspacing="1">

  <tr>
    <td width="214" align="center">contado</td>
    <td width="105">vn-2546</td>
    <td width="60">0000</td>
    <td width="84" align="center">001</td>
    <td width="91" align="lefth">001-0015171</td>
    <td width="84" align="left">03/11/2012</td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="1">
  <tr>
    <td width="7%">&nbsp;</td>
    <td width="5%">&nbsp;</td>
    <td width="4%">x</td>
    <td width="7%">&nbsp;</td>
    <td width="3%">&nbsp;</td>
    <td width="4%">&nbsp;</td>
    <td width="20%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="8%">&nbsp;</td>
  </tr>
</table>
<br />
<table width="100%" border="0" cellspacing="1">
  <tr>
    <td width="94" align="center"><p>1.579-0164-13</p>
    <p>1.579-0164-101</p>
</td>
    <td width="59" align="center"><p>105.00</p>
    <p>48.50</p>
</td>
    
    <td width="53" align="center"><p>Mts</p>
    <p>Mts</p>
</td>
    <td width="401"><p>Tela para cortina Tull bashir Perla light</p>
    <p>Tela para cortina Tull bashir Perla light</p>
</td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="1">
  <tr>
    <td width="13%" align="right">&nbsp;</td>
    <td width="12%" align="center">500.000</td>
    <td width="8%" align="center">Mts</td>
    <td width="67%" align="center" >&nbsp;</td>
  </tr>
</table>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<table width="113%" border="0" cellspacing="1">
  <tr>
    <td width="9%">&nbsp;</td>
    <td width="89%">roberto</td>
    <td width="1%">&nbsp;</td>
    <td width="1%">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>textil santa patricia</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>los alfareros</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>20101619240</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>d4m-848</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
