<span class="print btn btn-primary"> Print </span> <?php echo Html::linkAction('versalida','Regresar <i class="icon-hand-left"></i>','class="btn btn-xs"')?>
<div class="card-body">
<br />
<br />
<br />
<br />
<table width="255" border="0" cellspacing="1">
  <tr>
    <td width="169" align="right"><?php echo date("H:i:s")?></td>
    <td width="79">&nbsp;</td>
  </tr>
</table>
<table width="113%" border="0" cellspacing="1">
  <tr>
    <td align="right">&nbsp;</td>
    <td>&nbsp;</td>
    <td width="319" rowspan="2">&nbsp;</td>
  </tr>
  <tr>
    <td width="152" height="31" align="right" valign="middle"><?php echo Sp::formatFecha('%d / %m / %Y',$salida->femision)?></td>
    <td width="220" align="right" valign="middle"><?php echo Sp::formatFecha('%d / %m / %Y',$salida->finiciotraslado)?></td>
  </tr>
</table>
<br />
<br />
<table width="113%" border="0" cellspacing="0">
  <tr>
    <td width="47" align="right">&nbsp;</td>
    <td width="326" align="lefth"><?php echo $empresa->direccion?></td>
    <td width="322" align="lefth"><?php echo $salida->direccion_entrega?></td>
  </tr>

</table>
<br />
<br />
<table width="113%" border="0" cellspacing="1">
  <tr>
    <td width="48" height="45">&nbsp;</td>
    <td width="120" valign="bottom"><?php echo $salida->getTesdatos()->razonsocial?></td>
    <td width="10">&nbsp;</td>
    <td width="157" valign="bottom"><?php echo $salida->getTesdatos()->codigo?></td>
    <td width="19">&nbsp;</td>
    <td width="328" valign="bottom"><?php echo $prodetalletransportes->getProtransportes()->marca?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><?php echo $salida->getTesdatos()->direccion?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><?php echo $salida->getTesdatos()->distrito?></td>
    <td>&nbsp;</td>
    <td><?php echo $salida->getTesdatos()->ruc?></td>
    <td>&nbsp;</td>
    <td><?php echo $prodetalletransportes->getProtransportistas()->numerobrevete?></td>
  </tr>
</table>
<br />
<table width="106%" border="0" cellspacing="1">

  <tr valign="bottom">
    <td width="217" height="29" align="center" valign="bottom">CONTADO</td>
    <td width="78" valign="bottom"><?Php echo $salida->npedido?></td>
    <td width="103">LA INDICADA</td>
    <td width="51" align="center"> 00<?php echo $salida->getAclusuarios()->id?></td>
    <td width="112" align="center"> - </td>
    <td width="77" align="left">&nbsp;</td>
  </tr>
</table>
<br />

<table width="100%" border="0" cellspacing="1">
  <tr>
    <td width="7%" height="21">&nbsp;</td>
    <td width="5%">&nbsp;</td>
    <td width="4%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="4%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="16%">X</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="7%">&nbsp;</td>
    <td width="8%">&nbsp;</td>
  </tr>
</table>
<br />
<br />

<table width="100%" border="0" cellspacing="1">

  <?php $n=0;$totalkilos=0;
  foreach($detalles as $item){
	  $totalkilos=$totalkilos+$item->pesoneto;
	  $n++;?>
  <tr>
    <td width="94" align="center"><?php echo $n?>. <?php if(empty($item->getProrollos()->prorollos_id)){echo $item->getProrollos()->numero?>-M<?php echo $item->getProrollos()->maquina_numero;}else{echo $item->getProrollos()->codigo?>-<?php echo $item->getProrollos()->numeroventa; echo ' '.$item->getProrollos()->getNprocesos($item->prorollos_id);}?></td>
    <td width="59" align="center"><?php echo $item->pesoneto?></td>
    <td width="53" align="center">KLS</td>
    <td width="401"><?php echo $item->cantidad?> <?Php //echo $item->getTesunidadesmedidas()->simbolo?>/ <?php echo $item->getTesproductos()->codigo?><?php //echo strtoupper($item->getTesproductos()->getTestipoproductos()->detalle)?><?php echo $item->getTesproductos()->detalle?>, <?php echo $item->getTesproductos()->nombre?> <?Php //echo $item->getTescolores()->nombre?></td>
  </tr>
  <?php }?>
  <tr>
    <td width="94" align="center"></td>
    <td width="59" align="center"><?php echo $totalkilos?></td>
    <td width="53" align="center">KILOS</td>
    <td width="401"> </td>
  </tr>
</table>
<br />
<div style="width:300px; float:left; margin-left:50px;">
    TIPO DE FIBRA: <?php echo $proceso->tipo_de_fibra;?><br />
    <?PHP if(!empty($proceso->tescolores_id)){?>COLOR: <?php echo $proceso->getTescolores()->nombre;}?><br />
    ANCHO REQUERIDO: <?php echo $proceso->ancho_requerido;?><br />
    RENDIMIENTO: <?php echo $proceso->rendimiento;?><br />
    
    OBSERVACIONES: <?php echo $proceso->detalle;?>
</div> 
<div style="width:250px;float:left;">
    ACABADOS ESPECIALES:<br />
	<?php foreach($detalle_A as $det){?>
    <?php echo $det->getProacabados()->nombre;?>&nbsp;&nbsp;<i class="icon-ok"></i><br />
    <?php }?>
</div> 
<div style="clear:both;"></div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<table width="113%" border="0" cellspacing="1">
  <tr>
    <td width="9%">&nbsp;</td>
    <td width="89%"></td>
    <td width="1%">&nbsp;</td>
    <td width="1%">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><?php echo $prodetalletransportes->getProtransportistas()->nombre?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><?php echo $prodetalletransportes->getProtransportistas()->direccion?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><?php echo $prodetalletransportes->getProtransportistas()->ruc?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><?php echo $prodetalletransportes->getProtransportes()->numeroplaca?></td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</div>