<?php View::content() ?>
<div class="card">
	<div class="card-header">
		<h3 class="card-title">Cheques Emitidos Listado por mes!</h3>
		<div class="card-tools">
			<?php echo Menu::menuCheques(); ?>
		</div>
	</div>
	<div id="ver_resultado"></div>
	<div class="card-body">
		<?php echo Calendar::getMeses($anio, $meses, $mes_activo) ?>

		<?php echo Sp::imprimir('Abonos Adelanto - ', 'P'); ?>

		<div class="input-prepend input-append">
			<span class="add-on">Buscar :</span>
			<input type="search" id="txtBuscar" autofocus="" placeholder="Digite el texto que desea encontrar y presione ENTER. Para cancelar la tecla ESCAPE." class="form-control input-medium search-query">
		</div>
		<table id="exportar_excel" width="99%" class="table table-bordered table-striped">
			<caption>Cheques del Mes!</caption>
			<tr>
				<td width="17">Nº</td>
				<td width="63">F. Emision.</td>
				<td width="196">Cliente</td>
				<td width="91">Número Doc.</td>
				<td width="68">Sub-total</td>
				<td width="82">Total</td>
			</tr>
			<?php $number = 0;
			foreach ($cheques as $item) {
				$simbolo = "S/. ";

				switch ($item->tesmonedas_id) {
					case 1:
						$simbolo = 'S/. ';
						break;
					case 2:
						$simbolo = '$. ';
						break;
					case 4:
						$simbolo = 'S/. ';
						break;
					case 5:
						$simbolo = '$. ';
						break;
					case 0:
						$simbolo = 'S/. ';
						break;
				}

				$number++; ?>
				<tr id="<?php echo $item->id ?>">
					<td height="20"><?php echo $number ?></td>
					<td height="20"><?php echo Sp::formatFecha('%d / %m / %Y', $item->femision) ?></td>
					<td height="20"><?php echo $item->getTesdatos()->razonsocial ?></td>
					<td><?php if (!empty($item->serie)) echo $item->serie . '-'; ?><?php echo $item->numero ?> (<?php echo $item->estadoingreso ?>)</td>
					<td><?php if ($item->totalconigv != 'NaN.00' && !empty($item->totalconigv)) echo $simbolo . number_format($item->totalconigv - $item->igv, 2, '.', '');
						else echo ('S/ 00.00'); ?></td>
					<td><?php if ($item->totalconigv != 'NaN.00' && !empty($item->totalconigv)) echo $simbolo . number_format($item->totalconigv, 2, '.', '');
						else echo ('S/ 00.00') ?></td>
				</tr>
			<?php } ?>
		</table>

	</div>
	<script type="text/javascript">
		$(document).ready(function() {
			$("#anio").change(function(event) {
				var id = $("#anio").find(':selected').val();
				location.href = '/<?php echo $module_name ?>/<?php echo $controller_name ?>/index/' + id;
			});
			$(".enviar").click(function() {
				var fecha = $(this).attr('data-id');
				var F = fecha.split('-');
				location.href = '/<?php echo $module_name ?>/<?php echo $controller_name ?>/index/' + F[0] + '/' + F[1];
			});
			$('#txtBuscar').on('search', function() {
				//le decimos a la funcion que busque en la tabla tblTabla el
				//valor que contiene el campo actual
				$.fntBuscarEnTabla($(this).val(), 'exportar_excel');

			});
		});
	</script>
</div>