<?php View::content() ?>
<div class="card">
  <div class="card-header">
    <h13 class="card-title">Cheques Registrados <?php echo Auth::get('nombres') ?></h3>
      <div class="card-tools">
        <?php echo Menu::menuCheques(); ?>
      </div>

  </div>

  <div class="card-body">
    <div id="ver_resultado"></div>
    <table id="exportar_excel" width="99%" class="table table-bordered table-striped">
      <caption style="font-size:14px; color:#333; font-weight:bold;">
        <pre>Cheques del Mes!</pre>
      </caption>
      <tr>
        <th width="17">Nº</th>
        <th width="63">F. Emision.</th>
        <th width="196">Cliente</th>
        <th width="119">Banco</th>
        <th width="119">Fecha de Cobro</th>
        <th width="159">Número Doc.</th>
        <th width="86">Total</th>
        <th width="153">Accion</th>
      </tr>
      <?php $number = 0;
      foreach ($cheques as $item) {
        $simbolo = "S/. ";

        switch ($item->tesmonedas_id) {
          case 1:
            $simbolo = 'S/. ';
            break;
          case 2:
            $simbolo = '$. ';
            break;
          case 4:
            $simbolo = 'S/. ';
            break;
          case 5:
            $simbolo = '$. ';
            break;
          case 0:
            $simbolo = 'S/. ';
            break;
        }

        $number++; ?>
        <tr id="<?php echo $item->id ?>">
          <td height="20"><?php echo $number ?></td>
          <td height="20"><?php echo Sp::formatFecha('%d / %m / %Y', $item->getTesingresos()->femision) ?></td>
          <td height="20"><?php echo $item->getTesingresos()->getTesdatos()->razonsocial ?></td>
          <td><?php echo $item->getTesbancos()->nombre ?></td>
          <td><?php echo Sp::formatFecha('%d / %m / %Y', $item->fecha_cobro) ?></td>
          <td><?php echo $item->numerocheque ?> (<?php if (!empty($item->estadocheque)) echo $item->estadocheque;
                                                else echo "Sin registrar"; ?>)</td>
          <td align="right" valign="top"><?php if ($item->monto != 'NaN.00' && !empty($item->monto)) echo $simbolo . number_format($item->monto, 2, '.', '');
                                          else echo ('S/ 00.00') ?></td>
          <td><?php echo Html::linkAction('registrar/' . $item->id, 'Registrar', 'class="btn btn-xs"'); ?></td>
        </tr>
      <?php } ?>
    </table>

  </div>
</div>