<div class="page-header">
    <h1>Crear Usuario</h1>
</div>      
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('usuario.id') ?>
<div class="control-group">
    <label class="control-label">Nombre de Usuario (Login)* : </label>
    <div class="controls">
        <?php echo Form::text('usuario.usuario') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Contrase&ntilde;a* : </label>
    <div class="controls">
        <?php echo Form::pass('usuario.clave') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Volver a escribir Contrase&ntilde;a* : </label>
    <div class="controls">
        <?php echo Form::pass('usuario.clave2') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Nombre Completo* : </label>
    <div class="controls">
        <?php echo Form::text('usuario.nombres') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Correo Electronico* : </label>
    <div class="controls">
        <?php echo Form::text('datos.correo') ?> 
    </div>
</div>
<div class="control-group">
    <label class="control-label">Rol del Usuario* : </label>
    <div class="controls">
        <?php echo Form::dbSelect('usuario.aclroles_id', 'rol') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Empresa* : </label>
    <div class="controls">
        <?php echo Ajax::dbSelect('usuario.aclempresas_id', 'nombre',array('aclempresas','find','conditions: activo=1'),'areas','admin/usuarios/areas','Seleccione...') ?>
    </div>
</div>
<div class="control-group" id="areas">
<label class="control-label">Areas* : </label>
<select><option>Seleccione un Empresa</option></select>
</div>
<div class="control-group">
<label class="control-label">Cargos* : </label>
<?php echo Form::dbSelect('datos.placargos_id', 'nombre') ?>
</div>
<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
