<div id="mensajes_flash" >        
  <?php View::content() ?>
</div> 
<div class="card">
  <div class="card-header">
      <h3 class="card-title"><i class="fa fa-users"></i> Usuarios del Sistema</h3>
      <div class="card-tools">
        
      <?php echo Html::linkAction("crear", 'Crear Usuario','class="btn btn-xs btn-primary"') ?>
      </div>
  </div>
  <table class="table table-bordered table-striped">
    <tr>
      <td>Nº</td>
      <td>Usuario</td>
      <td>Nombres</td>
      <td>Correo Electronico</td>
      <td>Rol que Posee</td>
      <td>Acciones</td>
    </tr>
  <?php $n=0;
  foreach($usuarios->items as $item){ $n++;?>
    <tr>
      <td><?php echo $n?></td>
      <td><?php echo $item->usuario?></td>
      <td><?php echo $item->nombres?></td>
      <td><?php echo $item->getAcldatos()->correo?></td>
      <td><?php echo $item->getAclroles()->rol?></td>
      <td>
      <?php 
    if($item->activo=='0'){
    echo Html::linkAction('activar/'.$item->id,'<i class="fa fa-eye"></i>','');
    }else{
    echo Html::linkAction("desactivar/$item->id",'<i class="fa fa-eye-slash"></i>', 'onclick="return confirm(\'¿Está seguro?\')"');}?>
      <?php echo Html::linkAction('editar/'.$item->id,'<i class="fa fa-edit"></i>','')?>
      <?php echo Html::linkAction("eliminar/$item->id",'<i class="fa fa-solid fa-trash"></i>', 'onclick="return confirm(\'¿Está seguro?\')"');?>
      </td>
    </tr>
  <?php }?>
  </table>
  <?php View::partial('paginators/extended', false, array('page' => $usuarios ,'url' => Router::get('controller_path').'/index')); ?>
</div>  
  