<div class="card-header">
    <h1>Configuraci&oacute;n de Perfil</h1>
</div>       
<?php View::content() ?>
<ul class="nav nav-tabs">
    <li class="active"><a href="#datos-personales" data-toggle="tab">Datos Personales</a></li>
    <li><a href="#clave" data-toggle="tab">Contrase&ntilde;a</a></li>
</ul>
<div class="tab-content">
    <div id="datos-personales" class="tab-pane active">
        <?php echo Ajax::form('res-datos-personales', NULL, 'form-horizontal') //Form::open() ?>
        <fieldset>
            <legend>Configurar Datos Personales</legend>
            <div id="res-datos-personales"></div>
            <div class="control-group">                
                <label class="control-label">Nombre Completo* : </label>
                <div class="controls">
                    <?php echo Form::text('usuario1.nombres','size="40"') ?>
                </div>
            </div>
            <div class="control-group">                
                <label class="control-label">Correo Electronico* : </label>
                <div class="controls">
                    <?php echo Form::text('datos.correo','size="40"') ?>
                </div>
            </div>
            <div class="control-group">                
                <label class="control-label">Apellido Paterno : </label>
                <div class="controls">
                    <?php echo Form::text('datos.appaterno','size="40"') ?>
                </div>
            </div>
            <div class="control-group">                
                <label class="control-label">Apellido materno : </label>
                <div class="controls">
                    <?php echo Form::text('datos.apmaterno','size="40"') ?>
                </div>
            </div>
            <div class="control-group">                
                <label class="control-label">DNI : </label>
                <div class="controls">
                    <?php echo Form::text('datos.dni','size="40"') ?>
                </div>
            </div>
            <div class="control-group">                
                <label class="control-label">Telefonos : </label>
                <div class="controls">
                    <?php echo Form::text('datos.telefono','size="40"') ?>
                </div>
            </div>
            <div class="control-group">                
                <label class="control-label">Celulares : </label>
                <div class="controls">
                    <?php echo Form::text('datos.celular','size="40"') ?>
                </div>
            </div>
            <div class="control-group">                
                <label class="control-label">Fecha Nacimiento : </label>
                <div class="controls">
                    <?php
				 echo Calendar::selector('datos.fnacimiento')?>
                </div>
            </div>
            <div class="control-group">                
                <label class="control-label">Direccion : </label>
                <div>
				<?php echo Form::text('datos.direccion','size="60"') ?>
                </div>
            </div>
            <div class="form-actions">
                <?php echo Form::submit('Guardar Cambios', 'name="datos_personas" class="btn btn-xs btn-primary"') ?>
            </div>
        </fieldset>
        <?php echo Form::close() ?>
    </div>
    <div id="clave" class="tab-pane">
        <?php echo Ajax::form('res-clave', NULL, 'form-horizontal')//Form::open() ?>
        <fieldset>
            <legend>Cambiar Contrase&ntilde;a</legend>
            <div id="res-clave"></div>
            <div class="control-group">
                <label class="control-label">Contrase&ntilde;a Actual * : </label>
                <div class="controls">
                    <?php echo Form::pass('usuario2.clave_actual') ?>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Nueva Contrase&ntilde;a* : </label>
                <div class="controls">
                    <?php echo Form::pass('usuario2.nueva_clave') ?>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Volver a escribir Contrase&ntilde;a* : </label>
                <div class="controls">
                    <?php echo Form::pass('usuario2.nueva_clave2') ?>
                </div>
            </div>
            <div class="form-actions">
                <?php echo Form::submit('Guardar Cambios', 'name="cambiar_clave" class="btn btn-xs btn-primary"') ?>
            </div>
        </fieldset>
        <?php echo Form::close() ?>
    </div>
    
</div>