
<div class="card">
   <h1>Proveedores de la Empresa <span><?Php echo Session::get('EMPRESAS_NOMBRE')?></span></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="form-actions">
    <?php echo Html::linkAction('crear/'.$campo.'/'.$direccion, 'Nuevo Proveedor','class="btn btn-xs btn-primary"') ?>			    <?php echo Html::linkAction('listado/'.$campo.'/'.$direccion.'/', 'Volver','class="btn btn-xs btn-info"') ?> 
</div>
    <?php echo Sp::imprimir('Reportes Proveedores - ','P');?> 
<div id="ver_resultado"></div>
<div class="card-body">
<table width="90%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped" id="exportar_excel">
  <tr>
  	<th width="17">Nº</th>
    <th width="64">Codigo</th>
    <th width="53">NºAnt</th>
    <th width="77">Razon social</th>
    <th width="81">Ruc</th>
    <th width="107">Direccion </th>
    <th width="55">Telefono</th>
    <th width="26">Pais</th>
    <th width="57">Contacto</th>
  </tr>
<?php $n=0;
foreach($datos as $item){ $n++;?>
  <tr id="<?php echo $item->id?>" title="<?php echo $item->id?>">
  	<td><?php echo $n?></td>
    <td><?php echo $item->codigo?>-<?php echo $item->sufijo?></td>
    <td><?php echo $item->codigo_ant?></td>
    <td><?php echo $item->razonsocial?></td>
    <td><?php echo $item->ruc?></td>
    <td><?php echo $item->direccion?></td>
    <td><?php echo $item->telefono?></td>
    <td><?php echo $item->pais?></td>
    <td><?php echo $item->contacto?></td>    
  </tr>
<?php }?>
</table>
</div>
<script type="text/javascript">
$(document).ready(function() {
	$('#txtBuscar').on('search',function(){
		//le decimos a la funcion que busque en la tabla tblTabla el
		//valor que contiene el campo actual
		$.fntBuscarEnTabla($(this).val(),'exportar_excel');
	});
});
</script>