<?php
View::content();
echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<script type="text/javascript">
/*envio dew Formulario PROFORMAS*/

$(document).ready(function()
{
	$("#metroprogramados").blur(function()
	{
		var n_m=parseInt($(this).val());
		var N_MT=parseInt($("#metros_total").html());
		if(n_m>N_MT)
		{
			$('.alert-error').show();
			$('#finalizar').show();
		}else{
			$('.alert-error').hide();
			$('#finalizar').hide();
			}
		
	});
	
	//alert($("#tesordendecompras_id").val());
	$(".grabardetalle").click(function()
	{
	 var n_m=$('#metroprogramados').val();
	 var N_MT=$("#metros_total").html();
	 
	 var dataString=$("#prodetalleproduccion").serialize();
	 if($("#tesproductos_id").val() && $("#tesordendecompras_id").val())
	 {
		//alert(n_m+'>'+N_MT)
		if(n_m!='')
		{
			if(parseInt(n_m)>parseInt(N_MT))
			{
				$('.alert-error').html('No hay suficiente hilo en el plegador');
				$('.alert-error').show();
					
			}else
			{
			 $.ajax({
				type:"POST",
				url:"/santapatricia/produccion/grabardetalle/1",
				data:$("#prodetalleproduccion").serialize(),
				beforeSend:function()
				{
				  $("#loading").show();
				},
				success:function(response)
				{
					//alert(response);
					$("#loading").hide();
					$("#detalle_listado").html(response);
					$("#metroprogramados").val('');
					$("#observaciones").val('');
					var total=parseInt($("#metros_total").html())-parseInt(n_m);
					 //alert(N_MT);
					// alert(total);
					$("#metros_total").html(total);
					$("#trama").tokenInput("clear");
					$("#tesproductos_id").tokenInput("clear");
					$("#tescolores_id").tokenInput("clear");
					
				} 
			});
		$('.alert-error').hide();
		}
	   }else
	   {
		   $('.alert-error').html('Orden de compra y productos no pueden estar vacio');
		   $('.alert-error').show();
	   }
	 }
	 return false;
	});
	$("#limipar").click(function(){
		
		//$("#trama").tokenInput("clear");
		//$("#tesproductos_id").tokenInput("clear");
		//$("#tescolores_id").tokenInput("clear");
		//$("#metroprogramados").val('');
		$("#observaciones").val('');
		
		});  
/*
Buscar Artículo
*/
	$("#trama").tokenInput("<?php echo "/santapatricia/produccion/producto/3"?>", 
		{
		minChars: 1,/*preventDuplicates: true,*/
		onAdd: function (item) {
		  },
		onDelete: function (item) {
		}
	});
	$("#tesproductos_id").tokenInput("<?php echo "/santapatricia/produccion/producto/1"?>", 
		{
			
		tokenLimit: 1,
		minChars: 1,preventDuplicates: true,
		onAdd: function (item) {
			//alert(item.id);
			$("#tesproductos_id").val(item.id);
		  },
		onDelete: function (item) {
		}
	});

$("#tescolores_id").tokenInput("<?php echo "/santapatricia/ingresos/colores"?>", 
	{	
		tokenLimit: 1,
		minChars: 1,
		preventDuplicates: true,
		onAdd: function (item) {
		  },
		onDelete: function (item) {
		}
	});

$("#tescolores_id_trama").tokenInput("<?php echo "/santapatricia/ingresos/colores"?>", 
	{	
		//tokenLimit: 1,
		minChars: 1,
		preventDuplicates: true,
		onAdd: function (item) {
		  },
		onDelete: function (item) {
		}
	});
$("#tesordendecompras_id").tokenInput("<?php echo "/santapatricia/produccion/ordenescompra"?>", 
		{
			
		tokenLimit: 1,
		minChars: 1,
		preventDuplicates: true,
		onAdd: function (item) {
		  },
		onDelete: function (item) {
		}
	});


});
</script>
<div class="card">
<h1>Hoja de Ruta! <span>Agregar detalle.</span></h1><span style="float:right; font-size:22px; margin-top:-25px;"><?php echo Session::get('MAQUINA_PREFIJO')?><?php echo Session::get('MAQUINA_NUMERO')?></span>
</div>
<div class="card-body">  
<div id="loading" style="display:none;"><img src="/img/spin.gif" /></div>
<form id="hojaderuta">
<?php echo Form::hidden('id')?>
<table width="80%" border="0" align="center" cellpadding="0" cellspacing="0"  class="table-bordered table-striped">
  <caption>Detalles de la hoja de ruta</caption>
  <thead>
  <tr>
    <th colspan="10" align="center" valign="middle">HOJA DE RUTA DEL PLEGADOR</th>
  </tr>
  </thead>
  <tbody class="listado">
  <tr>
    <th width="7%" align="left">Guia Nº:</th>
    <td width="6%"><?php if(!empty($guianumero_mostrar))echo $guianumero_mostrar; else echo "-";?></td>
    <th width="10%" align="left">Titulo de Urdido:</th>
    <td width="16%"><?php echo $titulo?></td>
    <th width="12%" align="left">Servicio de:</th>
    <td width="13%"><?php echo $serviciode?></td>
    <th width="10%" align="left">Peso N:</th>
    <td width="10%"><?php echo $peso?></td>
    <th width="7%" align="left">Fecha:</th>
    <td width="9%"><?php echo Sp::formatFecha('%d / %m / %Y',$fecha)?><?php //echo $fecha;?></td>
  </tr>
  <tr>
    <th align="left">Nº de Hilos:</th>
    <td><?php echo $numerohilos?></td>
    <th align="left">Metros Uridos:</th>
    <td><?php echo $metros?></td>
    <th align="left">Colores (plegador):</th>
    <td><?php echo $colores?></td>
    <th align="left">Plegador:</th>
    <td colspan="3"><?php if($plegadoresuso){?>
		             <?php foreach($plegadoresuso as $puso):?>
					  <?php echo $puso->getProplegadores()->tipoplegador.' - '.$puso->getProplegadores()->numero?><br />
					 <?php endforeach;?>
		<?php }?></td>
  </tr>
  </tbody>
</table>
</form>
<?php 
if(Session::get('PRODUCCION_ID')!=0 && $estado!=0){?>
<form id="prodetalleproduccion">
<table width="80%" border="0" align="center" cellpadding="0" cellspacing="0"  class="table table-bordered table-striped">
<caption>Programar</caption>
<tr>
	<td width="12%">Muestra:<?php echo Form::check('muestra','1')?></td>
	<td width="12%">Ref O.C.:<?php echo Form::text('tesordendecompras_id','placeholder="Orden de compra" value"0"')?></td>
	<td width="17%">Artículo:<?php echo Form::text('tesproductos_id','placeholder="Articulo"')?></td>
    <td width="18%">Color:<?php echo Form::text('tescolores_id','placeholder="Color del Artículo"')?></td>
    <td width="9%"><div class="alert-error" style="display:none;"></div>Metros:<br /><?php echo Form::text('metroprogramados','placeholder="Metros programados" size="10"')?></td>
    <td width="21%">Trama:<?php echo Form::text('trama','placeholder="Trama"')?></td>
    <td width="21%">Colores trama:<?php echo Form::text('tescolores_id_trama','placeholder="Trama"')?></td>
    <td width="18%">Corte:<?php echo Form::select('corte',array("Sin corte"=>"Sin corte","Corte central"=>"Corte central","Otros"=>"Otros"),'',"Sin corte")?></td>
    <td width="18%">Observaciones:<?php echo Form::textArea('observaciones','placeholder="Observaciones"')?></td>
    <td width="5%"><a href="javascript:;" class="btn btn-primary grabardetalle">AGREGAR</a></td>
</tr>
</table>
</form>

<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table-bordered table-striped">
<thead>
  <tr align="left">
    <th width="6%">Ref O.C</th>
    <th width="13%">Artículo</th>
    <th width="12%">Color </th>
    <th width="10%">Metros Programados</th>
    <th width="25%">Trama</th>
    <th width="27%">Observaciones</th>
    <th width="7%">Acciones</th>
  </tr>
</thead>
<tbody id="detalle_listado" class="listado">
<?php 
$total=$metros;
foreach($detalles as $detalle){
	$total=$total-$detalle->metrosrevisados;
	?>
  <tr id="<?php echo $detalle->id?>">
    <td><?php if(empty($detalle->tesordendecompras_id))echo "-"; else echo $detalle->getTesordendecompras()->codigo." (".$detalle->getTesordendecompras()->numero_interno.")";?></td>
    <td><?php echo $detalle->getTesproductos()->nombre?></td>
    <td><?php echo $detalle->getTescolores()->nombre?></td>
    <td><?php echo $detalle->metroprogramados?></td>
    <td><ul><?php $tramas=$detalle->getProtrama();
	$n=0;
	foreach($tramas as $trama){
	$n++;	?>
		<li>S<?php echo $n?>-<?php echo $trama->getTesproductos()->nombre;?> <?php if(!empty($trama->tescolores_id))echo $trama->getTescolores()->nombre;else echo " - -";?></li>
		<?php	}?></ul></td>
    <td><?php echo $detalle->observaciones?> <?php echo $detalle->corte?></td>
    <td><?php if(empty($detalle->fechadecorte))echo Ajax::linkAction('borrardetalle/'.$detalle->id,Html::img("figuras/eliminar.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'detalle_listado');?><?php //echo Ajax::linkAction('editardetalle/'.$detalle->id,Html::img("figuras/editar.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'detalle_listado');?></td>
  </tr>
  <?php }?>
  <tfoot>
  <tr>
    <th width="6%"></th>
    <th width="13%"></th>
    <th width="12%">Total:</th>
    <th id="metros_total" width="10%" align="left"><?php echo $total?></th>
    <th width="25%"></th>
    <th width="27%"></th>
    <th width="7%"></th>
  </tr>
  </tfoot>
</tbody>
</table>

<div class="form-actions">
<?php 
echo Html::linkAction("finalizar/".Session::get("PRODUCCION_ID").'/PRODUCCION',"Enviar a Producción",'class="btn btn-primary"').'&nbsp;';
echo Html::linkAction("listado/","Ir a Listado de Hojas",'class="btn btn-secondary"');?>
</div>
<?php 

}else
{?>
<div class="form-actions">
	<a href="javascript:;" id="hoja" class="btn btn-primary">GRABAR</a><?php echo Html::linkAction("eliminar/","Cancelar",'class="btn btn-secondary"');?>
</div>
<?php }?>
<script>
$(document).ready(function(){

    $( "#detalle_listado" ).sortable({
      placeholder: "ui-state-highlight",
	  update: function(event, ui) {
            var newOrder = $(this).sortable('toArray');
			//alert(newOrder);
			$.ajax({
            type:"POST",
            url:"/<?php echo $module_name?>/<?php echo $controller_name?>/grabarorden/"+newOrder,
            beforeSend:function(){
            },
            success:function(response){
				//alert(response)
            }
			});
		}
    });
    $( "#detalle_listado" ).disableSelection();
});
</script>
</div>
