<div class="card">
<h1>Hoja de ruta de la maq:<?php echo Session::get('MAQUINA_PREFIJO')?><?php echo Session::get('MAQUINA_NUMERO')?></h1></div>

<span id="relojdigital"></span>
<script language="JavaScript" type="text/javascript">
function hora(){
if (!document.layers&&!document.all&&!document.getElementById)
return
var Digital=new Date();
var date="<?php echo date('Y-m-d')?>";
var horas=Digital.getHours();
var minutos=Digital.getMinutes();
var segundos=Digital.getSeconds();
  
var dn="PM"
if (horas<12)
dn="AM"
if (horas>12)
horas=horas-12
if (horas==0)
horas=12
  
 if (minutos<=9)
 minutos="0"+minutos
 if (segundos<=9)
 segundos="0"+segundos
 reloj=date+" "+horas+":"+minutos+":"+segundos;
if (document.layers){
document.layers.relojdigital.document.write(reloj)
document.layers.relojdigital.document.close()
}
else if (document.all)
relojdigital.innerHTML=reloj
else if (document.getElementById)
$("#fechadecorte").val(reloj);
setTimeout("hora()",10000)
} 
 
window.onload=hora
//-->
</script>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
  <caption>Detalle de la hoja de ruta</caption>
  <tr>
    <th colspan="9" align="center">HOJA DE RUTA</th>
  </tr>
  <tr>
    <th width="7%" align="left">Nº Guia:</th>
    <td width="9%"><?php echo $guianumero?></td>
    <th width="10%"align="left">Titulo de Urdido:</th>
    <td width="15%"><?php echo $titulo?></td>
    <th width="10%"align="left">Servicio de:</th>
    <td width="15%"><?php echo $serviciode?></td>
    <th width="14%"align="left">Peso:</th>
    <td width="10%"><?php echo $peso?> Kg</td>
    <th width="10%"align="left">Fecha:<?php echo $fecha?></th>
  </tr>
  <tr>
    <th align="left">Nº de Hilos:</th>
    <td><?php echo $numerohilos?></td>
    <th align="left">Metros Uridos:</th>
    <td><?php echo $metros?></td>
    <th align="left">Color:</th>
    <td><?php echo $colores?></td>
    <th align="left">Plegadores:</th>
    <td colspan="2"><?php foreach($plegadoresuso as $p){
		echo $p->getProplegadores()->numero.' - ';
		}?></td>
  </tr>
</table>
<hr />

<?php echo Form::open('santapatricia/produccion/generarollos','post');?>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
  <tr>
    <th width="6%" align="left">O.C.</th>
    <th width="10%" align="left">Producto</th>
    <th width="6%" align="left">Color</th>
    <th width="22%" align="center">Mts Programados</th>
    <th width="11%" align="left">F. de Corte</th>
    <th width="10%" align="center">Nº de rollo</th>
    <th width="12%" align="center">Trama</th>
    <th width="17%" align="left">Observacion</th>
    <th width="6%">Acc.</th>
  </tr>
  <?php 
  $n=0;
  $programados=0;
  foreach($detalles as $detalle){
	/*Validar si el detalle de produccion tiene toda la trama enregada*/
	
	
	if(empty($detalle->fechadecorte)){
	$n++;
	}
	$programados=$programados+$detalle->metroprogramados;

?>
  <tr title="<?Php echo $detalle->id?>">
    <td><?php echo $n;?>-<?php if(empty($detalle->tesordendecompras_id))echo "-"; else echo $detalle->getTesordendecompras()->codigo." (".$detalle->getTesordendecompras()->numero_interno.")";?></td>
    <td><?php echo $detalle->getTesproductos()->nombre.' ('.$detalle->getTesproductos()->codigo_ant.')'?></td>
    <td><?php echo $detalle->getTescolores()->nombre?></td>
    <td align="center"><?php echo $detalle->metroprogramados?></td>
    <td>
	<?php 
	/*if($detalle->tesproductos_id!=9643)
	{*/
		if($n==1)
			{
				echo Form::hidden('id','',$detalle->id).Form::text('fechadecorte').'<br /># Rollos:'.Form::select('numero',array("1"=>"1","2"=>"2"),'','rollos','Seleccione').' '.Form::Submit('Cortar','class="btn btn-xs"');
			}else
			{
				echo $detalle->fechadecorte;
			}
		/*if($NTP->getValidarDetallePedido($detalle->proproduccion_id,$detalle->id))
		{
			
		}else
		{
		echo "<span class='label label-important'>Verifique el pedido de trama !!!</span>";
		}*/
	//}
	?>
	
	
	</td>
    <td align="center">
	<?php if(!empty($detalle->fechadecorte))
	{
		$r=0; 
		foreach($detalle->getRollos() as $rollo):
		$r++; 
		if($r!=1) echo '/'; 
		if(empty($rollo->numero))echo $rollo->numeroventa;else echo $rollo->numero; 
		endforeach;}?></td> 
    <td align="center"><?php $t=0;foreach($detalle->getProtrama() as $trama): $t++; echo '<b>S'.$t.'.-</b> '.$trama->getTesproductos()->nombre.'<br />'; endforeach;?></td>
      <td><?php echo $detalle->observaciones?> - <?php echo $detalle->corte ?></td>
    <td align="center"><?Php if(empty($detalle->metrosrevisados))if(!empty($detalle->fechadecorte))echo Html::linkAction('rollos/'.$detalle->id,'Editar')?></td>
  </tr>
  <?php }?>
</table>
<?php echo Form::close()?>
<div class="form-actions">
<?php echo Html::linkAction("", 'Escoger Maquina','class="btn btn-xs btn-secondary"') ?>
<?php 
echo '&nbsp;';
echo Html::linkAction("listado/","Ir a Listado de Hojas",'class="btn btn-xs btn-secondary"');?>
<?php 
echo '&nbsp;';
echo Html::linkAction("terminarproduccion/".Session::get('PRODUCCION_ID'),"Detener produccion y descargar plegador",'class="btn btn-xs btn-warning"');?>
<?php 
if($n==0){
echo '&nbsp;';
echo Html::linkAction("cambiarestado/".Session::get('PRODUCCION_ID')."/TERMINADO/listado","Terminar ",'class="btn btn-xs btn-primary" id="verificar" onclick="return confirm(\'¿Está seguro? aun tienes '.($metros-$programados).' metrso en el plegador!!!! \')"');}?>
</div>