<div class="card">
<h1><?php echo Session::get('MAQUINA_NOMBRE')?></h1>
</div>
<div class="form-actions">
<?php echo Menu::menuProduccion();
$siguente=Session::get('MAQUINA_NUMERO')+1;
$anterior=Session::get('MAQUINA_NUMERO')-1;
?>
<div><?php echo Html::linkAction('cargarmaquina/'.$siguente,'','class="icoimg-siguente"')?>
<?php echo Html::linkAction('cargarmaquina/'.$anterior,'','class="icoimg-siguente rotar"')?></div>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="card-body">
<div class="menu">
<ul>
<li>
<a href="javascript:;">Año 
<select id="anio">
<?php
for($i=2011;$i<=2020;$i++)
{
	$selec='';
	if($anio==$i){
	$selec=' selected="selected"';
	}
	echo '<option value="'.$i.'" '.$selec.'>'.$i.'</option>';
}
?>
</select>
</a>
</li>
</ul> 
<?php 
$mes_actual=date('Y-m');
foreach($meses as $clave => $mes):
if($anio.'-'.$clave<=$mes_actual){
$class='';
if($mes_activo==$clave)$class=' active';
echo '<ul>';
echo '<li><a class="enviar'.$class.'" id="mes-'.$mes.'" href="javascript:;" data-id="'.$anio.'-'.$clave.'-01">'.$mes.'</a></li>'; 
echo '</ul>';
}
endforeach;?>
</div>
<table width="115%" border="0" cellpadding="0" cellspacing="0" class="table table-bordered table-striped">
<caption>
Hoja de Ruta Programada
</caption>
  <tr>
  	<th width="17" align="left">Nº</th>
    <th width="53" align="left">Guia</th>
    <th width="78" align="left">Hilo Urdido</th>
    <th width="36" align="left">Peso</th>
    <th width="54" align="left">Mts Urdidos</th>
    <th width="91" align="left">Mts Programados</th>
    <th width="68" align="left">Mts Revisados</th>
    <th width="50" align="left">Merma</th>
    <th width="77" align="left">Color Urdido</th>
    <th width="52" align="center">Estado</th>
    <th width="69">Acciones</th>
  </tr>
<?php $n=0;
foreach($hojas as $item){ 
$sn=1;
$n++;?>
  <tr id="<?php echo $item->id?>">
  	<td><?php echo $n?></td>
    <td><?php echo $item->guianumero?></td>
    <td><?php echo $item->titulo?></td>
    <td><?php echo $item->peso?></td>
    <td><?php echo $item->metros.' m'?></td>
    <td><?php echo $item->metroprogramados.' m'?></td>
    <td><?php echo $item->metrosrevisados.' m'?></td>
    <td><?php echo $item->merma?> m</td>
    <td><?php echo $item->colores?></td>
   <td align="center">
    <?php 
	echo $item->estadoproduccion;
	 if($item->estado!='1'){
	 echo Html::img("figuras/circulo_rojo.png",'Editar','style="width: 20px;margin-left:5px;margin-right:5px;"');
	 }else{
	 echo Html::img("figuras/circulo_verde.png",'Editar','style="width: 20px;margin-left:5px;margin-right:5px;"');
	 }?>
    </td>
    <td align="center">
    <?php if($item->estadoproduccion!='TERMINADO'){?><?php if($item->estadoproduccion=='PROGRAMACION' || Auth::get('id')=='3')echo Html::linkAction('cargarhoja/'.$item->id.'/hojaderuta',Html::img("figuras/editar.png",'Editar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar la hoja de ruta del plegador"')?>
    <?php if(($sn!=0 && $item->estadoproduccion=='PRODUCCION') || Auth::get('id')=='3')echo Html::linkAction('cargarhoja/'.$item->id.'/corte',Html::img("figuras/cortar.jpg",'Cortar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Ingresar Cortes te Tela "')?>
    <?php /*if($item->metros>$item->metroprogramados)*/echo Html::linkAction('cargarhoja/'.$item->id.'/agregardetalle',Html::img("figuras/mashoja.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'), 'title="Agregar mas detalles a la hoja de ruta"');?>
    <?php echo Html::linkAction('cargarhoja/'.$item->id.'/verhoja',Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'), 'title="Ver hoja de ruta"');?>
    <?php if($sn==0 || $item->estadoproduccion=='PROGRAMACION')
	{?>
    <a href="javascript:;">
	<?php echo Html::img("figuras/warning.png",'Cortar','style="width: 20px;margin-left:1px;margin-right:1px;"')?>
    <span class="tooltip">
    <span></span>
    Pedido incompleto:<br />
    - Muchos metros para merma<br />
    - No tiene nota de Pedido Entregado<br />
    - No tiene detalle de pedido <br />
    por favor verificar.
	</span>
    </a>
	<?php }?>
    <?php }else{
		echo Html::linkAction('cargarhoja/'.$item->id.'/verhoja',Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'), 'title="Ver hoja de ruta"');
		//echo Html::linkAction('cargarhoja/'.$item->id.'/corte',Html::img("figuras/cortar.jpg",'Cortar','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Ingresar Cortes te Tela "');
		}?>
    </td>
  </tr>
<?php }?>
</table>
<div class="form-actions">
<?php 
if(Session::get('MAQUINA_NUMERO')!=10)
{
	if($maquina->estadomaquina!="Produccion")echo Html::linkAction("cargarhoja/0/hojaderuta", 'Crear hoja para '.Session::get('MAQUINA_NOMBRE'),'class="btn btn-xs btn-primary"'); 
}?> 
<?php echo Html::linkAction("", 'Escoger Maquina','class="btn btn-xs btn-info"') ?>
</div>
<?Php /*if($maquina->estadomaquina!="Produccion"){*/
if(Session::get('MAQUINA_NUMERO')==10){
echo Form::open($module_name.'/produccion/generarhojaderuta','POST');
echo "<div id='mensajes_flash' >Debe seleccionar la guia con mayor peso para un mejor control de los rollos a cortar</div>";
 }?>
<table width="75%" align="center" class="table table-bordered table-striped">
<caption>Plegadores Listos para Generar Hoja de Ruta - Produccion </caption>
  <tr>
  	<th width="17" align="left">Nº</th>
    <th width="82" align="left">Urdido por:</th>
    <th width="60" align="left">Orden de Compra.</th>
    <th width="221" align="left">Nro. Plegadores</th>
    <th width="61" align="center">Acciones</th>
  </tr>
<?php $number=0;
foreach($guias as $item){ 
$simbolo="S/. ";

switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

$number++;?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $number?></td>
  	<td height="20"><?php echo $item->getTesdatos()->razonsocial?></td>
    <td><?php //echo $item->glosa?><?php echo $item->ordendecompra?></td>
    <td>
    <small style="color:#666; font-size:10px !important; font-style:italic; ">
	<?php
    $n=0;$m=0;
	foreach($item->getTesdetalleingresos() as $det)
	{
		if($det->tesproductos_id!=0){$n++;
		echo $det->getTesproductos()->nombre;if(count($item->getTesdetalleingresos())>$n){echo ", ";}
		}else
		{
			echo $det->concepto;
		}
	}
	?>
    </small>
    </td>
    <td align="center" title="Cargar Plegador/es a Mq.">
    <?php if(Session::get('MAQUINA_NUMERO')==10){?>
<label class="checkbox" style="float:left; width:90px;">
          <input type="checkbox" name="itemSelect[]" value="<?php echo $item->id?>" class="sele"> Seleccionar
        </label>
<?php }else{?>
	<?php 
if($DP->getValidarGuia($item->id)==0)echo Html::linkAction('generarhojaderuta/'.$item->id.'/',Html::img("figuras/facturar.png",'VER','style="width: 20px;margin-left:1px;margin-right:1px;"'),'onlick="return(\'¿Va enviar la guia a la maquina => '.Session::get('MAQUINA_NOMBRE').'?\')"'); else echo "<span class='label label-important'>Espere que el rollo  pase control de calidad!</span>";
}?>
    </td>
  </tr>
<?php }
?>
</table>
<?php /* }*/
if(Session::get('MAQUINA_NUMERO')==10){
?>

<button type="submit" class="btn btn-xs btn-primary">Generar Hoja de Ruta</button> 
  </fieldset>
  <?php echo Form::text('guias.ids');?>
<?Php echo Form::close();
?>
<script type="text/javascript">
$(document).ready(function(){
	
	$('.sele').click(function(){
		var selectedItems = new Array();
		
		$("input[@name='itemSelect[]']:checked").each(function(){
			selectedItems.push($(this).val());
		});
		$("#guias_ids").val(selectedItems);
	});
});
</script>
<?php }?>
<script type="text/javascript">
$(document).ready(function(){
	
	$("#anio").change(function(event){
    	var id = $("#anio").find(':selected').val();
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/'+id;
     });
	$(".enviar").click(function()
	{
		var fecha = $(this).attr('data-id');
		var F=fecha.split('-');
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/'+F[0]+'/'+F[1];
	});
});
</script>
</div>