<div class="page-header">
    <h1>Crear Color</h1>
</div>      
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('tescolores.id') ?>
<div class="control-group">
    <label class="control-label">Nombre de la Empresa* : </label>
    <div class="controls"><?php echo Form::dbSelect('tescolores.aclempresas_id', 'nombre') ?></div>
</div>
<div class="control-group">
    <label class="control-label">Nombre del Color* : </label>
    <div class="controls">
        <input class="span3" placeholder="Nombre del Color" type="<?php echo Form::text('tescolores.nombre') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Codigo Anterior* : </label>
    <div class="controls">
        <input class="span3" placeholder="Ingresar Codigo Anterior" type="<?php echo Form::text('tescolores.codigo_ant') ?>
    </div>
</div>

<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('index/'.$id_e.'/'.$page, 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
