<?php echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?><div class="card">
    <h1><em>Crear Salida<span><?php echo Session::get('DOC_NOMBRE')?></span></em></h1>
</div>
<div id="mensajes_flash" >        
   <?php View::content() ?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>
<?php echo Form::open(NULL,'POST','class="form-inline"')?>
<?php echo Form::hidden('salida.id')?>
<?php echo Form::hidden('prodetalletransportes.id')?>
<?php echo Form::hidden('prodetalletransportes.tessalidas_id')?>
<?php echo Form::hidden('salida.igv');?>
<?php echo Form::hidden('salida.totalconigv');?>
    <div class="input-prepend">
    <span class="add-on">Pedido</span>
    <?php echo Form::text('salida.npedido','size="8" readonly="readonly"');?>&nbsp;
    <span class="add-on">Serie</span>
    <?php echo Form::text('salida.serie','size="4" readonly="readonly"');?>&nbsp;
    <span class="add-on">Numero</span>
    <?php echo Form::text('salida.numero','size="10"  readonly="readonly"');?>&nbsp;
    <span class="add-on">Moneda</span>
    <?php echo Form::dbSelect('salida.tesmonedas_id','simbolo,nombre',array("tesmonedas",'find','conditions: aclempresas_id='.Session::get('EMPRESAS_ID')));?>&nbsp;
    <span class="add-on">Proveedor</span>
    	<input id="CL" />
      <?php echo Form::hidden('salida.tesdatos_id')?><br />
    <span class="add-on">Direccion de Entrega</span>
      <?php echo Form::text('salida.direccion_entrega','class="span8"');//finiciotraslado?><br />
    <span class="add-on">Fecha de Traslado</span>
      <?php echo Calendar::selector('salida.finiciotraslado');//finiciotraslado?>
      <span class="add-on">Adelanto / acuenta</span>
      <?php echo Form::text('salida.acuenta');//finiciotraslado?>
      <br />
    <?php if(Session::get('DOC_ID')==15){?>
    <span class="add-on">Conductor</span>
      <?php echo Form::text('prodetalletransportes.protransportistas_id')?>
    <span class="add-on">Transporte</span>
      <?php echo Form::text('prodetalletransportes.protransportes_id')?>      
   <?php }?>   
	</div>   
  <div class="control-group">
    <div class="controls">
       <button type="submit" class="btn btn-primary">Modificar</button> <?php echo Html::linkAction('salidas','Cancelar','class="btn"')?>
    </div>
  </div>
<?php echo Form::close();?>
<div id="guia">
<script type="text/javascript">
$(document).ready(function()
{
	$(".ocultar").live("click",function(){
		var id=$(this).attr('id');
		$("#caja-"+id).hide();
	});
  $("#CL").tokenInput("/<?php echo $module_name?>/salidas/buscarproveedor", 
	{
		tokenLimit: 1,
		minChars: 2,
	<?php if(!empty($salida->tesdatos_id)){?>
		prePopulate: [ 
	 {id: <?Php echo $salida->tesdatos_id?>, name: "<?php echo $salida->getTesdatos()->razonsocial?>"},
					 ],
	<?php }?>
		onAdd: function (item){
	   	var VAL=item.id;
		$("#salida_tesdatos_id").val(VAL);
 	    var DIR=item.name.split('(');
	    $("#salida_direccion_entrega").val(DIR[1]);
	   //$("#BC").hide();
	   //GrabarCliente();
		},
		onDelete: function (item) {
		}
	});
/*transporte*/
	$("#prodetalletransportes_protransportes_id").tokenInput("/<?php echo $module_name?>/salidas/transportes", 
		{
			tokenLimit: 1,
			minChars: 2,
			<?php if(!empty($prodetalletransportes->protransportes_id)){?>
			prePopulate: [ 
						 {id: <?php echo $prodetalletransportes->protransportes_id?>, name: "<?php echo $prodetalletransportes->getProtransportes()->marca.' '.$prodetalletransportes->getProtransportes()->numeroplaca?>"},
						 ],
			<?php }?>
		});
		
/*transportistas*/
		
	$("#prodetalletransportes_protransportistas_id").tokenInput("/<?php echo $module_name?>/salidas/transportistas", 
		{
			tokenLimit: 1,
			minChars: 2,
			<?php if(!empty($prodetalletransportes->protransportistas_id)){?>
			prePopulate: [ 
						 {id: <?php echo $prodetalletransportes->protransportistas_id?>, name: "<?php echo $prodetalletransportes->getProtransportistas()->nombre?> <?php echo $prodetalletransportes->getProtransportistas()->numerobrevete?>"},
						 ],
			<?php }?>
		});
	
	$("#detalles_tesproductos_id").tokenInput("<?php echo "/".$module_name."/".$controller_name."/getrepuestos/"?>", 
		{
		tokenLimit: 1,
		minChars: 1,
		onAdd: function (item) {
		},
		onDelete: function (item) {
		}
	});

});
</script>
<div align="center">
<?php 
if(empty($salida->tescontratos_id)){?>
<?php echo Ajax::form('guia',$module_name."/".$controller_name."/grabardetalle_guia",'form-inline','post')?>
<?php echo Form::hidden('detalles.tesunidadesmedidas_id','',13)?>
  <?php echo Form::hidden('detalles.tescolores_id','',773)?>
<pre> Ingresar productos para : <?php echo Session::get('DOC_NOMBRE')?></pre>
  <div class="input-prepend input-append">
  <span class="add-on">Producto</span>
  <?php echo Form::text('detalles.tesproductos_id')?>
  </div>
  <div class="input-prepend input-append">
  <span class="add-on">Cantida</span>
  <?php echo Form::text('detalles.cantidad','size="5" class="qty"')?>
  </div>
  <div class="input-prepend input-append">
  <span class="add-on">Precio</span>
  <?php echo Form::text('detalles.preciounitario','size="5" class="qty"')?>
  </div>
  <button type="submit" class="btn">Enviar</button>
<?php echo Form::close()?>
</div>
<?php }else{
echo $salida->getTescontratos()->observacion .' el contrato es por '.$salida->getTescontratos()->duracion;
}?>
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="1" class="table table-hover">
<caption> Lista de productos en contrato </caption>
  <tr>
    <th width="34%">Producto</th>
    <th width="9%">Cantidad</th>
    <th width="20%">Unidad</th>
    <th width="20%">Costo unitario</th>
    <th width="9%">Total</th>
    <th width="8%">Accion</th>
  </tr>
  <?php 
  $n=0;
  foreach($detalles as $item){
	  $n++;
	  ?> 
  <tr id="<?php echo $item->id?>">
    <td><?php echo $n?>. <?php echo $item->getTesproductos()->detalle?> <?Php echo $item->getTescolores()->nombre?></td>
    <td><?php echo $item->cantidad?></td>
    <td><?Php echo $item->getTesunidadesmedidas()->simbolo?></td>
    <td><?php echo $item->preciounitario?></td>
    <td><?php echo $item->importe?></td>
    <td><?php echo Html::linkAction('eliminar/'.$item->id,'Elminar',"class='btn'")?></td>
  </tr>
  <?php }?>
</table>
</div>
<div class="form-actions">
<?php 
echo Html::linkAction("versalida_guia/", 'Siguente<i class="icon-hand-right"></i>','class="btn btn-primary"') ?>&nbsp;<?php //echo Html::linkAction("salidas", 'Volver ','class="btn"') ?>
</div>
<hr />
</div>