<script type="text/javascript">


</script>
<?php echo Tag::js('jquery/jquery.tokeninput');
Tag::css('token-input');?>
<div class="card">
    <h1><em>Crear Salida de Repuestos<span><?php echo Session::get('DOC_NOMBRE')?></span></em></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>
<?php echo Form::open(NULL,'POST','class="form-horizontal"')?>
  <div class="control-group">
    <label class="control-label" for="pedido_serie">Control Interno</label>
    <div class="controls">
      <?php echo Form::text('pedido.codigo','size="10"');?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="pedido_tesmonedas_id">Moneda:</label>
    <div class="controls">
    <span style=" font-size:16px;">Dolares Americanos</span>
    <?php echo Form::hidden('pedido.tesmonedas_id','','2')?>
      <?php //echo Form::dbSelect('pedido.tesmonedas_id','simbolo,nombre',array("tesmonedas",'find','conditions: aclempresas_id='.Session::get('EMPRESAS_ID')));?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="CL">Areas:</label>
    <div class="controls">
    	<?php /*?><span style="width:50%; display:block; float:left"><input id="CL" /></span><?php */?>
      <?php echo Form::dbSelect('pedido.plareas_id','nombre',array('plareas','find','conditions: aclempresas_id=1'))?>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="pedido_femision">Fecha de Emision:</label>
    <div class="controls">
      <?php echo Calendar::selector('pedido.fecha');//finiciotraslado?>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
       <button type="submit" class="btn btn-primary">Siguiente</button> <?php echo Html::linkAction('salidas','Cancelar','class="btn"');?>
    </div>
  </div>
<?php echo Form::close();?>
</div>
<script type="text/javascript">
$(document).ready(function()
{
	$("#CL").tokenInput("/<?php echo $module_name?>/repuestos/getareas", 
		{
			tokenLimit: 1,
			minChars: 2,
	
			onAdd: function (item){
			   var VAL=item.id;
			   $("#pedido_plareas_id").val(VAL);
			},
			onDelete: function (item) {
			}
		});
		
		/*transporte*/
		$("#prodetalletransportes_protransportes_id").tokenInput("/<?php echo $module_name?>/pedidos/transportes", 
		{
			tokenLimit: 1,
			minChars: 2,
		});
		
		/*transportistas*/
		
		$("#prodetalletransportes_protransportistas_id").tokenInput("/<?php echo $module_name?>/pedidos/transportistas", 
		{
			tokenLimit: 1,
			minChars: 2,
	    });
		$('.ventana').live("click",function(){
		$("#myModal").modal("show");});
});
</script>
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Nuevo </h3>
  </div>
  <div class="modal-body" id="otro">
  </div>
  <div class="modal-footer">
  </div>
</div>
