<div class="card">
    <h1>Modulo de Repuestos - SP!</h1>
</div>
<div class="form-actions">
<?php echo Html::linkAction("ingresos/",'Ingresos','class="btn btn-info"') ?>   
<?php echo Html::linkAction("salidas/",'Salidas','class="btn btn-success"') ?>  
<?php echo Html::linkAction("reporteingresos/",'Compras','class="btn"') ?>  
<?php echo Html::linkAction("reportesotk/",'Consulta de Stock','class="btn"') ?>       
<?php echo Html::linkAction("reporterepocicion/",'Reposicion de Repuestos','class="btn"') ?>       
<?php echo Html::linkAction("reporteutilizacion/",'Reporte de Utilizacion','class="btn"') ?>     
<?php echo Html::linkAction("repuestoprecios/",'Reporte de Precios','class="btn"') ?>
<?php echo Html::linkAction("listado_guias/",'Devoluciones','class="btn btn-info"') ?>         
<?php echo Html::link($module_name."/maquinas/",'Producción','class="btn btn-primary"') ?> 
</div> 
<?php View::content() ?>  
<div class="card-body">
<h3>Repuestos para hacer pedido</h3>
</div>