<div class="card">
    <h1>Repuestos!<span><?php echo Session::get('INGRESO_ID')?></span></h1>
</div>
<div class="form-actions">
<?php echo Html::linkAction('crearingresos/','Ingresar Repuestos!','class="btn btn-primary"');?> 
<?php echo Html::linkAction('','Volver','class="btn"');?> 
</div>
<?php echo Sp::imprimir('Ingresos de repuestos','P');?> 
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="menu">
<ul>
<li><a>
Año 
<select id="anio">
<?php
for($i=2011;$i<=2020;$i++)
{
	$selec='';
	if($anio==$i){
	$selec=' selected="selected"';
	}
	echo '<option value="'.$i.'" '.$selec.'>'.$i.'</option>';
}
?>
</select>
</a></li></ul> 
<?php 
$mes_actual=date('Y-m');
foreach($meses as $clave => $mes):
if($anio.'-'.$clave<=$mes_actual){
$class='';
if($mes_activo==$clave)$class=' active';
echo '<ul>';
echo '<li><a class="enviar'.$class.'" id="mes-'.$mes.'" href="javascript:;" data-id="'.$anio.'-'.$clave.'-01">'.$mes.'</a></li>'; 
echo '</ul>';
}
endforeach;?>
</div>
<div class="card-body">
<table width="100%" border="0" class="table-bordered table-striped">
<caption>Guias de ingreso (Repuestos)</caption>
  <tr>
  	<th width="19" align="left">Nº</th>
    <th width="143" align="left">Proveedor</th>
    <th width="86" align="left">Nro. Doc.</th>
    <th width="290" align="left">Productos</th>
    <th width="60" align="center">Acciones</th>
  </tr>
<?php $number=0;
foreach($ingresos as $item){ 
$simbolo="S/. ";

switch ($item->tesmonedas_id)
{
	case 1: $simbolo='S/. '; break;
	case 2: $simbolo='$. '; break;
	case 4: $simbolo='S/. '; break;
	case 5: $simbolo='$. '; break;
	case 0: $simbolo='S/. '; break;
}

$number++;?>
  <tr id="<?php echo $item->id?>">
  	<td height="20"><?php echo $number?></td>
  	<td height="20"><?php echo $item->getTesdatos()->razonsocial?></td>
    <td><?php echo $item->serie?>-<?php echo $item->numero?></td>
    <td>
    <small style="color:#666; font-size:10px !important; font-style:italic; ">
	<?php
    
	$n=0;$m=0;
	foreach($item->getTesdetalleingresos() as $det)
	{
		if($det->tesproductos_id!=0){$n++;
		echo $det->getTesproductos()->nombre;if(count($item->getTesdetalleingresos())>$n){echo ", ";}
		}else{
			echo $det->concepto;
			}
	}
	?>
    </small>
    </td>
    
   <td align="center">
   <?php if($item->estadoingreso=="Editable"){echo Html::linkAction('cargaringreso/'.$item->id.'/agregardetalles_ingreso',Html::img("figuras/editar.png",'EDITAR','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Editar Guia - 002 - Hilos"')?>
   <?php echo Html::linkAction("borraringreso/$item->id",Html::img("figuras/eliminar.png",'Eliminar','style="width: 20px;margin-left:1px;margin-right:1px;"'), 'onclick="return confirm(\'¿Está seguro?\')"');}//echo $item->estadoingreso?>
	<?php echo Html::linkAction('cargaringreso/'.$item->id.'/veringreso',Html::img("figuras/ver.png",'Ver','style="width: 20px;margin-left:1px;margin-right:1px;"'),'title="Ver e Imprimir Guia - 002 - Hilos"')?>
    
    <?php //echo Html::linkAction("ver/$item->id/$page",Html::img("figuras/ver.png",'Eliminar','style="width: 20px;margin-left:1px;margin-right:1px;"'));?>
    </td>
  </tr>
<?php }?>
</table>
<script type="text/javascript">
$(document).ready(function(){
	
	$("#anio").change(function(event){
    	var id = $("#anio").find(':selected').val();
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/'+id;
     });
	$(".enviar").click(function()
	{
		var fecha = $(this).attr('data-id');
		var F=fecha.split('-');
		location.href = '/<?php echo $module_name?>/<?php echo $controller_name?>/<?Php echo $action_name?>/'+F[0]+'/'+F[1];
	});
});
</script>
 
</div>