<div class="card">
    <h1><em>Ver Salida<span><?php echo Session::get('DOC_NOMBRE')?></span></em></h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div>
<div class="card-body">
<div id="ver_resultado"></div>

    <form class="form-inline">
    <legend>Guia para tintoreria</legend>
    <div class="input-prepend">
    <span class="add-on">Pedido</span>
    <?php echo $salida->npedido;?>
    <span class="add-on">Serie</span>
    <?php echo $salida->serie;?>&nbsp;
    <span class="add-on">Numero</span>
    <?php echo $salida->numero;?>&nbsp;
    <span class="add-on">Moneda</span>
    <?php echo $salida->getTesmonedas()->nombre;?>&nbsp;
    <span class="add-on">Destino:</span>
    <?php echo "TINTORERIA";?><br />
    <span class="add-on">Proveedor</span>
      <?php echo $salida->getTesdatos()->razonsocial?><br />
    <span class="add-on">Direccion de Entrega</span>
      <?php echo $salida->direccion_entrega;//finiciotraslado?><br />
    <span class="add-on">Fecha de Traslado</span>
      <?php echo $salida->finiciotraslado;//finiciotraslado?><br />
    <span class="add-on">Conductor</span>
      <?php echo $prodetalletransportes->protransportistas_id;?>
    <span class="add-on">Transporte</span>
      <?php echo $prodetalletransportes->protransportes_id;?>
	</div>      
  <div class="control-group">
    <div class="controls">
       
    </div>
  </div>
  </form>

<div id="guia">
<table width="75%" border="0" align="center" cellpadding="0" cellspacing="1" class="table table-hover">
<caption> Lista de Telas en Guia </caption>
  <tr>
    <th width="9%">Codigo</th>
    <th width="17%">Cantidad</th>
    <th width="11%">Unidad</th>
    <th width="53%">Descripcion</th>
  </tr>
  <?php 
  $n=0;
  foreach($detalles as $item){
	  $n++;
	  ?> 
  <tr id="<?php echo $item->id?>">
    <td><?php echo $n?>. 
	<?php 
	echo $item->prorollos_id;
	if(empty($item->getProrollos()->prorollos_id))
	{
		echo $item->getProrollos()->numero?>-M
  <?php echo $item->getProrollos()->maquina_numero;
    }else{
		echo $item->getProrollos()->codigo?>-
		<?php echo $item->getProrollos()->numeroventa; 
		echo ' '.$item->getProrollos()->getNprocesos($item->prorollos_id);
	}?>
    </td>
    <td><?php echo $item->pesoneto?></td>
    <td><?Php echo $item->getTesunidadesmedidas()->simbolo?></td>
    <td><?php echo $item->getTesproductos()->detalle?> <?Php echo $item->getTescolores()->nombre?></td>
  </tr>
  <?php }?>
</table>
<?php echo Form::open(NULL,'POST','class="form-inline"')?>
<?php echo Form::hidden('salida.id')?>
<?php echo Form::hidden('salida.aclusuarios_id')?>
<?php echo Form::hidden('salida.tesmonedas_id')?>
<?php echo Form::hidden('salida.tesdatos_id')?>
<?php echo Form::hidden('salida.tesdocumentos_id')?>
<?php echo Form::hidden('salida.testipocambios_id')?>
<?php echo Form::hidden('salida.estadosalida','','Enviado')?>
<?php if($salida->estadosalida=='Editable'){?><button type="submit" class="btn btn-primary">Finalizar</button> 
<?php echo Html::linkAction('agregardetalles','Editar','class="btn"')?><?Php }else{?><?php echo Html::linkAction('salidas','Listado','class="btn"')?> <?php //echo Html::linkAction('versalida_i','Imprimir','class="btn"')?><?php }?>
<?php echo Form::close();?>
<button onclick="myFunction()" class="btn btn-info"> IMPRIMIR </button>
<?php 
$hrf='facturas';
if(Session::get('DOC_ID')==15)$hrf='guias';?>
<script>
function myFunction() {
    window.open("http://"+document.domain+"/imprimir/<?php echo $hrf?>", "_blank", "toolbar=NO, scrollbars=yes, resizable=yes, top=100, left=250, width=600, height=400");
}
</script>