
<div class="card">
<h1>Rollos <span>Modificar todos los rollos ordenado por producto</span></h1>
</div>
<div class="form-actions">
<?php echo Menu::menuControl($action_name);?>
</div>
<?php View::content()?>
<div class="card-body">  
<?php 
foreach($prorollos->items as $rollo){
$n=$rollo->id;
	?>
<div id="rollo<?php echo $n?>" style="float:left; margin:2px; border:1px #999999 inset; padding:5px;">
<?php echo Ajax::form('rollo'.$n,'santapatricia/rollos/grabarrollo_modificar/'.$rollo->id)?>
<?php echo Form::text('a','',$n)?>
<?php echo Form::text('prorollos'.$n.'.id','',$rollo->id);?>
<?php echo Form::hidden('prorollos'.$n.'.enalmacen','','1');?>
<?php //echo($rollo->prorollos_id)?><?php //echo($rollo->tesproductos_id)?>
<?php echo Form::hidden('prorollos'.$n.'.prodetalleproduccion_id','',$rollo->prodetalleproduccion_id);?>
<table width="97%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td width="94" align="left" valign="top">Producto:</td>
    <td width="25" valign="top"><?php
	echo Form::select('prorollos'.$n.'.tesproductos_id',$productos,'Seleccione',$rollo->tesproductos_id);?></td>
  </tr>
  <tr>
    <td width="94" align="left" valign="top">Codigo:</td>
    <td width="25" valign="top"><?php
	echo Form::text('prorollos'.$n.'.codigo','',$rollo->codigo);?></td>
  </tr>
  <tr>
    <td align="left" valign="top">Numero Venta:</td>
    <td valign="top"><?php 
	echo Form::text('prorollos'.$n.'.numeroventa','size="15"',$rollo->numeroventa);?></td>
  </tr>
  <tr>
    <td align="left" valign="top">Numero </td>
    <td valign="top"><?php echo Form::text('prorollos'.$n.'.numero','size="15"',$rollo->numero
	);?></td>
  </tr>
  <tr>
    <td>Metros</td>
    <td><?php 
	echo Form::text('prorollos'.$n.'.metros',' class="calc"',$rollo->metros);?></td>
  </tr>
  <tr>
    <td align="left" valign="top">Peso en kilos:</td>
    <td valign="top"><?php 
	echo Form::text('prorollos'.$n.'.peso','size="5" class="calc"',$rollo->peso);?></td>
  </tr>
  <tr>
    <td align="left" valign="top">Ancho en metros:</td>
    <td valign="top"><?php echo Form::text('prorollos'.$n.'.ancho','size="5"',$rollo->ancho);?></td>
  </tr>
  <tr>
    <td align="left" valign="top">Color:</td>
    <td valign="top"><?php echo Form::text('prorollos'.$n.'.color','',$rollo->color);?></td>
  </tr>
  <tr>
    <td align="left" valign="top">Calidad:</td>
    <td valign="top"><?php 
	echo Form::select('prorollos'.$n.'.calidad',array('1'=>'Primera','2'=>'Segunda','3'=>'Tercera'),'Seleccione...',$rollo->calidad);?></td>
  </tr>
  <tr>
    <td align="left" valign="top">Fecha de corte:</td>
    <td valign="top"><?php echo Calendar::text('prorollos'.$n.'.fechacorte','style="width:90%"',$rollo->fechacorte);?></td>
  </tr>
  <tr id="ver<?php echo $n?>" <?php if(empty($rollo->observacion_control)){?>style="display:none;"<?php }?>>
    <td>Describa el Problema: </td>
    <td>
	<?php echo Form::textArea('prorollos'.$n.'.observacion_control','',$rollo->observacion_control);?>
	</td>
  </tr>
  <tr>
    <td colspan="2"><?php echo Form::submit('Grabar','id="'.$n.'" class="btn btn-primary"')?></td>
  </tr>
</table>
<?php echo Form::close()?>
</div>
<script type="text/javascript">
$(document).ready(function(){
       $("#prorollos<?php echo $n?>_estadorollo").change(function(){
                var op = $("#prorollos<?php echo $n?>_estadorollo option:selected").val();
                //alert(op);
				if (op=="Re-Proceso"){$("#ver<?php echo $n?>").show();}else{$("#ver<?php echo $n?>").hide();}
				
        });
	});
</script>
<?php }?>
<div class="clear"></div>

<div class="form-actions">
<?php View::partial('paginators/bootstrap', false, array('page' => $prorollos, 'url' => Router::get('controller_path') . '/modificar')); ?>
</div>
</div>