<?php if($item->testipodatos_id=='1')
{
	$action='proveedores';
}else
{
	$action='clientes';
}
?>
<td><?php //echo $n?></td>
    <td><?php echo $item->codigo?></td>
    <td><?php echo $item->codigo_ant?></td>
    <td><?php echo $item->razonsocial?></td>
    <td><?php echo $item->ruc?></td>
    <td><?php echo $item->direccion?></td>
    <td><?php echo $item->telefono?></td>
    <td><?php echo $item->pais?></td>
    <td><?php echo $item->contacto?><br />
	<?php if(empty($item->contacto))
	{
		echo Ajax::link($module_name."/contactos/crear/$item->id",'Agregar',$item->id); }else{ 
		echo Ajax::link($module_name."/contactos/borrar/$item->idcontato",Html::img("figuras/eliminar.png",'Eliminar','style="width: 15px;margin-left:2px;margin-right:2px;"'),$item->id,'','onclick="return confirm(\'¿Está Seguro de borrar a este conacto?\')"');
		echo Ajax::link($module_name."/contactos/listado/$item->id",Html::img("figuras/ver.png",'Ver','style="width: 15px;margin-left:2px;margin-right:2px;"'),$item->id,'');}?></td>
    <td>
    <?php 
	 if($item->activo=='0'){
	 echo Html::link($module_name.'/'.$action.'/activar/'.$item->id,Html::img("figuras/circulo_rojo.png",'Editar','style="width: 20px;margin-left:5px;margin-right:5px;"'),'');
	 }else{
	 echo Html::link($module_name."/$action/desactivar/$item->id",Html::img("figuras/circulo_verde.png",'Editar','style="width: 20px;margin-left:5px;margin-right:5px;"'), 'onclick="return confirm(\'¿Está seguro?\')"');}?>
    </td>
    <td><?php echo Html::link($module_name.'/'.$action.'/editar/'.$item->id,Html::img("figuras/editar.png",'Editar','style="width: 20px;margin-left:5px;margin-right:5px;"'),'')?>
    <?php echo Html::link($module_name.'/'.$action.'/borrar/'.$item->id,Html::img("figuras/eliminar.png",'Eliminar','style="width: 20px;margin-left:10px;margin-right:10px;"'), 'onclick="return confirm(\'¿Está seguro?\')"');?>
    </td>