<!DOCTYPE html>
 <html lang="es">
	<head>
    	<meta charset='UTF-8' />
        <title>Santa Patricia</title>
        <link href="/css/backend/bootstrap.css" rel="stylesheet" type="text/css" media="screen" />
		<link href="/css/backend/estilos.css" rel="stylesheet" type="text/css" media="screen" />
        </head>
    <body>
    <div id='cabecera' class="navbar navbar-fixed-top">
 	<div class="navbar-inner">
        <div class="container">
            <a href="/" class="brand" >Bienvenidos a la Intranet</a>
        </div>
    </div>
    </div>  
	<div class="container">
            <div id="contenido" class="content">
            <div class="span12">
               <?php 
$monedas= $salida->tesmonedas_id;
switch ($monedas)
{
	case 1: $simbolo='S/ ';$moneda_letras='SOLES'; break;
	case 2: $simbolo='$. ';$moneda_letras='DOLARES AMERICANOS';  break;
	case 4: $simbolo='S/ ';$moneda_letras='SOLES';  break;
	case 5: $simbolo='$. ';$moneda_letras='DOLARES AMERICANOS';  break;
	case 0: $simbolo='S/ ';$moneda_letras='SOLES';  break;
}
if(Session::get('EMPRESAS_ID')==2)
{
	$pre_fijo="SC-";
}else
{
	$pre_fijo="SP-";
}

?>
<div class="page-header">
<h1>Datos <span>Datos importantes del documento</span></h1>
</div>
<?Php $MOV=explode("-",$salida->npedido);
$MOV[0];
?>
<b>Codigo</b> : <?Php if(!empty($salida->getTesdatos()->codigo_ant)) $codigo=$salida->getTesdatos()->codigo_ant; else $codigo= $salida->getTesdatos()->codigo.'-'.$salida->getTesdatos()->sufijo;
echo $codigo;?><br />
<b>Razonsocial</b> : <?php echo $razonsocial=utf8_decode($salida->getTesdatos()->razonsocial); ?><br />
<b>Fecha</b> : <?php echo $fecha=Sp::formatFecha('%d/%m/%Y',$salida->femision)?><br />
<b>Ruc</b> : <?php echo $ruc=$salida->getTesdatos()->ruc?><br />
<b>Direccion</b> : <?php echo $direccion=utf8_decode($salida->getTesdatos()->direccion.'-'.$salida->getTesdatos()->departamento)?><?php //echo $empresa->direccion?><br />
<b>Referencia</b> : <?php echo $referencia=utf8_decode($salida->glosa)?><br />
<?php 
$c_1='';
$c_2='';
/* \n salto de linea */
?>
<?php $n_total_r=10;?>
<?php  $n=0;$total=0;
foreach($detalles as $item){
  		$total=$total+$item->totalimporte;
	  $n++;
	 ?>
<?php $c_1.=utf8_decode($item->concepto);
	  $c_1.="\par\n";
?>
<?php $c_2.=number_format($item->importe,2,'.','');
	  $c_2.="\par\n";?>
<?php }

?>
<?php 
/*echo $c_1;?><br /><?php echo $c_2;?><br /><?php echo $c_3;?><br /><?php echo $c_4;?><br /><?php echo $c_5;?><br /><?php echo $c_6;?><br /><?php echo $c_7;*/
?>
<b>Monedaletras</b> : <?php echo $monedaletras="SON:".NumerosLetras::NL(number_format($salida->totalconigv,2,'.',''),$moneda_letras);?><br />
<b>Igv</b> : <?php echo $igv=$simbolo.''.number_format($salida->igv,2,'.','')?><br />
<b>Subtotal</b> : <?php echo $sub_total=$simbolo.''.number_format($salida->totalconigv-$salida->igv,2,'.','')?><br />
<b>Total</b> : <?php echo $total=$simbolo.''.number_format($salida->totalconigv,2,'.','')?> <br />
<?php
if($salida->tesdocumentos_id==13)$plt='nota_c.rtf';
if($salida->tesdocumentos_id==14)$plt='nota_d.rtf';
// Lee la plantilla
$plantilla = file_get_contents($plt);
// Agregamos los escapes necesarios
$plantilla = addslashes($plantilla);
//$plantilla = str_replace('\r','\\r',$plantilla);
//$plantilla = str_replace('\t','\\t',$plantilla); 
// Datos de la plantilla 
// Procesa la plantilla
eval( '$rtf = <<<EOF_RTF
' . $plantilla . '
EOF_RTF;
' );
$doc='';
if($salida->tesdocumentos_id==13)$doc='NotaCredito';
if($salida->tesdocumentos_id==14)$doc='NotaDebito';
$archivo_nombre=$pre_fijo.$doc."-".$salida->numero.".rtf";
// Guarda el RTF generado, el nombre del RTF en este caso sera el apellido-nombre.fechaactual.rtf
file_put_contents("./notas/".$archivo_nombre,$rtf);
$ruta=base64_encode("./notas/".$archivo_nombre);
//chmod("./facturas/".$archivo_nombre, 0444);if(Auth::get('id')==3)
echo Html::linkAction('descargar/'.$ruta,'descargar','class="btn btn-warning"');

?>
<div class="cl"></div>
			</div>
            </div>
    </div> 
    </body>
</html>

