<div class="page-header">
    <h1>Crear Cargo</h1>
</div>      
<?php View::content() ?>
<?php echo Form::open(NULL, 'post', 'class="form-horizontal"') ?>
<?php echo Form::hidden('placargos.id') ?>
<div class="control-group">
    <label class="control-label">Nombre de la Empresa* : </label>
    <div class="controls">
        <?php echo Form::dbSelect('placargos.aclempresas_id', 'nombre') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Nombre del Cargo* : </label>
    <div class="controls">
        <input class="span3" placeholder="Ingresar Nombre del Cargo" type="<?php echo Form::text('placargos.nombre') ?>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Descripcion* : </label>
    <div class="controls">
       <?php echo Form::textarea('placargos.detalle') ?>
    </div>
</div>

<div class="form-actions">
    <?php echo Form::submit('Guardar Datos', 'class="btn btn-primary"') ?>
    <?php echo Html::linkAction('', 'Cancelar', 'class="btn"') ?>
    </div>
<?php echo Form::close() ?>
